### PR TITLE
Make some WMAgent/WorkQueue metrics MonIT-friendly - wmagent version

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch version of #8923 , minus the couch views and setup_dependencies.

Creating this PR in case we decide to patch all the production agents, which sounds like a good idea but I might not manage to update the graphana dashboard before I leave on vacation...

### CODE REVIEW

**Comment by ticoann** [comment]
Alan, if graphana dashboard is not updated, will current dashboard still work?

**Comment by amaltaro** [comment]
Ok, the playground dashboard is up-to-date. Apparently I missed some metrics in my original PR, so I'll implement those in a later stage.
I suggest we keep this one open because it's very likely that this patch will be applied to the agents in January.

**Comment by amaltaro** [comment]
Cherry-picked further fixes made in #8940

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
applied to all the production agents, so let me merge it.

**Comment by amaltaro** [comment]
[Fix #8934 - Make some WMAgent/WorkQueue metrics MonIT-friendly](https://trello.com/c/6Xhpt17E/138-fix-8934-make-some-wmagent-workqueue-metrics-monit-friendly)

**Pull request merged**
