### PR TITLE
Only set events_per_lumi for the first cmsRun step

### LINKED ISSUE #8025: Problems tweaking PSet for StepChain - job splitting updates
regarding https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_task_B2G-RunIISummer15wmLHEGS-01341__v1_T_170725_221625_2289 it is getting some errors with code 70

----- Begin Fatal Exception 26-Jul-2017 04:33:41 CDT-----------------------
An exception of category 'Configuration' occurred while
[0] Constructing the EventProcessor
[1] Validating configuration of input source of type PoolSource
Exception Message:
Illegal parameter found in configuration. The parameter is named:
'numberEventsInLuminosityBlock'
You could be trying to use a parameter name that is not
allowed for this plugin or it could be misspelled.
----- End Fatal Exception -------------------------------------------------

indicating a mis-tweaking of the input module of the subsequent step of the chain

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8025 

In addition to that, I added a code which raises an exception if the splitting arguments provided are incorrect (including its data type). Also removed the "include_parents" from the splitting API, so it's something defined during creation-only.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Much better now! I did a few tests with the common splitting algos (eventbased, eventaware and lumibased) and everything looks fine.

@hufnagel FYI, since I don't know all the details of the T0 specs.

**Comment by hufnagel** [comment]
This should be fine for the T0.

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
Patch looks good to me.

**Pull request merged**
