### PR TITLE
Overwrite default WMAgent config couch doc - wmagent version

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch patch of #8349

Slightly different approach such that it doesn't depend on ReqMgr/cmsweb changes.

### CODE REVIEW

**Comment by amaltaro** [comment]
tested and it works fine.

**Comment by amaltaro** [comment]
[Fix #8351 - Overwrite default WMAgent config couch doc](https://trello.com/c/Uke9Toru/69-fix-8351-overwrite-default-wmagent-config-couch-doc)

**Comment by ticoann** [comment]
Is it because agent gets redeployed it doesn't update the config? 
I think we just need to deleted that config. (Maybe manually for now but we can add in deploy script for deletion later - I will do that).

**Comment by amaltaro** [comment]
That's right. If it's a new agent and there is no such document, then there are no problems.
So, deleting the document before uploading the new configuration, will have the same effect.

**Review by ticoann — APPROVED** [review]

**Pull request merged**
