### PR TITLE
fix bug in phedex recovery code

### PR DESCRIPTION
**Pull request by ticoann**
1.0.8_wmagent version of #6022

### CODE REVIEW

**Comment by amaltaro** [comment]
Thanks btw! ;)

**Comment by ticoann** [comment]
@amaltaro, you want me to create a new tag.1.0.8.patch1 with this or wait a little until we found the more problems. :smile:

**Comment by ericvaandering** [comment]
Where is the optimism?!?!?

**Comment by amaltaro** [comment]
:-) we can wait a bit more to cut a new tag. Thanks

**Pull request merged**
