### PR TITLE
Adapt error message in StatusPoller

### PR DESCRIPTION
**Pull request by amaltaro**
Decreased timeout for jobs that go into an error state.
Import error message from a single place
Aesthetic changes and pylint fixes in general

### CODE REVIEW

**Comment by amaltaro** [comment]
Perhaps we should disable this E1101 pylint check in etc/WMAgentConfig.py ?

**Comment by ericvaandering** [comment]
I think we can. You can also re-enable it later in the code if there is a need. Clearly PyLint does not understand our configs. :-)

**Comment by amaltaro** [comment]
Much better now :-) It should be good to go, but I'll give you my green light tomorrow Seangchan

**Comment by amaltaro** [comment]
Also ok to be merged now. Let me know the new branch to make a PR there.

**Pull request merged**
