### PR TITLE
Update most WorkQueue tests to work with mock

### PR DESCRIPTION
**Pull request by ericvaandering**
Need to run this through Jenkins

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann I think you can merge this. There are still issues I want to sort out with the emulator, but this improves on our current testing (and hopefully these unstable tests are no longer unstable).

**Comment by ticoann** [comment]
Thanks Eric.

**Pull request merged**
