### PR TITLE
Collect local workqueue info in AgentStatusWatcher

### PR DESCRIPTION
**Pull request by amaltaro**
Basic monitoring for local workqueue database.

I've also added a timeit decorator function that we can start using in the code for timing a method/function execution (unfortunately I squashed it with the real code change here).

### CODE REVIEW

**Comment by amaltaro** [comment]
already tested in my VM, so you can merge it at your will Seangchan.

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Thanks, the patch looks good.

**Comment by amaltaro** [comment]
@ticoann I'm keeping the wmagent branch labe on such that we don't forget backporting it in the coming week. I'm not doing so right now because we may have others to backport.

**Comment by ticoann** [comment]
Yes, we should keep branch label until we create branch patch.

**Comment by amaltaro** [comment]
[Fix #7777 (needs to be backported) - Collect local workqueue info in AgentStatusWatcher](https://trello.com/c/0MW6cCjA/23-fix-7777-needs-to-be-backported-collect-local-workqueue-info-in-agentstatuswatcher)

**Comment by amaltaro** [comment]
[Patch bundle #7788 - backport of #7777, #7779, #7782 and #7784](https://trello.com/c/Vcl1FezR/27-patch-bundle-7788-backport-of-7777-7779-7782-and-7784)

**Pull request merged**
