### PR TITLE
'long' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
Strips the `L` prefix on long literals and renames `long` to `int`.

### CODE REVIEW

**Comment by amaltaro** [comment]
The only way to have it working would be changing the SQL driver/class such that it **always** return integers. At the moment we always have `long` coming back from the DAOs.

Besides that, this patch has duplicate `int` types.

**Comment by amaltaro** [comment]
Looking at the oracle documentation, could it be that we see `long` in the responses because the tables are created either with LONGINTEGER or NUMBER
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/Oracle/Create.py#L111
?

Performing a quick test on the bossair tables (bl_runjob and bl_status), it seems there is no long data type returned when queried.

**Comment by ericvaandering** [comment]
@vilnius-dev please remember to update the code in test/python as well for all of these patches.

**Comment by ericvaandering** [comment]
@amaltaro I can imagine that SQLAlchemy is down sizing things to put it in the int type if it fits? 

But I thought we already did this as part of stage1. I'll have to look when I get into the office.

**Comment by amaltaro** [comment]
> @amaltaro I can imagine that SQLAlchemy is down sizing things to put it in the int type if it fits? 

I'm not sure. I remember seeing run numbers like 1L, 2L, etc a month ago when I was fixing a few issues related to LumiList.

**Comment by vilnius-dev** [comment]
Duplicate int types fixed

**Comment by mapellidario** [comment]
This is taken care by the fixer `lib2to3.fixes.fix_long`, which is in the futurize stage 2 list.
In #9731 the file `src/python/Utils/MathUtils.py` contains such changes.

I would therefore suggest to close this PR without merging.

**Comment by amaltaro** [comment]
Agreed! Thanks Roman and Dario for your effort! Closing it

**Pull request closed without merging**
