### PR TITLE
Override T0-spec assignment parameters with a new Override value

### LINKED ISSUE #8634: Make a different dir structure for T0 prod/recent logs (?)
Since T0 process much more workflows than central production (and workflows usually behave), I think we could isolate Tier0 logs from central production ones.

Default URL is 
https://eoscmshttp.cern.ch/eos/cms/store/logs/prod/recent/

how about we make it
https://eoscmshttp.cern.ch/eos/cms/store/logs/prod/recent/Express

and so on, such that we create an additional directory based on the request spec name?

Since I think it's a great idea, I'll go ahead and make the necessary changes and request Lina to push it into testbed today.

@hufnagel @drkovalskyi @vytjan let me know if you disagree by this Wednesday such that I can roll it back.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8634

However, since it's an assignment parameter and the T0 system "assigns" workflow differently, I'll leave this PR open until I can check with @hufnagel whether this fix is reasonable for T0 operations.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@hufnagel can you please remind me whether T0 uses this method in order to get workflows running
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1742
?

**Comment by hufnagel** [comment]
Yes, we do

https://github.com/dmwm/T0/blob/master/src/python/T0/RunConfig/RunConfigAPI.py#L684

https://github.com/dmwm/T0/blob/master/src/python/T0/RunConfig/RunConfigAPI.py#L1092

**Comment by amaltaro** [comment]
Ok, then this fix should be all we need. How about we get it tested in a replay?

**Comment by amaltaro** [comment]
@hufnagel @vytjan can we setup a replay to test these changes? It should be very simple to validate it:
a) just make sure all three request types run
b) look up at the eoscms logs to make sure all logs went into the correct dir structure.

**Comment by ticoann** [comment]
@hufnagel  @vytjan, is this change OK. If it is OK with you I will merge this.

**Review by ticoann — APPROVED** [review]

**Comment by hufnagel** [comment]
Looks ok. Once we have a production tag with this change in, Tier0Ops should validate it in a replay to make sure it works as intended.

**Comment by amaltaro** [comment]
@hufnagel if you are willing to test (and eventually push in into production) the newest stable tag (1.1.14.patchX), then we need to backport it. Please let us know.

**Comment by hufnagel** [comment]
Yeah, once I find some time and once 1.1.4 has settled a bit (might wait for a couple patch tags), I was planning to build a new Tier0 release with it.

**Comment by amaltaro** [comment]
@hufnagel just in case, Seangchan has cut a 1.1.14.patch4 with this T0 fix in. We've been running patch2 in production for about a week.

**Pull request merged**
