### PR TITLE
Wq unittest

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
Trying for that case of beer?

Sent from a mobile device. Please excuse my brevity or transcription errors.

**Comment by amaltaro** [comment]
BTW, since I'm triggering the tests, I want 15% of those :P

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
I think the error caused by production dbs problem this morning, hopefully this time it will pass.

**Comment by ticoann** [comment]
> Trying for that case of beer?

Free beer is always good. 😄

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Pull request merged**
