### PR TITLE
change fallback for missing system xrootd-client, fixes #10796

### LINKED ISSUE #10796: fallback option in XRDCP stageout plugin too old
**Impact of the bug**
Sites without a locally installed xrootd client will potentially not be able to stageout (depends what xrdcp options are used, it definitely doesn't work for stageout to FNAL storage).

**Describe the bug**
The XRDCP stageout plugin has a fallback option when it doesn't find a locally installed xrdcp. It currently used a 5 years old xrootd-client that is deployed in the CMS COMP cvmfs. When the fallback recently triggered on FNAL Wilson, I found out that the xrdcp version is too old to support the stageout options we use for FNAL (specifically the -p option, which seems to be needed for FNAL to automatically create new directories if they don't exist yet).

**How to reproduce it**
I can't directly reproduce it anymore since FNAL Wilson had an xrootd client installed on the worker nodes.

**Expected behavior**
If the XRDCP stageout plugin doesn't find xrdcp in the path, it should fallback to a usable xrootd client installation from cvmfs.

### PR DESCRIPTION
**Pull request by hufnagel**
Fixes https://github.com/dmwm/WMCore/issues/10796

#### Status
Not tested and will be hard to test, since I don't have any resources anymore without a system installed xrootd client (even the resources that initially triggered this development have since been updated). 

#### Description
In testing on the FNAL Wilson HPC cluster I observed that the fallback option for xrdcp stageout, using the 4.0.4 xrootd client from COMP, doesn't work anymore. The client is too old to support some options we later added for xrdcp stageout at some sites. There is no newer client in the COMP repo (or a CMS repo), but OSG provides one as part of their worker node client.

#### Is it backward compatible (if not, which system it affects?)
YES (should affect no CMS site since the changed code path is basically never executed at fully commissioning CMS sites)

### CODE REVIEW

**Comment by hufnagel** [comment]
Can we have this tested again? I don't see a reason why the initial checks failed.

**Comment by amaltaro** [comment]
Sure, I'm going to trigger a new test with my next comment. @hufnagel meanwhile, could you please create the relevant GH issue which this PR is supposed to fix?

**Comment by amaltaro** [comment]
test this please

**Comment by hufnagel** [comment]
Added a GH issue with the bug report. Let me also look at the failures.

**Comment by amaltaro** [comment]
Thanks, Dirk. Is this:
https://github.com/dmwm/WMCore/issues/10796
the issue you are addressing with this PR?

**Comment by hufnagel** [comment]
Yes, that's the one. Have looked at the unit test failures, but nothing immediately jumps out, i.e. I *think* the changes I made shouldn't affect the tests that now show error. Is there a way to get the full unit test logs, not just what the Details link shows?

**Comment by amaltaro** [comment]
Yes, have a look at this section, which gives you a brief explanation on how to check those failures in more details:
https://github.com/dmwm/WMCore/wiki/Understanding-Jenkins#unit-tests

**Comment by amaltaro** [comment]
@hufnagel Dirk, I would like very much to replace this ancient XRD fallback by something not so old.
Would you be willing to looking and fixing the unit tests? I think the change would only be required to this line:
https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/Storage_t/Backends_t/XRDCPImpl_t.py#L90

with the addition of what your PR provides, thus something like `source ....`.

**Comment by hufnagel** [comment]
The xrdcp stageout unit tests run at CERN and never included the fallback (since it's simply not triggered there).

So I don't know why the fail here. I would have to see an actual error message for the unit tests jenkins runs to track this down (and I am not setup anymore to run this interactively, would take some time to get that setup back).

**Comment by amaltaro** [comment]
This has been superseeded by https://github.com/dmwm/WMCore/pull/11117
Closing this one! Thanks Dirk!

**Pull request closed without merging**
