### PR TITLE
Validate EventStreams at task level in TaskChain

### PR DESCRIPTION
**Pull request by amaltaro**
and fix unittets that got broken yesterday.

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
Fix what now, @amaltaro ? :-)

**Comment by ticoann** [comment]
It is still in progress a little bit backward.  :-)

**Comment by amaltaro** [comment]
Hmm, it worked in my VM :-) Looking into it.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Unit test problems fixed, I'm just not sure whether it will break something else now :-)

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann please review and merge. Tests are good in my VM

**Review by ticoann — APPROVED** [review]

**Pull request merged**
