### PR TITLE
remove stdout.log and stderr.log from component

### LINKED ISSUE #7982: JobAccountant creating huge stderr.log
Happened in vocms0311 when a monster workflow (almost 2M jobs) got aborted. ComponentLog size is Ok (MBs), but stderr.log went up to 410GB from night to day.

More info on: https://its.cern.ch/jira/browse/CMSCOMPPR-1082

I'm cleaning that now, but we need to check what exactly happened and fix it. In addition to protect the system from such bad workflows (badly assigned).

BTW, that workflow was acquired by the following agents:
agent url: vocms0310.cern.ch,vocms0308.cern.ch,vocms0116.cern.ch,vocms0126.cern.ch,vocms0311.cern.ch

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7982

### CODE REVIEW

**Comment by amaltaro** [comment]
Really, that was it?!? :-)

**Comment by ticoann** [comment]
Didn't test it but hopefully that will remove the log. :-) I just want to check with you whether we should remove these logs.

**Comment by ticoann** [comment]
Now it is tested. 😄 It doesn't create the stdout.log stderr.log anymore.

**Review by amaltaro — APPROVED** [review]
Good job!

**Pull request merged**
