### PR TITLE
change complete status report

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann I ran several tests with this patch in and I didn't see any issues. I suggest we merge it.

**Comment by ticoann** [comment]
Thank Alan for test. I still need to update the reduce function and add API for that. Unless you want to create the new tag. In that case, I will separate the patch in two part.

**Comment by amaltaro** [comment]
I think it would be useful to cut a new tag (pre2) today, but only after you merge #7477 and #7452

**Comment by ticoann** [comment]
Hi Alan,

I will create a new tag today then.
Thanks,
Seangchan

On Dec 16, 2016, at 10:58 AM, Alan Malta Rodrigues <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it would be useful to cut a new tag (pre2) today, but only after you merge #7477<https://github.com/dmwm/WMCore/pull/7477> and #7452<https://github.com/dmwm/WMCore/pull/7452>

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Not sure why this one doesn't show any result of failure.  I will try to trigger one more time.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, Eric, do you know why test is failing without any detail.

**Comment by ericvaandering** [comment]
Not yet.

**Comment by ericvaandering** [comment]
Maybe was not happy about how I tried to exclude __init__.py Let me try it without that check.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
OK. I'll have to figure out later what my mistake was.

**Comment by ticoann** [comment]
Thanks Eric.

**Pull request merged**
