### PR TITLE
[py2py3] modernize scripts that rely on urllib

### LINKED ISSUE #10481: [py2py3] Scripts should support py3
**Impact of the new feature**

Mainly `dmwm/WMCore/bin`

**Is your feature request related to a problem? Please describe.**

We have quite some scripts, for example in `dmwm/WMCore/bin`, that have not been part of the modernization effort so far. We should make sure they support python2 and python3, too.

**Describe the solution you'd like**

We should run futurize and pylint on the scripts to have an idea of their python3 support status, then we apply the usual manual changes to make them compatible with both py2 and py3.

**Describe alternatives you've considered**

Some of the scripts may be removed, but it may take less effort to just modernize all of them than to dig into our code and make sure we do not drop some scripts that are actually used by the agents.

**Additional context**
(such information will likely be provided in the PR description)

### PR DESCRIPTION
**Pull request by mapellidario**
Fixes #10481 

#### Status

ready

- dario tested validate-test-wfs with py3 env
- over slack, Alan confirmed he validated both scripts both in py2 and py3.

#### Description
Modernize the scripts that have been left behind in #10482 , by leveraging the same "hacky" technique used in #9934 

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
follow up to #10482 

#### External dependencies / deployment changes
nope

### CODE REVIEW

**Comment by amaltaro** [comment]
Thanks for providing these changes, Dario.

I have tested those in a python3 environment/agent, and here is the outcome for workflowCompletion.py (working fine!):
```
cmst1@vocms0192:/data/srv/wmagent/current $ python3 apps/wmagentpy3/bin/adhoc-scripts/workflowCompletion.py -w amaltaro_TaskChain_PUMCRecyc_Agent152_Val_210817_124215_6631 -c cmsweb-testbed.cern.ch -r alancc7-cloud1.cern.ch
apps/wmagentpy3/bin/adhoc-scripts/workflowCompletion.py:58: DeprecationWarning: key_file, cert_file and check_hostname are deprecated, use a custom context instead.
  return HTTPSConnection(host, key_file=self.key, cert_file=self.cert)
==> amaltaro_TaskChain_PUMCRecyc_Agent152_Val_210817_124215_6631	(status: completed)
InputDataset:
    /RelValQCD_Pt_600_800_14/CMSSW_11_2_0_pre8-112X_mcRun3_2024_realistic_v10_forTrk-v1/GEN-SIM (total input lumis: 180)
OutputDatasets:
    /RelValQCD_Pt_600_800_14/CMSSW_11_2_0_pre8-DigiPU_2024PU_TaskChain_PUMCRecyc_Agent152_Val_Alanv11-v11/GEN-SIM-DIGI-RAW (lumis: 180, lumi completion: 1.0)
    /RelValQCD_Pt_600_800_14/CMSSW_11_2_0_pre8-RecoPU_2024PU_TaskChain_PUMCRecyc_Agent152_Val_Alanv11-v11/DQMIO (lumis: 180, lumi completion: 1.0)
    /RelValQCD_Pt_600_800_14/CMSSW_11_2_0_pre8-RecoPU_2024PU_TaskChain_PUMCRecyc_Agent152_Val_Alanv11-v11/MINIAODSIM (lumis: 180, lumi completion: 1.0)
    /RelValQCD_Pt_600_800_14/CMSSW_11_2_0_pre8-RecoPU_2024PU_TaskChain_PUMCRecyc_Agent152_Val_Alanv11-v11/GEN-SIM-RECO (lumis: 180, lumi completion: 1.0)
```

while we have problems with the validate script:
```
amaltaro@vocms0192:/data/amaltaro/July2020_Val $ python3 --version
Python 3.8.2
amaltaro@vocms0192:/data/amaltaro/July2020_Val $ python3 validate-test-wfs.py -w amaltaro_TaskChain_PUMCRecyc_Agent152_Val_210817_124215_6631 -c cmsweb-testbed.cern.ch -r alancc7-cloud1.cern.ch
validate-test-wfs.py:68: DeprecationWarning: key_file, cert_file and check_hostname are deprecated, use a custom context instead.
  return HTTPSConnection(host, key_file=self.key, cert_file=self.cert)
Traceback (most recent call last):
  File "validate-test-wfs.py", line 713, in <module>
    sys.exit(main())
  File "validate-test-wfs.py", line 673, in main
    rucioToken = getRucioToken(rucioUrl)
  File "validate-test-wfs.py", line 132, in getRucioToken
    token = getContent(rucioAuth, headers=[("X-Rucio-Account", rucioAcct)])
  File "validate-test-wfs.py", line 100, in getContent
    output = response.headers.getheader('X-Rucio-Auth-Token')
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
```

**Comment by mapellidario** [comment]
Ugh, you are correct! i saw something similar with DQMUpload but forgot about it. 

I added a new commit that has two options:
1. `            output = response.headers.get('X-Rucio-Auth-Token', '')  # option 1` is similar to what we are doing in DQMUpload at https://github.com/dmwm/WMCore/blob/88b70a21208c1b4b849a122336c600210a71c487/src/python/WMCore/WMSpec/Steps/Executors/DQMUpload.py#L292
2. `            # output = response.getheader('X-Rucio-Auth-Token')  # option 2` is what is suggested but the [python3 doc](https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse.getheader), but this is likely not compatible with py2.

Can i ask you @amaltaro to test if one of these two options work? Thank you!

**Comment by amaltaro** [comment]
@mapellidario the current implementation you have in this PR is now working. However, it now fails down the road in:
```
----------------------------------------------------
==> amaltaro_TaskChain_PUMCRecyc_Agent152_Val_210817_124215_6631
sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
----------------------------------------------------
Comments:
Traceback (most recent call last):
  File "validate-test-wfs.py", line 716, in <module>
    sys.exit(main())
  File "validate-test-wfs.py", line 682, in main
    reqmgrInputDset, reqmgrOutDsets = handleReqMgr(reqName, reqmgrUrl)
  File "validate-test-wfs.py", line 498, in handleReqMgr
    twPrint(reqmgrOut.get('Comments', ''))
  File "validate-test-wfs.py", line 428, in twPrint
    print(twPrinter(obj))
  File "validate-test-wfs.py", line 406, in twEnclosed
    for key, value in obj.iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'
```

**Comment by mapellidario** [comment]
Oh no! I forgot to run futurize on that script! it should be ok now :grimacing: Sorry for the inconvenience!

**Comment by amaltaro** [comment]
And now we have another problem. It's probably better if we discuss it over slack and I show you how to test it. Just ping me when you are available, please.

**Comment by amaltaro** [comment]
Thanks for following this up and getting all those issues fixed, Dario.

**Pull request merged**
