### PR TITLE
Make sure httplib2 is not required if using pycurl

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by ericvaandering** [comment]
What's the reasoning behind this? Just reducing a dependency for the CRAB client?

**Comment by mmascher** [comment]
Yep, and having the crabclient run in the CMSSW environment sourcing the
minimal amount of stuff

**Comment by ericvaandering** [comment]
Ah, I see longer discussion in the branch version and Alan saying exactly what I would have said: "I'm not a big fan of imports in the middle of the code"

**Comment by ericvaandering** [comment]
I think the goal here is important enough to have a sub-optimal coding practice, but I'd like to see an issue attached to the pycurl issue to investigate whether we can completely get rid of http2lib in this case.

**Comment by mmascher** [comment]
Ok, I will open a github issue. Which one is the pycurl issue?

**Comment by amaltaro** [comment]
I don't think we need an issue for that, there is a PR already in place for it:
https://github.com/dmwm/WMCore/pull/6360/files

and by reading the final comments, it seems we are waiting for reqmgr (one) to go
away in order to make pycurl default.

**Comment by mmascher** [comment]
Can we merge this one?

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Hmmm, I wonder why it suggested
`if isinstance(encoder, (type(self.get)) or isinstance(encoder, type(f)):`
instead of
`if isinstance(encoder, (type(self.get), type(f))):`
?

@mmascher , can you make another commit to fix the pre-python 2.6 comments and some pylint complaints (like imports unused and other things that are clear)?

**Comment by amaltaro** [comment]
ping, now is a good moment to get it fixed and merged

**Comment by mmascher** [comment]
done

**Comment by mmascher** [comment]
test this please

**Comment by mmascher** [comment]
retriggering tests since the unit test error seemed temporary: `DBS is not responding: https://cmsweb.cern.ch/dbs/prod/global/DBSReader`

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
pushing this one to my VM as well.

**Comment by amaltaro** [comment]
@mmascher can you squash the last two commits please? If you need to change any additional bits, let me please. Otherwise this patch is good to be merged.

**Comment by mmascher** [comment]
I split them in two commits on purpose but if you want I can still squash them.

Reason is that pylint changes are safe (just variable renaming, removed unused variables ect), while strictly speaking fixes for Pre-python 2.6 idioms change the semantic of the code (isinstance(a,b) is different than type(a)==b because it checks subclasses as well). So I put the "dangerous" commit alone (although it's really unlikely it will cause issues and I consider this safe as well :) )

**Comment by amaltaro** [comment]
Let's be optimistic, they both are quite safe. For the sake of going through the history, I think it's better to squash them :-)

**Comment by amaltaro** [comment]
Thanks, Marco

**Pull request merged**
