### PR TITLE
Updating all the templates with newer cmssw and config

### PR DESCRIPTION
**Pull request by amaltaro**
I'll use this PR to update all the test json templates, pushing them one by one before they get lost in my mess... Don't merge plese.

First, is the Premixing a la RelVals, that was discussed yesterday with @ericvaandering  et. al.

### CODE REVIEW

**Comment by ericvaandering** [comment]
:+1:

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
For future reference, I've just added a ReDigi_BadTier template that should fail creation, since there is no GEN-SIM-ALAN datatier :-D

**Comment by amaltaro** [comment]
Resuming this work this week...
For my information, I created this script to help creating these templates:
https://github.com/amaltaro/scripts/blob/master/ReqMgr2/buildWMCoreTemplates.py

**Pull request merged**
