### PR TITLE
Fix assignment-approved --> rejected transition in ReqMgr2

### LINKED ISSUE #7153: ReqMgr2: cannot reject workflows in assignment-approved
Because it validates all parameters instead of only RequestStatus and transition, for this case.

Traceback from the server:
```
[05/Sep/2016:15:07:08] vocms0131.cern.ch 2001:1458:201:a8::100:27c "GET /reqmgr2/data/splitting/amaltaro_ReDigi_BadTier_HG1609_ReqMgr2_Validation_160905_144008_4740 HTTP/1.1" 200 OK [data: 3839 in 5692 out 232910 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
Getting from Cache due to: CouchNotFoundError - reason: Object Not Found, data: {} result: None
[05/Sep/2016:15:07:14]  Error: Traceback (most recent call last):
  File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 205, in validate
    self._validateRequestBase(param, safe, validate_request_update_args, requestName)
  File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 113, in _validateRequestBase
    workload, r_args = valFunc(args, self.config, self.reqmgr_db_service, param)
  File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Utils/Validation.py", line 116, in validate_request_update_args
    workload.validateArgumentForAssignment(args_without_status)
  File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1650, in validateArgumentForAssignment
    validateArgumentsUpdate(schema, argumentDefinition)
  File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py", line 250, in validateArgumentsUpdate
    _validateArgumentOptions(arguments, argumentDefinition, "assign_optional")
  File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py", line 124, in _validateArgumentOptions
    raise WMSpecFactoryException(msg)
WMSpecFactoryException: WMSpecFactoryException
Message: Validation failed: ProcessingString is mandatory {'attr': 'processingString', 'default': '', 'assign_optional': False, 'optional': True, 'validate': <function procstring at 0x7fdf52b90410>, 'null': False, 'type': <type 'str'>}
        ModuleName : WMCore.WMSpec.WMWorkloadTools
        MethodName : _validateArgumentOptions
        ClassInstance : None
        FileName : /data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py
        ClassName : None
        LineNumber : 124
        ErrorNr : 0

Traceback: 



[05/Sep/2016:15:07:14]  SERVER REST ERROR WMCore.ReqMgr.DataStructs.RequestError.InvalidSpecParameterValue f9fc1ae536899b21d53131ba63701edb (Invalid spec parameter value: Validation failed: ProcessingString is mandatory {'attr': 'processingString', 'default': '', 'assign_optional': False, 'optional': True, 'validate': <function procstring at 0x7fdf52b90410>, 'null': False, 'type': <type 'str'>})
[05/Sep/2016:15:07:14]    Traceback (most recent call last):
[05/Sep/2016:15:07:14]      File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 708, in default
[05/Sep/2016:15:07:14]        return self._call(RESTArgs(list(args), kwargs))
[05/Sep/2016:15:07:14]      File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 779, in _call
[05/Sep/2016:15:07:14]        v(apiobj, request.method, api, param, safe)
[05/Sep/2016:15:07:14]      File "/data/srv/beHG1609c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.20.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 238, in validate
[05/Sep/2016:15:07:14]        raise InvalidSpecParameterValue(msg)
[05/Sep/2016:15:07:14]    InvalidSpecParameterValue: InvalidSpecParameterValue f9fc1ae536899b21d53131ba63701edb [HTTP 400, APP 1102, MSG "Invalid spec parameter value: Validation failed: ProcessingString is mandatory {'attr': 'processingString', 'default': '', 'assign_optional': False, 'optional': True, 'validate': <function procstring at 0x7fdf52b90410>, 'null': False, 'type': <type 'str'>}", INFO None, ERR None]

```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7153

Already tested in my VM. Yet, another patch... but eventually we'll refactor this class and make it solid, right @ticoann :-D

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
replaced by  #7163

**Comment by ticoann** [comment]
replaced by  #7163

**Pull request closed without merging**
