### PR TITLE
WorkQueue view to get elements stats by Status

### PR DESCRIPTION
**Pull request by amaltaro**
Added one more couch view to get a summary based on the elements status.

A query like https://alan-cloud1.cern.ch/couchdb/workqueue/_design/WorkQueue/_view/jobsByStatus?reduce=true&group=true should return a nice summary as
```
{"rows":[
{"key":"Available","value":{"sum":102,"count":2,"min":33,"max":69,"sumsqr":5850}},
{"key":"Done","value":{"sum":466,"count":6,"min":2,"max":350,"sumsqr":127778}},
{"key":"Running","value":{"sum":871,"count":10,"min":0,"max":329,"sumsqr":197293}}
]}
```

### CODE REVIEW

**Comment by ticoann** [comment]
Alan, are you getting the stats from LQ? GQ? or both? Don't you needs stats by request?

**Comment by amaltaro** [comment]
It will be used to get stats from both queues. This is supposed to be a very high level summary.

Then later we'll need to have a distribution of jobs per site, as written in the wiki (section 2 and 4):
https://github.com/dmwm/WMCore/wiki/WMAgent-monitoring

where we could either use `getElementsStatusAndJobsByWorkflow` with reduce=false, or use this method:
https://github.com/dmwm/WMCore/pull/7237/files#diff-3cf0385be35cd9b5a8689054609f9d20R104

though it may be too heavy.

BTW, I fixed a problem in `getElementsStatusAndJobsByWorkflow` with the options and it seems it breaks all the workqueue unit tests now. Why would it break if we pass `update_after`?
PS.: please don't reply today :), we can discuss it on Monday.

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
And the next result should be cleaner...

**Comment by amaltaro** [comment]
Ahaa! Apparently these workqueue tests are inserting a document into the database (queueWork) and then it starts processing them (processInbound), however in between there is a conflicts fix function (where it fails because it doesn't retrieve anything from couch).

@ticoann  so my theory is that the function `_stats` is not really happy about these elements with Jobs=None. Though I cannot see how one view could affect other views accesses... :(

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann I had a look at most of the views and it seems changing the Jobs default value from None to 0 doesn't cause any problems (confirmed by the unit tests as well). Would you have any concerns with this change?

**Comment by ticoann** [comment]
Alan, I don't think that will be the problem but let me check

**Comment by amaltaro** [comment]
Seangchan, do you want me to take advantage that I'm working with these views and also update your latest one to `_stats`
https://github.com/dmwm/WMCore/blob/master/src/couchapps/WorkQueue/views/elementsDetailByWorkflowAndStatus/reduce.js
?

**Comment by ticoann** [comment]
Alan, Actually I will change https://github.com/dmwm/WMCore/blob/master/src/couchapps/WorkQueue/views/jobStatusByRequest/reduce.js

to _stats and remove what I added
https://github.com/dmwm/WMCore/blob/master/src/couchapps/WorkQueue/views/elementsDetailByWorkflowAndStatus/reduce.js

**Comment by ticoann** [comment]
Alan I was looking at the code where Jobs == None is treated differently than other case. i.e. GQ work queue_inbox doesn't have Jobs so it will be None. But I don't find anything that would affect the statistics.

I don't think following codes are harmful but  if the default value is 0  Jobs != None is not necessary.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataStructs/WorkQueueElementResult.py#L27

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataStructs/WorkQueueElementResult.py#L143

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataStructs/WorkQueueElementResult.py#L150

**Comment by ticoann** [comment]
Alan, I created the #7524 to use the _stats for completion checking view.  (This patch need to be merged first for unittest to pass for #7524)

**Comment by amaltaro** [comment]
Thanks, Seangchan. I'm updating WorkQueueElementResult then.

**Comment by amaltaro** [comment]
For some reason one WorkQueue unittest was failing to see the up-to-date docs after a updateElements. I had to load the view once again before getting completedWork.

@ticoann can you please review again
I suggest we cut a new tag after merging this one and #7524

**Review by ticoann — APPROVED** [review]

**Pull request merged**
