### PR TITLE
Performance improvements for WorkQueueManagerCleaner thread - wmagent branch

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent 1.4.7 branch of https://github.com/dmwm/WMCore/pull/10695

### CODE REVIEW

**Comment by amaltaro** [comment]
These minor changes provided a pretty good boost in terms of thread execution time. Looking into vocms0284, this is how long the last 3 cycles took (before this patch):
```
2021-07-28 09:06:06,386:140058413758208:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 2729.946 secs to execute
2021-07-28 09:58:49,997:140058413758208:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 2983.334 secs to execute
2021-07-28 10:50:10,576:140058413758208:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 2900.238 secs to execute
```

while with this patch, it goes to to:
```
2021-07-28 11:18:19,373:139818184673024:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 94.996 secs to execute
2021-07-28 11:22:51,543:139818184673024:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 91.917 secs to execute
2021-07-28 11:27:24,585:139818184673024:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 92.782 secs to execute
```

I'm going to clean this patch from my debugging, keep useful important logging, and port it to master just to make sure I'm not missing/breaking anything. If everything is okay, we can patch the production agents in an hour or two.

**Comment by amaltaro** [comment]
submit7 and submit8 patched. I'm watching how that thread performs on those nodes, but I do see workflows moving out of force-completed....

**Comment by amaltaro** [comment]
All the production agents have been patched with this.
Performance on the FNAL agents isn't really great, and it has not yet finished the first cycle, but I guess it's only because it had to deal with hundreds of workflows force-completed (which are now below 100!).

**Comment by haozturk** [comment]
It's very good to see that force-completions are going through. I also see that we have a peak in workflows of `completed` state. Looks like the 666 workflows that I reported in the issue are going through as well. Thanks Alan!

**Comment by amaltaro** [comment]
And for completeness, the last cycles on submit8 are:
```
2021-07-28 07:42:20,458:139883627161344:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 6281.413 secs to execute
2021-07-28 08:11:36,138:139883627161344:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 1574.370 secs to execute
2021-07-28 08:32:02,517:139883627161344:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 1045.004 secs to execute
2021-07-28 08:52:45,806:139883627161344:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 1061.928 secs to execute
```

so, the first was indeed much longer, after that it has a pretty reasonable execution time.

**Comment by amaltaro** [comment]
[Fix #10694 - Performance improvements for WorkQueueManagerCleaner thread](https://trello.com/c/KceNGaSA/262-fix-10694-performance-improvements-for-workqueuemanagercleaner-thread)

**Pull request merged**
