### PR TITLE
Small clean-up based on Alan's comments

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes some suggestions from https://github.com/dmwm/WMCore/pull/9216

#### Status
In development

#### Description
Small clean-ups for MS transferor code

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
https://github.com/dmwm/WMCore/pull/9216

#### External dependencies / deployment changes
no

### CODE REVIEW

**Comment by vkuznet** [comment]
Alan, I only fixed few obvious parts from your suggestions. Others require more questions/thoughts/discussion. This PR is small enough and should be easy to review/merge.

**Comment by vkuznet** [comment]
Turns out our commits crossed and I was need to resolve the conflict. Now it is clean.

**Comment by amaltaro** [comment]
Valentin, Lina just merged my cmsdist PR. Giving that this is not critical, let's put it onhold till cmsweb production deployment.

**Comment by amaltaro** [comment]
Has it been tested?

**Comment by vkuznet** [comment]
yes, I run it in my VM

**Comment by amaltaro** [comment]
Please squash.

**Comment by vkuznet** [comment]
done

**Review by amaltaro — APPROVED** [review]
Thanks, the unit test failure is not related to these changes.

**Pull request merged**
