### PR TITLE
Do not report stage-out se-name to dashboard

### PR DESCRIPTION
**Pull request by amaltaro**
Master version of #7216

### CODE REVIEW

**Comment by amaltaro** [comment]
Changes look safe. However, if you prefer I can test it in my VM, but probably on Monday only :)

**Comment by ticoann** [comment]
Alan, stop working on Friday night. 😄 I already tested in my vm. I just want you to review if you can spot any thing wrong.

**Comment by ticoann** [comment]
It looks fine to me. Stop working on Friday night. When jenkins passes I will merge this.

**Comment by amaltaro** [comment]
Ok, I'm clearing the not merge label then. You're da man!!

**Pull request merged**
