### PR TITLE
add lock time out in db exception list

### LINKED ISSUE #8437: MySQL lock timeout in JobArchiver
Possible the same root cause as #8140 , so aborting a large workflow and getting lots of jobs killed and their status updated.

In this case, it was 38k jobs that were idle (in submit3)
`2018-02-05 04:09:15,098:139867153495808:INFO:WMBSHelper:Killing 38250 jobs for workflow: vlimant_task_SMP-RunIISummer15wmLHEGS-00162__v1_T_170919_144827_3219`

and here is the JobArchiver traceback [1].

I think slicing these db updates in smaller parts (5k? 1k?) might decrease the incidence of these timeouts(?)

[1]
```
2018-02-05 04:14:51,902:139867365783296:INFO:JobArchiverPoller:Found 38441 finished jobs to archive
2018-02-05 04:17:40,188:139867365783296:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobArchiver.JobArchiverPoller.JobArchiverPoller object at 0x7f3569e7ee50> <@========== WMException Start ==========@>
Exception Class: JobArchiverPollerException
Message: Caught exception in JobArchiver
(OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') 'UPDATE wmbs_job\n            SET state = (select id from wmbs_job_state where name = %s),\n                couch_record = %s,\n                state_time = %s\n            WHERE wmbs_job.id = %s' [('cleanout', '724382', 1517825758, 724382L), ('cleanout', '727632', 1517825758,
 727632L), ('cleanout', '727696', 1517825758, 727696L), ('cleanout', '727737', 1517825758, 727737L), ('cleanout', '727783', 1517825758, 727783L), ('cleanout', '727813', 1517825758, 727813L), ('cleanout', '727823', 1517825758, 727823L), ('cleanout', '727825', 1517825758, 727825L)  ... displaying 10 of 500 total bound parameter sets ...  ('cleanout', '724164', 
1517825758, 724164L), ('cleanout', '724167', 1517825758, 724167L)]


        ModuleName : WMComponent.JobArchiver.JobArchiverPoller
        MethodName : algorithm
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py
        ClassName : None
        LineNumber : 127
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py", line 110, in algorithm
    self.archiveJobs()

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py", line 159, in archiveJobs
    self.changeState.propagate(failList, "cleanout", "exhausted")

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 170, in propagate
    self.persist(jobs, newstate, oldstate)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 477, in persist
    transaction = self.existingTransaction())

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WMBS/MySQL/Jobs/ChangeState.py", line 40, in execute
    transaction = transaction)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 162, in processData
    returnCursor=returnCursor))

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 167, in processData
    returnCursor=returnCursor))

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/MySQLCore.py", line 140, in executemanybinds
    returnCursor)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 114, in executemanybinds
    result = connection.execute(s, b)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 924, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/connectors/mysqldb.py", line 67, in do_executemany
    rowcount = cursor.executemany(statement, parameters)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-mysqldb/1.2.4b4-comp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 234, in executemany
    r = r + self.execute(query, a)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-mysqldb/1.2.4b4-comp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 202, in execute
    self.errorhandler(self, exc, value)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-mysqldb/1.2.4b4-comp/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue

<@---------- WMException End ----------@>  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 183, in __call__
    tSpent, results, _ = self.algorithm(parameters)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py", line 127, in algorithm
    raise JobArchiverPollerException(msg)

2018-02-05 04:17:40,189:139867365783296:INFO:Harness:>>>Terminating worker threads
2018-02-05 04:17:40,193:139867365783296:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.JobArchiver.JobArchiverPoller.JobArchiverPoller object at 0x7f3569e7ee50> <@========== WMException Start ==========@>
Exception Class: JobArchiverPollerException
Message: Caught exception in JobArchiver
(OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') 'UPDATE wmbs_job\n            SET state = (select id from wmbs_job_state where name = %s),\n                couch_record = %s,\n                state_time = %s\n            WHERE wmbs_job.id = %s' [('cleanout', '724382', 1517825758, 724382L), ('cleanout', '727632', 1517825758, 727632L), ('cleanout', '727696', 1517825758, 727696L), ('cleanout', '727737', 1517825758, 727737L), ('cleanout', '727783', 1517825758, 727783L), ('cleanout', '727813', 1517825758, 727813L), ('cleanout', '727823', 1517825758, 727823L), ('cleanout', '727825', 1517825758, 727825L)  ... displaying 10 of 500 total bound parameter sets ...  ('cleanout', '724164', 1517825758, 724164L), ('cleanout', '724167', 1517825758, 724167L)]


        ModuleName : WMComponent.JobArchiver.JobArchiverPoller
        MethodName : algorithm
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py
        ClassName : None
        LineNumber : 127
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py", line 110, in algorithm
    self.archiveJobs()

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMComponent/JobArchiver/JobArchiverPoller.py", line 159, in archiveJobs
    self.changeState.propagate(failList, "cleanout", "exhausted")

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 170, in propagate
    self.persist(jobs, newstate, oldstate)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 477, in persist
    transaction = self.existingTransaction())

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WMBS/MySQL/Jobs/ChangeState.py", line 40, in execute
    transaction = transaction)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 162, in processData
    returnCursor=returnCursor))

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 167, in processData
    returnCursor=returnCursor))

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/MySQLCore.py", line 140, in executemanybinds
    returnCursor)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 114, in executemanybinds
    result = connection.execute(s, b)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 924, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/connectors/mysqldb.py", line 67, in do_executemany
    rowcount = cursor.executemany(statement, parameters)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-mysqldb/1.2.4b4-comp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 234, in executemany
    r = r + self.execute(query, a)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-mysqldb/1.2.4b4-comp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 202, in execute
    self.errorhandler(self, exc, value)

  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-mysqldb/1.2.4b4-comp/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue

<@---------- WMException End ----------@>
Backtrace:
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 211, in __call__
    raise ex

2018-02-05 04:17:40,193:139867365783296:INFO:BaseWorkerThread:Worker thread <WMComponent.JobArchiver.JobArchiverPoller.JobArchiverPoller object at 0x7f3569e7ee50> terminated

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8437

### CODE REVIEW

**Review by amaltaro — COMMENTED** [review]
Changes look good. Though I'm not sure we should treat the deadlock just as we treat the other transient failures. 

My concern is that the deadlock might not go away between polling cycles and it requires either transactions to be aborted or a mysql restart...
I'd rather have this one going to logDB such that we can at least see somewhere that something is going on.

**Comment by ticoann** [comment]
Yes I am not sure whether transaction rolls back, I assume it is. It seems when we restart the component it usually works which means it is not necessary to restart MySQL server. I think it is good idea to add the message to log db. I will try to add that in separate patch.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
And I just reminded we have the component heartbeat, so it's not that bad as it looks

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann as we discussed, I'm merging it

**Pull request merged**
