### PR TITLE
Add ConfigCachID link in reqmgr2 page

### LINKED ISSUE #7681: links to ConfigCache
It would be extremely useful to have links to taskname : configcacheid from 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_9_0_0_pre4BeamHalo_13__testUnif_170227_132846_7713

so as to be able to quickly navigate to them, by task

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7681

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, Valentin, I modified a little from you patch. please review.
@vlimant, Jean-Roch is this what you want.

screen shot 2017-03-16 at 4 59 09 pm

link will show

screen shot 2017-03-16 at 5 02 46 pm

**Comment by vlimant** [comment]
awesome @ticoann @vkuznet !

**Review by vkuznet — COMMENTED** [review]
Everything looks good, please go ahead and merge.

**Comment by ticoann** [comment]
It is Valentin's effort. :smile:

**Comment by ticoann** [comment]
test this please.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
