### PR TITLE
add default format as json

### LINKED ISSUE #6306: Change RESTFormatter to accept */* and return json as default.
Need to add under following. 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Server.py#L627

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6306

### CODE REVIEW

**Comment by amaltaro** [comment]
I'll probably confuse you more than review. Do I understand it right that if a user asks for xml, he gets XML formatted data, if he wants json, he gets json and if he wants plain text, he would get json?

**Comment by ericvaandering** [comment]
Those look real to me, @ticoann .

**Comment by ticoann** [comment]
Actually this is not necessary and seems it is intentional to require Accept header. Closing it without merge.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Server.py#L748

**Comment by ticoann** [comment]
Sorry about the buzz. Antanas was asking make more flexible to accept request if Accept header is not specified. I didn't know it was intentional doing this way until I saw Lassi's comment above. So I just sent email to Antanas that client need to specify the Accept header. And Alan, yes what you said is correct.

**Pull request closed without merging**
