### PR TITLE
Handle multi-scramArch in LogCollect

### PR DESCRIPTION
**Pull request by amaltaro**
And that's why LogCollect is failing everywhere. I thought it was the usual castor issue that we have from time to time.

Still needs to be tested, but it's probably good for review.

### CODE REVIEW

**Comment by ericvaandering** [comment]
I approve of moving that function.

**Review by ericvaandering — APPROVED** [review]

**Comment by ticoann** [comment]
So the log collect job currently failing due to this? Production agent need to be patched?

**Comment by amaltaro** [comment]
That's right! And it will only work for new requests being acquired by the agent (new sandbox). 
I'll create the wmagent branch PR once I'm sure this works Ok.

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
Looks good to me.

**Comment by amaltaro** [comment]
Patch works fine. However, I'll try to fix the exit code 0 issue as well (when it fails).

**Comment by amaltaro** [comment]
Actually, I'll fix that in another PR not to keep holding this one. That will likely require more testing anyways. @ticoann please merge. I'm creating the wmagent branch version soon.

**Pull request merged**
