### PR TITLE
'future_builtins' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
Builtins feature provides Py2/3 compatibility for new code using **future** is to include the following imports at the top of every module:
`from builtins import *`
On Python 3, this has no effect. (It shadows builtins with globals of the same names.)
On Python 2, this import line shadows 18 builtins (listed below) to provide their Python 3 semantics.
[[source]](http://python-future.org/imports.html#builtins)

### CODE REVIEW

**Comment by vkuznet** [comment]
@vilnius-dev , any progress on this. These changes introduce 184 failing unit tests. I'll suggest that you take a single test and run it. Please provide and report nature of failed test and how future import cause it.

**Comment by ticoann** [comment]
@vilnius-dev, could you rebase and update the patch.
Here are the error causing unittest failure.

```
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/1/label/cms-dmwm-cc7/deploy/1.1.5.pre5-comp2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/1/label/cms-dmwm-cc7/code/test/python/WMComponent_t/ErrorHandler_t/ErrorHandler_t.py", line 290, in testB_Submit
    workloadPath = workloadPath)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/1/label/cms-dmwm-cc7/code/test/python/WMComponent_t/ErrorHandler_t/ErrorHandler_t.py", line 206, in createTestJobGroup
    testJob.create(group = testJobGroup)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/1/label/cms-dmwm-cc7/code/src/python/WMCore/WMBS/Job.py", line 82, in create
    self.associateFiles()
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/1/label/cms-dmwm-cc7/code/src/python/WMCore/WMBS/Job.py", line 248, in associateFiles
    if len(files) > 0:
'object of type \'itertools.imap\' has no len()\n-------------------- >> begin captured logging << --------------------\nroot: DEBUG: 
```

**Comment by mapellidario** [comment]
This is taken care of in the usual gradual approach.

I would suggest closing this PR without merging

**Comment by amaltaro** [comment]
Agreed! Thanks Roman and Dario for your effort! Closing it

**Pull request closed without merging**
