### PR TITLE
send minimal info for process data and add wmstats proc info

### PR DESCRIPTION
**Pull request by ticoann**
as discussed in #8620 add minimal information.

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, Valentin, please review.
Urls are
https://reqmgr2-dev.cern.ch/reqmgr2/data/proc_status
https://reqmgr2-dev.cern.ch/wmstatsserver/data/proc_status

Here is the return format.

```
{"result": [
 {
  "server": {
    "memory_percent": 2.397824019445641, 
    "uptime": 10.8383309841156, 
    "cpu_times": {
      "children_user": 0.01, 
      "children_system": 0.06, 
      "user": 1.48, 
      "system": 0.29
    }, 
    "cpu_percent": 8.0, 
    "cpu_num": 0, 
    "timestamp": "24/May/2018:00:39:36", 
    "time": 1527115176.841897, 
    "pid": 4733, 
    "memory_full_info": {
      "lib": 0, 
      "text": 4096, 
      "uss": 40005632, 
      "swap": 0, 
      "shared": 4435968, 
      "pss": 41906176, 
      "rss": 46907392, 
      "data": 47243264, 
      "vms": 194719744, 
      "dirty": 0
    }
  }
}]}
```

**Comment by vkuznet** [comment]
Seangchan, the new data structure looks fine to me. I hope you can commit code before you’ll leave for vacation, that will allow me to develop some code for Prometheus.
Valentin

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Thank Valentin, I will make a new pull request for testbed upgrade before I leave.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
