### PR TITLE
Define 99303 and 99304 exit codes in the WMExceptions

### LINKED ISSUE #7268: ErrorCodes not defined in WMExceptions and twiki
99303, 99304 here:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7268

### CODE REVIEW

**Comment by jenimal** [comment]
Can I request when this goes through you let P&R know. What will these exit codes be telling us?  
We are working on trying to automate things in production, but we need to know what we are cueing off when work comes out of WMStats

**Comment by amaltaro** [comment]
These are not new exit codes Jen, I'm just "defining" them in the usual place.

**Comment by jenimal** [comment]
99303's we have been seeing but not 99304's
https://docs.google.com/spreadsheets/d/1onZky6rW2z7NRvvQaLrBGaS8iFfYSg_EL71F1l3mTWE/edit#gid=0

https://twiki.cern.ch/twiki/bin/view/CMS/CompOpsPRWorkflowTrafficController#Error_Codes_Mapping

and neither are on 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
@jenimal, Jen in that case those document you are pointing needs to be updated.
99303, 99304 exit code indicates as Alan explained in the patch (No Job report).
99303 is any case we don't have a job report. And 99304 is the specific case we don't even have job cache directory. Looking at the document you pointed it is related site issues, etc. But that is pure coincidence. WMAgent doesn't know which specific issue is since there is no job report.

**Comment by jenimal** [comment]
Thank you!  I will update the documents.  They come from observational looks at what we see in day to day operations.  Any input from developers on the list is welcome!  
Thanks,
Jen

**Pull request merged**
