### PR TITLE
fix typo on log reporting

### LINKED ISSUE #6919: Report more information about the failure for exit code 134
related to #6894 #6904 , we would need more information be reported back to wmstats. the python stack trace of wmcore is not really informative, while bits of logs on the worker node is

### LINKED ISSUE #7115: Files are not injected to PhEDEx but DBS is updated.
1. Although the files found in wmbs marked as PhEDEx injected but those are not in PhEDEx
   need to check the logic for the validation on PhEDEx inject status. 
2. Data is all deleted although it shouldn't have. (If the problem in the 1. case, drain status checking might get the wrong information from dbsbuffer_file table (in_phedex).
   need to review the drain status check script.
   Also it might be the case that dbsbuffer_file table gets deleted prematurely (although we don't clean up the table automatically,  - need to check the drain status.  

problem was reported initially #7107

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6919,  #7114 

Added to print command it fails when 127 error occurs.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L247

It seems already passing the argument but we are not using it.

Not sure how to test this though.

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Seangchan, how about we change `gethostname()` to `getfqdn()`. Depending on the site setup, it would return a reasonable domain that could be mapped (by the operator) to a site.

**Comment by ticoann** [comment]
> Seangchan, how about we change gethostname() to getfqdn(). Depending on the site setup, it would return a reasonable domain that could be mapped (by the operator) to a site.

Thanks Alan, updated (Still need to add more code for error message on the patch)

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Jenkins changed where it gets certs from, so just re-running a test.

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
There is still problem not reporting from the bottom 
However the code doing the tail of the log seems to be fine. (Need to check whether log is still written when file is opened for the error.

```
 Adding last 25 lines of CMSSW stdout:
  956 PulseChiSqSNNLS::Minimize 208307/55512405                   
  957 RecoMuon             208307/54888577  208307/54888577  
  958 TrackProducerBase    208307/54643554  208307/54623146  208307/56444825
  959 TrajectoryStateClosestToPoint_PerigeeConversions 208307/54772729  208307/54772729  208307/54772729
  960 TwoTrackMinimumDistance 208307/55778470  208307/55778470  208307/56628356
  961 XrdAdaptor           pre-events       pre-events       pre-events
  962 XrdAdaptorInternal   pre-events       pre-events       pre-events
  963 XrdFileWarning       pre-events       pre-events       pre-events
  964 MatrixInversionFailure 208307/55059748                   
  965 NoBeamSpotFit        Run: 208307 Lumi Run: 208307 Lumi Run: 208307 Lumi
  966 SiStripMonitorTrack  208307/54643554  208307/54623146  208307/56444825
  967 TimeReport           PostEndRun                        
  968 TrackRefitter        208307/54643554  208307/54623146  208307/56444825
  969 Fatal Exception      PostProcessEvent                  
  970 MemoryReport         PostEndRun                        
  971 fileAction           PostEndRun                        
  972 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning             16199               16199
Error                5856                5856
System                  5                   5
Complete
process id is 20235 status is 85
CmsRunFailure
Message: Error running cmsRun
{'arguments': ['/bin/bash', '/storage/local/data1/condor/execute/dir_32918/glide_EC0DUN/execute/dir_2139/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc491', 'scramv1', 'CMSSW', 'CMSSW_7_4_0_pre8', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
Return code: 85

	ModuleName : WMCore.WMSpec.Steps.WMExecutionFailure
	MethodName : __init__
	ClassInstance : None
	FileName : /storage/local/data1/condor/execute/dir_32918/glide_EC0DUN/execute/dir_2139/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py
	ClassName : None
	LineNumber : 18
	ErrorNr : 85

Traceback: 

```

**Pull request merged**
