### PR TITLE
add doc string to generat proper docment.

### PR DESCRIPTION
**Pull request by yuyiguo**
Fixes  NO GH issue opend

#### Status
ready

#### Description
Missing doc string and caused error in auto generated doc.

#### Is it backward compatible (if not, which system it affects?)
YES 

#### Related PRs
None
#### External dependencies / deployment changes
 it require deployment changes.  it does not rely on third-party libraries.

### CODE REVIEW

**Comment by yuyiguo** [comment]
@amaltaro 
Could you review and commit?

**Comment by amaltaro** [comment]
@yuyiguo can you just update the PR description following the template suggested (as you can see above)

**Comment by yuyiguo** [comment]
@amaltaro 
Please merge.

**Comment by amaltaro** [comment]
test this please

**Pull request merged**
