### PR TITLE
Handle db deadlock when setting lfn status

### PR DESCRIPTION
**Pull request by amaltaro**
PhEDExInjector is crashing several times in the last couple of days (in submit1). Scanning the logs, it seems the sleep 5s works for ~75% of the cases, but when it doesn't it means the component crashes.

@ticoann @hufnagel can you review please? I'm planning to push it to that agent (and possibly to the next patch release)

### CODE REVIEW

**Comment by hufnagel** [comment]
Looks good

**Comment by ticoann** [comment]
Looks good to me too.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
First commit pushed to submit1. It can be merged as soon as it passes jenkins tests.
I still have to backport it.

**Comment by amaltaro** [comment]
Tested in production :-)
Good to be merged.

**Comment by amaltaro** [comment]
Seangchan, I'm merging it such that I can cherry-pick it without too much hassle :)

**Pull request merged**
