### PR TITLE
Remove gLite submission plugin

### LINKED ISSUE #7068: Get rid of Glite BossAir plugins
Part of #7067 since this plugin uses some old python library for gLite. We never used this in production and it's unlikely to work. Should just be killed off.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7068
because removing code is always easier.
@ericvaandering please give your blessing :)

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
Here's your problem: 
```
File "/build/cmsbuild/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/4/label/slc6_amd64-cloud-tiny/code/src/python/WMComponent/TaskArchiver/CleanCouchPoller.py", line 32, in <module>
    from WMCore.BossAir.Plugins.gLitePlugin          import getDefaultDelegation
ImportError: No module named gLitePlugin
```

**Comment by ericvaandering** [comment]
"because removing code is always easier." 

but no so easy. :-)

**Comment by amaltaro** [comment]
sigh... I keep saying nothing is just, not even "just deleting some code" :-)
Updated CleanCouchPoller code as well, but frankly, I don't understand why that thread has to fetch a user proxy delegation???

Still some tests out there to be taken care of, though that will wait a while.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@mmascher @emaszs I took a look at the CRABServer and CRABClient repo and I couldn't find any use of getProxy() and uploadPublishWorkflow(). Could you please double-check that before we merge this PR?

BTW, JobArchiver could be using `uploadPublishWorkflow`, but it's disabled by default in the config. TaskArchiver also has these configuration parameters set to False (disabled), which would upload data to e.g.
config.TaskArchiver.userFileCacheURL = 'http://USERFILECACHEHOST:UFCPORT/userfilecache/'

perhaps this `userfilecache` was meant to be used when CRAB3 was going to be part of WMCore/ReqMgr?

I'm considering in completely removing this `uploadPublishWorkflow` code and its config from the components. @ticoann @ericvaandering any thoughts?

**Comment by emaszs** [comment]
I've never seen these used in CRAB, also grepped just in case, I say go ahead with your PR.

**Comment by ericvaandering** [comment]
I think you are right. That code was put where it is about a year ago, but before that, here is where it was: https://github.com/dmwm/WMCore/blame/16881c9ce38083ec9c940694d09a95614434a24f/src/python/WMComponent/TaskArchiver/TaskArchiverPoller.py You can see that 5 years ago @mmascher  and I were working on it. :-)

**Comment by amaltaro** [comment]
Awesome, then I'mg going to clean it a bit further. Thanks Eric and Emilis for the confirmation.

**Comment by amaltaro** [comment]
If i didn't mess it up in the last rebase :), then it's good for review and merge @ticoann

**Review by ticoann — APPROVED** [review]

**Pull request merged**
