### PR TITLE
Implement py3 sorting for JobSplitting

### LINKED ISSUE #10627: Broken unittests in WMCore_t/WMBS_t/JobSplitting_t/ in py3
**Impact of the bug**
Some unittests in `WMCore_t/WMBS_t/JobSplitting_t` are failing in py3 and not in py2.

**Describe the bug**
The following unittests are failing in py3 only and this may mean a regression caused by our modernization

- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/EventBased_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/ParentlessMergeBySize_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/RunBased_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/SplitFileBased_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/WMBSMergeBySize_t.py`

**How to reproduce it**
run the unittests

**Expected behavior**
the unittests should pass

**Additional context and error message**

Check the failing unittests in py3 at [this webpage from jenkins](https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCorePy3-UnitTests/lastBuild/)

### PR DESCRIPTION
**Pull request by goughes**
Fixes #10627

#### Status
ready

#### Description
Implements the necessary changes to allow for python3 sorting based on comparison functions

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
NA

#### External dependencies / deployment changes
NA

### CODE REVIEW

**Comment by mapellidario** [comment]
Hi @goughes, i had a quick look at the changes and they look terrific! :) Before I send the proper review, can I ask you if you had a look at

- WMCore_t.WMBS_t.JobSplitting_t.FileBased_t.FileBasedTest:testSiteWhiteBlacklist changed from success to failure
- WMCore_t.WMBS_t.JobSplitting_t.FileBased_t.FileBasedTest:testLocationSplit
- WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest:testMultipleRunsCombine changed from success to failure
- WMCore_t.WMBS_t.JobSplitting_t.EventBased_t.EventBasedTest:test100EventMultipleSite

? These have been marked as unstable likely because of non reproducible sorting. Thanks!

**Comment by goughes** [comment]
Indeed, testing this locally shows these tests do not sort reliably. I will take a closer look.

**Comment by goughes** [comment]
I added some debug statements to the code and found that `testSiteWhiteBlacklist` and `testLocationSplit` do not call any of the code I changed. In py2 these tests are successful and stable. There must be some other place that is sorting (or not sorting) these.

**Comment by goughes** [comment]
The fileset that comes back here does not get sorted consistently in py3

https://github.com/dmwm/WMCore/blob/7e6a0e5a8c9b75a8f8045c18d89cc362ff12dba0/src/python/WMCore/JobSplitting/JobFactory.py#L245

I committed a change that fixes the unit tests, but it is not a good change. :stuck_out_tongue: I'm getting into unfamiliar WMCore territory here... Does the order of this fileset actually matter? If it does not, then I can update the unit tests so they don't depend on the jobGroups always getting sorted one way. If it does, then we should discuss further. @mapellidario @amaltaro

**Comment by goughes** [comment]
test this please

**Comment by goughes** [comment]
test this please

**Comment by amaltaro** [comment]
@goughes regarding your question on the JobFactory fileset order. I was actually looking at that code today, so something is still fresh in my mind :)
What do you think about sorting this `fileIDs` list in this line: https://github.com/dmwm/WMCore/blob/7e6a0e5a8c9b75a8f8045c18d89cc362ff12dba0/src/python/WMCore/JobSplitting/JobFactory.py#L366
?

It's meant to be a list of integers, and it would give us a consistent behaviour between python versions.

**Comment by goughes** [comment]
Sorting on L366 of JobFactory would work for only some of the cases due to the logic here:

https://github.com/dmwm/WMCore/blob/7e6a0e5a8c9b75a8f8045c18d89cc362ff12dba0/src/python/WMCore/JobSplitting/JobFactory.py#L237

Which (at least for the unit test case) creates the fileset from the Subscription class:

https://github.com/dmwm/WMCore/blob/7e6a0e5a8c9b75a8f8045c18d89cc362ff12dba0/src/python/WMCore/DataStructs/Subscription.py#L147

So we would need to sort there as well. Or even here?

https://github.com/dmwm/WMCore/blob/7e6a0e5a8c9b75a8f8045c18d89cc362ff12dba0/src/python/WMCore/DataStructs/Fileset.py#L67

In any of these cases, I need to sort specifically with `reverse=True` to satisfy the unit test. So I think the unit test will updated as well.

**Comment by amaltaro** [comment]
@goughes Erik, I just noticed one of the problems I solved here: https://github.com/dmwm/WMCore/pull/10739
you had already resolved in this PR :) It might be worth it discussing it in our chat today.

**Comment by amaltaro** [comment]
From Dario's comment in: https://github.com/dmwm/WMCore/pull/10720#issuecomment-892021617
only the RunBased_t is really failing with something else than sorting the input files/fileset. So I'd suggest to remove those 3 other unit tests from the unstable list (if they are all marked as unstable):

@goughes Erik, can you please remove the relevant tests from the unstable list in:
https://github.com/dmwm/WMCore/blob/master/test/etc/UnstableTests.txt
?

Once that's done, I believe this is ready to be merged, right? I will then try to put it in in a new release tonight.

**Comment by goughes** [comment]
test this please

**Comment by goughes** [comment]
test this please

**Comment by goughes** [comment]
Here is a list of unstable tests after my last commit

- `WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest:testMultipleRunsCombine`
- `WMCore_t.WMBS_t.JobSplitting_t.EventBased_t.EventBasedTest:test100EventMultipleSite`

I will add some comments and squash my second commit shortly.

**Comment by mapellidario** [comment]
Regarding `WMCore_t.WMBS_t.JobSplitting_t.EventBased_t.EventBasedTest:test100EventMultipleSite`, I see going from failure to success consistently in last jenkins reports. Did i miss anything?

**Comment by goughes** [comment]
@mapellidario I was able to verify the `WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest:testMultipleRunsCombine
` test via local testing. It definitely is unstable. But, for `test100EventMultipleSite` I was relying on the output from Jenkins due to a cert error running the test locally. Maybe I misinterpreted all the results. Are you able to run this test manually with your setup?

**Comment by goughes** [comment]
I fixed my issue with the `test100EventMultipleSite` unit test and verified it runs with consistent success locally. I removed this test from the unstable list with my last commit. I think this one is ready for review @mapellidario

**Review by mapellidario — APPROVED** [review]
Thanks Erik! This looks great! Using [functools.cmp_to_key](https://docs.python.org/3/library/functools.html#functools.cmp_to_key) is a very nice solution, definitely better than the custom hacky function i would have come up with! :)
And also sorry for having sidetracked you by adding a couple more unittests into the mix

**Comment by amaltaro** [comment]
Erik, this code looks good to me, however, let me ask you a question.
AFAIU this functools code is a way to implement sorting compatible with both python versions, right? So I wonder if we could change the code from, for instance:
```
         mergeableFiles.sort(key=cmp_to_key(fileCompare)) if PY3 else mergeableFiles.sort(fileCompare)
```
to simply
```
         mergeableFiles.sort(key=cmp_to_key(fileCompare))
```
thus, not worrying about which python version we are working on.


I have executed unit tests for `WMCore_t/WMBS_t/JobSplitting_t/ParentlessMergeBySize_t.py`, with this variation, and all the PY2 and PY3 relevant unittests are successful. I could be missing something though(?)

**Comment by goughes** [comment]
@amaltaro you are correct, this logic is not needed. Thanks for the suggestion! It has been removed with my most recent commit and unit tests look good.

**Comment by amaltaro** [comment]
Wonderful! Thank you very much for the prompt follow up!

**Pull request merged**
