### PR TITLE
Update print statements from WMComponent/ directory

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Please merge

**Comment by ticoann** [comment]
Sorry Eric,  could you fix the conflict?

**Comment by ericvaandering** [comment]
@ticoann updated. Conflict was code you removed, so all good!

**Comment by ticoann** [comment]
Thanks Eric

**Pull request merged**
