### PR TITLE
Remove assignment default value for un/mergedLFN bases

### LINKED ISSUE #8002: Add validation to MergedLFNBase/UnmergedLFNBase arguments
We have these LFNs defined here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Tools/cms.py#L68

and unmerged just below it. I suggest we create a validate function in the Lexicon module and call that function from the StdSpecs validate function.

Or even better, we could have these MergedLFNBase lfns in the aux db

In addition to that:
* remove the assignment default values
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1092
* I don't know how correct are those "/store/results/" lfns, thus I'd suggest to validate it on `startswith('/store/results/')` and that's all, they are rarely used anyways and we can always enforce it to be assigned via script.

@ticoann what do you think?
BTW, slightly related to #7979

### PR DESCRIPTION
**Pull request by amaltaro**
Partially fixes #8002 
Possibly superseeds #8006 

I still have to test it.

### CODE REVIEW

**Comment by hufnagel** [comment]
This is not going to fix the Tier0 problem since the setAcquisitionEra, setProcessingString and setProcessingVersion calls all reset the LFNBases for the tasks. Without these calls being run aware this is not going to work for the Tier0.

**Comment by amaltaro** [comment]
But don't you set those during workflow creation? Then you simply don't set them during assignment again (as you're going to do for the LFN bases)

**Comment by hufnagel** [comment]
Hm, so I would only pass a minimal set of parameters to updateArguments, like before. I can give that a try.

**Comment by amaltaro** [comment]
That's right! Since T0 used to only "create" requests, I expect that to work out of the box and there is no need to override any of the output datasets related arguments during assignment.

Please let me know how it goes on the T0 side. I'm checking it on normal production env.

**Comment by hufnagel** [comment]
Ok, your patch doesn't work. Now for figuring out why...

**Comment by hufnagel** [comment]
Hm, let me test that some more. I think I might have looked at the wrong metrics plus there was interference from some other changes in that replay.

**Review by hufnagel — APPROVED** [review]
Seems to be working in Tier0 replays, code change also looks good. One thing, shouldn't we remove that FIXME comment line once we validate the changes ?

**Comment by amaltaro** [comment]
We already know how to validate these LFNs bases, but it's still not in place.
Thanks for testing it! I still have to check things on my end.

**Comment by hufnagel** [comment]
Found another problem. Can you also wrap the call to setMergeParameters and only call it if kwargs actually contains merge parameters ? This completely screws with any workflow that defines the forceMerged since that works by setting the merge parameters to 0 (so we always got to merged).

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
@ticoann from my side we can merge it. Feel free to go ahead and merge it please.

**Pull request merged**
