### PR TITLE
add api getting request by status and type

### LINKED ISSUE #6220: fixing bystatusandtype
could this view emit the status and type, and not the workflow name in addition ?

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6220, replace #6352

### CODE REVIEW

**Comment by ticoann** [comment]
@vlimant, Jean-Roch, I create the new view for bystatusandtype but please use following call instead of direct couch view(hasn't deployed yet)  - after this month production
Please don't use -archived status, that won't be supported. Let me know if you need to search archived status.

https://cmsweb.cern.ch/reqmgr2/data/request?status=new&request_type=Resubmission

it will return following format.
```
{"result": [
 {"sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_190722_1479": {"Group": "DATAOPS", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "InputDatasetTypes": {}, "OutputDatasets": ["/TTJets_MSDecays_matchingup_7TeV-madgraph/Integ_Test-MonteCarlo_PhEDEx_pnn_test-v1/GEN"], "RequestDate": [2015, 10, 7, 17, 7, 22], "AcquisitionEra": "Integ_Test", "PrepID": "TOP-Summer11LegwmLHE-00006", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836/Production", "RequestSizeFiles": 0, "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": null, "UpdateTime": 1444237643}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_190722_1479", "RequestString": "ACDC_MonteCarlo_PhEDEx_pnn_test", "InputDatasets": [], "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_190722_1479/spec", "Campaign": "Agent108_Validation", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "CouchDBName": "reqmgr_config_cache", "_id": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_190722_1479", "RequestStatus": "new", "RequestNumEvents": 0}, "sryu_ACDC_Test_151007_204635_3833": {"ReqMgr2Only": true, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "PrepID": "TOP-Summer11LegwmLHE-00006", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "Group": "DATAOPS", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "OriginalRequestCouchURL": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache", "RequestDate": [2015, 10, 7, 18, 46, 35], "CouchDBName": "reqmgr_config_cache", "CMSSWVersion": "CMSSW_5_3_19", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293/Production", "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "UpdateTime": 1444243595}], "RequestName": "sryu_ACDC_Test_151007_204635_3833", "RequestString": "ACDC_Test", "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_Test_151007_204635_3833/spec", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "_id": "sryu_ACDC_Test_151007_204635_3833", "RequestStatus": "new"}, "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_205152_4896": {"ReqMgr2Only": true, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "PrepID": "TOP-Summer11LegwmLHE-00006", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "Group": "DATAOPS", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "OriginalRequestCouchURL": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache", "RequestDate": [2015, 10, 7, 18, 51, 52], "CouchDBName": "reqmgr_config_cache", "CMSSWVersion": "CMSSW_5_3_19", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293/Production", "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "UpdateTime": 1444243912}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_205152_4896", "RequestString": "ACDC_MonteCarlo_PhEDEx_mc_lumi_validation", "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_205152_4896/spec", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "_id": "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_205152_4896", "RequestStatus": "new"}, "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185229_2780": {"Group": "DATAOPS", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "InputDatasetTypes": {}, "OutputDatasets": ["/TTJets_MSDecays_matchingup_7TeV-madgraph/Integ_Test-MonteCarlo_PhEDEx_pnn_test-v1/GEN"], "RequestDate": [2015, 10, 7, 16, 52, 29], "AcquisitionEra": "Integ_Test", "PrepID": "TOP-Summer11LegwmLHE-00006", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836/Production", "RequestSizeFiles": 0, "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": null, "UpdateTime": 1444236750}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185229_2780", "RequestString": "ACDC_MonteCarlo_PhEDEx_pnn_test", "InputDatasets": [], "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185229_2780/spec", "Campaign": "Agent108_Validation", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "CouchDBName": "reqmgr_config_cache", "_id": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185229_2780", "RequestStatus": "new", "RequestNumEvents": 0}, "sryu_ACDC_Test_151007_204723_8626": {"ReqMgr2Only": true, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "PrepID": "TOP-Summer11LegwmLHE-00006", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "Group": "DATAOPS", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "OriginalRequestCouchURL": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache", "RequestDate": [2015, 10, 7, 18, 47, 23], "CouchDBName": "reqmgr_config_cache", "CMSSWVersion": "CMSSW_5_3_19", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293/Production", "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "UpdateTime": 1444243643}], "RequestName": "sryu_ACDC_Test_151007_204723_8626", "RequestString": "ACDC_Test", "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_Test_151007_204723_8626/spec", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "_id": "sryu_ACDC_Test_151007_204723_8626", "RequestStatus": "new"}, "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_204100_3773": {"Group": "DATAOPS", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "InputDatasetTypes": {}, "OutputDatasets": ["/TTJets_MSDecays_matchingup_7TeV-madgraph/Integ_Test-MonteCarlo_PhEDEx_pnn_test-v1/GEN"], "RequestDate": [2015, 10, 7, 18, 41, 0], "AcquisitionEra": "Integ_Test", "PrepID": "TOP-Summer11LegwmLHE-00006", "CMSSWVersion": "CMSSW_5_3_19", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836/Production", "RequestSizeFiles": 0, "CouchWorkloadDBName": "reqmgr_workload_cache", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": null, "UpdateTime": 1444243261}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_204100_3773", "RequestString": "ACDC_MonteCarlo_PhEDEx_pnn_test", "InputDatasets": [], "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_204100_3773/spec", "Campaign": "Agent108_Validation", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "CouchDBName": "reqmgr_config_cache", "_id": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_204100_3773", "RequestStatus": "new", "RequestNumEvents": 0}, "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204237_4036": {"ReqMgr2Only": true, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "PrepID": "TOP-Summer11LegwmLHE-00006", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "Group": "DATAOPS", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "OriginalRequestCouchURL": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache", "RequestDate": [2015, 10, 7, 18, 42, 37], "CouchDBName": "reqmgr_config_cache", "CMSSWVersion": "CMSSW_5_3_19", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293/Production", "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "UpdateTime": 1444243357}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204237_4036", "RequestString": "ACDC_MonteCarlo_PhEDEx_mc_lumi_validation", "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204237_4036/spec", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "_id": "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204237_4036", "RequestStatus": "new"}, "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204142_2110": {"ReqMgr2Only": true, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "PrepID": "TOP-Summer11LegwmLHE-00006", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "Group": "DATAOPS", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "OriginalRequestCouchURL": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache", "RequestDate": [2015, 10, 7, 18, 41, 42], "CouchDBName": "reqmgr_config_cache", "CMSSWVersion": "CMSSW_5_3_19", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293/Production", "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "UpdateTime": 1444243302}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204142_2110", "RequestString": "ACDC_MonteCarlo_PhEDEx_mc_lumi_validation", "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_mc_lumi_validation_151006_211453_7293", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204142_2110/spec", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "_id": "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204142_2110", "RequestStatus": "new"}, "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185209_4335": {"Group": "DATAOPS", "Requestor": "sryu", "SizePerEvent": 1, "Memory": 2300, "ACDCServer": "https://reqmgr2-dev.cern.ch/couchdb", "RequestType": "Resubmission", "TimePerEvent": 0.98694, "InputDatasetTypes": {}, "OutputDatasets": ["/TTJets_MSDecays_matchingup_7TeV-madgraph/Integ_Test-MonteCarlo_PhEDEx_pnn_test-v1/GEN"], "RequestDate": [2015, 10, 7, 16, 52, 9], "AcquisitionEra": "Integ_Test", "PrepID": "TOP-Summer11LegwmLHE-00006", "InitialTaskPath": "/sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836/Production", "RequestSizeFiles": 0, "RequestorDN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu", "RequestPriority": 80000, "RequestTransition": [{"Status": "new", "DN": null, "UpdateTime": 1444236730}], "RequestName": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185209_4335", "RequestString": "ACDC_MonteCarlo_PhEDEx_pnn_test", "InputDatasets": [], "CouchURL": "https://reqmgr2-dev.cern.ch/couchdb", "CouchWorkloadDBName": "reqmgr_workload_cache", "OriginalRequestName": "sryu_MonteCarlo_PhEDEx_pnn_test_151007_062052_9836", "RequestWorkflow": "https://reqmgr2-dev.cern.ch/couchdb/reqmgr_workload_cache/sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185209_4335/spec", "Campaign": "Agent108_Validation", "ACDCDatabase": "acdcserver", "DbsUrl": "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader", "SoftwareVersions": ["CMSSW_5_3_19"], "CouchDBName": "reqmgr_config_cache", "_id": "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185209_4335", "RequestStatus": "new", "RequestNumEvents": 0}}
]}
```

If you only needs request name as return value use detail=false option

https://cmsweb.cern.ch/reqmgr2/data/request?status=new&request_type=Resubmission&detail=false

```
{"result": [
 {"sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_190722_1479": null, "sryu_ACDC_Test_151007_204635_3833": null, "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_205152_4896": null, "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185229_2780": null, "sryu_ACDC_Test_151007_204723_8626": null, "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_204100_3773": null, "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204237_4036": null, "sryu_ACDC_MonteCarlo_PhEDEx_mc_lumi_validation_151007_204142_2110": null, "sryu_ACDC_MonteCarlo_PhEDEx_pnn_test_151007_185209_4335": null}
]}
```

**Comment by vlimant** [comment]
Hi, can you please indicate what is the view in reqmgr1 so that we can work with this prior to the transition ? or is it never going to be available from https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/_design/ReqMgr ?

**Comment by ticoann** [comment]
> Hi, can you please indicate what is the view in reqmgr1 so that we can work with this prior to the transition ? or is it never going to be available from 
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/_design/ReqMgr ?

There is no view supporting what you want now. This patch include the new couch view as well so new view won't be available before the production reqmgr is deployed anyway.

The reason I want you to use reqmgr2 api instead of direct couch api.
1. it is more secure and we might remove any direct access to couch db.
2. I wanted to fix this view instead of creating the new view but there are many ops code using this currently but eventually I want to fixe this view and remove the view just created.  https://github.com/dmwm/WMCore/blob/master/src/couchapps/ReqMgr/views/bystatusandtype/map.js

**Comment by ticoann** [comment]
test this please

**Pull request merged**
