### PR TITLE
fixes This result object does not return rows error

### LINKED ISSUE #6732: WMCore doesn't work with sqlalchemy 1.0.12
Posted about it in HN

https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1424.html

The full error from agent deployment is

DEBUG:root:Problem creating database table

CREATE TABLE wmbs_fileset (
               id          INTEGER      NOT NULL,
               name        VARCHAR(700) NOT NULL,
               open        CHAR(1)      CHECK (open IN ('0', '1' )) NOT NULL,
               last_update INTEGER      NOT NULL
               )

This result object does not return rows. It has been closed automatically.
Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/bin/wmcore-db-init", line 156, in <module>
    create(cfgObject)
  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/bin/wmcore-db-init", line 131, in create
    wmInit.setSchema(modules, params = params)
  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/WMInit.py", line 170, in setSchema
    transaction = myThread.transaction)
  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/WMBS/CreateWMBSBase.py", line 483, in execute
    DBCreator.execute(self, conn, transaction)
  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/Database/DBCreator.py", line 66, in execute
    raise WMException(msg,'WMCORE-2')
WMCore.WMException.WMException: WMException
Message: Problem creating database table

CREATE TABLE wmbs_fileset (
               id          INTEGER      NOT NULL,
               name        VARCHAR(700) NOT NULL,
               open        CHAR(1)      CHECK (open IN ('0', '1' )) NOT NULL,
               last_update INTEGER      NOT NULL
               )

This result object does not return rows. It has been closed automatically.
        ModuleName : WMCore.Database.DBCreator
        MethodName : execute
        ClassInstance : None
        FileName : /data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/Database/DBCreator.py
        ClassName : None
        LineNumber : 66
        ErrorNr : WMCORE-2

Traceback:
  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/Database/DBCreator.py", line 61, in execute
    transaction = transaction)

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 150, in processData
    returnCursor=returnCursor)

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 71, in executebinds
    result.add(resultProxy)

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.15.pre1/lib/python2.7/site-packages/WMCore/Database/ResultSet.py", line 38, in add
    for r in resultproxy:

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/external/py2-sqlalchemy/1.0.12/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 713, in __iter__
    row = self.fetchone()

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/external/py2-sqlalchemy/1.0.12/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1026, in fetchone
    self.cursor, self.context)

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/external/py2-sqlalchemy/1.0.12/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/external/py2-sqlalchemy/1.0.12/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1017, in fetchone
    row = self._fetchone_impl()

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/external/py2-sqlalchemy/1.0.12/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 900, in _fetchone_impl
    return self._non_result(None)

  File "/data/tier0/srv/wmagent/2.0.2/sw.hufnagel/slc6_amd64_gcc493/external/py2-sqlalchemy/1.0.12/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 920, in _non_result
    "This result object does not return rows. "

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6732, This hasn't been tested need to be tested both 0.9.6 and 1.0.12 version of sqlarchemy

### CODE REVIEW

**Comment by amaltaro** [comment]
@ticoann I'm running central services and agent with this patch (1.0.15.pre1 as it is now in cmsdist).
I'll let you know about the outcome tomorrow.

**Comment by amaltaro** [comment]
@ticoann I haven't seen any issues with the agent and reqmgr

**Comment by ticoann** [comment]
Thanks Alan,

**Comment by ticoann** [comment]
It seems the patch fixes the issues in sqlalchemy 1.0.12 as well. (Also consulted with Yuyi about the patch). Merging it

**Pull request merged**
