### PR TITLE
fix memory problem on error handler

### PR DESCRIPTION
**Pull request by ticoann**
replace #8623 
Create only one instance of Run object for the duplicate file. It still creates duplicate files object (WMBSFile) but only one Run object is shared for multiple file object. It might be better to create only one file object as well. I think when the job mask runs I am not sure whether it is needed to have a separate file object. (It seems it doesn't need that though)

### CODE REVIEW

**Comment by ticoann** [comment]
It seems #8623 actually works. However, this would me more elegant solution and in case of MCFake file this will give more performance advantage when maxProcessSize is larger with the same memory usage. (If there are so many MCFake failure) I will try to run the test for this patch.

**Comment by ticoann** [comment]
@amaltaro, Alan please review.

**Comment by amaltaro** [comment]
Patch looks good Seangchan. Unless there are several different workflows with tons of lumis, it should indeed save quite some memory usage.

**Comment by ticoann** [comment]
Hope there is no case like that. :-)

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Hi Alan I ran the test for this. Also tested in submit5 as well.  Just crash the component before it upload can compare the result with the patch and without patch. So I think it is ready to patch the agents. I will create the branch patch.

**Comment by amaltaro** [comment]
Thanks, Seangchan. I'll push this patch in the agents right now then.

**Review by amaltaro — APPROVED** [review]

**Comment by ticoann** [comment]
Thanks Alan, Didn't anything blow up?

**Pull request merged**
