### PR TITLE
Home changes

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by ticoann** [comment]
Thanks, Valentin. That looks nice. I will merge this after cmsweb production deployment tomorrow. 
I updated https://reqmgr2-dev.cern.ch/reqmgr2/

**Comment by ticoann** [comment]
Valentin, I think may be we should leave out the archived workflow link from the front page. This will be too many in production ~40K. Noway people want to look through that many workflows. :smile:

**Comment by vkuznet** [comment]
That's fine. we just need to define a list to skip. You certainly have better ideas on the amount of workflow within each step, therefore it is up to you to define this list. But on another hand if we introduce a pagination it can handle any amounts.

**Comment by ticoann** [comment]
Hi Valentin, You can use this list for only active status display. (list to keep)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py#L71

Sorry there was conflict with your other patch. (Could you update this patch) Thanks,

**Comment by vkuznet** [comment]
Seangchan,
I merged and resolved conflict, please review and merge.
Valentin.

**Comment by ticoann** [comment]
Hi Valentin, Could you combine the commit? Sorry for the hassle.

**Comment by vkuznet** [comment]
Seangchan, it seems to me that this PR captured other changes and to avoid any mess-up I created a new PR with one commit, please take PR https://github.com/dmwm/WMCore/pull/5604 and discard this one.

**Comment by ticoann** [comment]
Thanks Valentin I am closing this then.

**Pull request closed without merging**
