### PR TITLE
1.1.0_wmagent version of add Campaign and PrepID in fwjr

### PR DESCRIPTION
**Pull request by ticoann**
1.0.21 wmagent version of #7664

### CODE REVIEW

**Comment by ticoann** [comment]
Still need to update to all the agent

**Comment by ticoann** [comment]
@amaltaro, To convince Alan that it was tested. 😄 

screen shot 2017-03-09 at 2 31 57 pm

**Comment by amaltaro** [comment]
Fake picture :P

**Comment by ticoann** [comment]
It is hard to trick you :-)

**Comment by amaltaro** [comment]
FYI @ticoann @vkuznet this patch has been pushed to all the production agents as of yesterday later in the afternoon.

**Pull request merged**
