### PR TITLE
Enforce primary dataset to start with a letter - Lexicon

### PR DESCRIPTION
**Pull request by amaltaro**
As reported by Antanas @anorkus , we allow two different regex for the primary dataset.
Questions are:
1) can the PD start with a number (or dot, dash, underscore)?
2) is there any reason to keep both regex (maybe some legacy data dating back to DBS2?)?

@belforte @ericvaandering @yuyiguo @ticoann maybe you know it better, since there was some discussion back a few years in this PR https://github.com/dmwm/WMCore/pull/4973/files

### CODE REVIEW

**Comment by amaltaro** [comment]
BTW. I'm not fixing those unittests until I have a word on whether it makes sense or not.

**Comment by ericvaandering** [comment]
It would be interesting to see what is in DBS, but I don't think primary or secondary should be allowed to start with ., -, _ for sure and perhaps not a number.

**Comment by amaltaro** [comment]
DBS is using this same function (so both regex ATM):
https://github.com/dmwm/DBS/blob/34efdec694c31c5084abb2ebf3358f134a96ea23/Server/Python/src/dbs/utils/DBSInputValidation.py#L87

**Comment by yuyiguo** [comment]
DBS does not allow to have number, . or _ as the starting part of any names, such as dataset, block or lfn. What Alan changed is not affect to DBS because the primdataset function will do the same thing before and after the patch. DBS checks the primary ds first so the block checking later will not affect the ds.

**Comment by ticoann** [comment]
I think the change is fine. It seems we don't allow primary dataset name start with 0 either.  I think unittest needs to be fixed though. 😄

**Comment by amaltaro** [comment]
I was pretty sure there was a logical OR between those checks ... indeed it won't change anything. I'll fix the unit tests tomorrow and this will go in in the March cmsweb deployment then.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
YESS!!!!!!!!!

**Comment by ticoann** [comment]
So Jenkins works. :-)

**Review by ticoann — APPROVED** [review]

**Pull request merged**
