### PR TITLE
Decouple PhEDEx from the DBS3Reader wrapper module - crab branch

### PR DESCRIPTION
**Pull request by amaltaro**
crab branch version for https://github.com/dmwm/WMCore/pull/9927
Note that changes unrelated to CRAB have been dropped here (like workqueue, etc).

### CODE REVIEW

**Comment by amaltaro** [comment]
@belforte Stefano, in case you want to run some tests before the day comes...
Please let me know when you want this merged. I assume it will be when we are ready to switch to Rucio(?)

**Comment by belforte** [comment]
Thanks @amaltaro . In principle yes, we merge when we do not want/need to fall back to PhEDEx location anymore. But since I need to change code more then expected anyhow, I can look into making it possible to use this immediately and be done with changes.

**Comment by belforte** [comment]
I tested with your branch https://github.com/amaltaro/WMCore/tree/fix-9869-crab and it works. But of course it does not support falling back to PhEDEx.
But given that migration is not done by datasets and is almost done, I doubt there is any case where the fallback woiuld be needed.

**Comment by belforte** [comment]
Hi @amaltaro CRAB if ready for this at last. Sorry, I started early but did not progress quickly. Please merge and create  a new tag.

**Comment by amaltaro** [comment]
No problem, Stefano! There you go:
```
1.3.6.crab3 tagged
```

**Comment by belforte** [comment]
thanks

**Pull request merged**
