### PR TITLE
Limit long jobs by estimated time limit instead of events per lumi - …

### PR DESCRIPTION
**Pull request by amaltaro**
…wmagent
WMAgent branch version of #8398 and #8426

@ticoann can you please review? I still want to run some simple tests tomorrow morning before pushing it to production.

### CODE REVIEW

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
Thanks Alan, patch looks good.

**Comment by amaltaro** [comment]
I had to make `eventLimit` default to 0 otherwise it was raising an exception. I'm glad we did a quick test before pushing it to prod :)

**Comment by amaltaro** [comment]
[Fix #8439 - Limit long jobs by estimated time limit instead of events per lumi](https://trello.com/c/Z7f1ikDq/79-fix-8439-limit-long-jobs-by-estimated-time-limit-instead-of-events-per-lumi)

**Comment by amaltaro** [comment]
It has been pushed to the prod agents.

**Comment by ticoann** [comment]
Thanks Alan.

**Pull request merged**
