### PR TITLE
Handle HTTP in the pycurl response header

### LINKED ISSUE #8882: pycurl_manager fails when remote server header contains GRIDHTTP_PASSCODE
I have found that when authenticating via a service certificate, CRIC server returns the following header [1], while when using a personal proxy it returns [2].
The problem with [1] is that it breaks pycurl_manager.py code in here
https://github.com/dmwm/WMCore/blob/c23a66cacdf7750121cbf62c87e811252ae7a05c/src/python/WMCore/Services/pycurl_manager.py#L74-L80
because the  line with `GRIDHTTP_PASSCODE` is interpreted as an `HTTP/.1.1. nnn ttttt` one and the code tries to assign the strings following it to status and reason, and thus the line
https://github.com/dmwm/WMCore/blob/c23a66cacdf7750121cbf62c87e811252ae7a05c/src/python/WMCore/Services/pycurl_manager.py#L80
raises an exception since `status` is not a number [3]

This was never noticed because CMSWEB always returnes headers of kind [2] (at least in the calls I saw running CRAB TaskWorker) and WMA deployments/tests always use operator proxy as credential (IIUC).

I am going to ask CRIC developers why the different headers, but for all I know (which is little) header [2] looks legal to me and works if minimally modify pycurl_manager code. So I believe that if would be good to make the parsing less fragile. E.g. changing `row.find('HTTP')` to `row.find('HTTP'/)` is enough !
I can make a PR with that, still looks a bit fragile though, maybe we want to make sure that HTTP is the first string of the header line instead ? So go for `row.find('HTTP')==0` in place of  `row.find('HTTP')!=-1`.
Would be better if someone who knows what HTTP specifications are, gives solid instructions.

More on the history of this bug discovery in this thread: https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2788/1/1/1/1/1.html

[1]
```
HTTP/1.1 200 OK
Date: Tue, 30 Oct 2018 15:23:26 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 mod_gridsite/2.3.4
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Set-Cookie: csrftoken=nlu6EiwuwEcyHgGaRQ9I6otz6wH88jC7OeRx2jjyAIgYPlvHAuTHDimooskiVSCm; expires=Tue, 29-Oct-2019 15:23:26 GMT; Max-Age=31449600; Path=/
Set-Cookie: sessionid=2vaa554o6cty3lintjvwzd5v00gyjs42; expires=Sun, 04-Nov-2018 15:23:26 GMT; httponly; Max-Age=432000; Path=/
Strict-Transport-Security: max-age=300; includeSubDomains
Set-Cookie: GRIDHTTP_PASSCODE=2c6da9c96efa2ad0farhda; domain=cms-cric.cern.ch; path=/; secure
Content-Length: 37354
Content-Type: application/json
```
[2]
```
HTTP/1.1 200 OK
Date: Tue, 30 Oct 2018 15:23:26 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/3.4 Python/2.7.5 mod_gridsite/2.3.4
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Set-Cookie: csrftoken=VPUDCTFhVVksPki5FvWKDQbCrm96oYdyUeioJBFTYJ8ESJt3pcYemqux6Xw13ub5; expires=Tue, 29-Oct-2019 15:23:26 GMT; Max-Age=31449600; Path=/
Set-Cookie: sessionid=0p59a1gjkjn2o62pzdax0qvevibfi7ng; expires=Sun, 04-Nov-2018 15:23:26 GMT; httponly; Max-Age=432000; Path=/
Strict-Transport-Security: max-age=300; includeSubDomains
Content-Length: 37354
Content-Type: application/json
```

[3]
```
  File "/data/user/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 84, in parse
    self.status = int(status)
ValueError: invalid literal for int() with base 10: 'Set-Cookie:'
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8882
Superseeds #8883

HTTP header/response format seems to be well defined, looking at:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages

The only real change is:
* Search for `HTTP/\d.\d \d{3}` (e.g. HTTP/1.1 200) at the very beginning of the header line.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Review by vkuznet — COMMENTED** [review]
Looks good to me, but it would be better if you'll not mix style adjustments with actual fix of functionality, because it is harder to follow.

**Comment by amaltaro** [comment]
Yes, you don't need to look at the second commit Valentin. We always push real changes into the 1st commit only, 2nd is for unit tests, pylint fixed, safe code refactoring. Thanks!

**Comment by belforte** [comment]
thanks. Looks good to me. I closed #8883 Let it be superseeded

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
I don't get why this WMInit test keeps failing, none of these changes should affect that test.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@belforte is there any easy way you can test these changes (just to see whether it breaks something)?
We still don't use pycurl in WMCore services, so it's a bit problematic to get it properly tested (besides unit tests).

Another option is to merge it and give you a new tag soon, and you keep it in mind when testing a new tag. I'm fine either way.

**Comment by belforte** [comment]
@amaltaro I forgot to mention that I put this  in in preprod CRAB yesterday
https://cms-logbook.cern.ch/elog/Analysis+Operations/2341
I believe that you can merge and tag whenever convenient.

**Review by ticoann — APPROVED** [review]

**Pull request merged**
