### PR TITLE
Fix for agents by team call

### PR DESCRIPTION
**Pull request by amaltaro**
global_workqueue doc broke this code.

### CODE REVIEW

**Comment by amaltaro** [comment]
In theory we should also backport it to 1.0.23, in practice I think we can just leave that as it is (using the default value).

**Comment by ticoann** [comment]
Yes we don't have to back port. Let's just add on the new agent.

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
@amaltaro, Alan this was added, right?

**Comment by amaltaro** [comment]
Yes, it's already in the wmagent branch (#7616) and applied to all production agents.

**Pull request merged**
