### PR TITLE
Fix bug injected in #6512 retrieving lumi from task

### PR DESCRIPTION
**Pull request by amaltaro**
I was mislead by my tests with a single run... sorry!
Testing it again in my VM to make sure I don't screw with testbed again :)

PS.: this is the simple fix, a whole new fix will be made only for March deployment.

### CODE REVIEW

**Comment by ericvaandering** [comment]
Whole new fix involves the #6533 code, I presume?

**Comment by amaltaro** [comment]
Yep! ;)

**Comment by amaltaro** [comment]
@ticoann tested in my VM and it's good to go. 

Can you please merge it and create a new tag (pre8?)
Then I can make a PR to cmsdist tomorrow early in the morning (off to bed now).

**Comment by ticoann** [comment]
Thank you very much, Alan. I will make the PR as well. You need some more vacation, you are working too much :smile:

**Pull request merged**
