### PR TITLE
1.1.14_wmagent branch (production agent need to be patched) set the dataset parentage for StepChain

### PR DESCRIPTION
**Pull request by ticoann**
1.1.14_wmagent version of #8676. This patch needs to be applied all the production agent before cmsweb upgrade (HG1809)

### CODE REVIEW

**Comment by amaltaro** [comment]
This patch  has been applied to all 1.1.14 production agents.

**Comment by amaltaro** [comment]
[Fix #8756 - set the dataset parentage for StepChain](https://trello.com/c/Al9bcUc5/123-fix-8756-set-the-dataset-parentage-for-stepchain)

**Comment by amaltaro** [comment]
Seangchan, this works :-) But we better keep an eye on it, I don't really like the time it took to fix the parentage for this GEN-SIM-RAW dataset in testbed:
```
2018-09-04 11:28:25,760:INFO:StepChainParentageFixTask:Fixed /Chib2PToUpsilon2SGamma_TuneCP5_13TeV-pythia8-evtgen/Integ_Test-StepChain_ReDigi3_HG1809_Validation_TEST_Alan_v14-v11/MINIAODSIM parentage: 1 out of 2 datasets. time took: 0 (sec)
2018-09-04 11:28:36,843:INFO:StepChainParentageFixTask:Fixed /Chib2PToUpsilon2SGamma_TuneCP5_13TeV-pythia8-evtgen/Integ_Test-StepChain_ReDigi3_HG1809_Validation_TEST_Alan_v14-v11/GEN-SIM-RAW parentage: 2 out of 2 datasets. time took: 11 (sec)
2018-09-04 11:28:37,060:INFO:StepChainParentageFixTask:Total 1 requests' ParentageResolved flag is set to True
```

this is the summary of the parent:
[{"num_file": 769, "num_lumi": 5379, "num_block": 73, "num_event": 4843129, "file_size": 2508499171639}]

so I quite small dataset.

**Comment by ticoann** [comment]
Are you saying it is too fast. :smile: Actually, it seems it depends on the  more of lumis than number of files but doesn't seem to be proportional to the size either. I don't think 11 sec is that bad but we will have to see more examples.

**Pull request merged**
