### PR TITLE
Custom err message

### PR DESCRIPTION
**Pull request by juztas**
Currently if any regular expression will not match, user will get error like

```
Incorrect edmoutfiles parameter
Invalid edmoutfiles parameter
```

Like this validation call validate_strlist("edmoutfiles", param, safe, RX_OUTFILES) 

With this patch you can specify 

```
validate_str("workflow", param, safe, RX_WORKFLOW, optional=False, custom_err = "Taskname has to agree on this regular expression '%s'. Your specified taskname: '%%s'. Please double check this regular expression matching or contact experts." % RX_WORKFLOW.pattern)
```

and you will have custom error with more information and this can be reused also in Reqmgr SiteDB, etc...

```
Reason is: Taskname has to agree on this regular expression '^[a-zA-Z0-9\-_:]{1,232}$'. Your specified taskname: 'crab_private_test4+++++'. Please double check this regular expression matching or contact experts.
```

More details : https://github.com/dmwm/CRABServer/issues/4588

@mmascher @ericvaandering 

P.S. I did knew there better to put `return_message` function, so I put in same Validation.py

### CODE REVIEW

**Comment by ericvaandering** [comment]
When you write these error messages, let me see them. Your example could be improved a bit. Why not use named parameters in the messages: http://www.diveintopython.net/html_processing/dictionary_based_string_formatting.html <http://www.diveintopython.net/html_processing/dictionary_based_string_formatting.html> rather than relying on the order being static?

Eric





> On Jan 8, 2015, at 04:09, Justas Balčas <notifications@github.com> wrote:
> 
> Currently if any regular expression will not match, user will get error like
> 
> Incorrect edmoutfiles parameter
> Invalid edmoutfiles parameter
> Like this validation call validate_strlist("edmoutfiles", param, safe, RX_OUTFILES)
> 
> With this patch you can specify
> 
> validate_str("workflow", param, safe, RX_WORKFLOW, optional=False, custom_err = "Taskname has to agree on this regular expression '%s'. Your specified taskname: '%%s'. Please double check this regular expression matching or contact experts." % RX_WORKFLOW.pattern)
> and you will have custom error with more information and this can be reused also in Reqmgr SiteDB, etc...
> 
> Reason is: Taskname has to agree on this regular expression '^[a-zA-Z0-9\-_:]{1,232}$'. Your specified taskname: 'crab_private_test4+++++'. Please double check this regular expression matching or contact experts.
> More details : dmwm/CRABServer#4588 <https://github.com/dmwm/CRABServer/issues/4588>
> @mmascher <https://github.com/mmascher> @ericvaandering <https://github.com/ericvaandering>
> P.S. I did knew there better to put return_message function, so I put in same Validation.py
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/juztas/WMCore custom_err_message
> Or view, comment on, or merge it at:
> 
>   https://github.com/dmwm/WMCore/pull/5559 <https://github.com/dmwm/WMCore/pull/5559>
> Commit Summary
> 
> Merge branch 'master', remote branch 'origin/master'
> Merge branch 'master', remote branch 'origin/master'
> Possibility to raise own error message
> File Changes
> 
> M src/python/WMCore/REST/Validation.py <https://github.com/dmwm/WMCore/pull/5559/files#diff-0> (81)
> Patch Links:
> 
> https://github.com/dmwm/WMCore/pull/5559.patch <https://github.com/dmwm/WMCore/pull/5559.patch>
> https://github.com/dmwm/WMCore/pull/5559.diff <https://github.com/dmwm/WMCore/pull/5559.diff>
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/WMCore/pull/5559>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by ticoann** [comment]
@juztas, Hi Justas, How about just adding argument and value in the InvalidParameters, shouldn't that be enough? If you want to be more clear why it is failed. you can add the specific reason for each function. (i.e. regular expression doesn't match), Since all the functions are doing small thing and checking one thing, I am not sure about custom error message is needed.

**Comment by juztas** [comment]
Hey @ticoann Sorry for delay. From my side it is fine what we had. I can view code and identify there the problem is. But this custom error message is needed for users as we are exposing this message to users. Also we want more info for user what they should do or how to solve, but to write these error messages I will leave for Stefano/Marco in CRABServer. Now I fixed it and not relying on static order.

**Comment by ericvaandering** [comment]
@ticoann is this OK for you now?

**Comment by ticoann** [comment]
Hi Justas, Sorry for the late reply. 
One thing I want to point out is it is a little complicated since the custom_err requires specify format of string. which need to incluede something like following. "....%(argname), %(val)... "

I think it might be better changing the return function, so it just take any custom_err string.
If you need to overwrite the original message, we can just overwrite whatever custom_err says. 
And it is the programers responsibility to specify if he want to specify args or values.

``` python
def return_message(main_err, custom_err):
    if custom_err:
        return custom_err
    return main_err
```

**Comment by ticoann** [comment]
Also it doesn't change message value when string is pass to InvalidParameter  but self.info
InvalidParameter("some message")

I think most browser doesn't only display message not info. (I might be wrong on this), Does your change works when call is made from browser?

**Comment by mmascher** [comment]
No, the messages are not shown in the browser, but the CRAB3 client checks for the HTTP headers and display the message to the users.

**Comment by ticoann** [comment]
Thanks Marco, for the information. Justas, Could you update the code if you agree on the change?
I will merge the code then.
1. not using specific format for custom error string.
2. squash the commit in one.

**Comment by mmascher** [comment]
Can you tell me if you create a WMCore tag with #5649 and this one please?

**Comment by ticoann** [comment]
Sure Marco, I will create a new tag when Justas update this patch and let you know.

**Comment by juztas** [comment]
@ticoann can you review ?

**Comment by ticoann** [comment]
Thanks Justas.

**Pull request merged**
