### PR TITLE
add MaxRSS etc per task in task chain workflow

### LINKED ISSUE #5940: Create task chain params for MaxRSS, etc
similar to #5937

### PR DESCRIPTION
**Pull request by ticoann**
fixes #5940. Initial patch - need to be tested. Also need to update unittest. (Please don't merge yet)
For task chain, workflow level performance monitoring shouldn't be defined in assignment stage, otherwise it will be overwritten. The value need to be defined in creation stage defining assignment stage doesn't work.

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, does these value (MaxRSS etc) need to be defined in assignment stage?

**Comment by amaltaro** [comment]
Hi Seangchan, the correct thing would be defining these values during assignment, since it's up to CompOps to decide them (not PPD, though we use their Memory provided to define that...).
It can also get confused if we have these settings at creation level only for TaskChain and at assignmnent for all the others.

In addition to that, I really think we do _not_ need to have 'SoftTimeout' and 'GracePeriod' defined for each task, it should not change among tasks. So we need to update only MaxRSS and MaxVSize.

**Comment by ticoann** [comment]
Thanks Alan, you are right. I will change in assignment stage. (It is a little more complicated to do that. I guess do it write is more important). I think we need to have general rule. 
If a parameter is set in workflow level it will be set for all the tasks, but if task level is set it will overwrite initial workflow level values. I will create the new patch.

**Comment by ticoann** [comment]
How about MaxMemory? Should that be in create stage?

**Comment by amaltaro** [comment]
This applies only for TaskChain workflows and the general rule should be:
 - if a parameter is set for the whole workflow but not for any task, then use it and set it for all the tasks
 - if a parameter is set only for task, well, then we don't really need it for the whole workflow, just use those provided by task
 - if a parameter is given both for whole workflow and task, use the task one

About MaxMemory, hmmmm, it sounds like a leftover from some old cleanup to me. I really don't remember anything about it. Maybe it's used only by T0?
PS.: Go sleep! :P

**Comment by amaltaro** [comment]
Seangchan, a good hint to develop this feature (change) :-)
In the current assignment of TaskChain workflows, we provide a dict for a few fields, examples are AcquisitionEra and ProcessingString, e.g.:
"AcquisitionEra": {"DIGIPU1": "CMSSW_7_0_0_pre11", "RECOPU1": "CMSSW_7_4_2"}

I believe this is what we would need to aim here, e.g.:
"MaxRSS" : {"DIGI": 8000000, "RECO" : 4000000}

**Comment by ticoann** [comment]
Thanks Alan, I changed that to put the params (AcquistionEra, etc) under tasks. (Actually supports both)
Isn't something like following more consistent, since we are setting other task level params that way?
Task1: {'MaxRSS': ...},
Task2: {'MaxRSS': ...}

**Comment by amaltaro** [comment]
Hi Seangchan,
> I changed that to put the params (AcquistionEra, etc) under tasks.

some of them should be under tasks already (at least those I mentioned), so no changes are needed here.

About your suggestion, it sound more clear to me, though in this case there would be breaking changes (at least on the assignment side) and probably more changes to make eveything task-based work like that, it's better to change the least possible at this point IMO.

**Comment by ticoann** [comment]
> About MaxMemory, hmmmm, it sounds like a leftover from some old cleanup to me. I really don't remember anything about it. Maybe it's used only by T0?

Sorry I meant actually Memory params, Is that need to be set in assigned phase as well?

**Comment by amaltaro** [comment]
Ahh, no no. Memory is set during request creation only, which BTW is working perfectly fine in testbed now :-)

**Comment by ticoann** [comment]
Alan, could you take a quick look at it? I still need to test and add the unittest. (Set the value for assign stage)
``` python
"assignRequest":
{  

"Tasks": {"ProdMinBias":  {"MaxRSS": 1234}
                  "
    "SiteWhitelist": [],
    "Team": "Team-OVERRIDE-ME",
    "AcquisitionEra": {"ProdMinBias" : "AcquisitionEra-OVERRIDE-ME",
                       "DIGIPROD1" : "AcquisitionEra-1-OVERRIDE-ME",
                       "RECOPROD1" : "AcquisitionEra-2-OVERRIDE-ME"},
    "ProcessingString": {"ProdMinBias" : "ProcessingString-OVERRIDE-ME",
                         "DIGIPROD1" : "ProcessingString-1-OVERRIDE-ME",
                         "RECODreHLT" : "ProcessingString-2-OVERRIDE-ME"},
    "Dashboard": "Dashboard-OVERRIDE-ME",
    "SiteBlacklist": [],
    "MergedLFNBase": "/store/relval",
    "UnmergedLFNBase": "/store/unmerged",
    "MinMergeSize": 2147483648,
    "MaxMergeSize": 4294967296,
    "MaxMergeEvents": 100000,
    "ProcessingVersion": 1,
    "MaxRSS": 3072000,
    "MaxVSize": 20294967,
    "SoftTimeout": 129600,
    "GracePeriod": 1000,
    "CustodialSites": [],
    "NonCustodialSites": [],
    "AutoApproveSubscriptionSites": [],
    "SubscriptionPriority": "Low",
    "CustodialSubType" : "Move",
    "BlockCloseMaxWaitTime" : 72000,
    "BlockCloseMaxFiles" : 500,
    "BlockCloseMaxEvents" : 200000000,
    "BlockCloseMaxSize" : 5000000000000
}
```

**Comment by amaltaro** [comment]
I'd choose the first format too. However, I'd really prefer the same format as AcquisitionEra
```
"MaxRSS": {"ProdMinBias" : 2000,
                     "DIGIPROD1" : 3000,
                     "RECOPROD1" : 2500}
```
But I believe this is out of question ... :-D

**Comment by ticoann** [comment]
Whatever you want. :smile:  dict format is supported now.

**Comment by ticoann** [comment]
I think this need to be cleanup later though. But I will try to test and request to put in the testbed today

**Comment by ticoann** [comment]
Merging it for the testbed update (change the code to support only 

``` python
"assignRequest":
{"MaxRSS": 3072000,
  "MaxVSize": 20294967,
  "SoftTimeout": 129600,
  "GracePeriod": 1000,
  "Task1": {"TaskName": "ProdMinBias", 
                 "MaxRSS": 1234},
  "Task2": {"TaskName":  "DIGIPROD1" :
                 "MaxVSize: 3456},
  "TaskChain": 2
   }
```
and

```
"MaxRSS": {"ProdMinBias" : 2000,
                     "DIGIPROD1" : 3000,
                     "RECOPROD1" : 2500}
```

**Pull request merged**
