### PR TITLE
[CouchDB] New CouchDB 3.x APIs for tracking replications; fix replication check in AgentStatusPoller

### LINKED ISSUE #11037: CouchDB 3.x: AgentStatusWatcher fails to parse document source_seq attr
**Impact of the bug**
WMAgent using CouchDB 3.x

**Describe the bug**
While testing a private build of WMAgent 1.5.7.patch2 + CouchDB 3.1, I noticed that AgentStatusWatcher fails with this error [1]

In addition to that exception, note that `CouchServer` is also reported as being down, but actually it's not.

**How to reproduce it**
None

**Expected behavior**
Needs further investigation, but that `source_seq` seems to be an integer followed by a uid hash, so we cannot cast it to integer.
Hopefully fixing this will also fix the "CouchServer is down"

**Additional context and error message**
[1]
```
2022-03-12 18:16:42,249:140419360032512:INFO:AgentStatusPoller:Getting agent info ...
2022-03-12 18:16:42,970:140419360032512:ERROR:CMSCouch:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.7.patch2-127c31293503ab5f4da2da887a06775a/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.7.patch2-127c31293503ab5f4da2da887a06775a/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 1249, in checkCouchServerStatus
    replicationFlag = self.checkReplicationStatus(activeStatus, dbInfo, source,
  File "/data/srv/wmagent/v1.5.7.patch2-127c31293503ab5f4da2da887a06775a/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.7.patch2-127c31293503ab5f4da2da887a06775a/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 1269, in checkReplicationStatus
    updateNum = int(activeStatus["source_seq"])
ValueError: invalid literal for int() with base 10: '664-g1AAAACheJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVCJDUv3___-zMpiTGBgY83KBYuzmyaZmFmnG2PTgMSmPBUgyNACp_wgDtcAGphqmpZmbWWDTmgUA14Ao_w'

2022-03-12 18:16:43,025:140419360032512:INFO:AgentStatusPoller:CouchDB is running with 5 processes
2022-03-12 18:16:43,025:140419360032512:INFO:AgentStatusPoller:List of agent components down: ['TaskArchiver', 'CouchServer']
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #11037 

#### Status
ready
Tested with WMAgents running with both CouchDB versions.

#### Description
This PR provides the following fixes and/or new features:
* fix how the replication document is created for local workqueue as source
* removed logic relying on update_sequence (given that `source_seq` is no longer an integer in CouchDB 3.x)
* added a new API for fetching a short summary of CouchDB (from the root endpoint `/`), including its version
* when a replication document is created, return the CouchDB response
* updated the logic to check the state of replication tasks/docs
* for the `CouchMonitor` class, the following has been implemented:
  * new `getActiveTasks` client API to retrieve the active tasks from the `_active_tasks` CouchDB endpoint
  * new `getSchedulerJobs` client API to retrieve jobs from the `_scheduler/jobs` CouchDB endpoint
  * new `getSchedulerDocs` client API to retrieve documents from the `_scheduler/docs` CouchDB endpoint
  * made a check for CouchDB and replication status compatible with both CouchDB 1.6 and 3.x

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
Related to https://github.com/dmwm/WMCore/pull/11001, but no longer requiring it.

#### External dependencies / deployment changes
Changes required for CouchDB 3.x, but it can be merged before that version gets integrated in our stack.

### CODE REVIEW

**Comment by amaltaro** [comment]
Instead of blocking this development while we wait for the final integration of CouchDB 3.x, I decided to make it compatible with both CouchDB versions, such that we can merge it sooner than later.

**Review by todor-ivanov — APPROVED** [review]
Thanks @amaltaro 
It looks good to me.

**Comment by amaltaro** [comment]
Despite testing it a few times. I deployed the latest changes today - with a fresh setup - and noticed that elements were not getting replicated from central workqueue to the agent workqueue_inbox. 

I might be wrong, but I think there might be a race condition between deleting the "old" replication documents and creating the new ones, around this code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py#L100-L106

I'm going to provide at least a better logging for this, in the open PR https://github.com/dmwm/WMCore/pull/11001

**Comment by amaltaro** [comment]
Thank you for looking into this, Valentin.
After further look, there is no race condition but actually the replication from cmsweb to localhost is failing:
```
[error] 2022-06-08T14:35:45.666481Z couchdb@127.0.0.1 <0.27500.0> -------- ChangesReader process died with reason: {changes_reader_died,{timeout,ibrowse_stream_cleanup}}
[error] 2022-06-08T14:35:45.666638Z couchdb@127.0.0.1 <0.27500.0> -------- Replication `1aacaa5d83c7aaec9343d878bc4c2fac+continuous` (`https://cmsweb-testbed.cern.ch/couchdb/workqueue/` -> `http://localhost:5984/workqueue_inbox/`) failed:
 {changes_reader_died,{timeout,ibrowse_stream_cleanup}}
```

which causes the replication task to be eventually removed from the active tasks (and retried). I do think the deletion/creation replication task code can be made more robust though.

Anyhow, I need to debug which configuration parameters I changed over the last days/weeks, because this is definitely something that I tested and which was working(!)

**Pull request merged**
