### PR TITLE
change to warning for drain and disk space warning

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, please review. It is updated couch-dev1 machine for the test.

### CODE REVIEW

**Comment by amaltaro** [comment]
Thanks Seangchan! Besides a few "else if" with double spacing in the beginning, it looks good to me.
I'll test them tomorrow from CERN.

**Comment by ticoann** [comment]
Thanks Alan, I changed that.

**Comment by amaltaro** [comment]
It passed on my tests and it looks awesome now! :-)

**Comment by ticoann** [comment]
Thanks for testing, Alan, merging it.

**Pull request merged**
