### PR TITLE
temp fix for empty team name handling (never merge)

### LINKED ISSUE #8095: agent need to acquire in their team
related to #8074 I do not understand the reason for having team="" go to *any* team. This is highly un-desirable IMO and WQE should just get in nowhere land. Better the request should not be able to assign if Team="" is the one that is decided.

I don't know why this is happening more frequently now, but this is happening and impacting urgent requests

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8095 @amaltaro, Alan I think this should prevent pulling down the team with empty string

### CODE REVIEW

**Comment by amaltaro** [comment]
Patch looks good, Seangchan.

**Comment by ericvaandering** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
@amaltaro, The unittest failure is real.  Since unittest assumes 'TeamName' is optional in WQ. 
but that shouldn't be the case. Anyway, I am not going to merge this patch since it is temp patch for production agents. Alan's team patch should fix this problem.

**Comment by ticoann** [comment]
real fix by Alan is added

**Pull request closed without merging**
