### PR TITLE
Update setup.py for use with pypi

### PR DESCRIPTION
**Pull request by PerilousApricot**
Necessary for, but doesn't solve #7647

### CODE REVIEW

**Comment by PerilousApricot** [comment]
@ericvaandering it's been a bit since I've committed to WMCore. Do I need to do something formal to request a review?

**Comment by ericvaandering** [comment]
We've been using the official review function sporadically, but in general you just mention one of us.

**Comment by ericvaandering** [comment]
Problem is this PR is blowing up the tests:
```
Traceback (most recent call last):
  File "code/setup.py", line 124, in <module>
    download_url="https://github.com/dmwm/WMCore/tarball/%s" % wmcore_version
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/0/label/slc6_amd64-cloud-tiny/deploy/1.1.1.pre3/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/0/label/slc6_amd64-cloud-tiny/deploy/1.1.1.pre3/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/0/label/slc6_amd64-cloud-tiny/deploy/1.1.1.pre3/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/0/label/slc6_amd64-cloud-tiny/code/setup_test.py", line 275, in run
    import WMQuality.TestInit
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/0/label/slc6_amd64-cloud-tiny/code/src/python/WMQuality/TestInit.py", line 25, in <module>
    from WMCore.Agent.Configuration import Configuration
ImportError: No module named Agent.Configuration
```

**Comment by ericvaandering** [comment]
Please do ```from WMCore import __version__``` rather than using the imp module. Much shorter and more understandable. Unless I really don't understand what you are doing.

**Comment by PerilousApricot** [comment]
@ericvaandering It's a chicken/egg thing. Using `from WMCore import __version__` requires that PYTHONPATH is set, but PYTHONPATH doesn't get set until the package is built.

**Comment by ericvaandering** [comment]
Ok. Please add a comment to that effect in what you've done, then.

**Comment by PerilousApricot** [comment]
Sweet, done.

**Comment by ericvaandering** [comment]
This is OK with me now. @ticoann ?

**Comment by PerilousApricot** [comment]
If this is acceptable, could a tag be cut after the commit is merged? I'd like to verify that the jenkins half works right.

**Comment by PerilousApricot** [comment]
Bleh, this isn't ready to go....

**Comment by ticoann** [comment]
@PerilousApricot, Andrew, not ready yet?

**Comment by ticoann** [comment]
test this please

**Comment by PerilousApricot** [comment]
Not quite, I ended up with a weird glitch when trying to install WMCore via pip. I'll need to sort it out real fast

**Comment by PerilousApricot** [comment]
OK, I added a couple commits to get the installation to work right. Once the tests go through, it's good to be merged. Thanks!

```
$ pip install 'wmcore==1.1.1.pre4' --force-reinstall -i https://testpypi.python.org/simple
Collecting wmcore==1.1.1.pre4
  Downloading https://testpypi.python.org/packages/26/df/85563d6a0d86687e8d636546b371bacd60acd9c7f836d9f6f9905e029790/wmcore-1.1.1.pre4.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 324kB/s 
Building wheels for collected packages: wmcore
  Running setup.py bdist_wheel for wmcore ... done
  Stored in directory: /home/meloam/.cache/pip/wheels/07/52/bc/21749304cee0c49c27855a029d59995aef0646fe7303bde6cc
Successfully built wmcore
Installing collected packages: wmcore
Successfully installed wmcore-1.1.1rc4
$ python
Python 2.7.11 (default, Oct 16 2016, 07:25:10) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import WMCore
>>> print WMCore.__file__
/home/meloam/projects/gen/from-jose/venv-lobster/lib/python2.7/site-packages/WMCore/__init__.pyc
```

**Comment by PerilousApricot** [comment]
If this code is committed, could the release version be bumped as well?

**Comment by ticoann** [comment]
Thanks Andrew, we will do that. Is it OK to merge this after next  production upgrade on next Tuesday?

**Comment by PerilousApricot** [comment]
Works for me! Thanks.

**Pull request merged**
