### PR TITLE
cleaning up after PNN patch

### LINKED ISSUE #6066: change table name from wmbs_location_senames to wmbs_location_pnn
related to the change by #5989

### PR DESCRIPTION
**Pull request by alexanderrichards**
This pull includes change to the wmbs_location_senames table as well as change to the column name se_name.

This pull fixes https://github.com/dmwm/WMCore/issues/6066

### CODE REVIEW

**Comment by ericvaandering** [comment]
I suspect this will blow up spectacularly since we will be running this test on a SQL database initialized with the older code.

**Comment by alexanderrichards** [comment]
@ericvaandering I think your right. :smile: 

**Note** this also changes the dbsbuffer_location table as well by changing the column from se_name to pnn so this can only really be merged I guess when dbs is also using pnn.

**Comment by alexanderrichards** [comment]
I'm quite surprised there are so few unit test ~~failures~~ changes (as one is a success), given the nature of the DB changes. Like @ericvaandering I was expecting more.

**Comment by alexanderrichards** [comment]
retest this please

**Comment by alexanderrichards** [comment]
retest this please

**Comment by alexanderrichards** [comment]
retest this please

**Comment by alexanderrichards** [comment]
Yey! :smile: one test actually got better!

**Comment by alexanderrichards** [comment]
@ticoann This has now been rebased so merges cleanly again

**Comment by amaltaro** [comment]
@alexanderrichards I'm sorry that we didn't look at it before :( Could you please fix the conflicts (maybe wait until tomorrow - Seangchan will merge a few more PRs today).

Then I suggest we create a new RPM including this fix and run a few tests in both oracle and mariadb.

**Comment by alexanderrichards** [comment]
@ticoann @amaltaro I have rebased these changes now so that the conflicts are gone and they merge cleanly

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
@alexanderrichards just to be clear, this is the patch you are (going to) testing in your VM that should get rid of all SE leftovers, isn't it?

**Comment by alexanderrichards** [comment]
yes thats right

**Comment by ticoann** [comment]
All tested went fine in agent side. Still need to test Tier0 patch.

**Comment by alexanderrichards** [comment]
looks like I need to rebase again ;-)

**Comment by ticoann** [comment]
@alexanderrichards, I am sorry Alex, could you rebase this one more time? I hope it would be the last time you do that.

**Comment by alexanderrichards** [comment]
No worries, I'm getting quite expert at rebasing now. All done :wink:

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Merging it now. However, this also completely drops the se name in wmagent not just name change in the table. (Which requires DBS will contain pnn not se names, that part needs to be tested)

**Pull request merged**
