### PR TITLE
1.1.15 wmagent patch5 Bundle

### PR DESCRIPTION
**Pull request by ticoann**
#8807 Try creating reqmgr_aux agent doc once again
#8806 don't apply speed mode when user drain mode is false
#8781 Remove lustre from the ignoredDisks list; added /mnt/ramdisk
#8769 Catch Proxy Error for wmstats query; updated error messages; others

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan, could you check whether I miss anything?

**Comment by amaltaro** [comment]
Sure, I can take it from here. Thank you very much, Seangchan!

**Comment by amaltaro** [comment]
[Fix #8815 - bundle of wmagent patches for 1.1.15.patch5](https://trello.com/c/mpAVT5dK/127-fix-8815-bundle-of-wmagent-patches-for-1115patch5)

**Comment by amaltaro** [comment]
Patch updated with the 2nd commit from #8806 
Merging it in a sec

**Pull request merged**
