### PR TITLE
Pycondor lagging

### PR DESCRIPTION
**Pull request by tsarangi**

### CODE REVIEW

**Comment by tsarangi** [comment]
@ticoann, @amaltro, @lucacopa 
I made changes only to PyCondor plugin, commit #eaa185f . There seems to be many other commits that I merged with my branch. Please have a look at the commits before merging this. 

-Tapas

**Comment by ticoann** [comment]
Hi Tapas, it seems the commit is all mixed up could you create the new pull request only with PyCondor change.

> git fetch upstream
> git checkout upstream/master
> git checkout -b [new_branch]
> curl https://github.com/tsarangi/WMCore/commit/eaa185f2427883d694cc8c2a4aa84425426bbcf2.patch | git am

That should create the [new_branch] with only your patch.

Thanks,

**Comment by PerilousApricot** [comment]
Hi Seangchan, Tapas,

you could also do "git cherry-pick eaa185f2427883d694cc8c2a4aa84425426bbcf2
<https://github.com/tsarangi/WMCore/commit/eaa185f2427883d694cc8c2a4aa84425426bbcf2.patch>"
to accomplish the same as the curl line

Cheers,
Andrew

**Comment by ticoann** [comment]
Thanks Andrew, cherry-pick looks much better.

**Comment by tsarangi** [comment]
@PerilousApricot @ticoann 

Thanks. Done. Created another PR. Closing this one.

**Comment by PerilousApricot** [comment]
NP, I just found that trick recently and thought I'd share it.

**Pull request closed without merging**
