### PR TITLE
remove wmbsservice component

### LINKED ISSUE #7552: problems starting WMBSService
Latest WMCore version I get this trying to start the WMBSService:

Starting : WMBSService
Starting WMBSService as a daemon
Log will be in /data/tier0/srv/wmagent/2.0.6/install/tier0/WMBSService
Waiting 1 seconds, to ensure daemon file is created

started with pid 273647
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method TempDirectory.__del__ of <WMCore.Services.Requests.TempDirectory object at 0x7fd4e6e62250>> ignored

### PR DESCRIPTION
**Pull request by ticoann**
Fixes #7552

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
Looks good. I'm just not sure whether the agent deployment will complain about the lack of this configuration.

**Comment by ticoann** [comment]
I don't think it will cause the problem, Dirk tested with Tier0 deployment.  We still need to clean up the code but I don't want to make too many changes for this deployment.

**Comment by amaltaro** [comment]
I can't agree more ;)

**Comment by ticoann** [comment]
test this please

**Pull request merged**
