### PR TITLE
Stage 2 futurize applied to PSetTweaks

### PR DESCRIPTION
**Pull request by vilnius-dev**
Jenkins tests for **complete** stage 2 of PSetTweaks

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Added @vilnius-dev to our list of contributors. Now his PRs should be tested automatically.

**Comment by amaltaro** [comment]
@ericvaandering there is something funny with these jenkins :)

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Docker pull on the start node got stuck.

**Comment by amaltaro** [comment]
@vilnius-dev Roman, since this is not how we're going to proceed with this migration, can I close this pull request?

**Comment by vilnius-dev** [comment]
@amaltaro could you please close this pull request?

**Comment by amaltaro** [comment]
this was just a test to get Roman familiar with this stuff

**Pull request closed without merging**
