### PR TITLE
Remove old/unused submitter plugins

### LINKED ISSUE #7588: remove CondorPlugIn and PyCondorPlugIn
We will switch to SimpleCondorPlugin in next agent deployment (Feburary)

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7588
To be merged before #7073 (since it should clear some of the failing unit tests in the other PR).

I'm still keeping around the LSF, PyCondor and SimpleCondor plugins.

### CODE REVIEW

**Comment by ticoann** [comment]
Not sure why WQ test is failing doesn't seems to be related.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann yes, I don't think it's related to this PR, in any case I'm firing the tests again.
@hufnagel what do you think about removing the LSF plugin as well? If the chances we'll need that within 5 years or so is very small, I'd just go ahead and shoot that plugin as well.

**Comment by amaltaro** [comment]
test this please

**Comment by hufnagel** [comment]
I would leave the LSF Plugin. It is not obsolete in the sense that it supports a different submission system, removing it would remove functionality. SimpleCondor and PyCondor is different since they both address the same underlying submission system. Yes, we likely won't be using LSF directly anytime soon, but that is purely for operational reasons. From a code management point of view there is no reason to remove it.

Also, how many plugins will we have left after this removal ? Might be worthwhile to at least one other plugin to have an example of how things can be done differently for a different submission system.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
We should keep the LSF, Simple and the test/Mock plugins :-)

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Only WorkQueue tests failing which I don't think is related to these changes.
Thus @ticoann please review and merge

**Review by ticoann — APPROVED** [review]

**Pull request merged**
