### PR TITLE
Switch from pep8 to pycodestyle

### LINKED ISSUE #10559: Replace pep8 by pycodestyle in the CI setup and wmcore devtools packages
**Impact of the new feature**
Specs and Jenkins CI

**Is your feature request related to a problem? Please describe.**
When running `pep8` checks from our python3 stack, it prints the following deprecation warning
```
/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3-comp/sw/slc7_amd64_gcc630/external/py3-pep8/1.7.1/lib/python3.8/site-packages/pep8.py:2124: UserWarning: 

pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.

$ pip install pycodestyle
$ pycodestyle ...
```

**Describe the solution you'd like**
Replace the `pep8` package by `pycodestyle`, in our WMCore python3 stack. If it's also available for python2, then we should perform the same switch.

Once a new RPM is made available with this new library, we also need to update the Jenkins jobs. It should be `DMWM-WMCore-PR-pylint*` jobs.

**Describe alternatives you've considered**
none

**Additional context**
none

### PR DESCRIPTION
**Pull request by goughes**
Fixes #10559 

#### Status
Ready

#### Description
Removes pep8 and installs pycodestyle for wmcore and devtools packages. Updates to setup.cfg to use pycodestyle.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
Docker PR for a new pylint container image: https://github.com/dmwm/Docker/pull/132

#### External dependencies / deployment changes
cmsdist PR to reflect the new version numbers for pycodestyle and pylint: https://github.com/cms-sw/cmsdist/pull/7846

### CODE REVIEW

**Comment by amaltaro** [comment]
@goughes Erik, since you are updating this requirements file, could you please downgrade the Cheeta3 version to post1 instead of post2?

I am testing the compatibility of all these packages, and pip was failing with this error:
```
WARNING: The candidate selected for download or install is a yanked version: 'cheetah3' candidate (version 3.2.6.post2 at https://files.pythonhosted.org/packages/75/8f/54099fb1d2bc830ed0a1e345aca10762fa412e400e13347920d7af991670/Cheetah3-3.2.6.post2-cp38-cp38-manylinux1_x86_64.whl#sha256=7fe156842964c5650a1a583fd958a2e6f2c99720b2b139ecfc69d1d3c1727578 (from https://pypi.org/simple/cheetah3/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*))
Reason for being yanked: Failed
```

I will take care of the cmsdist changes in https://github.com/cms-sw/cmsdist/pull/7846

**Comment by goughes** [comment]
Downgraded Cheetah with my latest commit. @amaltaro

**Review by amaltaro — APPROVED** [review]
Thanks Erik, it looks good to me.

**Comment by amaltaro** [comment]
@goughes Erik, the cmsdist and docker pull requests have been merged and a wmagentpy3-dev 2.0.3.pre5 has been made on top of those. 

Can you please switch the Jenkins job(s) configuration back to the official image in:
gitlab-registry.cern.ch/cmsdocks/dmwm:wmcore_pylint

and let me know the jenkins job names that you changed? 
We will have to update this documentation accordingly:
https://github.com/dmwm/WMCore/wiki/Understanding-Jenkins

**Comment by goughes** [comment]
Jenkins has been updated to point to `gitlab-registry.cern.ch/cmsdocks/dmwm:wmcore_pylint`.

Updates to documentation: https://github.com/dmwm/WMCore/wiki/Understanding-Jenkins/_compare/d7003c71b67e89b5d5074c4d83027c6aca150aec...492577c7795ffabcd5795aea9aa54a0ff46f4f5f

**Pull request merged**
