### PR TITLE
add kwargs for flexibiity in TagCollector

### PR DESCRIPTION
**Pull request by ticoann**
not sure whether default value for anytype and anyarch, 0 or 1.
@amaltaro, Alan please review.

### CODE REVIEW

**Comment by emaszs** [comment]
Thank you @ticoann :) If this PR is fine, can it also be merged to our 1.1.0_crab branch with a new tag (1.1.0.crab1 I assume)? Thanks!

**Comment by ticoann** [comment]
@emaszs, I will do that, when do you need a tag? Is later today fine?

**Comment by emaszs** [comment]
Whenever you have time @ticoann, later today works perfectly fine for me :)

**Review by amaltaro — APPROVED** [review]
A much better fix. Thanks Seangchan!

**Pull request merged**
