### PR TITLE
[py2py3] Apply changes from pylint --py3k to files involved in #10012

### LINKED ISSUE #10169: [py2py3] Apply changes from `pylint --py3k` to files involved in #10012
**Impact of the new feature**

Files involved in #10012

**Is your feature request related to a problem? Please describe.**

#10012 was not checked against `pylint --py3k`, whose report about the files involved in that PR is

```plaintext
************* Module src.python.WMCore.DataStructs.File
W: 90, 4: __cmp__ method defined (cmp-method)
************* Module src.python.WMCore.DataStructs.MathStructs.ContinuousSummaryHistogram
W: 99,17: round built-in referenced (round-builtin)
************* Module src.python.WMCore.DataStructs.Run
W: 59, 4: __cmp__ method defined (cmp-method)
W: 59, 4: __cmp__ method defined (cmp-method)
W: 90, 4: __cmp__ method defined (cmp-method)
W: 99,17: round built-in referenced (round-builtin)
```

We should then modernize the files mentioned in the report. This will likely involve some refactoring, since a change in how `__cmp__` is honored is involved.

**Describe the solution you'd like**

We should likely port the behavior of `__cmp__` to new `__lt__` and `__eq__` methods, following the guide provided by [fedora](https://portingguide.readthedocs.io/en/latest/comparisons.html#rich-comparisons) .

**Describe alternatives you've considered**

There is not much else we can do about this.

**Additional context**

This should require any change in third-party libraries

### PR DESCRIPTION
**Pull request by mapellidario**
Fixes #10169 

#### Status
In development 

#### Description

We need to modernize how we do comparisons and ordering in `DataStructs/Run.py` and `DataStructs/File.py` because python3 does not honor anymore the dunder method `__cmp__`.

(details will be updated)

- `src/python/WMCore/DataStructs/Run.py`
- `src/python/WMCore/DataStructs/File.py`

Reference: https://portingguide.readthedocs.io/en/latest/comparisons.html

Examples and some testing
- https://cms-dmwm-test.docs.cern.ch/py2py3/porting/comparisons_py2/
- https://cms-dmwm-test.docs.cern.ch/py2py3/porting/comparisons_py3/

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
This is a follow-up to #10441 

#### External dependencies / deployment changes
nope

### CODE REVIEW

**Comment by mapellidario** [comment]
Test this, please

**Comment by mapellidario** [comment]
Test this, please

**Comment by mapellidario** [comment]
@amaltaro I have a question for you. It is about this function

https://github.com/dmwm/WMCore/blob/5da7f3c898bb39cdb7efb64070af182419501602/src/python/WMCore/DataStructs/File.py#L90

From [this guide](https://portingguide.readthedocs.io/en/latest/comparisons.html#rich-comparisons) I get that it should return an integer: `< 0` is lhs is les than rhs, `0` is lhs is equal to rhs, `>0` if lhs is greater than rhs. However, it's years that `__cmp__` is set to be the same as `__eq__`, which should not be the case. `__cmp__` in python2 is used when you call `<, <=, >, >=` on two objects of a class and since the implementation puzzles me I wonder if we ever compare two `File`s in dmwm/WMCore code. 

I tried commenting `__cmp__` out of `DataStructs/File.py` and no unit test failed.

We have a couple of options
1. reimplement a meaningful comparison operator in py2 and py3 compatible fashion. I do not know if we need this though, because the more reasonable implementation of this cmp (comparing run number and lumi sections) method has been commented out 11y ago, so I assume we do not really need such a functionality
2. remove this and hope nothing beraks in testbed - production.

What do you think? Do you want me to better dive into our code looking for potential rich comparisons between files? == and != are correctly covered by `__eq__`, what seems that we do not need but I have not looked for yet are `<, <=, >, >=`.

What's your take on this?

**Comment by amaltaro** [comment]
@mapellidario sorry for the belated reply. 
I believe we only compare if file objects are equal or not, so I'd say it's safe enough to remove `__cmp__` and leave only the equality methods. However, I do not see a good coverage with the current unit tests, so can I ask you to create some basic equality comparison tests to verify these changes as well (might add a check for identity as well, even though it's unrelated AFAIU)?

**Review by amaltaro — APPROVED** [review]
I am scared with the Run changes, but it looks solid and covered with the unit tests. Thanks Dario.

**Pull request merged**
