### PR TITLE
remove reqmgr1 dependency

### PR DESCRIPTION
**Pull request by ticoann**
Initial patch for removing the code dependencies on ReqMgr1.

There are few things to clarify/update before merges the code.

1. crabserver (3) dependency. @mmascher  (created new tag collector service WMCore/Services/TagCollector.py)
2. https://github.com/dmwm/WMCore/blob/master/bin/runCmsDriver.py - is this used anywhere?
3.  https://github.com/dmwm/WMCore/tree/master/src/python/WMQuality/Emulators/RequestManagerClient - need to be removed or rewritten - done
4. https://github.com/dmwm/WMCore/blob/master/test/python/Integration_t/ACDCLifeCycle_t.py
    https://github.com/dmwm/WMCore/blob/master/test/python/Integration_t/RequestLifeCycleBase_t.py - need to be rewritten or removed  -done
5. deployment of reqmgr in dmwm/reqmgr need to be removed - done within wmagent deployment
6. There are still many ops script importing this code. (Will create the separate issue for https://github.com/CMSCompOps/WmAgentScripts) -done

### CODE REVIEW

**Comment by amaltaro** [comment]
Hodor!!! Don't delete the whole repository!!! :-)

Now you've made this PR already, otherwise I would suggest to split it in smaller PRs such that it can be viewed in the future.

**Comment by ticoann** [comment]
Hi Alan, Since there are too many dependencies, it is hard to break down.  I made one patch so it can be reverted easily. But I didn't realize github won't show the changes. 
Anyway, I am not going to merge this until all the bullet point is cleared above. Maybe we can even create the branch and separate for the test.

**Comment by ticoann** [comment]
@mmascher, Hi Marco, it seems there is  dependency on WMCore.RequestManager package in crabserver3. https://github.com/cms-sw/cmsdist/blob/comp_gcc493/crabserver3-setup.patch#L15
RequestManger 1 is already out of service (it is not deployed in cmsweb), 
Is there a any code dependencies in crabserver3? If you point me the api crab is using I can give you alternative ReqMgr2 api.  

We are trying to remove the code from WMCore in Feb. deployment. 

Thanks,

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
Not sure why following report is showing. That file is not deleted.
```
WMComponent_t.WorkQueueManager_t.WorkQueueManager_t.WorkQueueManagerTest:testComponentBasic was deleted. Prior status was success
```

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Seangchan, your idea sounds safer. We can create a new branch, merge this PR over there, cut a new tag (pre2) and build all possible RPMs for the integration tests.

**Comment by ericvaandering** [comment]
Whenever you see this:

Unit tests added

nose.failure.Failure:runTest was added with status error. Must be fixed

you have a broken import. That will cause tests to be "deleted" and replaced with that error. The "default Details" will help you sort out where the import is broken.

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann @mmascher This is the dependency of CRABServer on RequestManager: https://github.com/dmwm/CRABServer/blob/527ce6961256de99ba244da307f23ef7afd97863/src/python/CRABInterface/RESTUserWorkflow.py#L13

Surely we can solve that. :-)

**Comment by ticoann** [comment]
Eric, Thanks you very much for checking the code

> [edit] maybe even a drop-in replacement here: https://github.com/dmwm/WMCore/blob/6f580f444dca6ed8d3f1c1c34680b197bfeaf574/src/python/WMCore/ReqMgr/Service/Auxiliary.py#L353 but also no reason that is a function in ReqMgr(2). We could easily turn that into something in Services/ so it's more broadly accessible.

Actually above code is actually broken - I will clean up. 

@mmascher, Marco, you can either use ReqMgr2 REST api below. (Accept: "application/json") will return json instead of xml
https://cmsweb.cern.ch/reqmgr2/data/software

or you can use the new function we are updating.

https://github.com/dmwm/WMCore/pull/7480

As far as the default url,  you can use.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Tools/cms.py#L36

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
Man. I was hoping to win "most code removed this week" but Seangchan smoked me.

**Comment by ticoann** [comment]
I was cheating. :-)

**Comment by ericvaandering** [comment]
Not at all.

**Pull request merged**
