### PR TITLE
fix error handler memory problem

### LINKED ISSUE #8614: ErrorHandler very high memory footprint while creating ACDCs
vocms0255 was going from 0 to 20GB within 20min or so.

The problem seems to be coming from this query 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Jobs/LoadForErrorHandler.py#L43

when there are several MCFake file jobs to be handled (generating > 100k run/lumi maps).
Apparently we get the run/lumi map for unique fileids, but if we have 100 of them in the same binds, it might take all the memory...

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8614 Need to test

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
I had to restart jenkins, it should run now.

**Comment by ticoann** [comment]
Thanks Alan, I thought you are in Chicago.:-)

**Comment by amaltaro** [comment]
This weather is not really inviting to go out there... but I don't know, I might change my plans again :)

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
replaced by #8623

**Pull request closed without merging**
