### PR TITLE
List of unstable python3 unit tests

### LINKED ISSUE #10564: Create list of python3 unstable unit tests and use it in Jenkins
**Impact of the new feature**
Jenkins

**Is your feature request related to a problem? Please describe.**
Yes, there are a few unit tests in python3 that randomly flip between failure/success. We should mark those as unstable to make it clear in the PR report.

**Describe the solution you'd like**
The initial solution would be to create a second unstable txt files (for python3 unit tests), and adapt Jenkins jobs to use it and properly flag such tests in the PR report.

**Describe alternatives you've considered**
An alternative, which might be good enough, is to use the same list of unstable unit tests:
https://github.com/dmwm/WMCore/blob/master/test/etc/UnstableTests.txt

and simply extend it with the python3 unstable unit tests

**Additional context**
Here is where we are keeping the current python3 unstable unit test list:
https://github.com/dmwm/WMCore/wiki/setup-wmcore-unittest#unstable-tests-in-py3

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #10564

#### Status
ready

#### Description
Expand the current text file with the unstable python2 unit tests, to also list python3 tests that are floating between failure and success as well.

Initial list taken from (to be removed from the wiki btw): https://github.com/dmwm/WMCore/wiki/setup-wmcore-unittest#unstable-tests-in-py3

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
> 287 tests added

Wow, I do not know what magic was that, but I definitely like it!
Apparently those unit tests that were missing when compared against our python2 baseline.

**Comment by amaltaro** [comment]
Found this sentence:
```
++ export WMAGENTPY3_LATEST=1.4.9.pre3-comp2
```

in the WMCorePy3-unittests job. Which means, the `rucio-clients` update made by Todor in this GH issue https://github.com/dmwm/WMCore/issues/10525 fixed many of those problems (and it works). Well done @todor-ivanov

**Review by mapellidario — APPROVED** [review]
This list looks perfect, thanks Alan!

**Comment by amaltaro** [comment]
Thanks Dario! Our next baseline should see a jump in the absolute number of unit tests, hopefully not too many failing :-)
https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCorePy3-UnitTests/

**Pull request merged**
