### PR TITLE
use mock for apmon to speed up the test

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
Unit tests added

nose.failure.Failure:runTest was added with status error. Must be fixed
 

and deleted tests are a clear indication that some imports are screwed up somewhere.

**Comment by ticoann** [comment]
@ericvaandering, Eric test seems to got stuck. I wonder I remove some premature return statement for some profiling test. But add integration attribute so it won't run in jenkins environment.

Jenkins won't run test marked as integration test, right?

**Comment by amaltaro** [comment]
There was a test (I don't know which slice) that was hanging for more than 3h.
https://cmssdt.cern.ch/jenkins/view/DMWM/job/DMWM-WMCore-PR-test/6671/

I tried killing that test and I'll start a new one.
Tests marked as integration should be skipped by jenkins.

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
Correct, it will not run things marked integration

**Comment by ericvaandering** [comment]
Hmm. It's having trouble picking up this issue in GH. Never starts running the tests. I don't get it.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Pull request merged**
