### PR TITLE
upload wmbs info to wmstats

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan please review.

### CODE REVIEW

**Comment by amaltaro** [comment]
Thanks, Seangchan! And how do we retrieve this info from wmstats? I will check the final data structure uploaded tomorrow.

**Comment by amaltaro** [comment]
BTW, don't worry with testing it. I'll have a close look at it tomorrow

**Comment by ticoann** [comment]
Alan it seems it works fine.
Data is uploaded and more importantly nothing breaks. 😄 

https://reqmgr2-dev.cern.ch/couchdb/wmstats/vocms008.cern.ch%3A9999
https://reqmgr2-dev.cern.ch/couchdb/_utils/document.html?wmstats/vocms008.cern.ch%3A9999

@amaltaro, let me know if you think it is good to merge.

**Comment by amaltaro** [comment]
Well, you're da man Seangchan!

Just one suggestion, I think we should keep that `if` because running all those queries in a heavy loaded agent can take some time (and adds even more load), that's why I instrumented it to collect `WMBS_INFO` only once every 3 component cycles.

**Comment by amaltaro** [comment]
I didn't really time that, but the aggregation wmbs_job queries may take several secs AFAIR (<30secs). To be on the safe side, I think we can get that info once every 15min as it was before.

**Comment by ticoann** [comment]
As we discussed I added
1. query time. (in sec)
2. remove the monitoring config
3. add json file back
4. change log to debug.

Test seems fine. Just query seems to take less then 1 sec. 
https://reqmgr2-dev.cern.ch/couchdb/_utils/document.html?wmstats/vocms008.cern.ch%3A9999

**Comment by amaltaro** [comment]
Thank you very much, Seangchan! Changes look good.

**Comment by amaltaro** [comment]
> Alan, how long does the query takes on high load?

BTW, just got some numbers for the CERN nodes and it's 3secs in avg, though their load is quite small.

**Pull request merged**
