### PR TITLE
1.0.12 wmagent

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan, could you double check the patch. I will create the new tag for agent

### CODE REVIEW

**Comment by ticoann** [comment]
Alan, One more thing I would like to add is changing the block calls to dataset call in PileupFetcher class. I can add that one as on top of this. (We would still keep Brian's caching patch).
If you need to deploy new agent today, feel free to merge this and create a new tag 1.0.12.patch2 if the all the patch looks OK. Thanks

**Comment by amaltaro** [comment]
Sounds good Seangchan! It includes: 
#6450 (without the last update to sendAlert I'll apply to master only. The right thing)
#6434 
#6457 

About the block to dataset, if you feel that's important for this release. Then we wait.

**Comment by ticoann** [comment]
> About the block to dataset, if you feel that's important for this release. Then we wait.

The performance difference was 2h vs 1 minutes. It depends how many workflows left with this Pileup dataset.

**Comment by amaltaro** [comment]
Ok, I think we can wait then :-P

**Comment by ticoann** [comment]
added https://github.com/dmwm/WMCore/commit/61b216f62e8bf6a2fc3fe0196a2366c9a0dae2f5
Which is not tested. :smile: 
@amaltaro, please review and is possible to run test for this commit?

**Comment by ticoann** [comment]
Also increase the cache expiration for 12 hours.

**Comment by amaltaro** [comment]
Seangchan, this is the working version of your patch (https://github.com/dmwm/WMCore/commit/61b216f62e8bf6a2fc3fe0196a2366c9a0dae2f5):
https://github.com/amaltaro/WMCore/commit/b4388166d388bb22f7acddb60a87526e4a60a922

I made a few fixes, also backported Marco's fix for siteDB (#6466).

I compared the json created with the current version and the json with this patch using this ordered() method:
http://stackoverflow.com/questions/25851183/how-to-compare-two-json-objects-with-the-same-elements-in-a-different-order-equa
and other comparisons to make sure everything is ok.

I just removed my loggings and etc. And additional clean test shouldn't hurt :-)

**Comment by ticoann** [comment]
Thanks Alan! I replace my  patch to your patch. Please check

**Comment by amaltaro** [comment]
Hmmm, why my both redigi test workflows failed to find the secondary input... hold on on this one please Seangchan.

**Comment by amaltaro** [comment]
Nevermind, it seems data got deleted from FNAL a few hours ago. I'm running another test, but I won't wait awake for the outcome :)
@ticoann feel free to merge it

**Comment by ticoann** [comment]
Thanks Alan, 1.0.12.patch2 is created. https://github.com/dmwm/WMCore/tree/1.0.12.patch2

**Comment by amaltaro** [comment]
Thanks Seangchan! I'm creating a PR for this patch for both comp_gcc481 and comp_gcc493 architectures.

**Pull request merged**
