### PR TITLE
Add last row inserted to ResultSet

### PR DESCRIPTION
**Pull request by ericvaandering**
I need to save the inserted primary key between inserts in MySQL. I don't see another way in SQLAlchemy to do this or examples of how we do it. I'm happy to be wrong, @amaltaro or @ticoann

### CODE REVIEW

**Comment by ticoann** [comment]
I remember Yuyi needed this before. Not sure how we added though.

It seems mysql there is way to do this, 
https://dev.mysql.com/doc/refman/5.7/en/getting-unique-id.html

```
INSERT INTO foo (auto,text)
    VALUES(NULL,'text');         # generate ID by inserting NULL
INSERT INTO foo2 (id,text)
    VALUES(LAST_INSERT_ID(),'text');  # use ID in second table
```

For Oracle, use "returning into" clause. but I am not sure the oracle version we uses support this.
https://oracle-base.com/articles/misc/dml-returning-into-clause

@yuyiguo, Yuyi, did you add this feature some where in WMCore?

Anyway, if the change works I don't see anything is simpler than that though.

**Comment by ticoann** [comment]
Actually for Oracle. we can just use .currval

From here
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/Oracle/Files/Add.py#L15

```
sql = """INSERT INTO wmbs_file_details (id, lfn, filesize, events,
                                            first_event, merged)
             VALUES (wmbs_file_details_SEQ.nextval, :lfn, :filesize, :events,
                     :first_event, :merged)"""

```

wmbs_file_details_SEQ.curval will have the value just inserted

**Comment by ericvaandering** [comment]
Right, @hufnagel clued me in on how to do this in Oracle. In MySQL that should work, but @yuyiguo did not add it to WMCore (I grepped for that string). I can see other uses where the ID may be useful, so maybe this is not such a bad idea.

**Comment by ericvaandering** [comment]
Let's leave this unmerged. Yuyi's method works great too and is simpler. If I need IDs for some other reason, we can come back to this.

**Comment by ticoann** [comment]
Either way is fine with me.

**Comment by hufnagel** [comment]
Using .currval is dangerous, since you need to make sure that no one is advancing the sequence in between your calls. So basically single row insert followed by a select within the same transaction. If you have a bulk insert you'll only get the last sequence value, not all of the ones being inserted. If you don't have a transaction some other operation could change the sequence before you have a chance to look at .currval.

If you need to do this in Oracle it's much safer to just combine all the operations you want to do with the sequence value into one operation and use .nextval for all of them (within the same operation that doesn't advance).

**Pull request closed without merging**
