### PR TITLE
Update subscription methods to keep list of datasets under an output …

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch version of #8021

Still testing, but new requests (once cmsweb gets upgraded) may carry a different subscription structure, so we also have to update the agents.

### CODE REVIEW

**Comment by amaltaro** [comment]
Just tested it with the current reqmgr (1.1.5) and the newest one (1.1.6) and both works fine. So we can apply this patch at any time before the cmsweb upgrade.

**Comment by ticoann** [comment]
@amaltaro, This need to be apply before cmsweb upgrade, right?

**Comment by amaltaro** [comment]
Yes, I'll apply it in the coming days because it's backward compatible. If you want, feel free to merge it

**Comment by ticoann** [comment]
Unless you are redeploying the agent. I will just leave it open until production agents are status so we can track. Thanks Alan,

**Comment by amaltaro** [comment]
I've just pushed this patch in in all the agents. Feel free to merge it or just leave it open until we cut the next production release, by the next week.

**Comment by amaltaro** [comment]
[Fix #8053 - Update subscription methods to keep list of datasets under an output](https://trello.com/c/Njabd2G0/53-fix-8053-update-subscription-methods-to-keep-list-of-datasets-under-an-output)

**Review by ticoann — APPROVED** [review]

**Pull request merged**
