### PR TITLE
Implement IO and Site metrics for FWJR

### LINKED ISSUE #11538: Review and improve CMSSW I/O metric reporting
**Impact of the bug**

CMSSW I/O metric reporting is inaccurate.

**Describe the bug**

(followup from https://github.com/dmwm/WMCore/pull/11533#issuecomment-1500437122)

The I/O metrics extract from the framework job report in
https://github.com/dmwm/WMCore/blob/431f08f70f14733830e546d0ac4b1adc04fc912c/src/python/WMCore/FwkJobReport/XMLParser.py#L446-L462
need to be reviewed, taking into account e.g.
* exact meaning of each `Timing-*` number
* what other numbers (that are reported further) are derived from those
* why some quantities are read for some protocol (`readMethod`), and some from `tstoragefile`

In addition, the `readMethod` used in some of the quantities seems to not be well defined as the loop
https://github.com/dmwm/WMCore/blob/431f08f70f14733830e546d0ac4b1adc04fc912c/src/python/WMCore/FwkJobReport/XMLParser.py#L427-L432
picks the first protocol it sees that had non-zero number of operations. For a job reading a local file and a remote file, like pileup mixing in step chain the local file protocol comes before the remote root protocol in the XML (and more generally these numbers report statistics from any files opened by cmsRun, not just the event data).

**How to reproduce it**

N/A

**Expected behavior**

The quantities reported onwards by WMCore have a well-defined and documented meaning.

**Additional context and error message**

How much do these performance metrics matter for WMCore itself, or does it just treat them as "black box" defined by someone else?

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #11538 

#### Status
in development

#### Description
Implement CMSSW IO and Site metrics for WMCore FWJR report

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
<If it's a follow up work; or porting a fix from a different branch, please mention them here.>

#### External dependencies / deployment changes
<Does it require deployment changes? Does it rely on third-party libraries?>

### CODE REVIEW

**Comment by vkuznet** [comment]
For clarify this [gist](https://gist.github.com/vkuznet/2f27b11051f650d7e209fe67547247a8) provides JSON output of FWJR which contains new metrics, see sections `io` and `site`.

**Comment by amaltaro** [comment]
Valentin, I think it would be extremely valuable (also for the near future developments) to have a dump of an actual CMSSW FJR, in addition to the WMArchive document extracted from this. Such that we can properly map things out and have a concrete example for this.

**Comment by vkuznet** [comment]
here is FWJR configuration file: https://gist.github.com/vkuznet/08d7951f17f535f2586c7a3d6c667adc

**Comment by vkuznet** [comment]
@amaltaro , I provided everything in this PR, including requested dump of FWJR. Did you get chance to review it in order to proceed with it?

**Comment by amaltaro** [comment]
@vkuznet Valentin, I am happy to start testing this patch as is, such that we can target it for the new release due by the end of this week.
However, it would be extremely helpful if you could provide the XML of the original CMSSW job report as well and work on a couple of relevant unit tests under (likely Report_t):
https://github.com/dmwm/WMCore/tree/master/test/python/WMCore_t/FwkJobReport_t

For instance, this is how a processing job CMSSW report looks like: https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/FwkJobReport_t/CMSSWProcessingReport.xml


In addition to that, we could also update the WMArchive FWJR samples and relevant unit tests as well (likely in Data_t):
https://github.com/dmwm/WMCore/tree/master/test/python/WMCore_t/Services_t/WMArchive_t

**Comment by vkuznet** [comment]
The job report xml file can be found here: https://gist.github.com/vkuznet/6d70c17c455f7afa9f911abb910a1cc1 and it contains this section:
```
<PerformanceReport>
  <PerformanceModule Metric="cern.ch"  Module="XrdSiteStatistics" >
    <Metric Name="read-numOperations" Value="1235"/>
    <Metric Name="read-totalMegabytes" Value="23.918"/>
    <Metric Name="read-totalMsecs" Value="18337.6"/>
    <Metric Name="readv-numChunks" Value="9616"/>
    <Metric Name="readv-numOperations" Value="465"/>
    <Metric Name="readv-totalMegabytes" Value="2308.85"/>
    <Metric Name="readv-totalMsecs" Value="125944"/>
  </PerformanceModule>
```
which used for site/io metrics.

I'll provide unit test now.

**Comment by vkuznet** [comment]
Alan, I checked unit tests and the ones I added are successful. The one which fails is related to Rucio and I doubt it has anything to do with this PR. Therefore, could you please have another look at structure of this PR and let me know if we need to add anything over there. So far I resistance to add WMArchive since we need to agree first on structure of changes. Once this will be settle I can add site/IO metrics to one of the WMArchive FWJR used in unit tests and check for their presence.

**Review by amaltaro — COMMENTED** [review]
It's not that simple to review this PR as I lack knowledge of what exactly is provided by CMSSW and what is expected to get propagated throughout the monitoring system (likely WMArchive). We will have to iterate on this with the Core SW (Matti and Chris Jones) to ensure that we deliver the expected information and behavior.

Having said that and based on the CMSSW FJR that you provided here:
https://github.com/dmwm/WMCore/blob/99fe3c60ab3faf07f6ce49e0dccb735a4aeffd7a/test/python/WMCore_t/FwkJobReport_t/CMSSWSiteMetrics.xml

my understanding is that the `IO` metrics would be a duplication of the `Storage` ones, with the exception that the `Storage` metrics are aggregated by the agent (after passing a filter based on regex):
https://github.com/dmwm/WMCore/blob/99fe3c60ab3faf07f6ce49e0dccb735a4aeffd7a/src/python/WMCore/FwkJobReport/XMLParser.py#L510

while the `IO` one would simply fetch all those metrics once again, but this time persist them in the agent job report.

Looking at the example you provided above, for the conversion from CMSSW to WMAgent FJR:
https://gist.github.com/vkuznet/08d7951f17f535f2586c7a3d6c667adc

I noticed it is actually missing the `Site` metrics (supposedly under the module name `XrdSiteStatistics`). In other words, we have the report section but there are no metrics in there.

One last observation from the CMSSW FJR concerns this line:
```
  <PerformanceModule Metric="cern.ch"  Module="XrdSiteStatistics" >
```

is the metric really supposed to be called `cern.ch`?

@makortel could you please shed some light on the points above?

**Comment by vkuznet** [comment]
I added new CMSSW merged job XML file over here https://github.com/dmwm/WMCore/blob/07773ca1809efd6f0698e59ac4270c484e03c933/test/python/WMCore_t/FwkJobReport_t/CMSSWMergeReport2.xml and we need to know which parts (if any) should we use to address Site/IO metrics issue. @makortel could you please have a look and let us know which parts from CMSSW XML report relates to Site/IO metrics. I doubt they are presented in XML file I provided, and therefore we need another example where we can see these metrics. Once we'll know them I can adjust this PR to read and propagate them to WMArchive report.

**Comment by makortel** [comment]
> @makortel could you please shed some light on the points above?

I can take a closer look in August. My recollection is that we agreed for the WM layer to just forward all metrics from the XML job report, and all aggregations would be done within monitoring.

I'll tag @Dr15Jones in case he would have anything ja o add earlier than I can.

**Comment by amaltaro** [comment]
From a quick look, I would say we have around 300 performance metrics, with roughly .5 million jobs a day.

If we think this won't hurt MonIT infrastructure (database, data retention, data visualization), then I guess we should simply fetch everything reported in the CMSSW FJR under `PerformanceReport`. 

This information is also stored in the agent local CouchDB, we need to take that into consideration as well and if possible evaluate the size difference between the current report against the one that will include every performance metric.

**Comment by vkuznet** [comment]
@leggerf , @brij01 could you please clarify with MONIT if we'll add at the order of 300 performance metrics, with roughly .5 million jobs a day, to WMArchive doc will it affect retention policy in ES/OpenSearch (I understand that for HDFS it wont matter) since we'll increase a document size. You may look at any current WMArchive doc in MONIT and add to it 300 metrics (which will probably add O(1KB) to the doc size). Then, evaluate how it will affect MONIT retention policy for WMArchive docs since we use ES/OpenSearch for WMArchive dashboard.

**Comment by leggerf** [comment]
adding @nikodemas to do the calculations ;)

**Comment by nikodemas** [comment]
According to my very approximate calculations, addition of 300 metrics shouldn't increase the size of document too much (in one random example document I looked into the size changed from 5kB to 17kB). We asked MONIT about this and they said that such increase is fine and the retention policy wouldn't change.

**Comment by amaltaro** [comment]
As discussed above, we need to resume this once Matti and Valentin are back. There are a few metrics in the CMSSW job report that need to be well understood before we start consuming it in WMAgent.

**Comment by makortel** [comment]
(answering the questions above here despite of being superseded by #11663)

> my understanding is that the `IO` metrics would be a duplication of the `Storage` ones, with the exception that the `Storage` metrics are aggregated by the agent (after passing a filter based on regex):

Correct. Personally I'd be happy if we'd remove the `Storage` altogether to avoid confusion, but I also understand the concern on existing monitoring components that rely on it.

> One last observation from the CMSSW FJR concerns this line:
> 
> ```
>   <PerformanceModule Metric="cern.ch"  Module="XrdSiteStatistics" >
> ```
> 
> is the metric really supposed to be called `cern.ch`?

This is, for better or worse, the way the CMSSW's `XrdStatistics` component reports the numbers. Here the `Module` attribute tells that the performance numbers come from the xrootd per-site statistics monitoring, and the `Metric` attribute tells the site the numbers are for. The job report XML file can have many `<PerformanceModule Metric="SITE"  Module="XrdSiteStatistics" >` elements with different values of `SITE`. If the example https://gist.github.com/vkuznet/2f27b11051f650d7e209fe67547247a8 is still representative of this part, it would be clearer that the `"site"` part
https://gist.github.com/vkuznet/2f27b11051f650d7e209fe67547247a8#file-fwjr-io-json-L248-L256 would be renamed to e.g. `xrootd`, it would contain e.g. a list of "site" elements, and the name of the site would also be included.

**Comment by amaltaro** [comment]
I understand this PR has been superseeded by https://github.com/dmwm/WMCore/pull/11663, so I am closing this one out. @vkuznet please reopen it in case I missed anything.

**Pull request closed without merging**
