### PR TITLE
Change the UUID module name

### PR DESCRIPTION
**Pull request by ticoann**
Due to the same reason as #7580. Also it is better not to use the built in module name although case is different.

### CODE REVIEW

**Comment by ticoann** [comment]
There are a lot more places using this module than I thought. I am not sure whether there is better approach. 
If this patch is approved. We also need to change

https://github.com/dmwm/T0/search?utf8=%E2%9C%93&q=UUID

and following patch might need to be recreated.
https://github.com/cms-sw/cmsdist/blob/comp_gcc493/crabserver3-setup.patch

But if there is better option please advise.

**Review by ericvaandering — APPROVED** [review]
Looks good. Now you just have to address all the pylint comments. :-) Just kidding.

**Comment by ticoann** [comment]
> Now you just have to address all the pylint comments

My heart stopped for a while.

**Review by amaltaro — APPROVED** [review]
Patch looks good.

**Pull request merged**
