### PR TITLE
make reqmgr and reqmgr2 call automatically

### LINKED ISSUE #6303: Make agent talk both ReqMgr and ReqMgr2 to seamlessluy
1. try to call ReqMgr for status change first if it fails try ReqMgr2
2. need to distinguish ReqMgr server failure or missing request (reqmgr2 request)

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6303  (Do not merge still need to be tested)

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Please review

**Comment by ericvaandering** [comment]
After reading up on this, I understand this one now:

> On Oct 2, 2015, at 11:58, DMWM Autobot <notifications@github.com> wrote:
> 
> ine 86 in CleanCouchPoller.algorithm W1201 Specify string format arguments as logging function parameters
> Line 94 in CleanCouchPoller.algorithm W1201 Specify string format arguments as logging function parameters
> Line 96 in CleanCouchPoller.algorithm W1201 Specify string format arguments as logging function parameters
> Line 99 in CleanCouchPoller.algorithm W1201 Specify string format arguments as logging function parameters
> 



After reading up on this, I understand this one now:

if you do logging.debug(‘%s is the color of %s’ % (‘blue’, ‘sky’)) python builds this string and then passes it to debug where it is promptly thrown away. if instead you do  
logging.debug(‘%s is the color of %s’ , ‘blue’, ‘sky’) the string is only created if you actually are going to output it. This can be a performance issue if there are lots of strings, especially if they are, like debug, never used.

Eric

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
> if you do
> ```
> logging.debug(‘%s is the color of %s’ % (‘blue’, ‘sky’))
> ```
>  python builds this string and then passes it to debug where it is promptly thrown away. if instead you do
> ```
> logging.debug(‘%s is the color of %s’ , ‘blue’, ‘sky’)
> ```
>  the string is only created if you actually are going to output it. This can be a performance issue if there are lots of strings, especially if they are, like debug, never used.

Thanks Eric, I was wondering whether there is a way to not create the sting unless it is debug mode. I didn't know about, this that is good too know.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
tested in vm merging it

**Pull request merged**
