### PR TITLE
Don't wrap cStringIO in try/except

### PR DESCRIPTION
**Pull request by ericvaandering**
Has to go in after #6934

### CODE REVIEW

**Comment by ericvaandering** [comment]
Well that obviously didn't work. Let me investigate.

**Comment by ericvaandering** [comment]
```
try:
     from cStringIO import cStringIO as StringIO
 except ImportError:
     from StringIO import StringIO
```
always fell back in the first place since 
```
from cStringIO import StringIO
```
is the correct way.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Ok, good to merge after the JSON wrapper stuff. Remaining red X is for the pylint stuff.

Thanks @amaltaro

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Looks good as well. I'll merge this one and cut a new tag & create private RPMs

**Pull request merged**
