### PR TITLE
Swith to compatible xrd client for old dcache version at FNAL

### PR DESCRIPTION
**Pull request by lucacopa**

### CODE REVIEW

**Comment by ericvaandering** [comment]
How urgent is this?

**Comment by lucacopa** [comment]
there will be an update in all the FNAL workernodes, we need this patch to be in place for new workflows before that happens. Maybe Alan need to fix the workflow sandboxes for some workflows already created in the wmagents too.

**Comment by ericvaandering** [comment]
Fixing sandboxes sounds like a crazy idea to me. I'm pretty sure @amaltaro  has better things to do with his time.

If FNAL can't figure out a way around this, then we can drain the site and start over.

**Comment by amaltaro** [comment]
I guess that's the best option for us. We've updated the sandboxes in the past (very dangerous but possible :))

**Pull request merged**
