### PR TITLE
Remove default value for ProcessingVersion inside a task

### LINKED ISSUE #7891: Task ProcessingVersion default value shouldn't be 0
That change was made by me and there was a good reason to keep that set to 0 (I think to fallback to the workload level arg in case that was eval to false).

However, if one creates a TaskChain request with ProcessingVersion arg only at the top level, the task dict will override that to 0, thus the output dataset for that task will be `v0`.

We either set the inner task default to 1 or we don't set a default there, such that the top level (workload) is used instead. I think latter option is better and less error prone.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7891
Change is simple, I'm just not sure whether there will be bad side effects in some other random use case.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Better, but I still need to test this and #7893. We can talk tomorrow and ask for a new testbed tag.

**Comment by amaltaro** [comment]
Looks good in my tests and all suggestions were taken care of.
@ticoann please review and merge

**Comment by amaltaro** [comment]
Actually, suggestions were made on the other PR :-)

**Review by ticoann — APPROVED** [review]

**Pull request merged**
