### PR TITLE
use latest wmagent-dev for default rpm

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by ericvaandering** [comment]
Have a look at https://github.com/cms-sw/cms-bot/blob/master/DMWM/latest-dmwm-versions.sh if you like. It determines the latest version.

**Comment by ericvaandering** [comment]
This is a new one. I've never seen this test flip before.

**Comment by ticoann** [comment]
> Have a look at https://github.com/cms-sw/cms-bot/blob/master/DMWM/latest-dmwm-versions.sh if you like. It determines the latest version.

Thanks, that is much better. I will update that.

**Comment by ticoann** [comment]
> This is a new one. I've never seen this test flip before.

This patch shouldn't affect any unittest. Maybe some of the patches I already merged cause this?

**Comment by ericvaandering** [comment]
I don't know.

**Comment by ticoann** [comment]
> WMCore_t.Services_t.UUID_t.UUIDTest:testUUID changed from success to failure

Hmm, this shouldn't be failing with this? @ericvaandering Eric, have you ever seen this test failed before?

**Comment by ericvaandering** [comment]
Yes I have. No idea why, never investigated.

**Pull request merged**
