### PR TITLE
New DAO to check subscriptions with no jobgroup associated; new condi…

### LINKED ISSUE #8648: vocms0256 has created > 3 million jobs (!)
There is something weird going on with the production system.
According to grafana, today at 15:05 CERN time there was a spike of requests in ReqMgr2 (jumping from ~4k to ~17k requests in the system), where ~6k of them were in acquired status. (I bet it was a monit glitch, since it's back to normal after 15:15).

Then looking at the agents, it seems vocms0256 managed to acquire and create more than 3M jobs
```
2018-06-11 15:57:47,223:139947075262208:INFO:JobSubmitterPoller:Found 3375907 new jobs to be submitted.
```

having a quick look at wmstats, some of those workflows are
pdmvserv_task_SMP-RunIISummer15wmLHEGS-00224__v1_T_180416_194001_5265
pdmvserv_task_SMP-RunIISummer15wmLHEGS-00225__v1_T_180416_194002_549
pdmvserv_task_SMP-RunIISummer15wmLHEGS-00226__v1_T_180416_194018_271
pdmvserv_task_SMP-PhaseIISummer17GenOnly-00022__v1_T_180607_163200_4994

all MC from scratch AFAICT.

### PR DESCRIPTION
**Pull request by amaltaro**
…tion for pulling work from GQ

Fixes #8648

When work gets acquired from GQ to LQ, and then from LQ to WMBS, a new subscription is created for every input from the WQE (usually a block). This subscription is then picked up by JobCreator which creates one or several jobgroups and the related jobs.

With this patch, there is a new constraint at WorkQueueManager level before it starts pulling work down. If there are Production or Processing subscriptions without any jobgroup associated (thus no jobs created), the component will log that blocker and skip that cycle.

### CODE REVIEW

**Comment by amaltaro** [comment]
It doesn't work! :(
The database query should be limited to top level tasks/subscriptions, otherwise it sees further subscriptions in a ReDigi (and I believe TaskChain) and doesn't pull work down (because the agent - of course - cannot create StepTwo or StepThree jobs until StepOne is done)...

**Comment by ticoann** [comment]
Alan, go to sleep.

**Comment by amaltaro** [comment]
Ok, I've made a minor change joining wmbs_workflow and fetching the task name as well. Then some - not very nice - taskname parsing/assumption and, we can put our hands in the top level tasks :-)

Still, I'm certain it's better than working through the workqueue elements, I hope you agree with me :)
Testing now

**Comment by amaltaro** [comment]
Seangchan, initial tests look good. If you agree with these changes, I can run a few more tests before we merge and backport it.

**Comment by ticoann** [comment]
Thanks Alan patch looks good to me.

**Comment by amaltaro** [comment]
It's good to go. I'm merging the wmagent branch one and cutting a patch5 tag.

**Review by ticoann — APPROVED** [review]

**Pull request merged**
