### PR TITLE
add cascade closeout

### LINKED ISSUE #6335: add closeout request with cascade option in reqmgr2

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6335 Do not merge. need further test.

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
fixed one unitest failure caused by this. Merging it for the new tag

**Pull request merged**
