### PR TITLE
Fix for issue 6657

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by ericvaandering** [comment]
Fixes #6657 ?

**Comment by vkuznet** [comment]
I made a code change, but unable to test it yet on Seangchan's VM,
I'm awaiting for a fix from him about another issue.

**Comment by ericvaandering** [comment]
Oh, I was trying to generate a GitHub link between the issue and PR. :-)

**Comment by ticoann** [comment]
Valentin, it doesn't seems to be working. code is updated in reqmgr2-dev. Not sure why. I will check tomorrow

**Comment by vkuznet** [comment]
@ticoann , Seangchan do you have any example of non-editable taskname that I can have a look for this issue.

**Comment by vkuznet** [comment]
@ticoann, Seangchan I still need an input from you on this issue.

**Comment by amaltaro** [comment]
@vkuznet what are you waiting for on this PR?

Seangchan has an active workflow
https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_MonteCarlo_eff_reqmgr1_160516_204215_710

that does not show the behaviour you described 
`
I made a change from drop-down to non-modifiable textarea where entries will be shown as comma separated values. Please take PR
`

**Comment by vkuznet** [comment]
Alan,
I'm waiting when Seangchan will apply the PR and give me example if it does not
work.

**Comment by ticoann** [comment]
Sorry Valentin, for the long delay. I fetched this one in reqmgr2-dev.cern.ch

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=request-sryu_MonteCarloFromGEN_reqmgr1_160524_053421_9980

If you look at the site white list, or other drop down menu, they are still drop down and cannot be expended

**Comment by vkuznet** [comment]
Seangchan, Alan,
could you please have a look now at this URL
https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=request-sryu_MonteCarloFromGEN_reqmgr1_160524_053421_9980

and let me know if that what you want.
Thanks,
Valentin.

**Comment by amaltaro** [comment]
It sounds good now, Valentin. We still need to check what happens to workflows in:
 - new or assignment-approved state
 - assigned or acquired state.

I'll try to get back to it later today

**Comment by ticoann** [comment]
Thanks Valentin, this looks good. Alan, don't spend time. I am checking those conditions now.

**Comment by ticoann** [comment]
@vkuznet, Valentin, there is typo in line 100 of WMCore/ReqMgr/Web/utils.py
**visibile_attrs** I fixed in reqmgr2-dev and restarted the server. (Please update your patch as well).

```
            if  visible_attrs and isinstance(**visibile_attrs**, list) and key in visible_attrs:
```
Also I found when I change the sitewhite list in the assignment-approved using GUI but it doesn't seem to be update the field.

I added 3 requests for you to debug and test. (It need to make the state transition to "assigned" when you update) 
 https://reqmgr2-dev.cern.ch/reqmgr2/requests?status=assignment-approved

**Comment by vkuznet** [comment]
Seangchan,
I changed logic again, since what I provided remove drop-down list in your
assignment-approved state.

Please have a look at two different use case
1. where no visible attributes, the drop down are replaced with text area
https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=request-sryu_MonteCarloFromGEN_reqmgr1_160524_053421_9980
2. where there are visible attributes, we preserve drop-down
https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=request-sryu_MonteCarlo_eff_reqmgr2_160526_163634_4326

I'm not sure about sitewhitelist. What should happen? Client will put some
entries (should it be a single value, or comma separated list)?

If I put now into
https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=request-sryu_MonteCarlo_eff_reqmgr2_160526_163634_4326
some values I get

Server error message
Invalid spec parameter value: can't update value without state transition: {} 

From reqmgr2 log I get:
```
Getting from Cache due to: CouchNotFoundError - reason: Object Not Found, data: {} result: None
[26/May/2016:16:55:32]  SERVER REST ERROR WMCore.ReqMgr.DataStructs.RequestError.InvalidSpecParameterValue 2b0295e4b25abb59
d3cb5364b4c73d5b (Invalid spec parameter value: can't update value without state transition: {})
[26/May/2016:16:55:32]    Traceback (most recent call last):
[26/May/2016:16:55:32]      File "/data/srv/HG1605c-comp2/sw.sryu/slc6_amd64_gcc493/cms/reqmgr2/1.0.17.pre2/lib/python2.7/s
ite-packages/WMCore/REST/Server.py", line 701, in default
[26/May/2016:16:55:32]        return self._call(RESTArgs(list(args), kwargs))
[26/May/2016:16:55:32]      File "/data/srv/HG1605c-comp2/sw.sryu/slc6_amd64_gcc493/cms/reqmgr2/1.0.17.pre2/lib/python2.7/s
ite-packages/WMCore/REST/Server.py", line 776, in _call
[26/May/2016:16:55:32]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[26/May/2016:16:55:32]      File "/data/srv/HG1605c-comp2/sw.sryu/slc6_amd64_gcc493/cms/reqmgr2/1.0.17.pre2/lib/python2.7/s
ite-packages/WMCore/ReqMgr/Service/Request.py", line 561, in put
[26/May/2016:16:55:32]        result = self._updateRequest(workload, request_args)
[26/May/2016:16:55:32]      File "/data/srv/HG1605c-comp2/sw.sryu/slc6_amd64_gcc493/cms/reqmgr2/1.0.17.pre2/lib/python2.7/s
ite-packages/WMCore/ReqMgr/Service/Request.py", line 533, in _updateRequest
[26/May/2016:16:55:32]        report = self._handleNoStatusUpdate(workload, request_args)
[26/May/2016:16:55:32]      File "/data/srv/HG1605c-comp2/sw.sryu/slc6_amd64_gcc493/cms/reqmgr2/1.0.17.pre2/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 459, in _handleNoStatusUpdate
[26/May/2016:16:55:32]        raise InvalidSpecParameterValue("can't update value without state transition: %s" % request_args)
[26/May/2016:16:55:32]    InvalidSpecParameterValue: InvalidSpecParameterValue 2b0295e4b25abb59d3cb5364b4c73d5b [HTTP 400, APP 1102, MSG "Invalid spec parameter value: can't update value without state transition: {}", INFO None, ERR None]
```

which seems like server error rather than reqmgr2.

You originally claimed that we can send parameters with the same transition?
Did you applied another PR which I did to make it happen?

Valentin.

**Comment by vkuznet** [comment]
Seangchan, please take https://github.com/dmwm/WMCore/pull/6892 for a currently working fix for issue 6657 and discard this one.

**Comment by ticoann** [comment]
replaced by #6892

**Pull request closed without merging**
