### PR TITLE
Fix transaction logic; connection usage; use generator objects in DBCore; clean patch replacement of 6284

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by vkuznet** [comment]
Hi,
I see that over weekend Eric/Seangchan tested this PR on jenkins.
From this, last, build I see that it is clean. Am I right?

If so, since I combine all changes into single PR, I would propose the
following:

- once the upgrade is finished we create separate branch and merge this PR over
  there
- we build two set of RPMs, once from the head and one from this new branch
- we deploy two agents, one with the head RPMs and another with new branch RPMs
- we run normal tests over them, e.g. assign/run workflows, etc.
- if we didn't experience any hickups we merge branches and move on
with proposed changes (I'll be able to start working on further WMCore
re-factoring and take advantage of generators).

Please let me know your opinion,
Valentin.

**Comment by ericvaandering** [comment]
Yeah this one test is already in unstable tests (and of course you "fixed" it).

**Comment by ticoann** [comment]
Hi Valentin, patch itself is not big so I don't think we have to create the branch for that.
We can test just patching this on the latest rpm (production) rpm. If everything goes fine we can merge it after production deployment and create the new rpm. and keep running more tests with it.
If too many things are broken (which I don't expect) we can create the branch and fixes the bugs.
Is that OK with you?

**Comment by vkuznet** [comment]
yes, it is ok with me.

**Comment by ticoann** [comment]
@vkuznet, Hi Valentin, I am running the test with this patch but I get this error in reqmgr.

```
ERROR:cherrypy.error:Create request failed, reason: Traceback (most recent call last):
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrRESTModel.py", line 475, in putRequest
    self.workloadDBName, self.wmstatWriteURL)
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrWebTools.py", line 468, in makeRequest
    request = buildWorkloadAndCheckIn(webApi, reqSchema, couchUrl, couchDB, wmstatUrl)
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrWebTools.py", line 413, in buildWorkloadAndCheckIn
    reqDetails = requestDetails(request["RequestName"])
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrWebTools.py", line 474, in requestDetails
    request = GetRequest.getRequestDetails(requestName)
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/RequestManager/RequestDB/Interface/Request/GetRequest.py", line 142, in getRequestDetails
    request = getRequestByName(requestName)
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/RequestManager/RequestDB/Interface/Request/GetRequest.py", line 109, in getRequestByName
    return getRequest(requestID(requestName))
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/RequestManager/RequestDB/Interface/Request/GetRequest.py", line 39, in getRequest
    reqData = reqGet.execute(requestId)
  File "/data/srv/HG1511c/sw.pre/slc6_amd64_gcc481/cms/reqmgr/1.0.11.pre8/lib/python2.6/site-packages/WMCore/RequestManager/RequestDB/MySQL/Request/Get.py", line 38, in execute
    for field, val in value.items():
AttributeError: 'ResultRow' object has no attribute 'items'
```
I think in the ResultRow class we need to mock items() function as well. ( not sure that is the only one missing)
```
def items(self):
        """Imitate dict items method"""
        return [(k, self._data[k]) for k in self._keys]
```
Could you update the patch?  Thanks, Seangchan

**Comment by vkuznet** [comment]
Seangchan, I added items/iteritems methods since they both present in dict implementation. And I used internal get method to get key value from ResultRow. The items method just re-use iterator iteritems.

**Comment by ticoann** [comment]
Thanks Valentin, I will run the test again.

**Comment by ticoann** [comment]
It worked fine in my vm test. (MySQL), @amaltaro Alan, could you run the unittest in Oracle. (It doesn't have to be integration test)

**Comment by amaltaro** [comment]
Seangchan, I ran the Database and the WMBS unittests and couldn't see anything exploding there. These were the results
path lists is ['wmcore_unittest/WMCore/test/python/WMCore_t/Database_t']
Ran 37 tests in 31.049s
FAILED (errors=3)

path lists is ['wmcore_unittest/WMCore/test/python/WMCore_t/WMBS_t/']
Ran 212 tests in 2074.048s
FAILED (SKIP=2, errors=1, failures=12)

I'll fetch the master branch and run the same tests. Results later on.

**Comment by ticoann** [comment]
Thanks Alan, could you post what are the errors?

**Comment by amaltaro** [comment]
Sure, running tests again.

**Comment by amaltaro** [comment]
You can find both outputs here Seangchan:
http://amaltaro.web.cern.ch/amaltaro/forSeangChan/unittests/

several JobSplitting tests failed with this patch providing a wrong number of jobs and etc, which is worrisome

**Comment by ticoann** [comment]
Thanks Alan,  So it seems errors are the same for both test (CouchDB connection error). It is weird that patch cause different result on JobSplitting test.

**Comment by vkuznet** [comment]
Alan, Seangchan, where do we stand on this issue. My understanding was that
we had failure with ORACLE back-end and you suppose to setup a VM (or give me
access to it) that I can proceed with testing.

**Comment by ticoann** [comment]
Sorry Valentin, I will set it up today in one of the Fermi machine.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
