### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ticoann** [comment]
@ericvaandering, Eric, can I close this one?

**Comment by ericvaandering** [comment]
No, please leave it open. I want to play with this w.r.t. Jenkins.

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
Retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Pull request closed without merging**
