### PR TITLE
Reorganize imports

### PR DESCRIPTION
**Pull request by ericvaandering**
Each of these files original format surrounding imports, docstrings, and comments caused the futurize program to put new imports in the wrong place breaking the code.

### CODE REVIEW

**Comment by ericvaandering** [comment]
@ticoann please merge

**Comment by ticoann** [comment]
@ericvaandering, Is that a set of rules for this to work with futurize? Any other module needs to be corrected?

**Comment by ericvaandering** [comment]
This is most of it, at least. I don't really understand what happens per se. If things are not done like this (and I don't know which parts are essential) then futurize likes to add imports above the ```__future``` imports. 

Thanks for merging. I'll try running futurize again and see if there are more problems

**Comment by ericvaandering** [comment]
I'm not sure this even worked. I guess as we do these migrations we will just have to re-order things manually to avoid blowing stuff up.

**Pull request merged**
