### PR TITLE
New exit code for job pickle object badly formatted - JobSubmitter - wmagent branch

### LINKED ISSUE #9515: JobSubmitter crashing while loading pickle files
**Impact of the bug**
WMAgent (vocms0283)

**Describe the bug**
This node had to be rebooted this morning, after having a load of >>1000 and becoming unresponsive.
It looks like it has also been affected by the CEPH outage, and some (at least 1 so far) job pickle files are empty. 

The agent crashes when loading such empty pickle file, e.g.:
/data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeSKIMStreamMuTau/JobCollection_146408_0/job_1271395/job.pkl

**How to reproduce it**
none

**Expected behavior**
Ideally, we should recreate that job pickle file. Problem is that the whole job creation logic happens in the JobCreator, when handling a WQE/block/fileset and performing the job splitting algorithm.

I could say that we should not crash the component as well, but in that case, we would need to bypass the pickle file, which would cause incomplete statistics in the output...

I'm creating this issue to keep track of this problem and how we deal with it.

**Additional context and error message**
Component traceback:
```
2020-01-28 11:15:09,178:140481657870080:INFO:JobSubmitterPoller:Determining possible sites for new jobs...
2020-01-28 11:15:14,570:140481657870080:INFO:JobSubmitterPoller:Processed 5000/50000 new jobs.
2020-01-28 11:15:23,534:140481657870080:INFO:JobSubmitterPoller:Processed 10000/50000 new jobs.
2020-01-28 11:15:28,142:140481657870080:ERROR:JobSubmitterPoller:Error while loading pickled job object /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_253
2/DataProcessing/DataProcessingMergeSKIMStreamMuTau/JobCollection_146408_0/job_1271395/job.pkl

2020-01-28 11:15:28,203:140481657870080:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobSubmitter.JobSubmitterPoller.JobSubmitterPoller object at 0x7fc476ae07d0> <@========== WMException Start ==========@>
Exception Class: JobSubmitterPollerException
Message: Error while loading pickled job object /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeSKIMStreamMuTau/JobC
ollection_146408_0/job_1271395/job.pkl

        ModuleName : WMComponent.JobSubmitter.JobSubmitterPoller
        MethodName : refreshCache
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMComponent/JobSubmitter/JobSubmitterPoller.py
        ClassName : None
        LineNumber : 322
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMComponent/JobSubmitter/JobSubmitterPoller.py", line 317, in refreshCache
    loadedJob = pickle.load(jobHandle)

<@---------- WMException End ----------@>  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 182, in __call__
    tSpent, results, _ = algorithmWithDBExceptionHandler(parameters)
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMCore/Database/DBExceptionHandler.py", line 39, in wrapper
    return f(*args, **kwargs)
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMComponent/JobSubmitter/JobSubmitterPoller.py", line 817, in algorithm
    self.refreshCache()
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMComponent/JobSubmitter/JobSubmitterPoller.py", line 322, in refreshCache
    raise JobSubmitterPollerException(msg)

2020-01-28 11:15:28,203:140481657870080:INFO:Harness:>>>Terminating worker threads
2020-01-28 11:15:28,275:140481657870080:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.JobSubmitter.JobSubmitterPoller.JobSubmitterPoller object at 0x7fc476ae07d0> <@========== WMException Start ==========@>
Exception Class: JobSubmitterPollerException
Message: Error while loading pickled job object /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeSKIMStreamMuTau/JobCollection_146408_0/job_1271395/job.pkl

        ModuleName : WMComponent.JobSubmitter.JobSubmitterPoller
        MethodName : refreshCache
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMComponent/JobSubmitter/JobSubmitterPoller.py
        ClassName : None
        LineNumber : 322
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMComponent/JobSubmitter/JobSubmitterPoller.py", line 317, in refreshCache
    loadedJob = pickle.load(jobHandle)

<@---------- WMException End ----------@>
Backtrace:
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 208, in __call__
    raise ex

2020-01-28 11:15:28,891:140481657870080:INFO:BaseWorkerThread:Worker thread <WMComponent.JobSubmitter.JobSubmitterPoller.JobSubmitterPoller object at 0x7fc476ae07d0> terminated
```

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch version of #9520

#### Status
not-tested 

#### Description
Summary of changes is:
* adds a new exit code `71105`, for cases where the job pickle object is badly formatted
* swapped exit codes `71103` and `71104`, in order to keep similar problems as sequential as possible
* do not crash the component in case we hit an exception loading a pickle file. Set it to bad jobs and mark it as `SubmitFailed`.
* minor changes to the error messages
* add those error codes: 71104 and 71105 to the list of NoRetryExitCodes

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
applying it to vocms0283 for the moment.

**Comment by amaltaro** [comment]
That agent found a total of 10 jobs with an invalid pickle file
```
2020-01-28 14:28:35,319:140013322929920:INFO:JobSubmitterPoller:Found 50000 new jobs to be submitted.
2020-01-28 14:28:35,319:140013322929920:INFO:JobSubmitterPoller:Determining possible sites for new jobs...
2020-01-28 14:28:40,431:140013322929920:INFO:JobSubmitterPoller:Processed 5000/50000 new jobs.
2020-01-28 14:28:48,927:140013322929920:INFO:JobSubmitterPoller:Processed 10000/50000 new jobs.
2020-01-28 14:28:54,100:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271394, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeALCARECOStreamHcalCalHBHEMuonFilter/JobCollection_146407_0/job_1271394/job.pkl
2020-01-28 14:28:54,101:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271393, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeALCARECOStreamHcalCalHBHEMuonFilter/JobCollection_146407_0/job_1271393/job.pkl
2020-01-28 14:28:54,102:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271392, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeALCARECOStreamHcalCalHBHEMuonFilter/JobCollection_146407_0/job_1271392/job.pkl
2020-01-28 14:28:54,102:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271391, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeALCARECOStreamHcalCalHBHEMuonFilter/JobCollection_146407_0/job_1271391/job.pkl
2020-01-28 14:28:57,510:140013322929920:INFO:JobSubmitterPoller:Processed 15000/50000 new jobs.
2020-01-28 14:29:12,643:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271397, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeSKIMStreamZMu/JobCollection_146409_0/job_1271397/job.pkl
2020-01-28 14:29:12,643:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271396, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pgunnell_Run2018D-v1-SingleMuon-12Nov2019_UL2018_1064p1_200113_212951_2532/DataProcessing/DataProcessingMergeSKIMStreamZMu/JobCollection_146409_0/job_1271396/job.pkl
2020-01-28 14:30:02,683:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271382, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_HIG-RunIIAutumn18FSPremix-00018__v1_T_191210_120806_327/HIG-RunIIAutumn18FSPremix-00018_0/HIG-RunIIAutumn18MiniAOD-02388_0/HIG-RunIIAutumn18MiniAOD-02388_0MergeMINIAODSIMoutput/JobCollection_146402_0/job_1271382/job.pkl
2020-01-28 14:30:07,223:140013322929920:INFO:JobSubmitterPoller:Processed 20000/50000 new jobs.
2020-01-28 14:31:23,186:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271384, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_HIG-RunIIFall17wmLHEGS-02841__v1_T_200122_114728_2516/HIG-RunIIFall17wmLHEGS-02841_0/HIG-RunIIFall17wmLHEGS-02841_0CleanupUnmergedRAWSIMoutput/JobCollection_146404_0/job_1271384/job.pkl
2020-01-28 14:31:23,187:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271383, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_HIG-RunIIFall17wmLHEGS-02841__v1_T_200122_114728_2516/HIG-RunIIFall17wmLHEGS-02841_0/HIG-RunIIFall17wmLHEGS-02841_0CleanupUnmergedRAWSIMoutput/JobCollection_146403_0/job_1271383/job.pkl
2020-01-28 14:31:25,662:140013322929920:ERROR:JobSubmitterPoller:BAD pickle file for jobid: 1271381, pickle path: /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_SUS-RunIIFall17FSPremix-00176__v1_T_191210_115144_5285/SUS-RunIIFall17FSPremix-00176_0/SUS-RunIIFall17FSPremix-00176_0CleanupUnmergedAODSIMoutput/JobCollection_146401_0/job_1271381/job.pkl
2020-01-28 14:31:35,212:140013322929920:INFO:JobSubmitterPoller:Processed 25000/50000 new jobs.
2020-01-28 14:32:42,191:140013322929920:INFO:JobSubmitterPoller:Processed 30000/50000 new jobs.
2020-01-28 14:34:20,732:140013322929920:INFO:JobSubmitterPoller:Processed 35000/50000 new jobs.
2020-01-28 14:35:24,024:140013322929920:ERROR:JobSubmitterPoller:Could not find pickled jobObject /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIIFall17MiniAODv2-00059__v1_T_200124_052507_5063/BTV-RunIIFall17MiniAODv2-00059_0/JobCollection_146410_0/job_1271398/job.pkl
2020-01-28 14:35:24,059:140013322929920:ERROR:JobSubmitterPoller:Could not find pickled jobObject /data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIIFall17MiniAODv2-00059__v1_T_200124_052507_5063/BTV-RunIIFall17MiniAODv2-00059_0/JobCollection_146411_0/job_1271399/job.pkl
2020-01-28 14:35:36,417:140013322929920:INFO:JobSubmitterPoller:Processed 40000/50000 new jobs.
2020-01-28 14:36:49,126:140013322929920:INFO:JobSubmitterPoller:Processed 45000/50000 new jobs.
2020-01-28 14:38:46,733:140013322929920:INFO:JobSubmitterPoller:Processed 50000/50000 new jobs.
2020-01-28 14:38:47,192:140013322929920:ERROR:JobSubmitterPoller:Failed to write FWJR for submit failed job 1271398, message: [Errno 2] No such file or directory: '/data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIIFall17MiniAODv2-00059__v1_T_200124_052507_5063/BTV-RunIIFall17MiniAODv2-00059_0/JobCollection_146410_0/job_1271398/Report.0.pkl'
2020-01-28 14:38:47,193:140013322929920:ERROR:JobSubmitterPoller:Failed to write FWJR for submit failed job 1271399, message: [Errno 2] No such file or directory: '/data/srv/wmagent/v1.2.8/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIIFall17MiniAODv2-00059__v1_T_200124_052507_5063/BTV-RunIIFall17MiniAODv2-00059_0/JobCollection_146411_0/job_1271399/Report.0.pkl'
2020-01-28 14:38:57,229:140013322929920:INFO:JobSubmitterPoller:Found 10 jobs with bad/empty pickle files
```

we might have to fail those as well...

**Comment by amaltaro** [comment]
@dabercro Dan, this patch is likely going to get applied to the production agents. Given that it touches/changes the job exit codes, I'm tagging you just to make sure it won't cause any issues with the exit code analytics project you've been working on.

I still have to run some final tests though.

**Comment by amaltaro** [comment]
Patch updated and reapplied to vocms0283. Once I retrieve access to the service account, I'll push it to the other agents too.

**Comment by amaltaro** [comment]
[Fix #9516 - New exit code for job pickle object badly formatted - JobSubmitter](https://trello.com/c/uuH5g0G1/190-fix-9516-new-exit-code-for-job-pickle-object-badly-formatted-jobsubmitter)

**Comment by dabercro** [comment]
Thanks for the heads up.

Sharad and Jen say that they tend to look at the logs before they look at the exit codes, so switching codes does not necessarily help them. Are there other people are looking at these codes?

Though not ideal for us, if you do go ahead and make the swap between 71103 and 71104, just let us know the exact date that the exit codes will come back differently. Then we can translate our old data up to that point.

Also, do you know what the new 71106 exit code used to throw?

**Comment by amaltaro** [comment]
These exit codes are mostly important for P&R operations, but there might be some random folks also looking into them.
About `71106`, it's not an exit code thrown by WMCore (it's an upper limit in the range command, so it comes 71106 - 1).

I guess I just made your life harder than. Because the "problematic" WMAgent got patch on the Friday ~10am UTC, while all the other agents got patched now ~2pm UTC.

@vkuznet I don't remember what was the final conclusion. Is the exitCodes app going to automatically fetch these new exit codes/description from WMCore?

@todor-ivanov this patch is good to go. Can you please merge it? Thanks

**Comment by vkuznet** [comment]
Alan,
I made exitcodes app to fetch data from exitcodes github [area](https://github.com/vkuznet/CMSExitCodes/tree/master/codes). Once new file will appear there the app will properly display it. I didn't plan to fetch it directly from WMCore area for several reasons:
1. the exitcodes in WMCore area is a python code and not ASCII file, therefore it requires to parse it
2. WMCore stores them in format suitable for WMCore but not necessary in independent format which can be used in a generic way
3. the idea of exitcodes was to display different exit codes, and cover broader spectrum of them (beyond only WMCore), therefore I end-up with generic way to process and use them, i.e. the exit codes should be stored in ASCII file with format (code: description) and individual files will represent whatever system we may have
Said that, the app itself fetches codes from this area periodically, and therefore they codes will be updated once new commit will be made to github repository (there is no need to restart/upgrade the app).

Therefore, if we want to automate exitcodes updates, I suggest to add a script for WMCore which will provide exit codes in aforementioned data-format and push them to github.

**Comment by amaltaro** [comment]
Okay, please let me know if you want me to make a PR against your repo/project, or if you can commit such changes yourself. Thanks

**Pull request merged**
