### PR TITLE
add more information on SubmitFailed case

### LINKED ISSUE #6868: Expose the site of failure for SubmitFail
when a job is in status SubmitFailed, wmstats does not report to which site(s) it failed to do so : this should be reported instead so that one can judge on whether an ACDC is possible

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6868 
@amaltaro, Alan please review. I think this is the a hacky way to do this. If you know better way, please advise. Thanks,

### CODE REVIEW

**Comment by ticoann** [comment]
This still need to be tested

**Comment by amaltaro** [comment]
Sounds hacky and good :-) Have you tried running this code? Exercising exactly that exit code is tricky, but it would be great to have an example output.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Seangchan, as we discussed, I cloned and assigned another workflow in reqmgr2-dev
```
amaltaro@vocms049:/data/amaltaro/ReqMgr/Sept2016_Patches $ python /data/amaltaro/ReqMgr/WmAgentScripts/resubmitXClone.py anlevin_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160715_143350_6875
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183022_3574
```

And I created two more clones in case you need to play with them any further, you just need to assign the following:
```
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183044_7924
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183111_8542
```

**Comment by ticoann** [comment]
Thanks Alan

**Comment by ticoann** [comment]
Hmm, this time wf is actually running instead of SubmitFailed.

amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183022_3574

I will assign one of the other two workflows. (Should I set specify white list?)

**Comment by amaltaro** [comment]
Well, it's running fine because I'm stupid and forgot to set TrustSitelists to True, sorry :(
I suggest you to decrease the job splitting for the 1st task from 2k to 1k, to get smaller jobs and assign it to CERN (or CERN+FNAL) and enable AAA for the input dataset.

**Comment by ticoann** [comment]
You don't have to reply so fast. Not good you are still working. :-) Thanks Alan, I assigned one of your request amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183044_7924.
And the other one is now for aborting test. 😄

**Comment by ticoann** [comment]
Hmm I set 
amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183044_7924.tasks.ZTTFS_13.constraints.sites.trustPUlists = False
amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183044_7924.tasks.ZTTFS_13.constraints.sites.trustlists = True

and set site to CERN and FNAL, jobs still ran and failed.

I will try only CERN site with amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160919_183111_8542

**Comment by amaltaro** [comment]
The first workflow failed with maxRSS and the second is stuck (assigned to T0).
I created and assigned (hardcoded settings) the following:
```
amaltaro@vocms049:/data/amaltaro/ReqMgr/Sept2016_Patches $ python /data/amaltaro/ReqMgr2_scripts/assignWFtestbed.py -w amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160920_144524_1859 -t testbed-dev --trust
amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160920_144524_1859 	AcqEra: DMWM_Test 	ProcStr: DMWM_Test_Sept2016_TEST 	ProcVer: 99 	MaxRSS: 3072000 	Team: testbed-dev 	Site: ['T2_CH_CERN'] 	Trust: True
Assigned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160920_144524_1859 to site: ['T2_CH_CERN'] and team testbed-dev
```

**Comment by ticoann** [comment]
Hmm that workflow still runs. 
So far only initial workflows you sent a few days ago has SubmitFailure.

amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160916_144227_2456

Was there any difference in setting?

**Comment by amaltaro** [comment]
Ok, I think I remembered how to reproduce that issue. Last attempt with the following setup:
a) creating a workflow with the TrustSitelists=True
b) assigning this workflow without this flag

**Comment by amaltaro** [comment]
There we go, two more requests (though I forgot to decrease the job splitting to get shorter jobs).
```
Without providing any Trust* during assignment
Assigned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160920_175705_648 to site: ['T2_CH_CERN'] and team testbed-dev

Providing TrustSitelists=False
Assigned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160920_175841_3448 to site: ['T2_CH_CERN'] and team testbed-dev
```

**Comment by ticoann** [comment]
> Ok, I think I remembered how to reproduce that issue. Last attempt with the following setup:
> a) creating a workflow with the TrustSitelists=True
> b) assigning this workflow without this flag

This sounds like bug. If it is created with TrustSitelists should be True in assigned state as well or can be overwritten to False

**Comment by amaltaro** [comment]
We'll solve all these problem when we define create arguments and assignment arguments. I didn't forget there is an issue for that, just didn't manage to invest time on that yet :-)

**Comment by ticoann** [comment]
@amaltaro, Alan, could you send a couple of more request and leave one in assigned-approved status? Thanks

**Comment by amaltaro** [comment]
Sure, here are the new clones and the first one (*_4215) was assigned:
```
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160921_182101_4215
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160921_182121_4520
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160921_182240_4419
Cloned workflow: amaltaro_RVCMSSW_8_1_0_pre8ZTT_13__FastSim_160921_182253_984
```

**Pull request merged**
