### PR TITLE
Estimate job time based on the TimePerEvent only, not cores 

### LINKED ISSUE #8411: requested walltime is much less than 8h
people from the cpu-eff task force were looking at inefficiencies from 

https://cms-gwmsmon.cern.ch/prodview/fabozzi_Run2017F-v1-BTagCSV-17Nov2017_940_171218_171845_1070

coming from too short jobs. The requested walltime is ranging 20-75 minutes.

cmst1@vocms0250:/afs/cern.ch/user/v/vlimant $ condor_q -const 'WMAgent_RequestName =="fabozzi_Run2017F-v1-BTagCSV-17Nov2017_940_171218_171845_1070"' -af  EstimatedSingleCoreMins OriginalMaxWallTimeMins MaxWallTimeMins  RequestCpus WMCore_ResizeJob | sort | uniq
175 20 20 8 false
300 37 37 8 false
325 40 40 8 false
350 42 42 8 false
350 45 45 8 false
400 50 50 8 false
425 75 75 8 false
450 75 75 8 false
475 75 75 8 false
500 75 75 8 false
750 75 75 8 false

even if time/event is wrongly estimated, the target requested walltime should be more in the 8h region than 1h.
What is the limiting factor for creating/requesting longer running jobs ?

BTW https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_HIG-RunIIFall17wmLHEGS-00048__v1_T_180110_201332_6404 MC seems to have the same issue too.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8411

I also checked all the rest of the code and it looks to be consistent now.
In addition to that, I added a validation to the MonteCarlo spec to support only EventBased job splitting (then pylint fixes)

Disclaimer: the job splitting hasn't been touched, the only change is related to the job time estimation.

### CODE REVIEW

**Comment by amaltaro** [comment]
Tests look good! This is before patching the agent:
```
cmst1@vocms0192:/data/srv/wmagent/current $ condor_history -const 'WMAgent_RequestName =="amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402"' -af WMAgent_SubTaskName EstimatedSingleCoreMins OriginalMaxWallTimeMins MaxWallTimeMins RequestCpus WMCore_ResizeJob | sort | uniq -c
      1 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 100 12 12 8 false
      2 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 225 30 30 8 false
      1 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 425 75 75 8 false
    312 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 750 75 75 8 false
```

and this is after
```
cmst1@vocms0192:/data/srv/wmagent/current $ condor_q -const 'WMAgent_RequestName =="amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402"' -af WMAgent_SubTaskName EstimatedSingleCoreMins OriginalMaxWallTimeMins MaxWallTimeMins RequestCpus WMCore_ResizeJob | sort | uniq -c
      7 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 3500 450 450 8 false
     25 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 3750 450 450 8 false
     31 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 3750 475 475 8 false
     10 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 4000 475 475 8 false
      6 /amaltaro_Run2017F-v1-BTagCSV-17Nov2017_940_180115_142205_7402/DataProcessing 4000 500 500 8 false
```

I'm going to backport it to 1.1.8 and apply to the production agents.

**Comment by bbockelm** [comment]
Ouch.  The granularity is fairly small here (25 minute increments in `MaxWallTimeMins`)  Would it be possible to bin these into 120 minute bins prior to submitting to HTCondor?

**Comment by amaltaro** [comment]
The granularity is actually 1min :) 
Sure it's possible, but I'd rather handle that in a different issue/PR. And apply the same treatment to other metrics (Memory, Disk, ???)

**Comment by bbockelm** [comment]
Yup, will reopen a separate issue.  It's probably reasonable to also round disk usage -- memory usage tends to not need rounding as its not dependent on job length.

**Review by ticoann — APPROVED** [review]

**Pull request merged**
