### PR TITLE
No need these deps in apmon

### PR DESCRIPTION
**Pull request by juztas**
Tested with crab3: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=160422_074307%3Ajbalcas_crab_testapmon

### CODE REVIEW

**Comment by amaltaro** [comment]
Justas, all the new modules should have these imports
`
from __future__ import print_function
from __future__ import division
`

This PR goes on the other direction that we want to go. Including defining classes on the old way.

**Comment by juztas** [comment]
So in this case you need to have future package on WN

**Comment by amaltaro** [comment]
WMAgent certainly ships it with the job. If CRAB does not, then we have to solve it in a different way instead of demoting the code to python 2.4.

**Comment by juztas** [comment]
Ok, tested now. Missread what was the problem and it is not future. Problem is builtins and past.utils. 
for crab it is another problem, so not for this discussion. 

Will create new one. Thanks Vago ;)

**Pull request closed without merging**
