### PR TITLE
fix t0 disk usage report

### LINKED ISSUE #8212: AgentStatusPoller broken in Tier0 2.0.9
What is the error message trying to tell me ?

2017-10-02 21:42:13,354:140023845025536:INFO:AgentStatusPoller:Getting agent info ...
2017-10-02 21:42:13,777:140023845025536:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: You must include http(s):// in your server's address, ReqMgr2 rest service/data/ doesn't
Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 112, in algorithm
    agentInfo = self.collectAgentInfo()
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 188, in collectAgentInfo
    agentInfo['disk_warning'] = listDiskUsageOverThreshold(self.config, updateDB=True)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 141, in listDiskUsageOverThreshold
    reqMgrAux = ReqMgrAux(config.TaskArchiver.ReqMgr2ServiceURL)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 34, in __init__
    Service.__init__(self, httpDict)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Service.py", line 133, in __init__
    self["requests"] = requests(cfg_dict['endpoint'], cfg_dict)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 526, in __init__
    Requests.__init__(self, url, idict)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 109, in __init__
    check_server_url(self['host'])
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 58, in check_server_url
    raise ValueError(msg)
ValueError: You must include http(s):// in your server's address, ReqMgr2 rest service/data/ doesn't

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8212

### CODE REVIEW

**Comment by ticoann** [comment]
@hufnagel, Dirk in Tier0 config following line has to be added.

https://github.com/dmwm/T0/blob/master/etc/Tier0Config.py

```
config.AgentStatusWatcher.ignoreDisks = [/luster/] #list of path need to be ignored about size usage
config.AgentStatusWatcher.diskUseThreshold = 90 # percentage of warning i.e 90 (90%)
```

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
and this test
WorkQueue_t.WorkQueueTest:testProductionMultiQueue

works fine in my VM too. Trying it a last time.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
and now it failed with another unstable test that I have to fix (test_NotEnoughEvents). So we're good

**Review by amaltaro — APPROVED** [review]

**Pull request merged**
