### PR TITLE
#7605 #7620 for  1.1.0 wmagent 

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan this need to be included in wmagent branch for the deployment, right?

### CODE REVIEW

**Comment by amaltaro** [comment]
Yes, it's the only additional fix. I was actually thinking in accumulating a few more PRs before we merge it and cut a new patch release :)

**Comment by amaltaro** [comment]
@ticoann can you cherry-pick 7620 and edit this Pr subject please? We can then cut a patch2 tag once this one is merged

**Comment by ticoann** [comment]
@amaltaro, Alan 1.1.0.patch2 is created

**Comment by ticoann** [comment]
Oops, Sorry #7593 wasn't added. I will create that patch and new tag.

**Comment by amaltaro** [comment]
I knew there was another PR that should go in into this one, my bad :-(
Anyways it doesn't seem to have caused problems today (puzzled!)

**Comment by ticoann** [comment]
It only cause the problem if it fails to get the data from cmsweb. In that case, it will use the default value. Anyway, I will wait for the test to finish. One unittest was giving the error, then create a new tag. Or move the patch2 tag including that patch.

**Pull request merged**
