### PR TITLE
add gfal2 support.

### LINKED ISSUE #4880: Need new GFAL2 Stageout Plugin
The lcg-utils (based on GFAL) are being phased out in 2014 and are replaced by utilities based on GFAL2. The names of the tools as well as the APIs will change. Therefore we need to offer a successor of the srmv2-lcg stageout plugin.

Find some details about the WLCG plans in a presentation given during the recent GDB meeting:
http://indico.cern.ch/getFile.py/access?contribId=13&sessionId=2&resId=1&materialId=slides&confId=251192

Christoph ("CW")

### PR DESCRIPTION
**Pull request by juztas**
Fixes #4880, Thanks Justas

### CODE REVIEW

**Comment by amaltaro** [comment]
Looks interesting (though I did not review it) :-)
Justas, how about you setup an agent and get in touch to 1 or 2 sites to test this new storage plugin?

**Comment by juztas** [comment]
I tested this locally (by calling each function and checking output). This is also used in CRAB3, now we need to find volunteer sites :)

**Comment by tsarangi** [comment]
@juztas what would you like to test exactly ! You can T2_US_Wisconsin. Let me know if you need any help.

**Comment by juztas** [comment]
a) from site side we need gfal2 on all WN (see https://dmc.web.cern.ch/projects/gfal2-utils) 
b) Change siteconf in git https://git.cern.ch/web/siteconf.git/blob/HEAD:/T2_US_Wisconsin/JobConfig/site-local-config.xml#l13 (Which for me seems risky from site perspective, because this is not in production and all transfers will be using fallback method and AFAIK it is not possible to have multiple fallbacks in site-local-config.xml)
```
<local-stage-out>
  <command value="gfal2"/>
     <catalog url="trivialcatalog_file:/cvmfs/cms.hep.wisc.edu/osg/app/cmssoft/cms/SITECONF/local/PhEDEx/storage.xml?protocol=srmv2"/>
     <se-name value="cmssrm.hep.wisc.edu"/>
     <phedex-node value="T2_US_Wisconsin"/>
</local-stage-out>
```

**Comment by ticoann** [comment]
FYI, currently plugins under is not used (Andrew Melo started to convert all the stage in/out code to convert python call instead of running the shell command directly.
src/python/WMCore/Storage/Plugins/ 
We should do that sometime but Andrew is busy. :smile:

**Comment by tsarangi** [comment]
Good luck with this. You need a T2 simulator ! As you've pointed out, site-local-config.xml shouldn't be changed for testing while the site is in production... 

Can you override the se-name in the site-local-config.xml for your test ? and why the transfers will be using fallaback to begin with ? 

If you can override se name, you still need to wait a couple of more days to test on our site. I am in the process of upgrading gfal and other packages on our WNs...

**Comment by PerilousApricot** [comment]
@ticoann - it falls back to wrapping the "old style" plugins if the "new
style" plugin doesn't exist, if that helps :)

**Comment by PerilousApricot** [comment]
You can set an environment variable and a different site-local-config will
be loaded...

**Comment by juztas** [comment]
as @PerilousApricot wrote, seems it is enough to have gfal2. this is parameter which can be overwritten: `WMAGENT_SITE_CONFIG_OVERRIDE` so it can be tested on any site who has gfal2 :)

**Pull request merged**
