### PR TITLE
do not bulk submit jobs with different numberofcore to HTCondor

### PR DESCRIPTION
**Pull request by hufnagel**
HTCondor does not support bulk submission of jobs with different cpu requests. Multicore repacking is the first use case triggering this, put in a protection.

### CODE REVIEW

**Comment by amaltaro** [comment]
That's bad! Perhaps @bbockelm could comment whether it would be possible to get it fixed in HTCondor instead(?) Thus we can avoid over-complicating job submission...

**Comment by hufnagel** [comment]
As far as complicating job submission goes, I think this is peanuts. Instead of sorting jobs by sandbox (which is basically workflow/task), we sort by sandbox and numberOfCores. In practical terms this currently only affects multicore repacking, no other workflow has a variable numberOfCores within the same workflow/task.

**Comment by amaltaro** [comment]
There are taskChain workflows with mixed numberOfCores, though we're still not using PyCondor plugin in production.
Anyways, as you said, it's not a big deal since it's only a different sorting and you made the job already :).

**Comment by hufnagel** [comment]
TaskChain workflows with different numberOfCores should be supported already as the sandbox should be different from task to task. I *think*...

**Comment by ticoann** [comment]
@hufnagel, Dirk is this tested? Can I merge this?

**Comment by hufnagel** [comment]
We've been using this in the Tier0 for while now...

**Pull request merged**
