### PR TITLE
Replace xquery with query, due to deprecation of the former since HTCondor 10.7.0

### LINKED ISSUE #12027: Schedd.xquery() has been deprecated in HTCondor 10.7.0
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Yes, this method has been deprecated in HTCondor 10.7.0:
```
/usr/lib64/python3.9/site-packages/htcondor/_deprecation.py:41: FutureWarning: Schedd.xquery() was deprecated in version 10.7.0 and will be removed in a future release.
  warnings.warn(message, FutureWarning)
```

so we better migrate (back?) to Schedd.query(), before we have to patch things out.

**Describe the solution you'd like**
There are a few places in WMAgent codebase that we rely on the `Schedd.xquery()` method. We need to adopt `Schedd.query()`, which is supposed to be exactly the same as the former, but instead of returning a generator, it will expand everything in memory.

**Describe alternatives you've considered**
We are already in a dangerous situation, given that we are now running HTCondor python bindings 10.9.0. So it has to be done.

**Additional context**
Documentation: https://htcondor.readthedocs.io/en/latest/apis/python-bindings/api/htcondor.html#interacting-with-schedulers
IF needed, please talk to the CRAB folks, has they have already performed this migration.

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #12027

#### Status
READY

#### Description
Replaces xquery with query. Arguments do not change.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
HTcondor python bindings

### CODE REVIEW

**Comment by khurtado** [comment]
test this please

**Comment by khurtado** [comment]
Tested with 

https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_TC_EL8_khurtado_tc_el8_v2_241024_214833_5767

This is still in running-closed, but not for condor reasons. I did not see any errors with condor submission.

drainAgent is the only script I have not tried, but since the `xquery` and `query` functions get the same arguments and the difference is the output (iterator vs list), I do not expect any issues.

**Comment by khurtado** [comment]
test this please

**Comment by khurtado** [comment]
test this please

**Review by amaltaro — APPROVED** [review]
It looks good to me. Thanks Kenyi!

**Pull request merged**
