### PR TITLE
fix unicode is passed on location

### LINKED ISSUE #6391: ACDC workflows failing to be acquired in GQ
Testing agent 1.0.11.pre8 in testbed, all the ACDC workflows I assigned yesterday went directly to failed in GQ, this is the log for one of them (*). It seems the faulty code is this one:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/SiteDB/SiteDB.py#L308

which is called in ResubmitBlock. In principle that extend is getting a string, and then each char is splitted.

I'll fix it on Monday.

(*)
2015-11-12 18:05:09,910 INFO     WorkQueueReqMgrInterface: Processing request amaltaro_ACDC_StepChain_LumiMask_Agent1011_Validation_v2_151112_175531_917 at https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/amaltaro_ACDC_StepChain_LumiMask_Agent1011_Validation_v2_151112_175531_917/spec
2015-11-12 18:05:09,911 INFO     WorkQueue: queueWork() begin queueing "https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/amaltaro_ACDC_StepChain_LumiMask_Agent1011_Validation_v2_151112_175531_917/spec"
2015-11-12 18:05:10,593 INFO     WorkQueue: Splitting /amaltaro_ACDC_StepChain_LumiMask_Agent1011_Validation_v2_151112_175531_917/DIGI with policy ResubmitBlock params = {'ResubmitBlock': {'args': {}, 'name': 'ResubmitBlock'}, 'MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Dataset'}}
2015-11-12 18:05:11,324 WARNING  SiteDB: No PSNs for PNN: T
2015-11-12 18:05:11,325 WARNING  SiteDB: No PSNs for PNN: 1
2015-11-12 18:05:11,326 WARNING  SiteDB: No PSNs for PNN: _
2015-11-12 18:05:11,327 WARNING  SiteDB: No PSNs for PNN: I
2015-11-12 18:05:11,328 WARNING  SiteDB: No PSNs for PNN: T
2015-11-12 18:05:11,329 WARNING  SiteDB: No PSNs for PNN: _
2015-11-12 18:05:11,329 WARNING  SiteDB: No PSNs for PNN: C
2015-11-12 18:05:11,330 WARNING  SiteDB: No PSNs for PNN: N
2015-11-12 18:05:11,331 WARNING  SiteDB: No PSNs for PNN: A
2015-11-12 18:05:11,332 WARNING  SiteDB: No PSNs for PNN: F
2015-11-12 18:05:11,333 WARNING  SiteDB: No PSNs for PNN: _
2015-11-12 18:05:11,333 WARNING  SiteDB: No PSNs for PNN: D
2015-11-12 18:05:11,334 WARNING  SiteDB: No PSNs for PNN: i
2015-11-12 18:05:11,335 WARNING  SiteDB: No PSNs for PNN: s
2015-11-12 18:05:11,336 WARNING  SiteDB: No PSNs for PNN: k

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6391

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan, please review.

**Comment by amaltaro** [comment]
thanks Seangchan! that should fix the problem. Anyways, it's worth a double check in the next testbed

**Comment by amaltaro** [comment]
Seangchan, I did some interactive tests and the real fix is in L322, we have to replace "extend" by "append" there since se is a string (PNN).
The reason it works for for normal SEs is that it calls seToPNNs which returns a list of PNNs.

Bottom line, we cannot migrate to the new WMAgent because Resubmission will not work, since docs location will have a PNN instead of a SE... :-(

**Comment by ticoann** [comment]
Sorry, Alan. Yes you are right. We have to wait until cmsweb is updated to updated agent.
I guess there are 3 options.
1. wait until cmsweb is updated to update agent
2. add critical patch for cmsweb. and update the agent now.
3. add temporary patch to update se names in dbs instread of PNN and remove that when cmsweb is updated.

I would prefer 1. if we can wait. Otherwise, we have to take either options.

**Comment by amaltaro** [comment]
Good summary :)
It's not a big deal to wait for the next cmsweb upgrade, however, it would be nice if we could patch cmsweb production this week (in the end that would be only workqueue). I'll try to get a hold off Diego after the meeting.

**Comment by ticoann** [comment]
Thanks Alan, be safe. May the force be with you. :smile:

**Comment by amaltaro** [comment]
LoL. We are good, just sent an email to the HTTP group (you in cc) and they will push that patch to testbed today.

**Pull request merged**
