### PR TITLE
RucioInjector has to close only those blocks injected into Rucio

### LINKED ISSUE #9647: RucioInjector trying to close blocks injected into PhEDEx
**Impact of the bug**
WMAgent

**Describe the bug**
Sigh, from my testbed agent, it looks like I missed the datatier check on the `closeBlocks()` method. Which means, RucioInjector might try to close blocks that have actually being injected into PhEDEx, see:
```
2020-04-15 01:42:04,886:140658649351936:ERROR:RucioInjectorPoller:Failed to close block: /RelValQCD_FlatPt_15_3000HS_13/CMSSW_10_6_1_patch1-SC_ReDigi_Harvest_Agent133_Val_Alanv11-v11/GEN-SIM#af031cd3-55d5-44be-aedc-743feca2704d. Will retry again later.
```

It's not a terrible thing, because eventually PhEDExInjector will close those blocks and they won't be retried by RucioInjector. Yet, unneeded data service calls and other issues.

**How to reproduce it**
standard agent deployment with RucioInjector enabled

**Expected behavior**
The component should apply the same rules as specified by its configuration parameter:
```
config.RucioInjector.listTiersToInject = []
```
and only try to close blocks for data tiers that are listed in that parameter.

**Additional context and error message**
none

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9647 

#### Status
not-tested

#### Description
Rookie mistake! The same check we have for injecting data into Rucio, we need it to close blocks as well. So, verify that the data tier is allowed before trying to close blocks from the RucioInjector component. 
If it's not allowed, then we can assume the block has been inserted into PhEDEx instead.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
Sigh... it helps if I enable the component when running tests over the weekend....

**Review by todor-ivanov — APPROVED** [review]
Looks good to me

**Comment by amaltaro** [comment]
This fix is actually not okay. Reason is that there is no distinction between tiers to inject vs tiers to create rules, in `_isContainerTierAllowed`. I will have to separate those two, because there can be actually 4 combinations between them, not only 2...

**Comment by amaltaro** [comment]
Merging it to make a new release

**Pull request merged**
