### PR TITLE
Limit the work done by the archiver.

### PR DESCRIPTION
**Pull request by bbockelm**
Duplicate #6450 
In corner cases (particularly, large-scale kills), the JobArchiver
will try to pull all possible jobs - possibly more than it can
handle.

This limits the JobArchiver to 10k jobs per type (successful, killed,
exhausted).

### CODE REVIEW

**Comment by ticoann** [comment]
Thank you very much Brian, I guess you already applied this in cmssrv218, right?

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
I've made the same patch a few days ago, just a slightly different approach: #6450 

To be honest, mine sounds cleaner, but I'm not fighting for it :-) Shall I close mine now?

**Comment by bbockelm** [comment]
#6450 looks fine to me - I just needed something that would cause `cmssrv218` to start making progress.

This patch additionally causes the daemon to no longer wait if they hit the limits.  However, looking at logs, there's not much benefit: 10k jobs take about 3 hours to clear, so the 5 minutes this patch saves is fairly irrelevant.

**Comment by ticoann** [comment]
Thanks Alan, it missed your earlier patch. I am closing this one, then

**Pull request closed without merging**
