### PR TITLE
Make jobs auto-naming

### PR DESCRIPTION
**Pull request by ericvaandering**
Another stand-alone bit of what I need

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
Although we always the pass the job name but this would be safer protection. I will merge once the unittest finished.

**Comment by ericvaandering** [comment]
New code I'm working decides not to name the jobs. :-)

**Comment by amaltaro** [comment]
Sorry for the stupid question :), but what this job naming means? Is it simply the sequential job id assigned to a job (an integer number)? Or a real uid?
What's the impact of having this auto-naming?

**Comment by ericvaandering** [comment]
A lot of times we do this:
  self.newJob(name = self.getJobName())
other times we use makeUUID as that parameter. 

I decided with the former it was best just to make that the default.

**Comment by ticoann** [comment]
This is real uuid  for job. I am not completely sure why we even give the option to overwrite instead of using auto generated job name. Most of the cases does that anyway, except T0.

**Comment by amaltaro** [comment]
Yep, it should have been auto-generated since day 0 then, it makes a lot of sense. Thanks

**Comment by ericvaandering** [comment]
@ticoann please merge

**Pull request merged**
