### PR TITLE
Added prom_metrics REST API for prometheus-like metrics

### LINKED ISSUE #9939: Provide proper metrics for web based services
**Impact of the new feature**
Based on recent incident [INC2542764](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2542764) with low service performance of Python based services on k8s it would be extremely helpful to provide proper set of metrics from service stack. Since all cmsweb Python based services (DBS, ReqMgr2, CRAB etc.) are based on WMCore codebase it is natural to implement service metrics in WMCore rather in upstream services. This will allow proper monitoring of web services.

**Describe the solution you'd like**
Extend [ProcessStats.py](https://github.com/dmwm/WMCore/blob/master/src/python/Utils/ProcessStats.py) metrics to include the following
- number of requests
- status code stats
- response time of request
- number of connections
- number of open file descriptors
- if DB is in use DB related stats

**Is your feature request related to a problem? Please describe.**
Please see this incident discusssions [INC2542764](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2542764)

**Describe alternatives you've considered**
None, currently we run our services without proper knowledge how they behave, what is their throughput and how the perform under production load

**Additional context**
Once metrics are added to [ProcessStats.py](https://github.com/dmwm/WMCore/blob/master/src/python/Utils/ProcessStats.py) we need to modify WMCore WebTools and REST interface to add `/metrics` or `/status` end-points and enable this by default that it would not be required in upstream code to change anything in order to have them. Once they are available we can setup proper exporter (code should be developed in CMS Monitoring group) and integrate it into Prometheus metrics for each individual service.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9939
Superseeds https://github.com/dmwm/WMCore/pull/9940

#### Status
In development

#### Description
This PR provides two commits:
 * 1st: with an utilitarian module to convert CherryPy stats to an structure like those provided by Prometheus (flat structure)
 * 2nd: a new REST API `prom_metrics` created under WMCore/REST, which should provide the same output as stats, but in a different format.

Even though the complexity of the `flattenStats` function is O(n^4)!!, the request takes only 1ms more to get served. So I think it's still okay to keep this very complex code around.

NOTE-1: the WebTools package hasn't been touched because I'm not sure where the change has to go and how I could test it.
NOTE-2: need to implement the same logic for MicroServices (probably in a different PR).
NOTE-3: if the code is Okay, a proper unit test needs to be implemented to catch releases incompatibilities.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
@vkuznet  Valentin, I think this PR addresses everything that you needed in your PR #9940. Could you please confirm?

I noticed one weird output on the prometheus-like metrics, e.g.:
```
# HELP reqmgr2_cherrypy_server_worker_threads
# TYPE reqmgr2_cherrypy_server_worker_threads histogram
reqmgr2_cherrypy_server_worker_threads{thread_name="cp_server_thread_30",read_throughput="0.0",work_time="0",write_throughput="0.0",bytes_written="0",bytes_read="0",requests="0"} 1
```
that number `1` at the very end. I fail to see where that comes from. Could you please check the code and point where the problem is?

It would be great if you could check the exact output of those APIs under:
https://alancc7-cloud1.cern.ch/reqmgr2/data/stats
and
https://alancc7-cloud1.cern.ch/reqmgr2/data/prom_metrics

I believe you already have access to my VM. Thanks

**Comment by vkuznet** [comment]
@amaltaro , I don't understand why did you made a new PR? Anyway, few things:
- please do not change name of exposed endpoint. I used `/metrics` endpoint name because it is default for all exporters used by prometheus, while your invention to `prom_metrics` break the rule and will force to use special configuration parameter which I rather prefer to avoid
- you skipped unit test I provided, see https://github.com/dmwm/WMCore/blob/29e5086bd4251e44b85842e265a855a7688afc45/test/python/Utils_t/CPMetrics_t.py
- I don't understand why did you changed input parameters of metrics API either, i.e. you pass cherrypy dict to metrics API. Doing so you intentionally ask Python to allocate additional memory for it since it passed it by value (extra copy).
Please fix all of the above.

Meanwhile, your question about histogram syntax. It requires two parameters the name (with attributes) and a value. Value 1 correspond that it exists. There is nothing wrong here.

Regarding how to test these things. I suggest that you follow this recipt:
- download static executable of prometheus from https://prometheus.io/download/
- create the following config file `prometheus.yml` somewhere. You may adjust `localhost:8080` to whatever your cherrypy server is using (do not change `localhost:9090` which is default prometheus port):
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'cherrypy'
    static_configs:
    - targets: ['localhost:8080']
```
- start prometheus as following
```
./prometheus --config.file=prometheus.yml
```
- open whatever host you use on port 9090 and check the prometheus web UI which will contain your metrics. If you're busy, lazy, or unable to do that I can login to your VM and set it up. So far I don't have access to your VM `alancc7-cloud1` and if you need my help over there please provide me the access.

**Comment by amaltaro** [comment]
So, I made a new PR because there are a few things which I wanted to change in yours, and I figured it would be more efficient if I had done those myself, such as:
* Test code is not supposed to go into the source code, as present in your PR;
* I understood you were proposing to have a CheeryPy stats parser, not invoker + parser (see next comment);
* having the cherrypy stats call in the Utilitarian function:
https://github.com/dmwm/WMCore/pull/9940/files#diff-7b548d90012d34adcc512c981750b322R201
looks pretty bad to me. If there will be a REST endpoint serving such requests - through CherryPy engine - we should simply use that data from there and use the util function simply to 
* data/memory allocation is in the scale of a few Kb, I don't really think it's a concern. I hope we won't have multiple clients hammering this API, so more reason not to be concerned;

About the endpoint, I did not know prometheus monitoring was hard-wired to `metrics`, I can of course change it back to metrics.

This PR is not final (proper unit tests need to be created to validate the cherrypy stats structure, and the parser). I just wanted to get back to you to check whether this is what you were trying to get from WMCore.

You are right! I can't allocate more time on setting up this test environment and getting it tested through prometheus. It might be easier if you take care of that yourself on your PR (please take the changes I made here). If you do so, let me know and I can close this PR. Otherwise I can try to get back to it in the next week or two.

**Comment by vkuznet** [comment]
@amaltaro , I know you're busy and it's fine if I'll do it. As I said I need access to your VM, then I can setup things properly for prometheus over there. Feel free to close this PR and I'll incorporate whatever you'll tell me:
- ok, I'll pas around data from cherrypy
- I'm not sure I understood your concern about test, I put it into `test/python/Utils_t/CPMetrics_t.py` in my PR, please clarify this
If anything else needs to be done, please put it in my PR as comments/suggestions and I can proced.

**Comment by vkuznet** [comment]
@amaltaro , Alan I put your changes back to #9940 , please review over there.

**Comment by amaltaro** [comment]
@vkuznet about access to my VM, please check slack.

**Review by vkuznet — APPROVED** [review]
Found this one which was still pending under my review. All changes are fine.

**Comment by amaltaro** [comment]
Changes have been incorporated into the initial PR, so I am closing this one out.

**Pull request closed without merging**
