### PR TITLE
Add override to all tasks logArch step

### LINKED ISSUE #8595: Override needs to be applied to all steps of all tasks
I've just noticed the Override settings don't get applied to all steps. Can be reproduced with this template:
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/ReDigi_3steps.json

and this workflow in testbed
amaltaro_ReDigi_3steps_HG1805_Validation_180426_114348_7098

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8595

Go through every single task and set the override parameters to LogArchive steps (logArch1).

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan, patch looks good to me. Can I merge?

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
Sorry Seangchan, I still have to test it (and then we need a new testbed release :( )

**Comment by amaltaro** [comment]
And my test didn't run over the night because ITB is broken...

**Comment by amaltaro** [comment]
It works like a charm, I see no sign of
https://eoscmshttp.cern.ch/eos/cms/store/logs/prod/recent/amaltaro_ReDigi_3steps_May2018_Validation_180524_123540_9617
logs. 

Merging it and cutting a new tag for testbed.

**Pull request merged**
