### PR TITLE
Add pyjwt dependency

### LINKED ISSUE #10940: Add support for TOKEN based authentication
**Impact of the new feature**
We should provide support for token based authentication with external services. We gradually move all cmsweb service to new authentication mechanism and x509 authentication will be phase out.

**Is your feature request related to a problem? Please describe.**
The x509 authentication will be dropped in a near by future and all clients should adopt token based authentication.

**Describe the solution you'd like**
adjust HTTP request handlers and any other pieces within WMCore services to support TOKEN based authentication;

**Describe alternatives you've considered**
None
**Additional context**

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #10940, #10939

#### Status
ready

#### Description
Add necessary dependency on PyJWT library for token based authentication

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
#10939 

#### External dependencies / deployment changes
<Does it require deployment changes? Does it rely on third-party libraries?>

### CODE REVIEW

**Comment by vkuznet** [comment]
I found that `requirements_py3.txt` is no longer in master branch, but I still had it in my local area. Therefore, I removed original commit to this file to avoid conflict. Now the change only applied to `requirements.txt` file.

**Comment by amaltaro** [comment]
Given that this new library is introduced in the PR https://github.com/dmwm/WMCore/pull/10939 , I would say that that PR should be providing these requirements changes as well. Once we merge that PR, then we get a new dependency in the stack as well (like an atomic operation ;))

**Comment by vkuznet** [comment]
ok, I added pyjwt dependency in this commit https://github.com/dmwm/WMCore/pull/10939/commits/97e85176b8b1cc7ddb3b8e72d86ae2987a1f3463 to https://github.com/dmwm/WMCore/pull/10939

**Comment by amaltaro** [comment]
Given that this change has also been provided here: https://github.com/dmwm/WMCore/pull/10939
with the actual baseline code to using tokens, I think it's better if we close this PR.

@vkuznet please reopen it in case I am missing anything.

**Pull request closed without merging**
