### PR TITLE
Fixes for issue 7681

### LINKED ISSUE #7681: links to ConfigCache
It would be extremely useful to have links to taskname : configcacheid from 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_9_0_0_pre4BeamHalo_13__testUnif_170227_132846_7713

so as to be able to quickly navigate to them, by task

### PR DESCRIPTION
**Pull request by vkuznet**
fixes #7681

### CODE REVIEW

**Comment by ticoann** [comment]
Hi Valentin, it doesn't display. 
https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=request-sryu_MonteCarloFromGEN_reqmgr2_170315_171627_6301

Doesn't anything need to be added in template page?

https://github.com/dmwm/WMCore/blob/master/src/html/ReqMgr/templates/doc.tmpl

I can run the your patch for a while there. Let me know if you have trouble to accessing the vm.

Thanks,

**Comment by vkuznet** [comment]
Well,
that because that document has changed the structure.
The one JR pointed had this:
```
{
...
  "Task1": {
  "ConfigCacheID":"bla"
  }
```

and yours has this:
```
{
"ConfigCacheID": "bla"
}
```

The code I made assumed former and now your doc has different structure. It
also does not have "TaskName" key in a doc while former has.

Please provide consistent structure and DEFINE the schema, otherwise we're not
moving anywhere.

> Doesn't anything need to be added in template page?
> 
> https://github.com/dmwm/WMCore/blob/master/src/html/ReqMgr/templates/doc.tmpl

it does, see changes:
https://github.com/dmwm/WMCore/pull/7729/files

Best,
Valentin.

**Comment by ticoann** [comment]
Hi Valentin, 
Schemas are defined here. https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/WMSpec/StdSpecs

But we don't have the same structure for different type of workflow (Different types has different schema)

As far as ConfigCacheID goes, it can be defined top level, TaskLevel, and StepLevel.

Here are the 3 different types TaskChain, StepChain, and other Specs (You can find this in JSON Format)

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_TaskChain_Prod_reqmgr2_170307_175836_5664

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_StepChain_MC_reqmgr2_170307_181320_6462

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_StepChain_MC_reqmgr2_170307_181320_6462

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_ReDigi_cmsRun2_reqmgr2_170307_181446_485

Looking at the code, I think where to fix it now.  So don't worry about it I will update code.
Thanks for your help.

**Comment by vkuznet** [comment]
ok, I see, you didn't tell me about all possibilities.
Yes, the code to fix will be changes to
def tasks_configs function which construct everything. We just need to adopt it
for different use cases.

But also I think I'll need to tweak JS code to show/hide properly different
divs. Feel free to let me know when you're done and I can help with later.

**Comment by ticoann** [comment]
Thanks Valentin, I am sure I will bug you if I get stuck.

**Comment by ticoann** [comment]
replaced by #7733

**Pull request closed without merging**
