### PR TITLE
Utilitarian script to check outcome of test workflows

### PR DESCRIPTION
**Pull request by amaltaro**
... and after almost 2 years, here is the script to check the outcome of a request :)
The error handling is non-existent for the moment. though.

I'll write some documentation later today/tomorrow.

### CODE REVIEW

**Comment by amaltaro** [comment]
@ticoann moved both validation scripts to `test/data/ReqMgr`.
I also did some changes to the inject script, mostly migration from optparse to argparse, since optparse is retired in python 2.7

Quick tests were Ok, though we have no hurry to merge them.

**Comment by amaltaro** [comment]
@ticoann if you agree with the new location of these scripts, feel free to merge this PR

**Comment by ticoann** [comment]
Hi Alan, could you update print statement. Since Eric change all the current print statement to new style (for Python3). pylint is set to complain about that.

**Comment by amaltaro** [comment]
Aye aye sir, missed that one.

**Comment by ticoann** [comment]
Thanks Alan. :smile:

**Comment by amaltaro** [comment]
Code and wiki were updated:
https://github.com/dmwm/WMCore/wiki/Injecting,-assigning-and-validating-test-requests

Let me know if there is something missing.

**Pull request merged**
