### PR TITLE
Enable CherryPy stats for internal HTTP server - dbs branch

### PR DESCRIPTION
**Pull request by amaltaro**
#### Status
ready

#### Description
DBS branch version of #9237

#### Is it backward compatible (if not, which system it affects?)
YES

@yuyiguo please test it before we merge and cut a new tag.

### CODE REVIEW

**Comment by yuyiguo** [comment]
@amaltaro 
Please commit this to wmcore master branch. I will test it with next DBS build will against 1.2.3.pre*.

**Comment by amaltaro** [comment]
It is already in master, see the PR reference I made above. You can find it starting in the tag `1.2.4.pre1`

**Comment by yuyiguo** [comment]
Then I should build DBS against 1.2.4.pre1 instead of 1.2.3.pre5?

**Comment by amaltaro** [comment]
1.2.4.pre1 is not ideal because it's the first pre-release in the 1.2.4 cycle (and I'd like not to fork a dbs branch out of it). Maybe we should fork from 1.2.3 final release, add this patch on top of that and then you start from there(?)

**Comment by yuyiguo** [comment]
I can do 1.2.3 and add the patch on my VM. How should Lina do it for cmsweb?

**Comment by amaltaro** [comment]
@yuyiguo I have created a new branch for DBS, `1.2.3_dbs`, which is based on what's actually running in CMSWEB production at the moment (thus a stable version).

I also backported this fix and cut a new release for you: `1.2.3.dbs1`
Please use it for the upcoming CMSWEB cycle.

Should we close this PR? Or are you still working on this 1.1.16_dbs branch?

**Comment by amaltaro** [comment]
Given that DBS is now using WMCore 1.2.3, let me close this PR.

**Pull request closed without merging**
