### PR TITLE
Try to improve Alerts thresholds; changed email address

### PR DESCRIPTION
**Pull request by amaltaro**
Changing the email address to myself (I hope I don't regret it...) and also tweaking a few thresholds based on my "feeling" basically.
This won't solve #5857, but should mitigate the amount of messages.

### CODE REVIEW

**Comment by ticoann** [comment]
I think we should disable the email options. You can check first how much junk mail you get first by just updating one agent. If the message is very useful. We will propagate to log db or something.

**Comment by amaltaro** [comment]
Yep! I will use this PR as a reference for my first checks. Don't merge it

**Comment by amaltaro** [comment]
Recording here some of the messages this component sends out:
 1. "Could not find jobCacheDir /data/..." for JobArchiverPoller. It seems it happens when a workflow is aborted, so a flood of messages
 2. "Stopping retries for job 3470" for ErrorHandlerPoller. Again seems to happen when a workflow is aborted -> flood of messages.
 3. Components load in general. "Details: {u'numMeasurements': 5, u'threshold': u'10%', u'average': u'14.76%', u'period': 300}" for CPUPoller
 4. "Job 2973 exhausted due to a bad exit code (set([40, 50660, 99999]))" for ErrorHandlerPoller.

No wonder why it was flooding gmail with these emails, it's impossible to follow up all of them.
I'll try to:
 1. disable only those related to jobs (component alarms may be useful, though thresholds should be increased)
 2. otherwise, completely disable emails (but then there is no more meaning to have these components wasting resources there ...)

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by amaltaro** [comment]
... it reminds me I have to really fix this issue instead of putting it under the carpet :-(

**Comment by ericvaandering** [comment]
I'm using it for testing some new "improvements" to Jenkins.

**Comment by ticoann** [comment]
Alan, I will close this. since we will remove AlertSystem, Is that OK?

**Comment by amaltaro** [comment]
Go for it!

**Pull request closed without merging**
