### PR TITLE
Move filter replication json document under etc/

### LINKED ISSUE #11192: Replace replicator filters by selector objects
**Impact of the new feature**
CouchDB and WMAgent

**Is your feature request related to a problem? Please describe.**
Not a problem, but according to CouchDB experts, the selector objects deliver a better performance than javascript filter functions. Further information about selector objects can be found at:
https://docs.couchdb.org/en/latest/replication/replicator.html#selector-objects

**Describe the solution you'd like**
Evaluate the 3 standard WMAgent replications and see if a filter function can be replaced by an equivalent selector object. 

UPDATE: note that the `ParentQueueUrl` filter can likely be removed, given that the source or target database will always be pointing to one specific environment.

**Describe alternatives you've considered**
Not do anything.

**Additional context**
None

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #11192 

#### Status
ready

#### Description
Given that the json file isn't packaged into the distribution uploaded to PyPi, nor it can be packaged by instrumenting setup_dependencies.py [1] and [2]; I decided to move the json file under the `etc/` directory, which can be looked up through the `WMA_DEPLOY_DIR` environment variable (suffixed with `etc`).

Summary of changes are:
* remove `ParentQueueUrl` from the replication filter function
* reposition `replication_selector.json` under etc/
* fixed AgentStatusPoller unit tests have been instrumented such that it works in all scenarios (CC7 RPM, CC7 Docker, Alma9).
* lastly, added `RucioUtils_t.RucioUtilsTest:testWeightedChoice` to the unstable tests.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
Follow up of https://github.com/dmwm/WMCore/pull/12143

#### External dependencies / deployment changes
[1] ### Using the `statics` option like:
```
        'statics': ['bin+',
                         ...
                         'src/python/WMComponent/AgentStatusWatcher/replication_selector.json'],

### python3 setup.py clean sdist, fails with:
Traceback (most recent call last):
  File "/home/alan/build_pypi/WMCore/setup.py", line 26, in <module>
    data_files = list_static_files(dependencies[package_name])
  File "/home/alan/build_pypi/WMCore/setup_build.py", line 118, in list_static_files
    static_files.extend(data_files_for(static_dir))
  File "/home/alan/build_pypi/WMCore/setup_build.py", line 96, in data_files_for
    for ifile in os.listdir(dir):
NotADirectoryError: [Errno 20] Not a directory: 'src/python/WMComponent/AgentStatusWatcher/replication_selector.json'
```

[2] ### Using the `modules` option like:
```
        'modules': ['WMComponent.AgentStatusWatcher.replication_selector.json'],

### python3 setup.py clean sdist, fails with:
writing manifest file 'src/python/wmagent.egg-info/SOURCES.txt'
error: package directory 'src/python/WMComponent/AgentStatusWatcher/replication_selector' does not exist
```

### CODE REVIEW

**Comment by amaltaro** [comment]
And I can confirm that:
1. the json file is now packaged into the tarball uploaded to PyPi (tested private building in my private VM)
2. and upon patching AgentStatusWatcher - and locating this file under `/usr/local/etc` - it is able to find it and properly create the database replication documents.

**Review by todor-ivanov — APPROVED** [review]
looking good. Thanks @amaltaro

**Review by mapellidario — APPROVED** [review]
thanks alan! looks perfect

**Comment by amaltaro** [comment]
Thanks for the review!
I still have to figure what to do with the failing unit test though:
```
    WMComponent_t.AgentStatusWatcher_t.AgentStatusWatcher_t.AgentStatusWatcher_t:testAgentStatusPoller changed from success to error
```
given that Jenkins is currently running in the RPM base deployment, I will have to adapt it somehow.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Review by mapellidario — APPROVED** [review]
thanks for the changes and upgrading the list of unstable unittests!

**Comment by amaltaro** [comment]
Thanks Dario! Failing unit test seems to actually be unstable:
```
    WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testProductionMultiQueue changed from success to failure
```
let us keep an eye on it in near future PRs and set it appropriately, if needed.

**Pull request merged**
