### PR TITLE
Upgrade version of CherryPy

### LINKED ISSUE #11080: Upgrade python CherryPy and other Python3 packages
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
Given that in the beginning of 2022 we decided to drop support to python2 in WMCore, we should revisit the list of third-party python libraries and update them to the latest stable release. 

**Describe the solution you'd like**
Update python3 specs in the cmsdist repository and in our requirements.txt text file.
CherryPy is a good candidate, but we should also check whether there are other python libraries that we can update to a newer stable release. Note that those libraries no longer need to support python2.

If possible, we should avoid any releases that came out in the past month or two, since those could still be buggy.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #11080 

#### Status
not-tested

#### Description
Upgrade version of CherryPy only.

#### Is it backward compatible (if not, which system it affects?)
MAYBE

#### Related PRs
https://github.com/cms-sw/cmsdist/pull/8032
https://github.com/dmwm/WMCore/pull/11248

#### External dependencies / deployment changes
https://github.com/cms-sw/cmsdist/pull/8032

### CODE REVIEW

**Comment by vkuznet** [comment]
@amaltaro this PR only update CherryPy version. Let's see how jenkins will came out.

**Review by amaltaro — COMMENTED** [review]
Valentin, this actually does not trigger any sensible tests in Jenkins - other than the standard unit tests with the latest `wmagentpy3-dev` RPM available in the cmsdist repository.

The way forward is to provide changes to the cmsdist spec files (after ensuring that versions are compatible), then:
* create a cmsdist PR
* merge
* wait for the RPMs to become available
* (optional) trigger a WMCore docker image creation (based on the RPM above)
* test, either with unit tests or with private service deployment.

**Comment by vkuznet** [comment]
ok, new build came up clean. The RPMs are ready and correspond to docker approach.

**Comment by vkuznet** [comment]
@amaltaro please provide instructions how to trigger WMCore docker build using this set of RPMs, and how to setup private service deployment for testing.

**Comment by amaltaro** [comment]
I fear my answer is not going to be satisfying for you, but we are not yet able to fully test these things in the cmsweb-testXXX clusters (Erik had some good progress on this though). So, the only ways to test it would be:
a) deploy services in cmsweb-testbed
b) deploy services in a private VM (but a couple of microservices are no longer functional since a python3 mongodb update).

To test those changes you provided in the cmsdist repository, you can (ideally, one would build things in a private repository before merging things in comp_gcc630):
* merge the cmsdist PR, once all the required changes are in place
* wait for new RPMs to show up in cmsrep repository (likely something like HG2208d-compX)
* deploy this HG tag above

On what concerns the deployment of this on VMs, we have a single script for this or a sequence of steps, all documented here:
https://github.com/dmwm/WMCore/wiki/WMCore-central-services-deployment

Anyways, it looks like you still have to sort out the cryptography dependency update. Once you converge on that, I can help you out with further tests.

**Comment by vkuznet** [comment]
This PR may be obsolete if we merge https://github.com/cms-sw/cmsdist/pull/8032 which covers the changes here.

**Comment by amaltaro** [comment]
This PR has been superseeded by https://github.com/dmwm/WMCore/pull/11258
Closing this one out.

**Pull request closed without merging**
