### PR TITLE
initial patch for eos stageout (has error do not merge)

### PR DESCRIPTION
**Pull request by ticoann**
Error message

```
MSG: Unable to stage out log archive to EOS: 
StageOutFailure
Message: Failure for fallback stage out:
StageOutError
Message: Command exited non-zero
        ErrorCode : 60311
        ModuleName : WMCore.Storage.StageOutError
        MethodName : __init__
        ErrorType : GeneralStageOutFailure
        ClassInstance : None
        FileName : /pool/condor/dir_1319717/glide_jTKtqa/execute/dir_6580/job/WMCore.zip/WMCore/Storage/StageOutError.py
        ClassName : None
        Command : #!/bin/sh
source /etc/profile.d/grid-env.sh; lcg-cp -b -D srmv2 --vo cms --srm-timeout 2400 --sendreceive-timeout 2400 --connect-timeout 300 --verbose  srm://srm-cms.cern.ch:8443/srm/managerv2?SFN=/castor/cern.ch/cms/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar  srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar

            EXIT_STATUS=$?
            echo "lcg-cp exit status: $EXIT_STATUS"
            if [[ $EXIT_STATUS != 0 ]]; then
               echo "Non-zero lcg-cp Exit status!!!"
               echo "Cleaning up failed file:"
                source /etc/profile.d/grid-env.sh;  lcg-del -b -l -D srmv2 --vo cms srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
               exit 60311
            fi

            FILE_SIZE=`stat -c %s srm://srm-cms.cern.ch:8443/srm/managerv2?SFN=/castor/cern.ch/cms/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar `
echo "Local File Size is: $FILE_SIZE"

        for ((a=1; a <= 10 ; a++))
        do
           LCG_OUTPUT=`lcg-ls -l -b -D srmv2 srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar 2>/dev/null`
           SRM_SIZE=`echo "$LCG_OUTPUT" | awk 'NR==1{print $5}'`
           SRM_CHECKSUM=`echo "$LCG_OUTPUT" | sed -nr 's/^.*\s([a-f0-9]{8})\s*\([aA][dD][lL][eE][rR]32\)\s*$/\1/p'`
           echo "Remote Size is $SRM_SIZE"
           echo "Remote Checksum is $SRM_CHECKSUM"
           if [[ $SRM_SIZE > 0 ]]; then
              if [[ $SRM_SIZE == $FILE_SIZE ]]; then
                 exit 0
              else
                 echo "Error: Size Mismatch between local and SE"
                 echo "Cleaning up failed file:"
                 source /etc/profile.d/grid-env.sh;  lcg-del -b -l -D srmv2 --vo cms srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
                 exit 60311
              fi
           else
              sleep 2
           fi
        done
        echo "Cleaning up failed file:"
        source /etc/profile.d/grid-env.sh;  lcg-del -b -l -D srmv2 --vo cms srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
        exit 60311


        LineNumber :32
        ErrorNr : 0
        ExitCode : 151

Traceback:
  File "/pool/condor/dir_1319717/glide_jTKtqa/execute/dir_6580/job/WMCore.zip/WMCore/Storage/StageOutImpl.py", line 196, in __call__
    self.executeCommand(command)

  File "/pool/condor/dir_1319717/glide_jTKtqa/execute/dir_6580/job/WMCore.zip/WMCore/Storage/StageOutImpl.py", line 65, in executeCommand
    raise StageOutError(msg, Command = command, ExitCode = exitCode)


        TargetPFN : srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
        ErrorCode : 60311
        ModuleName : WMCore.Storage.StageOutError
        MethodName : __init__
        LFN : /store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
        ClassInstance : None
        FileName : /pool/condor/dir_1319717/glide_jTKtqa/execute/dir_6580/job/WMCore.zip/WMCore/Storage/StageOutError.py
        ClassName : None
        Command : srmv2-lcg
        LineNumber : 32
        InputPFN : srm://srm-cms.cern.ch:8443/srm/managerv2?SFN=/castor/cern.ch/cms/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
        ErrorNr : 0
        ErrorType : GeneralStageOutFailure

Traceback:
  File "/pool/condor/dir_1319717/glide_jTKtqa/execute/dir_6580/job/WMCore.zip/WMCore/Storage/StageOutMgr.py", line 260, in fallbackStageOut
    impl(fbParams['command'], localPfn, pfn, fbParams.get("option", None), checksums)

  File "/pool/condor/dir_1319717/glide_jTKtqa/execute/dir_6580/job/WMCore.zip/WMCore/Storage/StageOutImpl.py", line 214, in __call__
    raise ex
```

### CODE REVIEW

**Comment by ticoann** [comment]
@hufnagel, @amaltaro, Dirk, Alan could you review the code what I am doing wrong?
Does following code try to cp the log archive from castor to eos? Shouldn't it supposed to copy log from worker node to eos? I am not sure how this code is generated.

```
lcg-cp -b -D srmv2 --vo cms --srm-timeout 2400 --sendreceive-timeout 2400 --connect-timeout 300 --verbose  srm://srm-cms.cern.ch:8443/srm/managerv2?SFN=/castor/cern.ch/cms/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar  srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/store/logs/prod/2015/09/WMAgent/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435/sryu_MonteCarlo_LHE_mc_lumi_validation_150929_175102_2435-LogCollect-b69cfa5dbd-1-logs.tar
```

**Comment by amaltaro** [comment]
It should be Ok to stage from castor to eos, but it seems the stage out plugins can't handle third part stage out (from a remote to another), since it needs to check checksum and file size.
I'll figure out how the source file is built today and then I get back to you.

**Comment by ticoann** [comment]
Thanks Alan,  I am not sure why it gets input from castor since I didn't change the stage in code.

**Comment by hufnagel** [comment]
Hm, from the code I would think it does two copies from local. I found an unrelated problem

lfnEOSPrefix = overrides.get('lfnPrefix', "srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs")

should be

lfnEOSPrefix = overrides.get('lfnPrefix', "srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms")

as the /store/logs is part of the lfn and already appended. You have it twice right now in your output path. That doesn't explain your error though.

If the stageout call really modifies tarInfo, you could just get rid of that dict and create it directly twice on the stageout call.

Btw, why the extra tr/except block for the eos stageout ? Isn't it easier to just put one line directly after the castor stageout ?

**Comment by hufnagel** [comment]
If you look a few lines later, tarInfo is modified during stageout as the later code extracts information from there. Which makes my suggestion also not workable. You need a tarInfoCastor and a tarInfoEOS and then pick one to give you back the PFN to put into the job report.

**Comment by amaltaro** [comment]
and I was going to say the same thing that Dirk already told you, just noticed tarInfo is changed down stream :-)
I'm running a test with this fix and if things work well, we can merge our code

**Comment by ticoann** [comment]
Thanks Alan, Dirk. I missed that tarInfo code changes. 

> Btw, why the extra tr/except block for the eos stageout ? Isn't it easier to just put one line directly after the castor stageout ?

The logic was if the castor copy is successful consider as job successful regardless of eos copy status.
I am not sure how important and how it is likely fail, but I think it is only used for occasionally and failure rate shouldn't be high. Although, I think we make the eos copy failure information more visible than writing on the log file.

**Comment by amaltaro** [comment]
quick update, my test failed again with the following command (from Pisa WN):
```
lcg-cp -b -D srmv2 --vo cms --srm-timeout 2400 --sendreceive-timeout 2400 --connect-timeout 300 --verbose  file:/home/grid/cmsplt17/home_cream_848122462/CREAM848122462/glide_wrFihU/execute/dir_2253/job/WMTaskSpace/logCollect1/amaltaro_MonteCarlo_Ext_alan_TEST_StageOut_v12_150930_170421_6785-LogCollect-s2wn5-1-logs.tar  srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs/prod/2015/09/WMAgent/amaltaro_MonteCarlo_Ext_alan_TEST_StageOut_v12_150930_170421_6785/amaltaro_MonteCarlo_Ext_alan_TEST_StageOut_v12_150930_170421_6785-LogCollect-s2wn5-1-logs.tar
```

I'll try to get a job on the fly and play with some commands...

**Comment by amaltaro** [comment]
Okay, it seems the reason it's failing is because srm protocol is not able to properly create a directory (which is required before writing files to EOS). This is the error message I got running it interactively:
```
Destination SE type: SRMv2
[SE][Mkdir][SRM_INVALID_PATH] httpg://srm-eoscms.cern.ch:8443/srm/v2/server: Error:/bin/mkdir: cannot create directory `/eos/cms/store/logs/prod/2015/09': No such file or directory
Ref-u cmsprd  /bin/mkdir /eos/cms/store/logs/prod/2015/09
```

I'm changing the protocol (plugin) to be used to 'rfcp-CERN', though I'm not very confident it will work :(

**Comment by hufnagel** [comment]
It won't. And Justas had remote stageout to CERN EOS through the srm plugin working AFAIK.

**Comment by amaltaro** [comment]
Ok, I'll talk to him tomorrow then. Meanwhile I leave this rfcp test running anyways..

**Comment by amaltaro** [comment]
Indeed, also failed. Talked to Justas, but their case uses FTS3. I'll try to get a hold of @nikmagini  today to sort this out

**Comment by juztas** [comment]
We are not using FTS3 if local stageout fails. In that case we use gfal2 if it exists, if not, lcg-cp to stageout directly to CERN EOS.
But as I was mentioning to @amaltaro prod still can`t use gfal2, because of this: https://its.cern.ch/jira/browse/DMC-737

**Comment by nikmagini** [comment]
Hi all,

Alan's certificate is mapped to the "cmsprd" account on EOS - I have now granted write permission to "cmsprd" on the /eos/cms/store/logs tree

Cheers
Nicolo'

**Comment by amaltaro** [comment]
Yeah, that was the only missing piece, thanks Nicolo.
@ticoann here is a working version of your patch https://github.com/amaltaro/WMCore/commit/8cc73029bfe03f5d875c248f9153cc35f376c49c
can you merge it and update this PR please?

Nicolo, one more thing, could you please also map Dave Mason's cert to cmsprd account? If something bad happen to me, he would be the backup man :-)

**Comment by ticoann** [comment]
Thank you very much Alan, You are the Man! Could you make the pull request with your new patch I will close this one?

**Comment by amaltaro** [comment]
Done in #6300 . Thanks a lot Seangchan!

**Comment by nikmagini** [comment]
> Nicolo, one more thing, could you please also map Dave Mason's cert to cmsprd account? If something bad happen to me, he would be the backup man :-)

Hi Alan,

this was already in place, presumably Ivan did it:

bash-4.1$ grep Mason /afs/cern.ch/cms/caf/gridmap/gridmap.txt
"/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=dmason/CN=664436/CN=David Alexander Mason" cmsprd

Cheers
Nicolo'

**Comment by amaltaro** [comment]
Perfect! Thanks Nicolo

**Pull request closed without merging**
