### PR TITLE
Move WMBSHelper_t to the mock emulators.

### PR DESCRIPTION
**Pull request by ericvaandering**
…he emulator switch either

### CODE REVIEW

**Comment by ericvaandering** [comment]
@ticoann please merge this pending Jenkins saying all the WMBS helper tests are OK. Now uses real datasets and blocks.

**Comment by ticoann** [comment]
> WMCore_t.ResourceControl_t.ResourceControl_t.ResourceControlTest:testInsertAllSEs2 changed from success to failure

This doesn't make sense to be failed.

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann please merge. I think a race condition was causing the reported failure earlier.

**Comment by ericvaandering** [comment]
I'll take care of some pylint stuff for completeness.

**Comment by ticoann** [comment]
Thanks, Eric.

**Pull request merged**
