### PR TITLE
Log calls to clearDatabase()

### PR DESCRIPTION
**Pull request by ericvaandering**
Try to figure out what is going on with WQ tests

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, Eric, this is just for the test not to be merged, correct?

**Comment by ericvaandering** [comment]
Correct, not to be merged.

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Pull request closed without merging**
