### PR TITLE
fix 500 errors

### PR DESCRIPTION
**Pull request by ticoann**
fixes 500 errors in reqmgr2 server

### CODE REVIEW

**Comment by ticoann** [comment]
tested in vm, @amaltaro, Alan please review.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Sounds good Seangchan. Did it make the logs free of 500 errors? Or you still see it in a lowest frequency?

**Comment by ticoann** [comment]
On my test, it was 500 free. (Test was made by querying ~200 workflows at the same time from 4 different clients)

**Comment by amaltaro** [comment]
You're da man!

**Pull request merged**
