### PR TITLE
'dict' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
Fixes dictionary iteration methods. **`dict.iteritems()`** is converted to` dict.items()`, **`dict.iterkeys()`** to `dict.keys()`, and **`dict.itervalues()`** to `dict.values()`. Similarly, **`dict.viewitems()`**,**`dict.viewkeys()`** and **`dict.viewvalues()`** are converted respectively to `dict.items()`, `dict.keys()` and `dict.values()`. It also wraps existing usages of `dict.items()`, `dict.keys()`, and `dict.values()` in a call to list.

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
This is a fix we should only partly apply.

dict.items() to list(dict.items()) is fine. But the dict.iteritems() to dict.items() bits (and keys and values) should be left until later and (hopefully) done automatically. 

Otherwise we are just going to make our python2 code worse now.

**Comment by vkuznet** [comment]
@vilnius-dev could you please walk through PR and make fixes suggested by Eric.

**Comment by ericvaandering** [comment]
A graphical tool like SourceTree might help because it lets you reject or revert every individual bit of the patch.

**Comment by mapellidario** [comment]
This is covered by our gradual migration. Moreover, we are following the performance suggestions at https://python-future.org/compatible_idioms.html#dictionaries .

I would suggest closing this PR without merging, since it is superseded by our current efforts.

**Comment by mapellidario** [comment]
Thanks Roman for your work! Closing this

**Pull request closed without merging**
