### PR TITLE
Adding comments for unused classes, updated mox.  

### PR DESCRIPTION
**Pull request by SaltumDis**
StageOutImplV2 is not implemented completely. All sites use Backends directory implementations.

### CODE REVIEW

**Comment by ericvaandering** [comment]
Ok, the nose.failure thing is this: 

```
    from mox3 import mox
ImportError: No module named mox3
```

Which means we would have to add it to our distribution. But considering that the original mox page says not to use it for new development and the Google project links its based on lead nowhere AND that these are tests for code that doesn't get used yet... I think we should just rip out mox entirely (comment it out) and plan on switching to unittest.mock instead when we do pick this up.

**Comment by SaltumDis** [comment]
Ok, gonna update it

**Comment by ericvaandering** [comment]
Thanks. I couldn't really even find documentation on mox at this point, which would make it pretty hard to use.

**Comment by ericvaandering** [comment]
test this please

**Comment by amaltaro** [comment]
Adelina, all, here is the list of stage-out command (you need to map the command to the actual plugin) we have out there for ALL sites:
```
     92 <commandvalue="srmv2-lcg"/>
     38 <commandvalue="srmv2"/>
     14 <commandvalue="cp"/>
     13 <commandvalue="srm"/>
      8 <commandvalue="gfal2"/>
      6 <commandvalue="stageout-xrdcp-fnal"/>
      5 <commandvalue="rfcp-CERN"/>
      5 <commandgvalue="srmv2"/>
      3 <commandvalue="rfcp"/>
      3 <commandgvalue="srmv2-lcg"/>
      1 <ommandgvalue="srmv2-lcg"/>
      1 <commandvalue="xrdcp"/>
      1 <commandvalue="vandy"/>
      1 <commandvalue="rfio"/>
      1 <commandvalue="rfcp-RAL"/>
      1 <commandvalue="rfcp-2"/>
      1 <commandgvalue="srm"/>
      1 <commandgvalue="cp"/>
```

Otherwise, the most _important_ sites comprised by T0, T1s and T2s list is:
```
     56 <commandvalue="srmv2-lcg"/>
     12 <commandvalue="srmv2"/>
      4 <commandvalue="rfcp-CERN"/>
      4 <commandvalue="gfal2"/>
      4 <commandgvalue="srmv2-lcg"/>
      4 <commandgvalue="srmv2"/>
      3 <commandvalue="srm"/>
      2 <commandvalue="stageout-xrdcp-fnal"/>
      2 <commandvalue="rfcp"/>
      2 <commandvalue="cp"/>
      1 <commandvalue="xrdcp"/>
      1 <commandvalue="vandy"/>
      1 <commandvalue="rfcp-RAL"/>
      1 <commandvalue="rfcp-2"/>
      1 <commandgvalue="srm"/>
```

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Instead of marking plugins as not used, why don't we actually remove them then?
BTW, I think this is how these storage implementations are used:
 a) WMAgent uses Impl v1 and plugins under Backends
 b) CRAB uses plugins under Plugins (no idea which Impl version)
 c) SAM tests use plugins under Plugins (idem)

**Comment by ticoann** [comment]
I didn't know CRAB is actually using some plugins. It is more like not completed rather than not used. I think we need to move everything to Plugins not using Backend eventually

**Comment by juztas** [comment]
@amaltaro are you sure about CRAB? afair it uses Impl v1 and plugins under Backends, same as prod. Only SAM tests are using plugins under plugins

**Comment by amaltaro** [comment]
Since we have removed half of these files, and the other half is actually used somewhere in WMCore and CRAB, I'll just close this issue.

**Pull request closed without merging**
