### PR TITLE
Use modern raise() statement, mostly in how it deals with message str…

### PR DESCRIPTION
**Pull request by ericvaandering**
…ings attached to exceptions

### CODE REVIEW

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
First run failed with a C++ exception in WMCore/test/python/WMCore_t/Alerts_t/ZMQ_t/Receiver_t.py Will see if it's repeatable and related. If so, will have to start splitting up the commit.

**Comment by PerilousApricot** [comment]
Hi Eric,

That ZMQ business has been annoying for a while ... https://github.com/dmwm/WMCore/issues/3631

**Comment by ericvaandering** [comment]
Do not merge yet. 

ZMQ thing has gone away, but there is a legitimate problem:

WMCore_t.Agent_t.Configuration_t.ConfigurationTest.testB  does not raise the right exception

**Comment by ericvaandering** [comment]
Closing this one, have another one that is mergable

**Pull request closed without merging**
