### PR TITLE
Fix location flag; Improved PNNxPSN sitedb apis

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes a bug of empty location when useSiteListAsLocation is enabled.
Added a couple siteDB apis.

I changed the return format of PNNtoPSN, it was returning a dict where the key was the PNN you were trying to map. I could not see any reason not to return a simple list with the PSNs, @alexanderrichards let me know if I'm wrong.

@ticoann welcome back from vacation ;-) Do not merge yet please.
My tests are still ongoing, but everything looks good so far. I fixed the emulator as well, hopefully no unittests will scream

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Damnit! I was going to tell you it's ready to merge :-( Let me fix these unittests first and then we merge it tomorrow if everything is green

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
All the tests above are failing with empty input location
```
Invalid WMSpec: 'MultiTaskReReco': Input data has no locations "/Cosmics/ComissioningHI-PromptReco-v1/RECO
Invalid WMSpec: 'ReRecoWorkload': Input data has no locations "/MinimumBias/ComissioningHI-v1/RAW"
Invalid WMSpec: 'testParentProcessing': Input data has no locations "/SingleMu/CMSSW_6_2_0_pre4-PRE_61_V1_RelVal_mu2012A-v1/RECO"
```
because, AFAIR from a previous discussion, the emulator is not thread safe and thus it ends up calling the cmsweb services in jenkins. Since those data are only at *_MSS or *_Export, it cannot find input location sites. Anyways, only one test changed from success to error. All the others are from failure to error.

I'll look for other datasets with valid location, though at some point they may be not accessible as well.
Otherwise I do not have anything else to add to this PR.

**Comment by ticoann** [comment]
Thanks Alan, patch looked good to me I will merge this. As far as unittest goes using Emulator we will fix it separately.

**Pull request merged**
