### PR TITLE
Support SSB site status to be unknown - wmagent branch

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch of #9585

### CODE REVIEW

**Comment by amaltaro** [comment]
@todor-ivanov Todor, we need to push this patch in in all the production agents. Can you please patch the FNAL agents and restart AgentStatusWatcher? I'll take care of the CERN agents.

**Comment by amaltaro** [comment]
All the CERN agents (including a few testbed) have been patched.

**Comment by todor-ivanov** [comment]
@amaltaro Done

**Comment by amaltaro** [comment]
[Fix #9586 - Support SSB site status to be unknown](https://trello.com/c/SQsRpVXv/195-fix-9586-support-ssb-site-status-to-be-unknown)

**Comment by amaltaro** [comment]
Thank you, Todor.

**Pull request merged**
