### PR TITLE
add mock logdb

### PR DESCRIPTION
**Pull request by ticoann**
@ericvaandering, please review.  

Unittest using logdb need to be updated with something like below.

```
from WMQuality.Emulators.EmulatedUnitTestCase import EmulatedUnitTestCase
class ErrorHandlerTest(EmulatedUnitTestCase):
```

### CODE REVIEW

**Comment by ericvaandering** [comment]
This looks like a good start. One piece of advice is the use some prints or what not initially to really make sure that the mock is being called. Getting the mocked code to be called from all uses was my biggest challenge.

**Comment by ticoann** [comment]
@ericvaandering, I added print statement for MockClasses. Also added ApMon mock.
However, it doesn't seem to take Mock class. Could check what I am doing wrong?

**Comment by ticoann** [comment]
Never mind Eric. I made some stupid mistake. I takes Mock classes.

**Comment by ticoann** [comment]
@amaltaro, Alan I think this is ready. I created a few Mock classes to speed up the test and fix some of the exceptions which wasn't affecting result.
What takes long now is profiling test. (Which is expected but Jenkins won't run it)

```
@attr('integration')
    def testF_PollerProfileTest(self)
```
If you are OK I will merge it when Jenkins comes back.

**Comment by amaltaro** [comment]
Sure, go ahead Seangchan.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
