### PR TITLE
Update buildreleases script to handle different branches

### PR DESCRIPTION
**Pull request by amaltaro**
I also removed all the CVS handling, since it's dead anyways for quite a bit.
The building of RPM was also cleared.

@ticoann please review. I already tested with the tag for 1.0.14_crab branch :-D
I still have to update this documentation:
https://github.com/dmwm/WMCore/wiki/TaggingAndReleasing

### CODE REVIEW

**Comment by ticoann** [comment]
Thanks Alan, Does this also update the tagging differences on branch as well?

**Comment by amaltaro** [comment]
It seems to update the differences based on the branch base, like:
https://github.com/dmwm/WMCore/commit/ba0a5f6ffc59520a1056b9a1dc68c85d6de09306

Is it what you mean?

**Comment by ticoann** [comment]
Yes, Alan. Good work. :smile:

**Comment by amaltaro** [comment]
:-) I also updated the documentation in:
https://github.com/dmwm/WMCore/wiki/TaggingAndReleasing

**Comment by ticoann** [comment]
Thanks Alan, stop working. :smile:

**Pull request merged**
