### PR TITLE
Improve request creation/assignment validation error messages

### LINKED ISSUE #7829: Make validation message more explicit
at least report back what is the valid condition is.

i.e. "the campaign is too long : 60 allowed" or for campaign, '^[a-zA-Z0-9-_]{1,60}$'

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7829

A few examples of this code and the result from the inspect.getsource call
```
Message: Argument 'TimePerEvent' with value 0.0, doesn't pass the validation function.
Validate function definition is:
                     "TimePerEvent": {"default": 12.0, "type": float, "validate": lambda x: x &gt; 0},
                     


Message: Argument 'CMSSWVersion' with value 'CMSSW_7_1_25_patch22', doesn't pass the validation function.
Validate function definition is:
                     "CMSSWVersion": {"validate": lambda x: x in releases(),
                                      "optional": False, "attr": "frameworkVersion"},

Message: Argument 'RequestPriority' with value -180000, doesn't pass the validation function.
Validate function definition is:
                                         "validate": lambda x: (x &gt;= 0 and x &lt; 1e6)},
```

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Hmm, I wonder why my own pylint doesn't report this error:
` E0602, line 87 in _validateArgumentDict: Undefined variable 'value' `
...

**Comment by amaltaro** [comment]
Unless we write one specific message per argument/check, I don't think we can improve it much more.
@ticoann please review and merge

**Review by ticoann — APPROVED** [review]

**Pull request merged**
