### PR TITLE
Change cmsRun executable with cmsRunPython3

### LINKED ISSUE #9598: Test Python3 workflows
**Impact of the new feature**
WMAgent, ReqMgr2, CouchDB

**Is your feature request related to a problem? Please describe.**
This issue is created as a follow up from the conversation at the Mattermost channel, regarding the steps we should take in WMCore in order to check the submission of Python3 workflows. Here is the summary:

We are about to use CMSSW_11_1_0_pre5 

First test - to make the necessary changes to the RunTime code such that we execute cmsRunPython3 instead of cmsRun.

Second test - depending on a release to fully support python 3 - would be to start with python3 from the very beginning, thus creating the job configuration and uploading it to ReqMgr2/CouchDB

**Describe the solution you'd like**
About the First test:

Two options can be discussed here. 

1. Just for the sake of the current test we can change the executable. Create a patch from the PR and apply the patch in one of the agents, then submit a Workflow and debug. We should never merge the PR.

2. To implement a proper and configurable switch between the two executables
 
About the second test:

It should be mostly operational work (generating the proper .pset configuration and uploading it to CouchDB), but no code changes are expected.

**Describe alternatives you've considered**
N/A

**Additional context**
There is a related PR [1] which will never be merged. That's why I am putting the link here.

[1]

https://github.com/dmwm/WMCore/pull/9599

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #9598

#### Status
In development && DO NOT MERGE

#### Description
Changes needed for Python3 tests. For more details see the: issue https://github.com/dmwm/WMCore/issues/9598

#### Is it backward compatible (if not, which system it affects?)
NO

### CODE REVIEW

**Comment by todor-ivanov** [comment]
@amaltaro, I suspect it is not the only place where I should change the cms Executable. So far I submitted one workflow  [1] with a patched agent (vocms0260). The original WF from which the template was generated is [2].  The CMSSW version is CMSSW_11_1_0_pre5.

I was expecting to see 'cmsRunPython3' as a parameter to CMSSW.py, instead in the 'wmagentJob.log', I see 'cmsRun' [3]. I strongly hope, I simply made a mistake and submitted before cleaning the CMSSW.pyc file or something like that..., because the trail leads to the template where the executable should be changed, so after that it could enter the Executor here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L124

[3]
2020-04-03 21:28:22,994:INFO:CMSSW:Executing CMSSW. args: ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', u'slc7_amd64_gcc820', 'scramv1', 'CMSSW', 'CMSSW_11_1_0_pre5', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']


[1]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_TaskChain_CMSSW_11_1_0_pre5_SingleMuPt10Extended_python3Tests_v4_200403_210211_2278
 
[2]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=muahmad_RVCMSSW_11_1_0_pre5SingleMuPt10Extended__2026D48noPU_200331_100634_8310

**Comment by amaltaro** [comment]
Todor, I think that value gets overwritten by what is provided in the workflow spec, which you can see from your link [1], when you click in the `config` button of the ReqMgr2 GUI:
```
tivanov_TaskChain_CMSSW_11_1_0_pre5_SingleMuPt10Extended_python3Tests_v4_200403_210211_2278.tasks.GenSimFull.steps.cmsRun1.application.command.executable = 'cmsRun'
```

You might have to hard code the cmsRunPython3 command in this line instead:
https://github.com/dmwm/WMCore/blob/96a7582e8b6f96879e2c8bb97d15e4698cb3e301/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L124

**Comment by todor-ivanov** [comment]
@amaltaro. Ok I will hard code it and re-inject. But I will do it manually in the agent only.

**Comment by todor-ivanov** [comment]
@amaltaro , it does the job. Here is the  Workflow [1], and here is what I see in the logs [2]. So far all the jobs are completing without any errors.

[1]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_TaskChain_CMSSW_11_1_0_pre5_SingleMuPt10Extended_python3Tests_v5_200404_180553_2107

[2]
wmagentJob.job.log:

```
2020-04-04 18:28:25,536:INFO:CMSSW:Executing CMSSW. args: ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', u'slc7_amd64_gcc820', 'scramv1', 'CMSSW', 'CMSSW_11_1_0_pre5', 'FrameworkJobReport.xml', 'cmsRunPython3', 'PSet.py', '', '', '']

```

cmsRun1-stdout.log:

```
Executing CMSSW
cmsRunPython3  -j FrameworkJobReport.xml PSet.py
```

**Comment by amaltaro** [comment]
That's great news, Todor.

From the logs, I'm concerned about this:
```
2020-04-04 18:28:22,766:INFO:Scram:    Invoking command: /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre5/external/slc7_amd64_gcc820/bin/python2.7 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 
```
that will likely fail when execute with python3. This is where we tweak the standard job configuration (PSet).

**Comment by todor-ivanov** [comment]
@amaltaro You mean when the Pset is generated with python3, while we try to unpickle it with python2, right? And this should be the second test we are talking about.

**Comment by makortel** [comment]
I may be shooting completely in the dark, but
* Would it be sufficient to make `WMCore.WMRuntime.ScriptInvoke` to work with both python2 and python3?
* Who sets the path to `python2.7`? Is it decided by the WM, does it come from scram, or something else?

**Comment by hufnagel** [comment]
Python binary replacement happens here

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Tools/Scram.py#L346

You'll need to add a condition for python3 to make that work with future CMSSW versions.

And yes, all scripts executed with his code need to be able to run in all python versions used by CMSSW. All of this code is super hacky though, so no guarantees this will work out of the box.

**Comment by amaltaro** [comment]
Now that we started having python3 workflows being tested in our dev setup, this seems no longer relevant. @todor-ivanov shall we close it?

**Comment by todor-ivanov** [comment]
Fully agree @amaltaro I would have closed it myself months ago. I just did not want to do it before I hear from you, but I actually never brought up the topic due to the other focuses!

**Pull request closed without merging**
