### PR TITLE
Adopt wmcore_pileup Rucio account in workqueue

### LINKED ISSUE #11669: Adopt a different Rucio account for pileup data in global and local workqueue (wmcore_pileup)
**Impact of the new feature**
Global and Local Workqueue

**Is your feature request related to a problem? Please describe.**
 CompOps/DM decided to change the Rucio account used for WM secondary data placement, such that it is easier to see what the secondary data contribution is to input data required by central production.

After the change is made in MSPileup, such that new rules are created under the new Rucio account `wmcore_pileup`, tracked in: https://github.com/dmwm/WMCore/issues/11668
we need to also change the Rucio account used by global and local workqueue for secondary data location. Hopefully there is a clear separation of the Rucio account used for primary/parent vs secondary data in workqueue.

**Describe the solution you'd like**
The expected solution is that secondary data needs to be tracked (location) with a Rucio account that is different than the one used for primary and parent data.
Whenever secondary data location is performed by workqueue, either in global and local level, a rucio account `wmcore_pileup` has to be used.

When the agent builds the secondary data availability, it uses this PileupFetcher module:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py#L38

but under the WorkQueue package, we also define a default Rucio account that needs to be investigated:
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/WorkQueue

**Describe alternatives you've considered**
Maybe an actual requirement, but we might consider creating a new argument for the workqueue service:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/workqueue/config.py

such that there is a clear distinction between pileup vs other data location.

**Additional context**
Note that Global WorkQueue will need to be upgraded (or have a new configuration).
WMAgents will also need to be pached and WorkQueueManager restarted.

Lastly, note that this can only be deployed once https://github.com/dmwm/WMCore/issues/11668 has been addressed and deployed in production.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #11669 

#### Status
Not tested

#### Description
This pull request changes the Rucio account used for secondary input data location, using `wmcore_pileup` instead of `wmcore_transferor` account.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
Depends on the following services_config (for prod, preprod and test branches):
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/226
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/227
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/228

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Review by todor-ivanov — APPROVED** [review]
thanks @amaltaro  it looks good

**Review by vkuznet — APPROVED** [review]

**Comment by amaltaro** [comment]
This has been tested at the local workqueue level - WMAgent, so it **should** work for global workqueue. We shall see later today in testbed. This will also have to backported to `2.2.2_cmsweb` branch.

**Comment by amaltaro** [comment]
I have updated the initial description, because I forgot that services_config changes were required for the global workqueue as well.

**Pull request merged**
