### PR TITLE
Fix a shell syntax error in the xrdcp/xrdfs command

### PR DESCRIPTION
**Pull request by amaltaro**
There was a syntax error when removeCommand is empty. Largely seen in the HLT farm

### CODE REVIEW

**Review by hufnagel — COMMENTED** [review]
Code is ok, but I would like to know more about how we are triggering this use case. The remove command should only be empy for stagein and I am not aware we are using stagein anywhere.

Is there a code path where the removeCommand can be empty for stageout ?

**Comment by amaltaro** [comment]
That's right, this stage in code is kicked in the logcollect step.

**Comment by amaltaro** [comment]
test this please

**Comment by hufnagel** [comment]
Didn't I change the LogCollect code a while back to not stage in the files via the Stageout plugin but via edmCopyUtil ?

**Comment by hufnagel** [comment]
Ah, that's only support in CMSSW8X or higher.

**Comment by hufnagel** [comment]
Ok, no more questions, code looks good :-)

**Comment by amaltaro** [comment]
Yep, only supported by CMSSW_8x

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@hufnagel if you approve the code, then you have to "approve" it :-)
@ticoann it's good to be merged from my side.

**Review by hufnagel — APPROVED** [review]

**Review by ticoann — APPROVED** [review]

**Pull request merged**
