### PR TITLE
Fix arguments for T0 workflows

### LINKED ISSUE #10800: Issue creating /tmp/cmst0/.wmcore_cache file
**Impact of the bug**
T0 Agent not able to create/run any job/workflow using WMCore agent 1.5.2

**Describe the bug**
T0 use the Tier0Feeder component to create the sandbox. When Tier0 started to test a new release based con WMCore 1.5.2, Tier0Feeder component was unable to start properly given the following error:
```
2021-09-13 06:55:27,603:140108589012736:WARNING:Service:The cachefile /tmp/cmst0/.wmcore_cache_xlpsm5ls/cmssdt.cern.ch/-3895757188456107843_GET__SDT_cgi-bin_ReleasesXML_ does not exi
st and the service at https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML/ raised a FileNotFoundError(2, 'No such file or directory') when accessed
2021-09-13 06:55:27,673:140108589012736:ERROR:StdBase:About to raise exception <@========== WMException Start ==========@>
Exception Class: WMSpecFactoryException
Message: [Errno 2] No such file or directory: '/tmp/cmst0/.wmcore_cache_xlpsm5ls/cmssdt.cern.ch/-3895757188456107843_GET__SDT_cgi-bin_ReleasesXML_'
        ClassName : None
        ModuleName : WMCore.WMSpec.WMWorkloadTools
        MethodName : _validateArgFunction
        ClassInstance : None
        FileName : /data/tier0/srv/wmagent/3.0.0/sw.jamadova/slc7_amd64_gcc630/cms/t0/3.0.0/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkloadTools.py
        LineNumber : 105
        ErrorNr : 0
```

**How to reproduce it**
Deploying the T0 (3.0.0) agent and start all the components of the agent or only Tier0Feeder.

**Expected behavior**
The /tmp/cmst0/.wmcore_cache file must be correctly created and finally Tier0Feeder will be able to create the sandbox

**Additional context and error message**
Issue is **only** affecting when T0 use WMCore 1.5.2.

### PR DESCRIPTION
**Pull request by jhonatanamado**
Fix an issue with "missing" arguments for T0 Repack workflows that triggered a nested wmexceptions. Related to tmp wmcache file

Fixes #10800 

#### Status
Tested with T0 replay

#### Description
Digging within the nested wmexceptions after the warning
```
WARNING:Service:The cachefile /tmp/cmst0/.wmcore_cache_xlpsm5ls/cmssdt.cern.ch/-3895757188456107843_GET__SDT_cgi-bin_ReleasesXML_ does not exi
st and the service at https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML/ raised a FileNotFoundError(2, 'No such file or directory') when accessed
```
The issue that triggers the chain is during the Repack workflow arguments validation. Checking StdSpecs/Repack.py all the arguments that are used on T0 agent are described in that piece of the code. But I found within StdSpecs that the function **factoryWorkloadConstruction**  is defined in StdBase.py and Resubmission.py and are kind of similar. 
The changes that I made was to retrieve some functions from Resubmission.py and  adapt those for the T0 agent.
Still,  is not clear to me why this validation of the repack arguments trigger the issue with the cache file,  and why this happened during the transition between  python2-wmcore-agent and python3-wmcore-agent due that this PR is not needed if a python2 T0 agent is created/deployed.
 
Also if production doesn't run Repack workflows that may be the cause that this issue did not affect the deployment of python3 version of WMAgent.

At least I believe this makes it clear that the problem is not due to the configuration of the T0 vms.

#### Is it backward compatible (if not, which system it affects?)
Maybe. 

#### Related PRs
Other proposal to fix #10800 is using #10801

#### External dependencies / deployment changes
No

### CODE REVIEW

**Comment by amaltaro** [comment]
You completely removed the validation, that's why it's now going to work :)

At this point, I think the best we can do is to give you a debugging patch, such that you can apply it to the agent and try to collect more information to see what's happening here.

**Comment by jhonatanamado** [comment]
Hi @amaltaro @todor-ivanov 
So this issue about creating the wmcore-cache file is "properly" handled by two solutions. One is #10801  where if the cache file is expired or None it will "force" the creation. 
The other solution is by this PR where if the usual creation of the cache file fails it will try it again only if the error was an IOError. With this new PR Im trying not to be "penalized" in performance by others users that use Services.py  due as far as I know this issue didn't pup-up during the transition between py2-p3 agents.
By proposing this new solution all the arguments of the T0 workflows are been validated by this [line](https://github.com/dmwm/WMCore/blob/4b6676a4350addd15b6e9abe48a4e41e5217d920/src/python/WMCore/WMSpec/WMWorkloadTools.py#L302).
I will leave 3 samples of T0 workflows arguments that must be validated. Check for example that the arg `RequestString` doesn't appear in the files Repack.py,Express.py,Promtp.py. So Im still not sure if by #10801 all the arguments of T0 workflows are been validated.
Repack:
```
{'Memory': 2000, 'Requestor': 'Tier0', 'RequestName': 'Repack_Run345595_StreamPhysics_Tier0_REPLAY_2021_v1_21
1118_0554', 'RequestString': 'Repack_Run345595_StreamPhysics_Tier0_REPLAY_2021_v1_211118_0554', 'RequestorDN': 'Tier0', 'RequestDate': [], 'RequestTransition': [], 'RequestStatus': '
new', 'RequestPriority': 256000, 'PriorityTransition': [], 'CMSSWVersion': 'CMSSW_12_0_3_patch1', 'ScramArch': 'slc7_amd64_gcc900', 'ProcessingVersion': 1, 'MaxSizeSingleLumi': 25769
803776, 'MaxSizeMultiLumi': 8589934592, 'MinInputSize': 2254857830.4, 'MaxInputSize': 4294967296, 'MaxEdmSize': 25769803776, 'MaxOverSize': 8589934592, 'MaxInputEvents': 3000000, 'MaxInputFiles': 1000, 'MaxLatency': 86400, 'MinMergeSize': 2254857830.4, 'MaxMergeEvents': 3000000, 'UnmergedLFNBase': '/store/unmerged/data', 'MergedLFNBase': '/store/backfill/1/data', 'RunNumber': 345595, 'AcquisitionEra': 'Tier0_REPLAY_2021', 'Outputs': [{'dataTier': 'RAW', 'eventContent': 'ALL', 'selectEvents': ['HLT_L1SingleMu3_v1:HLT', 'HLT_L1SingleMu5_v1:HLT', 'HLT_L1SingleMu7_v1:HLT', 'HLT_L1SingleMuCosmics_v1:HLT', 'HLT_L1SingleMuOpen_DT_v2:HLT', 'HLT_L1SingleMuOpen_v2:HLT'], 'primaryDataset': 'Cosmics'}, {'dataTier': 'RAW', 'eventContent': 'ALL', 'selectEvents': ['HLT_Physics_v7:HLT'], 'primaryDataset': 'HLTPhysics'}, {'dataTier': 'RAW', 'eventContent': 'ALL', 'selectEvents': ['HLT_HcalNZS_v12:HLT', 'HLT_HcalPhiSym_v14:HLT'], 'primaryDataset': 'HcalNZS'}, {'dataTier': 'RAW', 'eventContent': 'ALL', 'selectEvents': ['HLT_L1EXT_HCAL_LaserMon1_v1:HLT', 'HLT_L1EXT_HCAL_LaserMon4_v1:HLT', 'HLT_L1SingleEG10_v1:HLT', 'HLT_L1SingleEG15_v1:HLT', 'HLT_L1SingleJet10erHE_v1:HLT', 'HLT_L1SingleJet12erHE_v1:HLT', 'HLT_L1SingleJet16_v1:HLT', 'HLT_L1SingleJet200_v1:HLT', 'HLT_L1SingleJet20_v1:HLT', 'HLT_L1SingleJet35_v1:HLT', 'HLT_L1SingleJet8erHE_v1:HLT', 'HLT_Physics_v7:HLT', 'HLT_Random_v1:HLT', 'HLT_ZeroBias_v2:HLT'], 'primaryDataset': 'MinimumBias'}], 'ValidStatus': 'VALID'}
```
Express:
```
{'TimePerEvent': 4, 'SizePerEvent': 1700, 'Memory': 11900, 'Multicore': 8, 'Requestor': 'Tier0', 'RequestName': 'Express_Run345595_StreamCalibration_Tier0_REPLAY_2021_v1_211118_0554', 'RequestString': 'Express_Run345595_StreamCalibration_Tier0_REPLAY_2021_v1_211118_0554', 'RequestorDN': 'Tier0', 'RequestDate': [], 'RequestTransition': [], 'RequestStatus': 'new', 'RequestPriority': 261000, 'PriorityTransition': [], 'ProcessingString': 'Express', 'ProcessingVersion': 1, 'Scenario': 'AlCaTestEnable', 'CMSSWVersion': 'CMSSW_12_0_3_patch1', 'ScramArch': 'slc7_amd64_gcc900', 'RecoCMSSWVersion': 'CMSSW_12_0_3_patch1', 'RecoScramArch': 'slc7_amd64_gcc900', 'GlobalTag': '120X_dataRun3_Express_v2', 'GlobalTagTransaction': 'Express_345595', 'GlobalTagConnect': 'frontier://PromptProd/CMS_CONDITIONS', 'MaxInputRate': 23000, 'MaxInputEvents': 100000000, 'MaxInputSize': 4294967296, 'MaxInputFiles': 10000, 'MaxLatency': 3600, 'AlcaSkims': ['EcalTestPulsesRaw', 'PromptCalibProdEcalPedestals'], 'DQMSequences': [], 'AlcaHarvestTimeout': 43200, 'AlcaHarvestCondLFNBase': '/store/unmerged/tier0_harvest/2021', 'AlcaHarvestLumiURL': 'root://eoscms.cern.ch//eos/cms/store/unmerged/tier0_harvest/2021', 'DQMUploadProxy': None, 'DQMUploadUrl': 'https://cmsweb.cern.ch/dqm/dev;https://cmsweb-testbed.cern.ch/dqm/offline-test', 'StreamName': 'Calibration', 'SpecialDataset': 'StreamCalibration', 'UnmergedLFNBase': '/store/unmerged/data', 'MergedLFNBase': '/store/backfill/1/data', 'PeriodicHarvestInterval': 86400, 'RunNumber': 345595, 'AcquisitionEra': 'Tier0_REPLAY_2021', 'Outputs': [{'dataTier': 'DQMIO', 'eventContent': 'DQMIO', 'primaryDataset': 'StreamCalibration'}, {'dataTier': 'ALCARECO', 'eventContent': 'ALCARECO', 'primaryDataset': 'StreamCalibration'}, {'dataTier': 'RAW', 'eventContent': 'RAW', 'selectEvents': ['HLT_EcalCalibration_v2:HLT', 'HLT_HcalCalibration_v1:HLT'], 'primaryDataset': 'TestEnablesEcalHcal'}], 'ValidStatus': 'VALID'}
```
PromtReco:
```
{'TimePerEvent': 1, 'SizePerEvent': 1500, 'Memory': 11900, 'Multicore': 8, 'Requestor': 'Tier0', 'RequestName': 'PromptReco_Run345880_MinimumBias_Tier0_REPLAY_2021_v1_211118_0559', 'RequestString': 'PromptReco_Run345880_MinimumBias_Tier0_REPLAY_2021_v1_211118_0559', 'RequestorDN': 'Tier0', 'RequestDate': [], 'RequestTransition': [], 'RequestStatus': 'new', 'RequestPriority': 251000, 'PriorityTransition': [], 'AcquisitionEra': 'Tier0_REPLAY_2021', 'CMSSWVersion': 'CMSSW_12_0_3_patch1', 'ScramArch': 'slc7_amd64_gcc900', 'RunNumber': 345880, 'SplittingAlgo': 'EventAwareLumiBased', 'EventsPerJob': 6000, 'RobustMerge': False, 'ProcessingString': 'PromptReco', 'ProcessingVersion': 1, 'Scenario': 'ppEra_Run3', 'GlobalTag': '120X_dataRun3_Prompt_v2', 'GlobalTagConnect': 'frontier://PromptProd/CMS_CONDITIONS', 'InputDataset': '/MinimumBias/Tier0_REPLAY_2021-1/RAW', 'WriteTiers': ['AOD', 'MINIAOD', 'DQMIO', 'ALCARECO'], 'AlcaSkims': ['SiStripCalZeroBias', 'SiStripCalMinBias', 'TkAlMinBias', 'HcalCalHO', 'HcalCalIterativePhiSym', 'HcalCalHBHEMuonFilter', 'HcalCalIsoTrkFilter'], 'PhysicsSkims': [], 'DQMSequences': ['@common', '@commonSiStripZeroBias', '@ecal', '@hcal', '@muon', '@jetmet'], 'UnmergedLFNBase': '/store/unmerged/data', 'MergedLFNBase': '/store/backfill/1/data', 'ValidStatus': 'VALID', 'EnableHarvesting': 'True', 'DQMUploadProxy': None, 'DQMUploadUrl': 'https://cmsweb.cern.ch/dqm/dev;https://cmsweb-testbed.cern.ch/dqm/offline-test'}
``` 
Please let me know if any of you have comments about this issue due that T0 is still running with #10801 and if we don't use 10801 basically we are not able to run any job.

Thanks

**Comment by amaltaro** [comment]
@jhonatanamado thanks for providing these examples. I would suggest to pick the Repack configuration you provided above and try to reproduce it in our unit test setup, basically calling the workload construction with those key/value pairs. Something similar to:
https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/WMSpec_t/StdSpecs_t/Repack_t.py#L249-L253

I suspect we won't be able to reproduce it though, since we have basic tests done with the test arguments already in place.

If nothing works, we should then create a temporary patch, deploy a replay instance and patch it before injecting anything and try to fetch the exact error. That would allow us to pin point the root cause and make the proper fix.

This PR provides some valuable spec validation though. Can I ask you to create a new GH issue requesting the implementation of such T0 spec parameter validation? Then move most of these changes to a new feature branch/PR  and we can follow this separate development from there. Thanks

**Comment by amaltaro** [comment]
@jhonatanamado I think you started working on it in order to fix the Tier0Feeder cache, right?
Would you like to continue working on the spec validation for T0 workflows (partially in this PR), or shall we close it?

**Comment by jhonatanamado** [comment]
Hi @amaltaro , this was a second approach to fix the cache issue where we will force the creation of that directory it if it hits only the `not os.path.exists(cachefile)` exception. You can close it.

**Comment by amaltaro** [comment]
Thanks Jhonatan. I am closing it then.

**Pull request closed without merging**
