### PR TITLE
move TagCollect class under Service

### LINKED ISSUE #7483: Make a TagCollector service
This will be useful for CRAB and can refactor some code out of ReqMgr2

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7483

### CODE REVIEW

**Comment by ticoann** [comment]
Valentin, please review

**Comment by ticoann** [comment]
test this please

**Review by vkuznet — APPROVED** [review]
Seangchan, everything looks good. Please go ahead with this mgration

**Comment by ericvaandering** [comment]
This PR turned up a bug in the new Jenkins reporting... Will try to fix it.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann you'll be happy. This should be the last test that complains about missing imports in __init__

**Comment by ticoann** [comment]
Thanks Eric. 😄

**Comment by ticoann** [comment]
@mmascher, HI Marco, could you update Crab3 code to use this instead of RequestManager code.

**Comment by amaltaro** [comment]
or @emaszs :-)

**Pull request merged**
