### PR TITLE
Update schematics for WM, MSTransferor and MSMonitor

### LINKED ISSUE #11293: Update some of the WMCore diagram and schematics
**Impact of the new feature**
WMCore

**Is your feature request related to a problem? Please describe.**
Some of those diagrams are outdated, either still mentioning PhEDEx, or with old comments and data flow.

**Describe the solution you'd like**
Remove the no-longer relevant UnifiedTransferor architecture, updated its v2 and update the WM schematic.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #11293 

#### Status
ready

#### Description
Changes provided are:
* removed no-longer relevant UnifiedMS diagrams;
* updated/renamed UnifiedMS_v2 diagram by removing PhEDEx, rewording SiteWhitelist and visual enhancements
* on the WM_Schematic, added logos for k8s and docker

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Review by todor-ivanov — CHANGES_REQUESTED** [review]
Thanks for working on approving those documents @amaltaro 
I have few comments though. And I cannot point inline so I hope I can point to the right places correctly from here. 


file: [doc/MicroServices/MSTransferor_Monitor_Schematic.png](https://github.com/dmwm/WMCore/pull/11294/commits/6976f7c9383ecdcac66003e444fd61702164da61#diff-6f9f405e1d19ceb163eefaa91075aeec508c04e2b8b2f75ba29b7d29fe8c2d4b)

The Global outlook:

* A legend is missing, classifying what the different arrows means / what category they fall in (e.g. 
    * **Thick red square shaped arrows** - request status transition path
    * **Red arrows** - component information collection/persistence flow
    * **Green arrows** - component action flow
or similar )
* The last line of text saying "From here on it's all the same", presumes people reading the diagram are supposed to know the history of the development process and to connect the current digram with previous state of the code or other documents. A diagram should be self contained and explain only its own logic, while the connection with other pieces of the system should be unambiguous and pointing directly to the next component in the line. So I'd suggest a  change with "To regular Reqmgr2 Status transition logic" or similar.

MStransferor:
* Rightmost components in the diagram - I am not sure, but I think the data discovery happens first, so I'd reorder Rucio and DBS such that  the step happening first to sit on top 
* Isn't consulting Rucio for an already existing rule considered part of the data discovery step?
* Missing an arrow or a mark or text noting which component is moving the request's status from `assigned` to `staging`, if this is supposed to be the green arrow, the action of status transition itself needs to be added to the text above/bellow the arrow as well.




MSMonitor:
* The text "PU transfer beyond x component" is quite confusing. It stays with no relation to any action in the diagram.
* Same for "no data transfer at all". If they list one or more possible workflow or data transfer rule states during this status transition, it better be listed on the left side of the status transition arrow as a full list together with "PU transfer....." (if the above text also relates to the same).
* Missing a text or a label of an arrow related to the action of status transition from `staging` to `staged` and a general condition under which the status transition happens.   

Global WorkQueue:
* Green arrow missing any text or note. No action indicated, being it request status transition or any.

file: [doc/wmcore/WM_Schematic.png](https://github.com/dmwm/WMCore/pull/11294/commits/6976f7c9383ecdcac66003e444fd61702164da61#diff-98e0c0530bb7c8db0346ff2b54cd55c5cf255dca6aa6ffccdb511c320fb3b18c)

Because the new image went too small, It isn't very well visible what the change was, except the few new system labels we add. This is important, indeed. Anyway, my comment refers only to the size of the image here. Provided we preserve the aspect ratio, I wouldn't sacrifice the resolution.

**Review by vkuznet — COMMENTED** [review]
I'm not sure if I need to approve or comment on this. Anyway here is my concern with data flow diagrams:
- it is unclear what arrow represents, is it data coming to the service where the errors goes. In this case, in this [diagram](https://github.com/dmwm/WMCore/blob/6976f7c9383ecdcac66003e444fd61702164da61/doc/wmcore/WM_Schematic.png) the WQ put data to DBS and I doubt it
- the data flow quite often goes in both directions, e.g. in this [diagram](https://github.com/dmwm/WMCore/blob/6976f7c9383ecdcac66003e444fd61702164da61/doc/MicroServices/MSTransferor_Monitor_Schematic.png) the MSTransferor I think reads and writes to ReqMgr2, while we have only one arrow direction
- Most importantly, we lack of data schema for these diagrams which I strongly suggest in future updates (not this one). The data flow is fine but for the external reviewer of these diagrams it is unclear how data is represented in each step. For instance, when the data comes from one state to another does the data transformed or not, or only states are updated. The schema is important for many reasons including understanding performance of services, throughput, hardware resources, portability, data-streaming, etc.

**Comment by amaltaro** [comment]
Thank you Todor and Valentin, those are pretty good comments!

My second commit has some modifications based on your input. However, please keep in mind that this is a HIGH level diagram representing the most important dependencies and data flow in our system. If we go any deeper in details, it becomes much harder to explain and visualize it. This includes status transitions, which are actually a request to ReqMgr2 (and CouchDB), but it's show in that column of states.

And just a note on the arrows, they represent the direction of HTTP requests.

Please let me know how this one looks like.

**Review by todor-ivanov — CHANGES_REQUESTED** [review]
Thanks @amaltaro for the prompt rework on those. In some ways things look much better now, but the fact that you removed few things deprived the diagram from some really good information representation features that it was having before. 
* Please do return the thick square shaped arrows representing the workflow status transition path and just mention them in the legend. They were  extremely explanatory and were making it  really obvious what is happening here.
* All the text around the green arrows I understand as a generic condition for progressing workflow's  status. So I'd add a prefix or something stating this to all of them. something like:
   * cond: data available
   * cond: no input required ... etc.  or: 
   * put the text in an oddly shaped or colored box and state in the legend that the text enclosed in that  box relates  to a condition for status transition/progression.

**Comment by amaltaro** [comment]
Todor, for your first point, I didn't want to have 2 different arrows for status transition, which is basically what the thick and green arrows do.

For the second point, this is what I am trying to avoid. This will overload the diagram with too much information, a person cannot understand every condition and details from a high level diagram. If it becomes too detailed, then most of the people won't get even the high level picture.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro, In my understanding the thick squared shaped arrows were referring to the status path itself, similar to other diagrams of ours, while the green arrows were referring to the component acting on this  transition. So both of them are serving their purpose well. I think removing any of them makes the diagram confusing.

**Comment by todor-ivanov** [comment]
And for the second point, basically the text and conditions are already there in the diagram. I do not suggest  to add more. My suggestion was basically to note somewhere/somehow that the text adjoining the arrow is a condition for status transition. Nothing more. Ergo my offer to just note that in the legend.

**Comment by vkuznet** [comment]
Alan, what is unclear to me from this diagrams how I can ready data flow. For instance, the arrow represent HTTP request, but we get GET one and POST ones. Those are two different directions, in former case we get the data from the service, e.g. WQ get data from DBS, while in second case we post data to the service. The current states of errors makes it very confusing to understand the actual data flow. Therefore, you either need to change directions based or add GET/POST to the errors (which may seems impossible due to density of errors) or use solid/dashed errors represent GET/POST requests.

**Comment by amaltaro** [comment]
@todor-ivanov , 4th commit has the thick arrows showing the workflow status path (well, sort of). If you really want to see all the status path, then one has to look into the correct diagram:
https://github.com/dmwm/WMCore/blob/master/doc/wmcore/RequestStateTransition.png

@vkuznet GET or POST does not change the direction flow (who is making the HTTP request)

**Review by todor-ivanov — APPROVED** [review]
thanks @amaltaro

**Comment by amaltaro** [comment]
Thank you again for the great suggestions. With this PR, I provided the source diagram in format draw.io (to be opened with draw.io app), so further changes can be easily done as well.

**Pull request merged**
