### PR TITLE
fix task archiver for tier0 case

### PR DESCRIPTION
**Pull request by ticoann**
tested in vocms001. @hufnagel, Dirk, please review

### CODE REVIEW

**Comment by hufnagel** [comment]
Hm, tier0 has different team names for replay and production. Does this matter ?

**Comment by ticoann** [comment]
It doesn't matter as long as it uses different database. If there is plan for using two different team (agents) running for tier0, we need to change things.

1. put team in the request document
2. create the view for team and status.

**Comment by hufnagel** [comment]
Replay tier0 instances should never publish information in the same databases as the production instance. We can have two production instances running in parallel though and these would write to the same central database.

**Comment by ticoann** [comment]
with the same team name or different team name? Anyway, it it not completely necessary to have team name for this case It just reduces what request pulled down. I added this since there are few different teams in production agents.

**Comment by hufnagel** [comment]
Same team name I believe, although you might want to check with John or Eliana.

**Comment by ticoann** [comment]
OK I will do that.

**Pull request merged**
