### PR TITLE
MSpileup integration with MSManager

### LINKED ISSUE #11426: [MS] Define MSPileup logic for data placement and rule monitoring
**Impact of the new feature**
 New WMCore microservice

**Is your feature request related to a problem? Please describe.**
Creation of a new microservice to make pileup management more efficient and easier.
Subtask of https://github.com/dmwm/WMCore/issues/9779

**Describe the solution you'd like**
The bulk of the MSPileup logic has to be implemented within this ticket, which involves:
* read all the pileup configurations from the database, act on them if necessary, then persist any updates to the pileup configuration in the database

The expected actions to be performed by MSPileup is:
* rule creation: for pileup configuration that is active, create Rucio rules against the expectedRSEs (or in the future for the number of fullReplicas) under the `wmcore_transferor`. Rules should only be created if not yet existent.
* pileup/rule monitoring: active pileup ids should be continuously monitored to ensure that the expected RSEs contain a rule locking the pileup id. Non-active pileup ids should be checked to ensure that no Rucio rules are left behind, under the `wmcore_transferor` rucio account.
* rule removal: when a pileup configuration is found to be active: False, the microservice needs to delete all the `wmcore_transferor` rules found for the relevant pileup id. NOTE that the removal logic is supposed to be addressed in a different ticket: https://github.com/dmwm/WMCore/issues/11428

Log records should be done whenever appropriate, including a summary by the end of the cycle.

**Describe alternatives you've considered**
Perhaps changing the Rucio account for pileup input data placement would help with data management/monitoring, but this will incur further changes in WMCore.

We might consider using the dataset locks before actually deleting Rucio rules.

**Additional context**
None

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #11426 

#### Status
not-tested

#### Description
This PR provides integration of MSPilup data placement logic as separate data service

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
#11499 , and we need this PR in place in order to test this one and new MicroService.

#### External dependencies / deployment changes
- We need to have new k8s manifest file in place in order to deploy it, corresponding CMSWEB PR is https://github.com/dmwm/CMSKubernetes/pull/1322
- we also need https://github.com/dmwm/CMSKubernetes/pull/1323
- and, new config: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/tree/test/reqmgr2ms-pileup-tasks
   - new port 8361
   - new end-point `ms-piileup-tasks`
- FE redirect rules in https://github.com/dmwm/deployment/pull/1253

### CODE REVIEW

**Comment by vkuznet** [comment]
@amaltaro , I prepared this PR for integration with MSManager, but it requires #11499 to be merged in order to test things (as therefore, we may need to rebase it after the merge of #11499). Anyway, I would appreciate your initial review. The corresponding PR for k8s deployment is provided in description.

**Review by amaltaro — CHANGES_REQUESTED** [review]
@vkuznet changes provided in this PR look good to me, thanks.

However, please compare the `test` branch configuration:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/test/reqmgr2ms-pileup-tasks/config.py
with the one that already went under review:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/test/reqmgr2ms-pileup/config.py

and fix the inconsistencies (at least CLUSTER_NAME is wrong, but please compare everything).
Also provide the relevant changes to the `preprod` branch.

Given that it's a new service, you seem to be missing the frontend rules (or backend rules) in this PR. Please provide them everywhere where it's relevant (deployment repo, gitlab frontends, CMSKubernetes nginx, etc) and properly link them in the initial description.

**Comment by amaltaro** [comment]
Documentation will have to be updated as well:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Pileup
and
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-APIs#mspileup-rest-apis

**Comment by vkuznet** [comment]
And, I updated corresponding wikies.

**Comment by vkuznet** [comment]
Alan, I'm not against exposing service but if it has real use-case. Please evaluate your use-case:
- we do not check service from outside, instead we let k8s scrape its metrics and have dashboard, if k8s fails to access the service (which it does use `/status` for its liveness probe) the service will be dead and restarted.
- the dashboard will show all relevant info and we can have an alert
- we also check logs which provides everything about service

All of the above use-case do not need outside access. Anyway, here is PR for frontend, see https://github.com/dmwm/deployment/pull/1253,  but I literally do not see any use for that.

**Comment by amaltaro** [comment]
@vkuznet your first 2 bullets are correct for an automated system.
It does not mean that one cannot query the status endpoint for a given service though, especially as an extra check right after upgrading services. Logs are definitely useful, but again, if you just want a quick and simple check, this API will do that.

Thank you for providing the required deployment changes. I just updated that ticket asking for another change to the nginx rules. 

I don't think we need to wait for that before we can merge this PR though. So things look good to me! Thanks

**Pull request merged**
