### PR TITLE
allow not adding hostname to DN for hash

### PR DESCRIPTION
**Pull request by belforte**
Fixes a problem with myproxy credential handling in CRAB
when user switched to a certificate with a different DN
refs:
https://github.com/dmwm/CRABClient/issues/4927
https://github.com/dmwm/CRABClient/issues/4931
https://github.com/dmwm/CRABServer/issues/6110

#### NOTE TO WM DEVELOPER(S)
I would like this to be available as an incremental patch to 1.3.6 version, since as discussed with Alan current WMCore mater has python3 compatibility things and my require changes in CRAB as well to be used. A good thing to do, but which I'd like to decouple.

I am making a PR for master branch, but I can make for a different one if you prefer, simply I do not know which one you would prefer. Thanks.

#### Status
Ready and Tested

#### Description
There is a small change to one method which is only used by CRAB, namely  `WMCore/Credential/Proxy/getMyproxyUsernameForCRAB`

#### Is it backward compatible ?
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by amaltaro** [comment]
Changes look good to me. I have just created `1.3.6_crab`, which points to the commit tagging 1.3.6. Could you please backport it to that branch (otherwise let me know and I can take care of it)?

For the record, for your future PRs, please explicitly ask Todor and I to review your PRs via the "Reviewers" option on the top-right side.

**Comment by belforte** [comment]
will do. thanks

**Review by amaltaro — APPROVED** [review]

**Comment by belforte** [comment]
I have made the PR for the 1.3.6_crab branch as requested.
https://github.com/dmwm/WMCore/pull/9867

this can be closed

**Comment by belforte** [comment]
as @amaltaro rightfully pointed out, this change will have to go in master as well in order to still be present in future versions !

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Those Rucio unit test failures are being followed up via email and have nothing to do with this PR, merging it.

**Pull request merged**
