### PR TITLE
Typo fixed in wmbs_fileset_seq creation

### PR DESCRIPTION
**Pull request by amaltaro**

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
[WMAgent does not crash on new data](https://trello.com/c/GVg53MEM/1-wmagent-does-not-crash-on-new-data)

**Comment by ticoann** [comment]
Wow! how did you even find this? At least it wasn't breaking anything. :-)

**Comment by ticoann** [comment]
test this please

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
It was breaking wmagent pre9 :-)

**Pull request merged**
