### PR TITLE
Handle requests without prep_id

### PR DESCRIPTION
**Pull request by amaltaro**
Diego G. reported a problem with WMDataMining in testbed. From the traceback, it seems to fail when a request does not have Prep_Id, it should fix that issue

@ericvaandering please review. I could not test it in my VM because it fails to generate a SSO cookie (?)
otherwise I'll wipe my VM in make a fresh installation this evening just to make sure there won't be another bug after this one.

### CODE REVIEW

**Comment by ericvaandering** [comment]
Is the failure at this exact place? Like it's trying to do "starts with" on a None?

**Comment by ericvaandering** [comment]
In any case, looking at this more carefully, I think it's better to move this test and action after line 92 (before we try to contact McM)

**Comment by amaltaro** [comment]
That's right Eric, it happens in this exact line
```
2015-08-25 10:27:26,257:ERROR:CherryPyPeriodicTask:     if prep_id.startswith('task_'):
2015-08-25 10:27:26,257:ERROR:CherryPyPeriodicTask: AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by ericvaandering** [comment]
Alright, then this is a good patch. @ticoann please merge.

**Comment by ericvaandering** [comment]
retest this please

**Comment by ticoann** [comment]
retest this please

**Comment by ericvaandering** [comment]
@ticoann this is good to merge. I'll address the idiom thing in another PR since Alan did this one.

**Comment by amaltaro** [comment]
Sorry guys, I completely forgot to update this one before going to bed :(

**Comment by ticoann** [comment]
Ah, you mean pylint recommendation? Don't worry about it. :smile: we can always add that later.

**Comment by amaltaro** [comment]
Yes, I see Eric updated it in 6171. Thanks!

**Pull request merged**
