### PR TITLE
Stop staging out log tarball to Castor (deprecated)

### LINKED ISSUE #10708: Deprecate CASTOR (deprecated) from LogCollect in master branch
**Impact of the new feature**
This will deprecate the usage of castor in LogCollect

**Is your feature request related to a problem? Please describe.**
T0 replays saw this error with branches that don't have changes from PR [#10255](https://github.com/dmwm/WMCore/pull/10255)

**Describe the solution you'd like**
Port changes from  PR [#10255](https://github.com/dmwm/WMCore/pull/10255) to master branch 

**Describe alternatives you've considered**
Do nothing

### PR DESCRIPTION
**Pull request by khurtado**
Cherry picked from #10255

Fixes #10708

#### Status
ready

#### Description
Port changes from PR #10255 to master branch

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
PR [#10255](https://github.com/dmwm/WMCore/pull/10255)

### CODE REVIEW

**Comment by khurtado** [comment]
@amaltaro These are the changes from PR [#10255](https://github.com/dmwm/WMCore/pull/10255), cherry picked for the master branch

**Comment by amaltaro** [comment]
Thanks, Kenyi. However, I think it missed the removal of one block of code. Did you manage to use "git cherry-pick"? Or you had to pick this patch in a different way?

**Comment by amaltaro** [comment]
@khurtado since I already had that commit in my remote, it was easier for me to cherry-pick it and make a new PR in (already requested for a T0 replay as well):
https://github.com/dmwm/WMCore/pull/10712

Once we merge that, we can simply close this one.

**Comment by amaltaro** [comment]
Kenyi, I have just merged another PR superseeding this one: https://github.com/dmwm/WMCore/pull/10712

So, I'm about to close this PR without merging anything. Thanks for getting this moving though!

**Pull request closed without merging**
