### PR TITLE
split lumiList into smaller slices for dbs call

### PR DESCRIPTION
**Pull request by amaltaro**
It should fix an issue reported in elogs and here dmwm/dbs#462

When @yuyiguo manages to set that API to use POST instead of GET, then we can delete this slicing.
@ticoann please review

### CODE REVIEW

**Comment by ticoann** [comment]
Patch looks good. This has to be applied in GQ as well, right?

**Comment by amaltaro** [comment]
@ticoann , since you made #5700 , I guess we can close this one (?) Thanks

**Comment by ticoann** [comment]
Yuyi is still testing the listFileArray api so please hold on to that issue.

**Comment by ticoann** [comment]
Will revert when DBS Server for handling Oracle handling is updated.

**Comment by yuyiguo** [comment]
@ticoann 
Seangchan, I will use string binding in order to avoid Oracle's maximum 1000 per query. However, if you look at the data caused this problem, we did not only have problem with the big lumi list but also have the lumi was repeated in the list. I simply counted that 9% of the lumi list is repeated. Carrying repeated data will slow down our query as we are trying to push the limit of Oracle. It is very easy to remove the repeated lumi in python by converting the list to set and convert it back. Can you please remove the repeated lumis  in the agent code?

**Comment by ticoann** [comment]
Yuyi, If you are talking about following request, 
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/alahiff_HCA-Fall14DR73-00003_00007_v0__150318_074242_9537
It seems it is using mask, which means it is not the list of lumis. It is the range of lumis. I have to double check, initial dbs api (listFiles) handle this as list of lumis, instead of range?
[244180,244211] means [244180 - 244211]

**Comment by yuyiguo** [comment]
@ticoann 
@amaltaro
I have asked a DBS 3.2.10 release on cmsweb testbed. The detailed info can be found in cmsweb pull request ticket.  I hope Diego can deploy it tomorrow. This is a major rewrite on file daos that will be used for both listFiles and listFileArray. So it does not matter which API you are using, please test it as much as you can. I did myself too. 

I added checking in DBS to remove any duplicated lumis so you did not have to do it in wmagent. The https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/alahiff_HCA-Fall14DR73-00003_00007_v0__150318_074242_9537  request is lumi range. So it has even more lumi sections. Please let me know if you have any questions on the API and let me know how your test goes.

**Comment by ticoann** [comment]
Thanks Yuyi for the update. But still listFiles uses GET request and listFileArray uses POST, correct?
So it we have too many lumis it will still fail on listFiles, correct? Or are you breaking down the call in client side? For duplicate lumis, it is fine if you check in DBS side. However, we shouldn't pass the duplicate lumis to DBS in first place. I thought we are not doing that (we are passing the range). Did you find any duplicate lumis from our call?

**Comment by yuyiguo** [comment]
NP. Yes,  listFiles uses GET and lisFileArray uses POST. This is true to all DBS APIs.
I did not break down on the client  side. If you use listFileArray it will call POST and there is no needs to break down on the client side. The 1000 array limit is from Oracle so it is from the server side. I did not go back to check the call since I remove the duplicate anyway  before I pass it to Oracle. If you already removed the duplicate is even better we can save some network  bandwidth  too.  I don't think it is over do even if both WMAgent and DBS do check for duplicate. Python can do these effort less and I thought it is better DBS do it in case other application has duplicate lumis.

If you don't have enough time to test it, please let me know. We may consider to release it in May. Do you have an estimate what is the biggest lumi list could be?

**Comment by ticoann** [comment]
I don't think we have enough time to test before I make the pull request today. However, Alan said he will intensively test when it goes to testbed(So I merged our changes) since we still have week for the validation. Thanks,

**Comment by yuyiguo** [comment]
Sounds good. Let me know your test result on testbed. If there is any problem with the APIs, Please let me know ASAP.

**Pull request merged**
