### PR TITLE
Limit number of jobs in JobSubmitter - 1.0.5 version

### PR DESCRIPTION
**Pull request by amaltaro**
1.0.5_wmagent version of #5656
I guess we can create a patch2 tag with this patch now

### CODE REVIEW

**Comment by amaltaro** [comment]
Also updated the config file

**Comment by ticoann** [comment]
How about the master branch?

**Comment by amaltaro** [comment]
You probably saw it already :), but the master one is in #5859

**Comment by ticoann** [comment]
Thanks Alan, yes I merged that already.

**Pull request merged**
