### PR TITLE
Pylint red errors #3

### PR DESCRIPTION
**Pull request by ericvaandering**
@vkuznet the code I fixed some in https://github.com/dmwm/WMCore/commit/7d2ed3fb22a5a17f2d069afcbdc28b9afb350781 seems so riddled with errors (undefined variables, wrong imports, etc) that I can't believe it is used if it ever was. Is there any point to this code or should we delete it?

### CODE REVIEW

**Comment by vkuznet** [comment]
Eric, we moved to ReqMgr2 service long time ago, but ReqMgr code is located at different places in WMCore. I proposed a long time ago to Seangchan to clean-up old code. It seems to me that we safely delete:
WMCore/ReqMgr/Tools/WorkflowTools.py
WMCore/ReqMgr/Utils/url_utils.py
The later (getdata) is still in use in WMCore/ReqMgr/Web/ReqMgrService.py but it can be easily replaced with getdata method of pycurl_manager.py

Let's hear @ticoann Seangchan opinion.

**Comment by ericvaandering** [comment]
Thanks. I could not tell if this was ReqMgr or ReqMgr2

**Comment by ticoann** [comment]
I agree with Valentin, we can remove those modules. as well as ReqMgr/Tools/reqMgrClient.py.

**Comment by vkuznet** [comment]
As I wrote, if we'll remove url_utils.py we'll need to change WMCore/ReqMgr/Web/ReqMgrService.py since it relies on getdata from url_utils.

So here is how fix will look like

```
diff --git a/src/python/WMCore/ReqMgr/Web/ReqMgrService.py b/src/python/WMCore/ReqMgr/Web/ReqMgrService.py
index fe575bbb7..8cd6340c9 100644
--- a/src/python/WMCore/ReqMgr/Web/ReqMgrService.py
+++ b/src/python/WMCore/ReqMgr/Web/ReqMgrService.py
@@ -34,7 +34,6 @@ from WMCore.ReqMgr.Tools.cms import site_white_list, site_black_list
 from WMCore.ReqMgr.Tools.cms import web_ui_names, SITE_CACHE, PNN_CACHE
 # WMCore modules
 from WMCore.ReqMgr.Utils.Validation import get_request_template_from_type
-from WMCore.ReqMgr.Utils.url_utils import getdata
 # ReqMgrSrv modules
 from WMCore.ReqMgr.Web.tools import exposecss, exposejs, TemplatedPage
 from WMCore.ReqMgr.Web.utils import gen_color
@@ -43,8 +42,17 @@ from WMCore.Services.LogDB.LogDB import LogDB
 # new reqmgr2 APIs
 from WMCore.Services.ReqMgr.ReqMgr import ReqMgr
 from WMCore.WMSpec.StdSpecs.StdBase import StdBase
+from WMCore.Services.pycurl_manager import RequestHandler
+from Utils.CertTools import getKeyCertFromEnv


+def getdata(url, params, headers=None):
+    "Helper function to get data from the service"
+    ckey, cert = getKeyCertFromEnv()
+    mgr = RequestHandler()
+    res = mgr.getdata(url, params=params, headers=headers, ckey=ckey, cert=cert)
+    return json.loads(res)
+
 def sort_bold(docs):
     "Return sorted list of bold items from provided doc list"
     return ', '.join(['<b>%s</b>' % m for m in sorted(docs)])
```

Please keep this in mind that this code should be tested. Is it need to be in this PR is an open question. It can go into separate PR and then this PR will need to wait until it will be merged.

**Comment by ericvaandering** [comment]
@vkuznet can you make a PR with just that change?

**Comment by vkuznet** [comment]
Here is individual PR: https://github.com/dmwm/WMCore/pull/8147
It should be applied before removing utils/url_utils.py

**Comment by ericvaandering** [comment]
Thanks

**Comment by amaltaro** [comment]
@ticoann this one looks good to be merged before the wmagent release too.

**Comment by amaltaro** [comment]
and @ericvaandering you'll need to squash it

**Comment by ericvaandering** [comment]
Also squashed. Please merge.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann please merge

**Comment by ticoann** [comment]
Actually WorkflowTools.py and url_utils.py can be removed since Valentin, remove the usage of the code. But I will create a new patch.

**Pull request merged**
