### PR TITLE
Improve release notes

### PR DESCRIPTION
**Pull request by goughes**
Issue #9040

### CODE REVIEW

**Comment by goughes** [comment]
Notes look like this:

```
[goughes@esg WMCore]$ git log --no-merges  --pretty=format:'  - %<(25)%aN %s' ${LASTCOMMIT}..
  - Erik Gough                Improve release notes
  - Alan Malta Rodrigues      Default Harvesting job retries to 4; updated deploy script
  - Dirk Hufnagel             fix unittest schema init, fixes #9062
  - Alan Malta Rodrigues      Set Rucio account in the agent config file; cleaned up Alerts config
  - Alan Malta Rodrigues      Skip WorkQueue MonIT statistics for T0 agent
  - khurtado                  Add CMSSW exception message to condor chirp, when present
  - Alan Malta Rodrigues      pylint fixes
  - Alan Malta Rodrigues      Trigger transaction rollback if exception is raised in wmbsPreparation
```
Getting the bonus points for having the PR # on the commit message line might take some additional investigation.

**Comment by amaltaro** [comment]
@goughes one more thing. Can you please make sure it runs the diff against the latest tag instead of the latest final tag? For instance, 1.1.20.pre3 should be compared against 1.1.20.pre2, not against 1.1.19.

If it's easy, we could add the committer name between parenthesis at the end of the line instead of the beginning.

**Comment by goughes** [comment]
The updated regex makes it run against the latest tag.

```
1.2.1.pre2 to 1.2.2:
  - Erik Gough                Add another test file

1.2.1.pre1 to 1.2.1.pre2:
  - Erik Gough                Add a test file

1.2.0 to 1.2.1.pre1:
  - Alan Malta Rodrigues      Default Harvesting job retries to 4; updated deploy script
  - Dirk Hufnagel             fix unittest schema init, fixes #9062

```
I made the changes to the committer line.

```
 - Default Harvesting job retries to 4; updated deploy script (Alan Malta Rodrigues)
  - fix unittest schema init, fixes #9062 (Dirk Hufnagel)
  - Set Rucio account in the agent config file; cleaned up Alerts config (Alan Malta Rodrigues)
```

**Comment by amaltaro** [comment]
Thanks, Erik. I think we can do it without the PR number, but then we need to policy ourselves and write meaningful commit messages (and amend then when needed).
Please let me know what your thoughts are.

**Comment by goughes** [comment]
```
1.2.0 to 1.2.5:
  - Default Harvesting job retries to 4; updated deploy script (Alan Malta Rodrigues) #9081
  - fix unittest schema init, fixes #9062 (Dirk Hufnagel) #9075
  - Set Rucio account in the agent config file; cleaned up Alerts config (Alan Malta Rodrigues) #9073
  - Skip WorkQueue MonIT statistics for T0 agent (Alan Malta Rodrigues) #9066
  - Add CMSSW exception message to condor chirp, when present (khurtado) #9057
  - pylint fixes (Alan Malta Rodrigues) #9045
  - Trigger transaction rollback if exception is raised in wmbsPreparation (Alan Malta Rodrigues) #9045
```
Here is the result of my latest changes to the build script.

**Comment by amaltaro** [comment]
Erik, I tested these changes and this is the outcome:
https://github.com/dmwm/WMCore/commit/a3bf7fe341b7bf3cda4c717e9c469d89ab5387f9

It looks great now and it's ready to go from my side.

**Review by amaltaro — APPROVED** [review]
Thanks, Erik!

**Pull request merged**
