### PR TITLE
Change file deletion from srm to xrd for FNAL plugin

### PR DESCRIPTION
**Pull request by amaltaro**
Overseeds #6849 based on @hufnagel comments.

Still needs to:
1. be tested
2. be reviewed, Dirk, have a look please
3. clean zillions of pylint complaints
4. backported to 1.0.17_wmagent branch

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
It works fine. I ran a few workflows both at CERN and at FNAL. I'll merge it tomorrow, once I create the wmagent branch PR.
@hufnagel still, you're welcomed to have a look

**Comment by hufnagel** [comment]
Looks ok in general, but you should change xrd to xrdfs. The xrd tool is deprecated.

**Comment by amaltaro** [comment]
The `xrd` piece came from Dave :-) Is `xrdfs` supposed to have exactly the same behavior, options, etc than `xrd`?

**Comment by amaltaro** [comment]
Dirk, I'm merging this one such that we can cut a new wmagent release.
I suggest we follow the `xrdfs` work in a different patch, probably CERN plugin needs to be updated too, right? Would you like to take care of it? :-D

**Pull request merged**
