### PR TITLE
1.1.4 wmagent for patch2

### PR DESCRIPTION
**Pull request by ticoann**
Include following patch

#7933 filter exceptions on error log for wmstats
#7937  Accept plain list of lumis in the Run object
#7946 Fix merge cmssw version mismatch
#7952 Add site info for skipped file report
#7955 Add drain thread
#7957 Rollback unfinished transactions if ErrorHandler hits an exception
#7959 Fix a problem with new lumilist format
#7964 Raise HTTPException instead of ServerNotFoundError

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan I created the branch patch for the test #7943 is not included. Also I didn't merge to master either. I will run the quick test first.

**Comment by amaltaro** [comment]
7943 is not added yet to this bundle. It's better to make it clear in the first comment such that it doesn't slip through the cracks.

**Review by amaltaro — CHANGES_REQUESTED** [review]
We'll likely have to cherry-pick again #7933 and possible #7615. Without mentioned #7943 is not picked yet.

**Comment by amaltaro** [comment]
Seangchan, I believe you're not picking the test commits, are you? That would explain those unit test failures.
BTW, if you have a slightly concern on not cherry-picking everything that is needed, I suggest creating a new PR from scratch to avoid surprises in patch2

**Comment by ticoann** [comment]
create against wrong branch. Bad job. :-( replaced by #7965

**Pull request closed without merging**
