### PR TITLE
validate MC site whitelist

### LINKED ISSUE #7707: MonteCarlo request with empty WQE SiteWhitelist
As reported here: https://its.cern.ch/jira/browse/CMSCOMPPR-699

the workflow has a proper SiteWhitelist (and it was properly assigned) and even so the GQE have an empty SiteWhitelist list.

For the record, this is the dict posted during assignment
```
{u'AcquisitionEra': 'pPb502Winter16GS',
 u'AutoApproveSubscriptionSites': [u'T1_DE_KIT_Disk'],
 u'BlockCloseMaxEvents': 2000000,
 u'BlockCloseMaxWaitTime': 172800,
 u'CustodialSites': [],
 u'CustodialSubType': 'Replica',
 u'Dashboard': 'production',
 u'GracePeriod': 300,
 'HardTimeout': 159900,
 u'MaxMergeEvents': 200000,
 u'MaxMergeSize': 4294967296,
 u'MaxRSS': 2355200,
 u'MaxVSize': 4394967000,
 u'MergedLFNBase': '/store/himc',
 u'MinMergeSize': 2147483648,
 u'NonCustodialGroup': 'DataOps',
 u'NonCustodialSites': [u'T1_DE_KIT_Disk'],
 u'NonCustodialSubType': 'Replica',
 u'ProcessingString': 'MB_80X_mcRun2_pA_5TeV_v4',
 u'ProcessingVersion': 3,
 u'RequestStatus': u'assigned',
 u'SiteBlacklist': [],
 u'SiteWhitelist': [u'T1_IT_CNAF',
                    u'T2_DE_DESY',
                    u'T2_AT_Vienna',
                    u'T2_CH_CSCS',
                    u'T2_FI_HIP',
                    u'T2_TW_NCHC',
                    u'T2_UK_SGrid_RALPP',
                    u'T2_FR_GRIF_LLR',
                    u'T2_UK_SGrid_Bristol',
                    u'T2_PT_NCG_Lisbon',
                    u'T2_KR_KNU',
                    u'T1_ES_PIC',
                    u'T1_UK_RAL',
                    u'T2_IT_Legnaro',
                    u'T2_IT_Rome',
                    u'T2_UK_London_Brunel',
                    u'T2_RU_JINR',
                    u'T2_IT_Pisa',
                    u'T2_US_Vanderbilt',
                    u'T2_IN_TIFR',
                    u'T2_FR_CCIN2P3',
                    u'T2_CH_CERN_HLT',
                    u'T1_FR_CCIN2P3',
                    u'T2_FR_GRIF_IRFU',
                    u'T0_CH_CERN',
                    u'T2_UK_London_IC',
                    u'T2_IT_Bari',
                    u'T2_ES_CIEMAT',
                    u'T1_DE_KIT',
                    u'T2_FR_IPHC',
                    u'T2_RU_IHEP',
                    u'T2_HU_Budapest',
                    u'T2_CN_Beijing',
                    u'T2_US_MIT',
                    u'T2_BE_IIHE',
                    u'T2_CH_CERN',
                    u'T2_PL_Swierk',
                    u'T1_RU_JINR'],
 u'SoftTimeout': 159600,
 u'Team': 'production',
 u'TrustPUSitelists': False,
 u'TrustSitelists': False,
 u'UnmergedLFNBase': '/store/unmerged'}
```

global_workqueue logs show the following:
```
2017-03-09 01:43:27,115:INFO:WorkQueue:queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524/spec"
2017-03-09 01:43:29,436:INFO:WorkQueue:Splitting /pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524/Production with policy MonteCarlo params = {'ResubmitBlock': {'args': {}, 'name': 'Resub
mitBlock'}, 'MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Block'}}
2017-03-09 01:43:29,444:INFO:WorkQueue:Queuing element 2c0da21b2d78e9d93c600de309c834b7 for /pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524/Production with 1000 job(s) split with MonteC
arlo on events 1-478000
...
2017-03-09 01:43:29,452:INFO:WorkQueue:Queuing element 8815cb3f41831b7ab1ef7e79a3999c5e for /pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524/Production with 762 job(s) split with MonteCarlo on events 29636001-30000000
2017-03-09 01:43:58,541:INFO:WorkQueue:Split work for request(s): "pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524"
...
...
2017-03-09 01:49:27,157:INFO:WorkQueue:queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524/spec"
2017-03-09 01:49:27,799:INFO:WorkQueue:Resume splitting of "pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524"
2017-03-09 01:49:28,620:INFO:WorkQueue:Request "pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524" already split - Resuming
2017-03-09 01:49:28,620:INFO:WorkQueue:Split work for request(s): "pdmvserv_HIN-pPb502Winter16GS-00003_00003_v2_MB_170309_001506_524"
```

as can be seen, it tries to split work again twice. Checking...

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7707 @amaltaro, Alan please review

### CODE REVIEW

**Comment by amaltaro** [comment]
Seangchan, giving it a second thought... we should have a valid non-empty sitewhitelist for any request/policy type. Thus, how about we make a
`else: raise blah`
after this `if`
https://github.com/ticoann/WMCore/blob/6a1e4eaec262735e5f7860503cc638efde520a3f/src/python/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py#L50
?

**Comment by ticoann** [comment]
So every request will have sitewhite list, even if with inputdataset? This will be fine if that is always the case. We probably need to change the spec validation for SiteWhiltelist as well. (Not allowing empty list)

**Comment by amaltaro** [comment]
That's right, it should be provide for all sorts of workflows.
Actually, that's weird, I thought I had done some SiteWhitelist work in the last 3 months or so... haaa, I found it:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L434

anyways, it's not the best place to have this validation. So I'll add it to my spec refactoring PR.

**Comment by ticoann** [comment]
Alan, I updated the patch as you suggested. Please review

**Review by amaltaro — APPROVED** [review]
Patch looks awesome! :-) Though we have to eventually find out where the issue really lies, but that can be done later

**Comment by ticoann** [comment]
I looked through the code I couldn't find the place where this could happen. When it happens again, we can dig deeper.

**Comment by ticoann** [comment]
Alan, I don't think I can really test this, though. :-) I will just run the few workflows, if nothing breaks I will  create the new tag and make another pull request. Thanks,

**Comment by amaltaro** [comment]
Agreed, Seangchan! If a few workflows get into running state, that should be good enough. Thanks!

**Comment by ticoann** [comment]
@amaltaro, Alan, My vm test went fine. However, there are several unittest were broken.
While I am fixing the unittest. I realize that we don't set the site whitelist for DQMHarvest workflow, right? I updated the patch with that. If that is not correct assumption, could you fix the patch.
Otherwise could you merge this and create a new tag and pull request? 

Thanks,

**Comment by amaltaro** [comment]
All of them have a SiteWhitelist, it's mandatory at assignment, including for DQMHarvest.
Sigh... a simple fix that causes so many unit tests failures :( I'll have a look at it soon and create a new PR if needed. Thanks, Seangchan!

**Comment by amaltaro** [comment]
Stop working, it's 1am!

**Comment by ticoann** [comment]
Hi Alan, I revert back the patch and I think I fixed all the unittest. :smile: (hopefully), if the test goes OK, please merge and create a new tag. Thanks.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Replaced by #7758

**Comment by amaltaro** [comment]
Thanks a lot, Seangchan!

**Pull request closed without merging**
