### PR TITLE
Upgrade WMCore dependencies

### LINKED ISSUE #11080: Upgrade python CherryPy and other Python3 packages
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
Given that in the beginning of 2022 we decided to drop support to python2 in WMCore, we should revisit the list of third-party python libraries and update them to the latest stable release. 

**Describe the solution you'd like**
Update python3 specs in the cmsdist repository and in our requirements.txt text file.
CherryPy is a good candidate, but we should also check whether there are other python libraries that we can update to a newer stable release. Note that those libraries no longer need to support python2.

If possible, we should avoid any releases that came out in the past month or two, since those could still be buggy.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #11080 

#### Status
not-tested

#### Description
I provided updated versions of WMCore dependency packages
Associative PR for cmsdist can be found here: https://github.com/cms-sw/cmsdist/pull/8032

#### Is it backward compatible (if not, which system it affects?)
MAYBE

#### Related PRs
https://github.com/cms-sw/cmsdist/pull/8032

### CODE REVIEW

**Comment by vkuznet** [comment]
@amaltaro I'm not sure how you want to proceed with that. I updated cmsdist specs with new versions of packages I updated here. I don't think jenkins tests are relevant here as we need new RPMs in place first.

**Comment by amaltaro** [comment]
@vkuznet Valentin, we have these 3 other issues on the python dependency upgrade:
* Upgrade sqlalchemy in our python3 cmsdist stack #11205
* Upgrade cx-Oracle in our python3 cmsdist stack #11206
* Upgrade pycurl and pyOpenSSL in our python3 cmsdist stack #11207 

I would suggest to do incremental upgrades to isolate possible issues. Maybe start only with the CherryPy upgrade (+ dependencies) first?

**Comment by vkuznet** [comment]
The build https://github.com/cms-sw/cmsdist/pull/8032 is successful now, i.e. it means that we have RPMs for all packages. Therefore, we may try to run entire test suit on all changes and if build fails we can start the split. But since we have lots of  dependencies I doubt it would be easy, as we will need the order of dependencies.

Let's trigger the jenkins tests and see. If fails, we'll start the split, ok?

**Comment by vkuznet** [comment]
test this please

**Comment by amaltaro** [comment]
@vkuznet that's fine. My point is that we need to at least make sure python versions are compatible between each other.

One way to test it is to create a Dockerfile (mimic'ing the same environment we build production services), e.g.:
```
FROM python:3.8.2

RUN python -m pip install --upgrade pip==20.3.3 \
    && python -m pip install CherryPy==18.8.0
```

then building this docker image with a command like:
```
docker build .
```

This yields the following output (at the very end of the terminal):
```
Successfully installed CherryPy-18.8.0 autocommand-2.2.1 cheroot-8.6.0 importlib-resources-5.9.0 inflect-6.0.0 jaraco.classes-3.2.2 jaraco.collections-3.5.2 jaraco.context-4.1.2 jaraco.functools-3.5.1 jaraco.text-3.9.1 more-itertools-8.14.0 portend-3.1.0 pydantic-1.9.2 pytz-2022.2.1 six-1.16.0 tempora-5.0.2 typing-extensions-4.3.0 zc.lockfile-2.0 zipp-3.8.1
```

so, we should cross-check these packages+versions and make sure they get reflected in the spec files to avoid package incompatibility.

Of course, we do not need to run this step for every single python package, but I would say for the main ones, e.g.: cherrypy, cx-oracle, sqlalchemy, pycurl and maybe pyopenssl.

Can you run these checks and cross-check it against the changes you have implemented in the cmsdist PR? Updating whatever isn't matching as best as you can.

**Comment by vkuznet** [comment]
ok, that's a good trick. I updated other dependencies and await for RPM build. Again, if finished correctly I'll update tickets.

**Comment by amaltaro** [comment]
@vkuznet Valentin, please review and reflect the changes from https://github.com/cms-sw/cmsdist/pull/8032

**Comment by vkuznet** [comment]
@amaltaro , I had some issue with my clone of WMCore repo and I recreated it from scratch. As such this PR can't be changed since my tree was gone. I recreated it here https://github.com/dmwm/WMCore/pull/11256 and I'm closing this PR in favor of later one.

**Pull request closed without merging**
