### PR TITLE
Remove cp plugin

### LINKED ISSUE #7940: Deprecating stage out plugins
I just talked to @stlammel and @roksys to see if the SS team can start pushing sites away of (almost) deprecated transfer tools. I'm posting here a summary of what I found in SITECONF repo,  feel free to x-check these numbers.

**local stage out for T0/T1/T2 sites** see command used to grep here [1]
```
      2 cp
     17 gfal2
      1 rfcp
      1 rfcp-2
      5 srmv2
     31 srmv2-lcg
      2 stageout-xrdcp-fnal
      1 vandy
      5 xrdcp
```

**fallback stage out for T0/T1/T2 sites**
```
     14 gfal2
      1 rfcp
      2 srm
      5 srmv2
     15 srmv2-lcg
```

As you can see, I discarded T3s configuration since we mostly don't use them.

I believe the goal is to keep only 3 implementations around (well, 4 with vandy). So gfal2, xrdcp and cp (+ vandy). Correct?

In a short term, I think we can deprecate only rfcp* and srmv2. By the way, is there any difference between `srmv2` and `srmv2-lcg`?

[1]
grep -A5 -r '<local-stage-out>' /cvmfs/cms.cern.ch/SITECONF/T{0,1,2}*/JobConfig/site-local-config.xml | grep 'command value' | awk -F'=' '{print $2}' | awk -F'"' '{print $2}' | sort | uniq -c

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7940

As confirmed by SS/Stephan, there are no sites using this storage plugin anymore and it can be finally removed from WMCore.

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Alan, I seems unittest failure is real ones. Could you fix that as well?

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Thanks, Seangchan! There were a few other tests relying on the cp command (CPImpl plugin). I replaced them by `test-copy` and tests are succeeding now. Feel free to review and merge.

**Pull request merged**
