### PR TITLE
Ignore anything but RequestPriority for no status update

### LINKED ISSUE #8457: Changing priority in assignment-approved fails
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_PPD-RunIISummer17PrePremix-00006__v1_T_180212_090017_6410 trying to set up to 111000 gives people

Server error message
Invalid spec parameter value: There are invalid arguments for no-status update: {u'SoftTimeout': 129600, u'BlockCloseMaxEvents': 25000000, u'MaxMergeEvents': 100000000, u'CustodialSites': u'', u'Ma... 

please advise, and prioritize a fix

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8457

### CODE REVIEW

**Comment by amaltaro** [comment]
Tests are fine

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
That's a good point! Until this very second, we support only RequestPriority (and RequestStatus) changes along the lifetime of a request. Any other parameters can only be changed during assignment.

Once we make the system more flexible (like updating the SiteWhitelist/BlackWhitelist), then we'll have to revisit it.

**Pull request merged**
