### PR TITLE
Added Pileup support to MCFromGEN

### LINKED ISSUE #6219: Support MCPileUp in MonteCarlo and MonteCarloFromGEN request types
for fastsim workflows, one needs to use either type and should be able to provide MCPileup parameter and it should be treated properly. This would facilitate greatly central production.
This ticket should have been opened a few months ago already @srimanob

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #6219 which was already available in MonteCarlo but not in MonteCarloFromGEN.

I also added the deterministicPileup capability to these 2 specs and TaskChain.

@ticoann do NOT merge it yet. I ran basic tests in my VM and workload gets properly filled, I just need to check a couple other things (and unittests + pylint).

TODO: I noticed EventBased splitting is not capable to handle it yet.. I will create another issue to get it fixed there as well.

### CODE REVIEW

**Comment by amaltaro** [comment]
sigh, I messed up this PR by working on the same branch in different computer... let me try to clean this up

**Comment by amaltaro** [comment]
@ticoann it won't pass the pylint checks (setattr pylint issue).
feel free to merge it

**Comment by ericvaandering** [comment]
test this please

**Comment by amaltaro** [comment]
I believe those transient unit test failures came up from the mess I previously made merging more code than I should. It was fixed before and the last jenkins run shows that :)

@ticoann please merge and then I will create a new tag. Do we need to add anything else in the pre3 tag?

**Pull request merged**
