### PR TITLE
add events column in file_runlumi_map

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, @hufnagel, please review. If looks OK I will merge first and run the test then create wmagent patch.

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
Looks good!

**Comment by ticoann** [comment]
I can't be off the hook so easily.  I think due to the events column name, it cause a lot ambiguity. I will change column to num_events

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
unittest failure seems not related. I will merge this and run the test before creating the branch patch

**Comment by amaltaro** [comment]
[Fix #7779 (needs to be backported) - add events column in file_runlumi_map](https://trello.com/c/VEl2mymV/24-fix-7779-needs-to-be-backported-add-events-column-in-file-runlumi-map)

**Comment by amaltaro** [comment]
[Patch bundle #7788 - backport of #7777, #7779, #7782 and #7784](https://trello.com/c/Vcl1FezR/27-patch-bundle-7788-backport-of-7777-7779-7782-and-7784)

**Pull request merged**
