### PR TITLE
Open parsed file in bytes.

### LINKED ISSUE #10533: [py2py3] Check unittests from Slice 2 in py3
#### Intro

We need to make sure that the work done in the migration slices
is py3 compatible. In particular, we should make sure that the
unittests that are involved in each slice do not fail.

The schedule for this validation / bug-fixing campaign is kept at #10422

#### Details

This issue is about checking that the unittests from Slice 2,
issue #10098 and PR #10103, do not fail.
A non-exhaustive list of the ut that need to pass is

```
test/python/WMCore_t/GroupUser_t/Decorators_t.py
test/python/WMCore_t/MicroService_t/Tools_t/PycurlRucio_t.py
test/python/WMCore_t/Services_t/Rucio_t/Rucio_t.py
test/python/WMCore_t/Storage_t/TrivialFileCatalog_t.py
test/python/WMCore_t/WMSpec_t/ConfigSectionTree_t.py

```

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #10533

#### Status
ready

#### Description
Working on the unit tests errors for Slice2.
The current PR solves only the issue with the py2-py3 conversion of the test/python/WMCore_t/Storage_t/TrivialFileCatalog_t.py test from https://github.com/dmwm/WMCore/issues/10533

#### Is it backward compatible (if not, which system it affects?)
YES

### CODE REVIEW

**Comment by todor-ivanov** [comment]
Hi @amaltaro 
The current PR solves only the issue with `test/python/WMCore_t/Storage_t/TrivialFileCatalog_t.py` test from #10533
IIRC @mapellidario mentioned the rest of the errors are covered by some other slice/issue

**Comment by mapellidario** [comment]
We merged #10514, I tried to run `nosetests test/python/WMCore_t/MicroService_t/Tools_t/PycurlRucio_t.py` and i get `'Cannot authenticate to account wma_test with given credentials'`. Could you have a look at that? Maybe it's my environment, but maybe we are doing something wrong with the tokens/certificates. I do not know unfortunately, so another pair of eyes here can help. Thanks in advance, Todor!

**Comment by todor-ivanov** [comment]
Same here @mapellidario :

```
======================================================================
ERROR: Test the listReplicationRules function, which fetches the container
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/MicroService_t/Tools_t/PycurlRucio_t.py", line 70, in testListReplicationRules
    self.rucioToken, self.tokenValidity = getRucioToken(self.rucioAuthUrl, self.rucioAccount)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/MicroService/Tools/PycurlRucio.py", line 78, in getRucioToken
    res = mgr.getheader(url, params=params, headers=headers, ckey=ckey(), cert=cert())
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 324, in getheader
    header, _ = self.request(url, params, headers, verb,
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 306, in request
    raise exc
http.client.HTTPException: url=https://cmsrucio-auth-int.cern.ch/auth/x509, code=401, reason=Unauthorized, headers={'Date': 'Fri, 04 Jun 2021 16:07:57 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.7.1 Python/3.6', 'Access-Control-Allow-Origin': 'None', 'Access-Control-Allow-Headers': 'None', 'Access-Control-Allow-Methods': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Expose-Headers': 'X-Rucio-Auth-Token', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, post-check=0, pre-check=0', 'Pragma': 'no-cache', 'ExceptionClass': 'CannotAuthenticate', 'ExceptionMessage': 'Cannot get DN', 'X-Rucio-Host': 'cmsrucio-auth-int.cern.ch', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/octet-stream'}
-------------------- >> begin captured logging << --------------------
root: INFO: Requesting a token to Rucio for account: wma_test, against url: https://cmsrucio-auth-int.cern.ch
--------------------- >> end captured logging << ---------------------

```

**Review by amaltaro — APPROVED** [review]
Code looks pretty good to me, Todor. Unless you have more work to put into this PR (from the "Work in progress" label), once you squash these commits, it's ready to go.

Do not worry about the Rucio and PycurlRucio unit tests, I will get them fixed via https://github.com/dmwm/WMCore/issues/10469

**Comment by todor-ivanov** [comment]
Thanks @amaltaro, all done now. You may merge it.

**Comment by amaltaro** [comment]
Thanks Todor.

**Pull request merged**
