### PR TITLE
fix unicode encoding failure

### LINKED ISSUE #8403: Another unicode encoding failure
It is in

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Execute.py#L70

output contains "\x95" which cause encoding error
  
and

'utf8' codec can't decode byte 0xb2 in position 24451

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8403

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan, please review.

**Comment by amaltaro** [comment]
We "fixed" it so many times that I don't even know whether it's right or not anymore :P
Seangchan, did you actually run this code against that bad FWJR? Just to make sure this fix really fixes that issue.

If you have that example handy, could you check the performance impact on decoding that string 10k times, for instance. Just to avoid making JobAccountant even fattier.

**Comment by ticoann** [comment]
Hi Alan, I check the one document, but not performance test.
However if you are concerning about the performance, the cheapest option is the temporary fix we had. https://github.com/dmwm/WMCore/pull/8404 since that only does when error occurs.

**Comment by ticoann** [comment]
One thing more concerning is this not Python3 compatible.

**Review by amaltaro — APPROVED** [review]
In this case, thumbs up! 
About python3, it passed the checks. Why you say it's not compatible?

**Comment by ticoann** [comment]
> About python3, it passed the checks. Why you say it's not compatible?

I don think python3 string type has decode method. (I might be wrong though)

https://docs.python.org/3/library/stdtypes.html#string-methods

**Comment by amaltaro** [comment]
Hmm, good point. Should we then chase the source of this problem and have a fix py3 compatible? It must be coming from one of the log files in the worker node, so if we can open/parse those logs following the latest attempt, that would be better. If it takes too long, we just merge this one then.

PS.: What surprises me is that it hasn't happened in any of the production nodes...

**Pull request merged**
