### PR TITLE
Log workflows going through DeterministicPileup job creation

### PR DESCRIPTION
**Pull request by amaltaro**

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Should we make following in unstable list?

WMCore_t.WorkerThreads_t.WorkerThreads_t.WorkerThreadsTest:testWorkerError changed from success to failure

**Comment by ticoann** [comment]
FYI. this is the error.

 File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/5/label/cms-dmwm-cc7/deploy/1.1.8.pre6/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/5/label/cms-dmwm-cc7/code/test/python/WMCore_t/WorkerThreads_t/WorkerThreads_t.py", line 221, in testWorkerError
    self.assertEqual(manager.activeThreadCount, 0)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/5/label/cms-dmwm-cc7/deploy/1.1.8.pre6/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/5/label/cms-dmwm-cc7/deploy/1.1.8.pre6/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
'1 != 0

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann it has been backported already to 1.1.8, but please review even if it's already merged :)

**Pull request merged**
