### PR TITLE
Add new filter by campaign; re-factor code to match common name patterns for sorting/filter functions; add changes to templates

### LINKED ISSUE #7704: Add search filter for Campaign on approved page in reqmgr2 GUI
@fabozzi, do you need exact matching or substring matching or wild card for this field?

### PR DESCRIPTION
**Pull request by vkuznet**
fixes #7704

### CODE REVIEW

**Comment by ticoann** [comment]
Thanks Valentin, I will run the test.

**Comment by ticoann** [comment]
Valentin, There is a couple of errors.

https://reqmgr2-dev.cern.ch/reqmgr2/approve

Campaign is not showing (next to Group).
Data is not populated when page is initially updated. Only after click the sort option.

**Comment by vkuznet** [comment]
Seangchan,
could you please re-apply the PR, I added few more changes which I missed
originally. This time campaign will show up along with default page loading.

And, I need you to inject data with different campaigns such that we'll test
the filter.

Thanks,
Valentin.

**Comment by ticoann** [comment]
Thanks Valentin, But search still doesn't work. I added new campaign name. 
https://reqmgr2-dev.cern.ch/reqmgr2/approve

**Comment by vkuznet** [comment]
Seangchan,
could you please apply PR again and re-deploy, it seems like I forgot to change
the filter name and campaign search didn't work.
Let me know, when it's ready.
Thanks,
Valentin.

**Comment by ticoann** [comment]
Thank Valentin, Now it works fine. Could you squash the commit?

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Instead of Filter by pattern..., Could you change to Filter by request name?

**Comment by vkuznet** [comment]
Seangchan,
what's the point? The pattern is more flexible. I don't mind to change it but I
think pattern is more interesting from end-user point of view.
Best,
Valentin.

**Comment by ticoann** [comment]
Valentin, pattern is against request name field right? no other properties, correct? 
I think it is more clear to specify which fields they are searching it for. so first box is search against request name and second box is search against campaign.

**Comment by vkuznet** [comment]
> Valentin, pattern is against request name field right? no other properties, correct? 
yes

> I think it is more clear to specify which fields they are searching it for. so first box is search against request name and second box is search against campaign.

ahh, I think you want to change text in red within search field, e.g.

replace

Filter by pattern ...

change to

Filter by request name

while Filter by campaign is a right text, Filter by campaign, and it does
search Campaign field of request but it does that by pattern.

So, I changed PR, please take it and redeploy and let me know if you're
satisfied.

**Comment by ticoann** [comment]
> ahh, I think you want to change text in red within search field, e.g.

Sorry I wasn't clear. Yes I just want to change in the display in the text box.

**Comment by ticoann** [comment]
It looks good to me Valentin, Once it gets in testbed next well. I will ask @fabozzi to check.
When you squash the commit, I will merge that. Thank you very much.

**Comment by ticoann** [comment]
FYI @fabozzi, this is the added search campaign field

screen shot 2017-03-15 at 11 19 08 am

**Comment by vkuznet** [comment]
Done, squashed.

**Comment by ticoann** [comment]
Unittest failure doesn't seem to be related. Will investigate separately.

**Pull request merged**
