### PR TITLE
report the correct dashboard activity from Tier0, fixes #7256

### LINKED ISSUE #7256: Set T0 workflows activity to "t0"
As mentioned here #7253
Several dashboard activities are mapped to `t0`. So we should update it from `tier0` to `t0` in the T0 specs here and in the T0 repository as well. No hurry though

### PR DESCRIPTION
**Pull request by hufnagel**
Fixes #7256
There is also an updateArguments call from Tier0 code when the workflow is created.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
Is "tier0" is not the correct dashboard activity? I thought that was, not "t0".

**Comment by ticoann** [comment]
Due to following code. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1633

Activity will be overwritten with default value "production". I think it might be better to set the default value for Repack, Express, PromptReco to "t0".

**Comment by hufnagel** [comment]
No, it'll be overwritten with t0.

https://github.com/dmwm/T0/blob/master/src/python/T0/RunConfig/RunConfigAPI.py#L676

**Comment by hufnagel** [comment]
That's what Alan suggested. If there is a way to change the spec so it's default is t0 and I don't need to overwrite I'll take that though, makes the code a bit easier to manage. These specs are Tier0 specific.

**Pull request merged**
