### PR TITLE
WMAgent should use dictionary for reporting. Fixes #6931

### LINKED ISSUE #6931: Failing to upload workflow/task metadata to dashboard
Creating this issue before I forget it. It seems dashboard report is failing at least at two different level:
1. when uploading the task metadata, from central services (reqmgr), see logs from my VM:
```
Creating ApMon with static configuration
Mon Jun 13 21:41:23 2016: ApMon[ERROR]: Cannot open cms-wmagent-job.cern.ch:8884
Mon Jun 13 21:41:23 2016: ApMon[ERROR]: IOError: [Errno 2] No such file or directory: 'cms-wmagent-job.cern.ch:8884'
Mon Jun 13 21:41:23 2016: ApMon[WARNING]: Not sending parameters since no destination is defined.
Mon Jun 13 21:41:24 2016: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
```
2. from the worker node (likely when the job/step is completing), see more logs from the WN:
```
WMAgent bootstrap : Mon Jun 13 20:55:39 UTC 2016 : WMAgent is now running the job...
Startup.py : 2016-06-13T22:55:39 : loading job definition
Startup.py : 2016-06-13T22:55:39 : loading task
Startup.py : 2016-06-13T22:55:39 : setting up monitoring
Startup.py : 2016-06-13T22:55:39 : setting up logging
Startup.py : 2016-06-13T22:55:39 : building task
CMSSW.coreBuild invoked
Builders.CMSSW.build called on cmsRun1
StageOut.coreBuild invoked
Builders.StageOut.build called on stageOut1
LogArchive.coreBuild invoked
Builders.LogArchive.build called on logArch1
Startup.py : 2016-06-13T22:55:39 : executing task
Creating ApMon with static configuration
Mon Jun 13 22:55:39 2016: ApMon[ERROR]: Cannot open cms-wmagent-job.cern.ch:8884
Mon Jun 13 22:55:39 2016: ApMon[ERROR]: IOError: [Errno 2] No such file or directory: 'cms-wmagent-job.cern.ch:8884'
Mon Jun 13 22:55:39 2016: ApMon[WARNING]: Not sending parameters since no destination is defined.
Mon Jun 13 22:55:39 2016: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
Creating ApMon with static configuration
Mon Jun 13 22:55:39 2016: ApMon[ERROR]: Cannot open cms-wmagent-job.cern.ch:8884
Mon Jun 13 22:55:39 2016: ApMon[ERROR]: IOError: [Errno 2] No such file or directory: 'cms-wmagent-job.cern.ch:8884'
Mon Jun 13 22:55:39 2016: ApMon[WARNING]: Not sending parameters since no destination is defined.
Mon Jun 13 22:55:39 2016: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
Creating ApMon with static configuration
Mon Jun 13 22:55:39 2016: ApMon[ERROR]: Cannot open cms-wmagent-job.cern.ch:8884
Mon Jun 13 22:55:39 2016: ApMon[ERROR]: IOError: [Errno 2] No such file or directory: 'cms-wmagent-job.cern.ch:8884'
Mon Jun 13 22:55:39 2016: ApMon[WARNING]: Not sending parameters since no destination is defined.
Mon Jun 13 22:55:39 2016: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
Creating ApMon with static configuration
Mon Jun 13 22:56:12 2016: ApMon[ERROR]: Cannot open cms-wmagent-job.cern.ch:8884
Mon Jun 13 22:56:12 2016: ApMon[ERROR]: IOError: [Errno 2] No such file or directory: 'cms-wmagent-job.cern.ch:8884'
Mon Jun 13 22:56:12 2016: ApMon[WARNING]: Not sending parameters since no destination is defined.
Mon Jun 13 22:56:12 2016: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
StageOutMgr::__init__()
```

For completion, this is what I see in the condor.JOBID.err log file (seems to be succeeding):
```
INFO:root:Initializing monitor DashboardMonitor
INFO:root:In DashboardMonitor.initMonitor
INFO:root:About to set destination to cms-wmagent-job.cern.ch:8884
INFO:root:Initializing monitor PerformanceMonitor
INFO:root:MonitorThread: JobStarted
INFO:root:About to send UDP package to dashboard: {'StatusDestination': 'T1_US_FNAL_Disk', 'StatusEnterTime': '2016-06-13 20:43:52', 'MessageType': 'JobStatus', 'jobId': '1d0a2856-31a5-11e6-8384-02163e00f074-3_0', 'StatusValue': 'running', 'MessageTS': '2016-06-13 20:43:52', 'StatusValueReason': 'Job started execution in the WN', 'taskId': 'wmagent_amaltaro_MonteCarlo_Ext_Test_SeveralPRs_160613_214526_949', 'NCores': 1}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:About to send UDP package to dashboard: {'SyncCE': 'T1_US_FNAL_Disk', 'MessageType': 'jobRuntime-jobStart', 'jobId': '1d0a2856-31a5-11e6-8384-02163e00f074-3_0', 'MessageTS': '2016-06-13 20:43:52', 'taskId': 'wmagent_amaltaro_MonteCarlo_Ext_Test_SeveralPRs_160613_214526_949', 'GridName': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues/CN=724053508/CN=507630540/CN=1960800387/CN=1835498783/CN=2041772649\n', 'WNHostName': 'cmswn2025.fnal.gov', 'ExeStart': 'cmsRun1'}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:About to send UDP package to dashboard: {'1_stepName': 'cmsRun1', 'MessageType': 'jobRuntime-stepStart', 'jobId': '1d0a2856-31a5-11e6-8384-02163e00f074-3_0', 'MessageTS': '2016-06-13 20:43:52', 'taskId': 'wmagent_amaltaro_MonteCarlo_Ext_Test_SeveralPRs_160613_214526_949', '1_ExeStart': 'cmsRun1'}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:Pre-executing CMSSW step
```

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by amaltaro** [comment]
Can you also update the collector name here
https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L129
?

**Comment by juztas** [comment]
done

**Comment by amaltaro** [comment]
Thanks, Justas. I'm gonna test it now.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
It seems the situation improved on the reqmgr side, here is a piece of log:
```
Creating ApMon with static configuration
Wed Jun 15 21:10:59 2016: ApMon[INFO]: Adding destination 128.142.166.151:8884 
Wed Jun 15 21:10:59 2016: ApMon[DEBUG]: Overwritting option: sys_monitoring = 0
Wed Jun 15 21:10:59 2016: ApMon[DEBUG]: Overwritting option: general_info = 0
Wed Jun 15 21:10:59 2016: ApMon[DEBUG]: Overwritting option: job_monitoring = 0
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter datasetFull = DoesNotApply
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter tool = WMAgent
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter MessageType = TaskMeta
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter JobName = taskMeta
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter application = CMSSW_7_0_0_pre11
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter JSToolVersion = 1.0.17.pre6
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter TaskType = relval
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter CMSUser = cmsdataops
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Adding parameter TaskName = wmagent_amaltaro_TaskChain_MC_Test_SeveralPRs_160615_211057_3758
Wed Jun 15 21:10:59 2016: ApMon[DEBUG]: previously sent: 0; dropped: 0
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Building XDR packet [wmagent_amaltaro_TaskChain_MC_Test_SeveralPRs_160615_211057_3758/taskMeta] <1/1976947765> 9 params, 460 bytes.
Wed Jun 15 21:10:59 2016: ApMon[NOTICE]: Packet sent to 128.142.166.151:8884 
Wed Jun 15 21:11:00 2016: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
```

Justas, do you have any idea how we can check whether dashboard received this info?

**Comment by amaltaro** [comment]
And from the worker node:
```
2016-06-16 10:55:35,688:INFO:DashboardMonitor:In DashboardMonitor.initMonitor
2016-06-16 10:55:35,688:INFO:DashboardMonitor:About to set destination to cms-jobmon.cern.ch:8884
2016-06-16 10:55:35,688:INFO:Watchdog:Initializing monitor PerformanceMonitor
2016-06-16 10:55:35,691:INFO:Watchdog:MonitorThread: JobStarted
2016-06-16 10:55:35,700:INFO:DashboardInterface:About to send UDP package to dashboard: {'StatusDestination': 'T2_CH_CERN', 'StatusEnterTime': '2016-06-16 08:55:35', 'MessageType': 'JobStatus', 'jobId': 'ad5170d0-3390-11e6-bff6-02163e00f074-18_0', 'StatusValue': 'running', 'MessageTS': '2016-06-16 08:55:35', 'StatusValueReason': 'Job started execution in the WN', 'taskId': 'wmagent_amaltaro_MonteCarlo_LHE_Test_SeveralPRs_160615_210944_2153', 'NCores': 1}
2016-06-16 10:55:35,700:INFO:DashboardInterface:Using address ['cms-jobmon.cern.ch:8884']
2016-06-16 10:55:35,861:INFO:DashboardInterface:About to send UDP package to dashboard: {'SyncCE': 'T2_CH_CERN', 'MessageType': 'jobRuntime-jobStart', 'jobId': 'ad5170d0-3390-11e6-bff6-02163e00f074-18_0', 'MessageTS': '2016-06-16 08:55:35', 'taskId': 'wmagent_amaltaro_MonteCarlo_LHE_Test_SeveralPRs_160615_210944_2153', 'GridName': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues/CN=724053508/CN=507630540/CN=733681875/CN=759651836/CN=2064584578\n', 'WNHostName': 'b63290d0de.cern.ch', 'ExeStart': 'cmsRun1'}
2016-06-16 10:55:35,861:INFO:DashboardInterface:Using address ['cms-jobmon.cern.ch:8884']
2016-06-16 10:55:35,940:INFO:DashboardInterface:About to send UDP package to dashboard: {'1_stepName': 'cmsRun1', 'MessageType': 'jobRuntime-stepStart', 'jobId': 'ad5170d0-3390-11e6-bff6-02163e00f074-18_0', 'MessageTS': '2016-06-16 08:55:35', 'taskId': 'wmagent_amaltaro_MonteCarlo_LHE_Test_SeveralPRs_160615_210944_2153', '1_ExeStart': 'cmsRun1'}
2016-06-16 10:55:35,941:INFO:DashboardInterface:Using address ['cms-jobmon.cern.ch:8884']
2016-06-16 10:55:36,145:INFO:CMSSW:Pre-executing CMSSW step
```

I'll ping Eddie to see whether this info is all correct in dashboard.

**Comment by amaltaro** [comment]
Sorry for being so verbose :-) and the `stepEnd` and `jobEnd` seems to be properly sent as well:
```
2016-06-16 12:33:00,701:INFO:LogArchive:Steps.Executors.StageOut.post called
2016-06-16 12:33:00,703:INFO:DashboardInterface:About to send UDP package to dashboard: {'3_ExeEnd': 'logArch1', '3_ExeExitCode': 0, 'MessageType': 'jobRuntime-stepEnd', 'jobId': 'a3d32f30-3390-11e6-bff6-02163e00f074-4_2', '3_NCores': 1, 'MessageTS': '2016-06-16 10:33:00', 'taskId': 'wmagent_amaltaro_MonteCarlo_PhEDEx_Test_SeveralPRs_160615_211036_9852', '3_ExeWCTime': 1.3229570388793945}
2016-06-16 12:33:00,703:INFO:DashboardInterface:Using address ['cms-jobmon.cern.ch:8884']
2016-06-16 12:33:00,814:INFO:Watchdog:MonitorThread: JobEnded
2016-06-16 12:33:00,814:INFO:DashboardInterface:About to send UDP package to dashboard: {'JobExitReason': 'Job completed execution in the WN', 'ExeEnd': 'logArch1', 'WrapperCPUTime': 7.57685, 'MessageType': 'jobRuntime-jobEnd', 'jobId': 'a3d32f30-3390-11e6-bff6-02163e00f074-4_2', 'WrapperWCTime': 3442.6943531036377, 'MessageTS': '2016-06-16 10:33:00', 'JobExitCode': 0, 'taskId': 'wmagent_amaltaro_MonteCarlo_PhEDEx_Test_SeveralPRs_160615_211036_9852', 'NCores': 1}
2016-06-16 12:33:00,814:INFO:DashboardInterface:Using address ['cms-jobmon.cern.ch:8884']
2016-06-16 12:33:00,952:INFO:Watchdog:MonitorState: Shutdown called
```

@juztas @ericvaandering let me know if you see something unexpected/weird on these reports.

**Comment by amaltaro** [comment]
I noticed JobAccountant component was getting stuck since I put this fix in place. It only happens when a job has > 1 step.

It seems we need to free the apmon (close the sockets) in between each data that is sent to dashboard.
@juztas can you move this line https://github.com/dmwm/WMCore/blob/7cda7bc5c76158790bf8e3912c5ec4332da52541/src/python/WMCore/Services/Dashboard/DashboardReporter.py#L226 inside the `for stepName in steps:` please?

Eventually we should rework it, to be able to send data in bulk and also get rid of all those messy global variables, but ...

**Comment by amaltaro** [comment]
@juztas ping

**Comment by amaltaro** [comment]
A new PR was created, thanks Justas!

**Pull request closed without merging**
