### PR TITLE
Fixes misindented lines in the PhEDExInjectorPoller

### PR DESCRIPTION
**Pull request by johnhcasallasl**
Please review @hufnagel

### CODE REVIEW

**Comment by ticoann** [comment]
patch looks good to me. (I am not sure why this bug wasn't found earlier)

**Comment by ticoann** [comment]
test this please

**Comment by hufnagel** [comment]
Looks good to me too.

**Comment by ericvaandering** [comment]
I think John is not in our teams which is why Jenkins asked this.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Nov 20, 2016, at 08:04, DMWM Jenkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Can one of the admins verify this patch?

-

**Pull request merged**
