### PR TITLE
Encode query args for TagCollector

### PR DESCRIPTION
**Pull request by amaltaro**
I'm really sorry about that sick PR #7576 . It was so simple that I left the testing for testbed :(
We must encode the query strings otherwise the `anyarch` is not "seen" in the get request.

Waiting for the unittestt to come back. But this time it was tested in my VM.

### CODE REVIEW

**Comment by ticoann** [comment]
Sorry Alan, when I tested yesterday. I couldn't catch this problem. I think I already have cached data in and I didn't check the log for failure. Sorry about that.

**Comment by amaltaro** [comment]
The unittest should catch this problem now :-) BTW, here is the deployment change:
https://github.com/dmwm/deployment/pull/436

Seangchan, I'm just waiting for jenkins to finish. Once that comes green, I'll merge it, cut a pre10 tag and make the cmsdist PR not to make Bruno/Lina waiting for too long.

**Comment by amaltaro** [comment]
Merging it to cut the new tag.

**Comment by amaltaro** [comment]
I'm glad the tagcollector unittest didn't fail :-)

**Pull request merged**
