### PR TITLE
return exit code in Start.py

### LINKED ISSUE #8422: WMAgent wrapper script exits non-zero if the last step in the job fails
That is, exit non-zero in the case where the last CMSSW fails (but stageout succeeds) or stageout of non-logfile job outputs fails (and CMSSW succeeds).
 Effectively, anything that would trigger a retry in the agent.

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8422

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@amaltaro, Alan please review

**Review by amaltaro — APPROVED** [review]
Code seems to be correct. However it's better to get some tests done first to make sure we are not missing anything (new label created for that).

**Comment by amaltaro** [comment]
@ticoann I ran a test with a known to be problematic workflow and this is what we see in the job wrapper of the original code:
```
======== WMAgent final job runtime checks STARTING at Tue Jul 10 13:45:48 GMT 2018 ========
Tue Jul 10 13:45:48 GMT 2018: Job Runtime in seconds:  834
Tue Jul 10 13:45:48 GMT 2018: Job bootstrap script exited:  0
Tue Jul 10 13:45:48 GMT 2018: Job execution exited:  0
======== WMAgent final job runtime checks FINISHED at Tue Jul 10 13:45:48 GMT 2018 ========
```

While the code patched with this fix yields
```
======== WMAgent final job runtime checks STARTING at Mon Jul 16 12:57:58 GMT 2018 ========
Mon Jul 16 12:57:58 GMT 2018: Job Runtime in seconds:  372
Mon Jul 16 12:57:58 GMT 2018: Job bootstrap script exited:  0
Mon Jul 16 12:57:58 GMT 2018: Job execution exited:  92
======== WMAgent final job runtime checks FINISHED at Mon Jul 16 12:57:58 GMT 2018 ========

2018-07-16 12:57:58,544:INFO:DashboardInterface:About to send UDP package to dashboard: {'JobExitReason': 'Step cmsRun1 failed in the WN', 'ExeEnd': 'logArch1', 'WrapperCPUTime': 0.0, 'MessageType': 'jobRuntime-jobEnd', 'jobId': '5e39aa31-76e9-4382-baca-48608410fa8d-0_0', 'WrapperWCTime': 370.6609778404236, 'MessageTS': '2018-07-16 12:57:58', 'JobExitCode': 92, 'taskId': 'wmagent_amaltaro_ReDigi_AllFlag_Agent1114_Validation_180716_143509_4739', 'NCores': 1}
```

so I think that's what we wanted. The only last bit is to exit the job wrapper with the same exit code returned from the job itself (unless I missed something), for that see #8683

**Comment by ticoann** [comment]
Thanks Alan for testing. I combined your patch here incase we need to create the patch for production agent.

**Pull request merged**
