### PR TITLE
Clear all occurrences of the typo: 'ouput -> output'

### LINKED ISSUE #9390: Typo in FJR attribute name
**Impact of the bug**
WMAgent/CRAB

**Describe the bug**
As mentioned on this commit:
https://github.com/dmwm/CRABServer/commit/a647fa3eb5d728d53f502646bdfc2d582b2abe8e

WMCore is setting, there is a typo in WMCore where the file attr `output_module_class` is set as `ouput_module_class`

**How to reproduce it**
None

**Expected behavior**
We should rename the attribute to `output_module_class`, here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L96

and fix whatever unit tests need to be fixed.

**Additional context and error message**
none

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #9390 

#### Status
not-tested

#### Description
Fixing some typos

#### Is it backward compatible (if not, which system it affects?)
YES 

#### Related PRs
NO

#### External dependencies / deployment changes
Does it require deployment changes? -  Requires test deployment for CRAB{Server/TW}
Does it rely on third-party libraries? - NO

### CODE REVIEW

**Comment by amaltaro** [comment]
@todor-ivanov did you manage to run a quick test for this (patch your WMAgent and run a couple of workflows, just to be on the safe side)?

**Comment by amaltaro** [comment]
test this please

**Comment by todor-ivanov** [comment]
test this please

**Comment by todor-ivanov** [comment]
@amaltaro I managed to run few test workflows and they were successful. I think we may go now and merge this.

**Review by amaltaro — APPROVED** [review]
Changes look good to me. Thanks!

**Pull request merged**
