### PR TITLE
Change the way to move to normal archived status - wmagent version

### PR DESCRIPTION
**Pull request by ticoann**
related #7693. When cmsweb April production upgrades happens, this patch need to be applied in production agent.  

@amaltaro, Alan, please review

### CODE REVIEW

**Comment by amaltaro** [comment]
Seangchan, just to be clear, can you rename this PR to something like
"Change the way to move to normal archived status - wmagent version"
such that we know - by the title - what the PR is about :-)

**Review by amaltaro — APPROVED** [review]
Besides the gazilion pylint fixes in the same commit, patch looks fine.

**Comment by ticoann** [comment]
Oh shoot, I set up something and it automatically fix the pylint. I will revert back pylint fix. There is no reason to fix this in the branch and might cause the problem of applying other patch.

**Comment by ticoann** [comment]
Now it is cleaner. 😄

**Comment by amaltaro** [comment]
Much better! Thanks ;)

**Comment by amaltaro** [comment]
@ticoann please merge. The production agents were patched.

**Comment by amaltaro** [comment]
[Fix #7724 - Change the way to move to normal archived status - wmagent version](https://trello.com/c/hiCVTTd0/20-fix-7724-change-the-way-to-move-to-normal-archived-status-wmagent-version)

**Pull request merged**
