### PR TITLE
Fix regexp pattern to match HTTP/1.1 and HTTP/2

### LINKED ISSUE #11399: pycurl_manager should properly parse HTTP/2 HTTP reponses
**Impact of the bug**
Current version of pucurl only able to parse HTTP/1.1 responses, while HTTP standard support HTTP/1, HTTP/1.1, and HTTP/2

**Describe the bug**
pycurl_manager parses HTTP response via regexp, see
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/pycurl_manager.py#L103-L105
and the following pattern is wrong:
```
>>> import re
>>> row="HTTP/2 200"
>>> startRegex = r"^HTTP/\d.\d \d{3}"
>>> re.search(startRegex, row)
```

**How to reproduce it**
```
>>> import re
>>> row="HTTP/2 200"
>>> startRegex = r"^HTTP/\d.\d \d{3}"
>>> re.search(startRegex, row)
```

**Expected behavior**
The fix should include ability to properly parse HTTP/1.1 and HTTP/2 HTTP responses, e.g.
```
>>> startRegex = r"^HTTP/(\d|\d.\d) \d{3}"
>>> re.search(startRegex, "HTTP/1.1 200")
<re.Match object; span=(0, 12), match='HTTP/1.1 200'>
>>> re.search(startRegex, "HTTP/2 200")
<re.Match object; span=(0, 10), match='HTTP/2 200'>
```

**Additional context and error message**
This is the reason why reqmgr2-tasks pod is failing on k8s using pypi deployment.

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #11399 

#### Status
ready

#### Description
fix regexp pattern to properly match "HTTP/1.1 200" and "HTTP/2 200" responses

#### Is it backward compatible (if not, which system it affects?)
YES

### CODE REVIEW

**Review by todor-ivanov — APPROVED** [review]
Looks good to me

**Review by amaltaro — CHANGES_REQUESTED** [review]
@vkuznet can you please provide a unit test for this:
https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/Services_t/pycurl_manager_t.py

? Such that we can avoid similar problems in the future.

**Comment by vkuznet** [comment]
I made additional changes as it turns out the parsing code was broken too. I added proper unit test too. Please review.

**Review by amaltaro — APPROVED** [review]
Thanks Valentin, it looks good to me.

**Pull request merged**
