### PR TITLE
remove WMBSService from WMCore and WMAgent

### PR DESCRIPTION
**Pull request by ticoann**
Need to test. Also need to remove "WMBS_SERVICE_PORT" from T0/manage wmagent/manage script

### CODE REVIEW

**Comment by ticoann** [comment]
@emaszs, Emilis, crabserver doesn't need HTTPFrontEnd dependency anymore, right? I couldn't find the code using that.

https://github.com/dmwm/WMCore/pull/7735/files#diff-d073738f4bf39da0585f5bb9c5f499efL115

**Comment by ticoann** [comment]
@hufnagel,  do you need to get proxy from WMBSService config?

https://github.com/dmwm/T0/blob/d7b772a7425e06870f775f2bfb482bafed7d7bde/test/python/T0_t/WMBS_t/RunConfig_t/RunConfig_t.py#L53

**Comment by hufnagel** [comment]
Latest Tier0 release has a patch that removes WMBSService from the agent configuration. We don't need it.

**Comment by emaszs** [comment]
@ticoann Yeah, looks like we don't use it in CRAB anymore now that we've switched to the TagCollector service.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
