### PR TITLE
dbs api change listFiles -> listFileArray

### LINKED ISSUE #5698: change listFiles to listFileArray for dbs api in WMCore.

### PR DESCRIPTION
**Pull request by ticoann**
fixes #5698 (using new api for long list of input in general) There is limit for the uri length in get call.
listFileArray uses POST call

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, @yuyiguo, please review

**Comment by amaltaro** [comment]
Looks good to me. I was grepping the code to look for leftovers and I found these 2:
src/python/WMComponent/DBSUpload/DBSInterface.py
src/python/WMCore/WMBSFeeder/PhEDExNotifier/PhEDExNotifierComponent.py

AFAIK the first one is not used anywhere. The latter I have no idea :-)

**Comment by ticoann** [comment]
Latter is not used either. Unless someone else is using it outside the WMAgent. We will find out. :smile:

**Comment by ticoann** [comment]
Revert https://github.com/dmwm/WMCore/pull/5692 before merge this.

**Pull request merged**
