### PR TITLE
Comment out workunit code and tests

### PR DESCRIPTION
**Pull request by ericvaandering**
A pull request to turn off the work unit to job association that seems somewhat problematic.

### CODE REVIEW

**Comment by amaltaro** [comment]
Should we backport it to 1.1.6_wmagent branch? @ticoann

**Comment by ericvaandering** [comment]
I thought this stuff wasn't in that branch. This is a placeholder in the (likely) case we don't fix the underlying problem before I leave. :-)

**Comment by ticoann** [comment]
Yes workunit code change is not in wmagent branch

**Comment by amaltaro** [comment]
@ticoann I guess we'll have to merge it today such that we can cut the new wmagent release candidate tag.

**Pull request merged**
