### PR TITLE
Updates in wmcore for CRAB3

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by ticoann** [comment]
Thank you very much Marco, I included your DBS fix in #6463.
For pycurl fix we already have patch #6360 but integration test is not done. I will try to merge those as soon as integration test is done.  Could you check whether that fetch fixes the problem you have?

**Comment by amaltaro** [comment]
@mmascher @ticoann how about we follow up the pycurl changes in #6360 (after cmsweb production upgrade) and close this one?

**Comment by amaltaro** [comment]
@mmascher @ticoann how about we follow up the pycurl changes in #6360 (after cmsweb production upgrade) and close this one?

**Comment by mmascher** [comment]
Hi @amaltaro , here is the PR https://github.com/dmwm/WMCore/pull/6916

**Pull request closed without merging**
