### PR TITLE
Fix a some WMBSHelper unit tests - SE to PNN transition

### PR DESCRIPTION
**Pull request by amaltaro**
Fix at least 2 tests that fail since we merged this PR #6365

@ericvaandering @jha2 please review. I'm not sure this is the correct way...

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
Which unit tests? You're actually editing the old SiteDB emulator to get these to pass, which is OK, but we are trying to get rid of that one.

**Comment by amaltaro** [comment]
It was meant to fix these 2
```
WMCore_t.WorkQueue_t.WMBSHelper_t.WMBSHelperTest:testDuplicateSubscription changed from error to success
WMCore_t.WorkQueue_t.WMBSHelper_t.WMBSHelperTest:testMCFakeFileInjection changed from error to success
```
but it seems I got several others for free... beers are accepted ;-)

**Comment by ticoann** [comment]
Thanks Alan, I thing we should merge this one first even though eventually will change to use sitedb mock. What do you think?

**Comment by ericvaandering** [comment]
Yes, I agree

**Comment by amaltaro** [comment]
Thanks!

**Comment by jha2** [comment]
Alan, this is concerning the pull request #7017 . Here, I also added the meta data for fake sites like 'T2_XX_SiteB'.  The meta data are different for the pull request #7005 and #7017.  The type of meta data depends on the service (or call)  which we want to test.

**Pull request merged**
