### PR TITLE
remove properties with empty string

### LINKED ISSUE #7284: ReqMgr2: default assignment value for AutoApproveSubscriptionSites
I've just hit an issue on the agent side while going through an ACDC workflow that had subscriptions settings and changed during UI assignment in ReqMgr2. WorkQueue is failing to process it [1]

@ticoann I think the reason it's failing is because we set the default value to empty string:
https://github.com/dmwm/WMCore/pull/7254/files#diff-4129fdb6f4ac8568d6ac3fa9cb51f010R101

in case no sites are selected, which then fails in the lambda function.

Would you have a better than creating a specific default value for this case?

[1]
2016-10-12 10:49:08,593:140631694944000:INFO:WorkQueue:Adding WMBS subscription for amaltaro_ACDC_MonteCarlo_Ext_Agent1021_Validation_161011_133611_1649
2016-10-12 10:49:08,614:140631694944000:INFO:WMBSHelper:Top level subscription created: 1543
2016-10-12 10:49:08,642:140631694944000:INFO:WMBSHelper:Child subscription created: 1544
2016-10-12 10:49:08,721:140631694944000:INFO:WMBSHelper:Child subscription created: 1545
2016-10-12 10:49:08,772:140631694944000:INFO:WMBSHelper:Child subscription created: 1546
2016-10-12 10:49:08,791:140631694944000:INFO:WMBSHelper:Child subscription created: 1547
2016-10-12 10:49:08,811:140631694944000:ERROR:WMBSHelper:Failed to create subscription Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 406, in createSubscriptionAndAddFiles
    sub = self.createSubscription(self.topLevelTask, self.topLevelFileset)
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 264, in createSubscription
    self._createDatasetSubscriptionsInDBSBuffer()
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 497, in _createDatasetSubscriptionsInDBSBuffer
    subInfo = self.wmSpec.getSubscriptionInformation()
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1297, in getSubscriptionInformation
    taskSubInfo = self.getSubscriptionInformation(task)
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1305, in getSubscriptionInformation
    subInfo[dataset]["AutoApproveSites"])
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1280, in <lambda>
    extendWithoutDups = lambda x, y: x + list(set(y) - set(x))
TypeError: cannot concatenate 'str' and 'list' objects

2016-10-12 10:49:08,812:140631694944000:ERROR:WorkQueue:amaltaro_ACDC_MonteCarlo_Ext_Agent1021_Validation_161011_133611_1649, /acdc/amaltaro_ACDC_MonteCarlo_Ext_Agent1021_Validation_161011_133611_1649/:amaltaro_MonteCarlo_Ext_Agent1021_Validation_161008_105904_7030:Production/0/1: 
creating subscription failed in LQ: 
cannot concatenate 'str' and 'list' objects

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7284, Alan please review.

### CODE REVIEW

**Comment by amaltaro** [comment]
That will fix the issue. But allow me to have a look and test this code first:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkloadTools.py#L160

this is where the correct value should be reassigned to that key.

**Comment by amaltaro** [comment]
Hmm, it seems we missed this PR.

**Comment by ticoann** [comment]
@amaltaro, Alan this can be just closed, #7374 handles this already, right?

**Comment by amaltaro** [comment]
In theory it doesn't solve exactly the same issue. However, it did solve the problems we had with UI interactions :-) So I think we can just close it.

**Pull request closed without merging**
