### PR TITLE
Add loggin of incoming requests to RESTModel end-points - dbs version

### PR DESCRIPTION
**Pull request by amaltaro**
1.1.16_dbs branch version of #9124

### CODE REVIEW

**Comment by amaltaro** [comment]
@yuyiguo please check whether this is what you need. If so, I'll merge and cut a 1.1.16.dbs1 tag for you.

**Comment by yuyiguo** [comment]
@amaltaro It looked good to me. Please merge and cut the tag.

**Comment by amaltaro** [comment]
Alright! You can find this fix in the tag `1.1.16.dbs1`

**Comment by yuyiguo** [comment]
@amaltaro 
Thanks a lot, Alan.

**Pull request merged**
