### PR TITLE
Fix regex support

### PR DESCRIPTION
**Pull request by HassenRiahi**
Pls review. It fixes the support of regex. that matches more that 1 pattern.

### CODE REVIEW

**Comment by ericvaandering** [comment]
Can you give an example of what the problem is? I wonder if this is the thing that Tony was complaining about that WMAgent didn't really do things correctly.

You should also provide a new unit test that fails with the current code and succeeds now.

**Comment by HassenRiahi** [comment]
Here is an example: https://cmsweb.cern.ch/phedex/datasvc/xml/prod/tfc?node=T2_CH_CERNBOX

I will provide a new unit test.

**Comment by ericvaandering** [comment]
So I guess what this is doing (from your example) is mapping /store/user/ewv/ to /local/dir/e/ewv and /store/user/hassen to /local/dir/h/hassen ?

**Comment by HassenRiahi** [comment]
Yup!

**Comment by mmascher** [comment]
I have a general comment. We all know that we have two implementations of the LFN<=>PFN conversion in CMS: one that is in Perl in phedex (lfn2pfn API), and one in python here in WMCore. Unfortunately we do not have anything that checks that the two are the same, and I know for sure that on some particular iinput the two were not returning the same result.

I think it would be nice to have a unit test that takes some lfn that are used in WMCore and CRAB3, all the sites, and checks that the phedex lfn2pfn API, and the WMCore API return the same information.

**Comment by HassenRiahi** [comment]
The algo. is adjusted. I tested it over all CMS TFCs and it provides the same results as the current code for LFN ---> PFN convesion. A new unit test has been included as well.

**Comment by ericvaandering** [comment]
Did you mention that you had some LFNs that initial failed in your new code? Can you put those in as unit tests too (same test is OK) so that we prevent easy regressions?

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
You should definitely fix the indentation issue in TrivialCatalog

**Comment by mmascher** [comment]
Also @HassenRiahi , can you make a pull request to the branch 1.0.12_crab of WMCore as well please? That's the branch we are going to use for the February release. The patch should have the title "1.0.12_crab version of Fix regex support"

**Comment by HassenRiahi** [comment]
Patch updated. Pls @ericvaandering review.  
Ok @mmascher once we agree on this pull I will make another one against the branch.

**Comment by ericvaandering** [comment]
Looks OK to me.

**Pull request merged**
