### PR TITLE
Fix 404 error message when request cannot be found

### PR DESCRIPTION
**Pull request by amaltaro**
I've been seeing central workqueue error messages like

```
2016-09-15 02:05:02,651 INFO     WorkQueueReqMgrInterface: Checking Request Manager for open requests and closing old ones
2016-09-15 02:05:18,361 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb.cern.ch/-6294466533491977500_PUT_request does not exist and the service at https://cmsweb.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 404 because Not Found
 with result: {"exception": 404, "message": "Given requestName not found", "type": "HTTPError"}

2016-09-15 02:05:23,127 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb.cern.ch/-7783241445259924149_PUT_request does not exist and the service at https://cmsweb.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 404 because Not Found
 with result: {"exception": 404, "message": "Given requestName not found", "type": "HTTPError"}
```

which are not helpful at all :) 
I updated the error message and also removed some duplicate code.

I still have to test it.

### CODE REVIEW

**Comment by amaltaro** [comment]
I had to fix again imports for ChangeState and GetRequest. I don't understand what happens, but I cannot import only a couple of functions from each others file. The second commit should work just fine IMO, but it complains with e.g.:
`ImportError: cannot import name getProgress`

And in the 3rd commit, if I import "...ChangeState as ChangeState", then it complains with
`AttributeError: 'module' object has no attribute 'ChangeState'`

@ericvaandering @ticoann maybe you guys can see something stupid that I'm trying to do?

With the current patch I can start reqmgr, though pylint complains about 
`E: 67,14: Undefined variable 'ChangeState' (undefined-variable)`
:(

**Comment by ericvaandering** [comment]
Looks like you figured it out

**Comment by amaltaro** [comment]
Nope! :-(
However, I'm making other changes right now.

**Comment by amaltaro** [comment]
Ok, some reorganization and it works now :)

**Comment by amaltaro** [comment]
@ticoann please review and merge. Already tested it in my VM and everything looks good.

**Comment by amaltaro** [comment]
Well, I didn't manage to replicate the same failure, but nothing breaks :)

**Pull request merged**
