### PR TITLE
Add timer context manager

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ericvaandering** [comment]
@ticoann please merge (unless we have this kind of thing already)

**Comment by ticoann** [comment]
@ericvaandering, Are we keeping the default precision? It seems default is 1/10000. I was wondering we just keep 1/100 sec?

**Comment by amaltaro** [comment]
We have this function/decorator already:
https://github.com/dmwm/WMCore/blob/master/src/python/Utils/Utilities.py#L65

**Comment by ericvaandering** [comment]
@ticoann it uses whatever is the base timer. I like the high precision since I was timing some stuff that was well under 1/100th of a second.

@amaltaro this kind of proves my point about Utils/Utilities. I want to keep the context manager as well as the decorator, but I'll do a little refactoring to pull them together into one file. I also don't like the name "timeit" since that's the name of a python library as well.

**Comment by amaltaro** [comment]
Which point? That it has all sorts of utils? Yes, timeit was a bad choice indeed.

**Comment by ericvaandering** [comment]
@amaltaro what do you think now?

**Comment by ericvaandering** [comment]
That Utils/Utilities is a grab bag of unrelated stuff. :-)

**Review by amaltaro — APPROVED** [review]
Looks good, thanks!

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
That failing test is a newly unstable test. This is ready to merge.

**Comment by ticoann** [comment]
OK, thanks. It doesn't seems to be related but just make sure.

**Pull request merged**
