### PR TITLE
Bundle of patches for WMAgent 1.4.1.patch4

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch version of a bunch of patches:
* Use list_replication_rules Rucio API to list rules #9963 
* If listDataRules API fail, raise a WMRucioException #9999 
* Delete blocks using container-block mapping #9959 
* Deal with T0 output data subscription in RucioInjector #10006 
* Only add replicas if parent block has been properly added/attached into Rucio #10024

### CODE REVIEW

**Comment by amaltaro** [comment]
[Fix #10025 - Bundle of patches for WMAgent 1.4.1.patch4](https://trello.com/c/ZWEV62vE/230-fix-10025-bundle-of-patches-for-wmagent-141patch4)

**Comment by amaltaro** [comment]
FYI @todor-ivanov tag `1.4.1.patch4` has been created on top of this patch. There were lots of changes, so I will run some further basic tests in a clean patch4 agent before pushing these patches to our production nodes.

**Comment by amaltaro** [comment]
All the agents have been patched.

**Comment by todor-ivanov** [comment]
> FYI @todor-ivanov tag `1.4.1.patch4` has been created on top of this patch. 
Thanks @amaltaro

**Pull request merged**
