### PR TITLE
fix fwjr error string

### LINKED ISSUE #8056: JobAccountant crashing with undecoded bytes
Seeing repeat crashes on the JobAccountant on cmssrv237 -- attached (one hopes) is an exerpt of the log and the offending pkl file -- 

[JobAccountant.err.txt](https://github.com/dmwm/WMCore/files/1223271/JobAccountant.err.txt)
[Report.0.pkl.txt](https://github.com/dmwm/WMCore/files/1223273/Report.0.pkl.txt)

Tried removing that file to see if it moved on -- but crashed again...

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8056

### CODE REVIEW

**Comment by ticoann** [comment]
Not sure about Python3 compatibility

**Comment by ticoann** [comment]
@amaltaro, @ericvaandering, Please review

**Review by amaltaro — COMMENTED** [review]
It seems `unicode` built-in is gone in python3.

I was looking at the io.StringIO class but I didn't manage to get that working for this case.

**Review by ericvaandering — COMMENTED** [review]
Can you make a unit test for this change?

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann hold on this fix for a little while. I'll try to fix it tomorrow in a way that's py3 compatible. If I fail, then we merge it for the next agent later this week :)

**Comment by ticoann** [comment]
replaced by #8295

**Pull request closed without merging**
