### PR TITLE
Make phedex block deletion level instead of datasets

### LINKED ISSUE #8630: T0 making dataset level deletions instead of blocks
After the delete method got fixed
https://github.com/dmwm/WMCore/pull/8625

T0 team noticed the agent was making dataset level phedex deletion requests instead of blocks, see
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1900.html

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8630

I guess this issue was created when those modules got splitted up.
@drkovalskyi @vytjan this should solve the problem, but I can't really test it. Can you guys setup a replay to get it tested before it goes in in production?

Keep in mind this temp patch has to be then removed: #8629

### CODE REVIEW

**Comment by amaltaro** [comment]
Vytas and I tested this patch and it works fine, these are the arguments we pass to the PhEDEx `delete` API:
```
 {
'node': ['T2_CH_CERN'], 
'rm_subscriptions': 'n', 
'data': '<data version="2">
<dbs dls="dbs" name="https://cmsweb.cern.ch/dbs/prod/global/DBSReader">
	<dataset is-open="y" is-transient="n" name="/L1Accept/Tier0_REPLAY_vocms0500-v35/RAW">
		<block is-open="n" name="/L1Accept/Tier0_REPLAY_vocms0500-v35/RAW#22fb8200-34bd-41ec-af32-8b907ba04f1f"/>
	</dataset>\n\t\t<dataset is-open="y" is-transient="n" name="/MinimumBias/Tier0_REPLAY_vocms0500-v35/RAW">
		<block is-open="n" name="/MinimumBias/Tier0_REPLAY_vocms0500-v35/RAW#e4b7459b-423a-4d26-8855-531bfe22eb4c"/>
	</dataset>
</dbs>\n</data>\n', 
'comments': 'WMAgent blocks auto-delete from T2_CH_CERN', 
'level': 'block'}
```

However, there is something weird, since two deletion phedex requests were created with a second of difference between then, see:
https://cmsweb-testbed.cern.ch/phedex/datasvc/xml/prod/requestlist?dataset=/L1Accept/Tier0_REPLAY_vocms0500-v35/RAW

we think that's because we had to apply some changes to the code to properly see what's happening and etc. Anyways, Vytas is going to run another replay with these patches properly in place.

**Comment by amaltaro** [comment]
test this please

**Comment by vytjan** [comment]
@amaltaro a new replay was just started on the vocms0500.
Both patches were applied before starting it, so this time we can follow it properly.

**Comment by amaltaro** [comment]
Woooohoooo!!!! Jenkins is working again!
Ok Vytas, let me know when it's over please.

**Comment by amaltaro** [comment]
Vytas ran a replay on vocms0500 and the block level deletion was successfully created. So I'm merging it tomorrow for the next WMAgent release candidate tag.

**Comment by amaltaro** [comment]
@vytjan I have just created a new tag including those last 2 phedex fixes. You can use 1.1.12.patch5 which will contain all the necessary patches for phedex block deletions.

**Pull request merged**
