### PR TITLE
Upgrade WMCore dependencies for issue 11080

### LINKED ISSUE #11080: Upgrade python CherryPy and other Python3 packages
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
Given that in the beginning of 2022 we decided to drop support to python2 in WMCore, we should revisit the list of third-party python libraries and update them to the latest stable release. 

**Describe the solution you'd like**
Update python3 specs in the cmsdist repository and in our requirements.txt text file.
CherryPy is a good candidate, but we should also check whether there are other python libraries that we can update to a newer stable release. Note that those libraries no longer need to support python2.

If possible, we should avoid any releases that came out in the past month or two, since those could still be buggy.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes #11080 , #11206, #11205

#### Status
not-tested

#### Description
I provided updated versions of WMCore dependency packages in PR for cmsdist:
https://github.com/cms-sw/cmsdist/pull/8032
Among other things it will bring the following fixes:
- cherrypy 17.4.0 -> 18.8.0
- sqlalchemy 1.3.3 -> 1.4.40
- cx-oracle 7.3.0 -> 8.3.0
And, it includes new version of dbs3-client which is required for https://github.com/cms-sw/cmsdist/pull/8040#issuecomment-1227300844

#### Is it backward compatible (if not, which system it affects?)
MAYBE

#### Related PRs
https://github.com/cms-sw/cmsdist/pull/8032
https://github.com/dmwm/WMCore/pull/11248

### CODE REVIEW

**Review by amaltaro — CHANGES_REQUESTED** [review]
can you please squash these commits? I will have a final look at the changes once I get home, but if they are reflecting the changes provided to cmsdist, we are all good!

**Comment by vkuznet** [comment]
I'm not sure I need to sqush anything, here is git log output:
```
commit 36c072cb29a1968e4612d5c3a2b17d44ae30e23c (HEAD -> wmcore-upgrade, origin/wmcore-upgrade)
Author: Valentin Kuznetsov <vkuznet@gmail.com>
Date:   Mon Aug 22 13:49:03 2022 -0400

    new versions of WMCore dependency packages

commit 372622563c4b93373ad1813e2bad90227c9b4674 (origin/comp_gcc630, comp_gcc630)
Author: mimran <muhammad.imran@cern.ch>
Date:   Thu Aug 11 10:01:25 2022 +0200

    Bump HG2209a
```
Since it is new PR it has only one commit, all other references comes from previous PR which I closed.

**Comment by amaltaro** [comment]
@vkuznet Valentin, you have 4 commits in this PR, so you need to squash all of them into a single commit.
In case it helps, you can find further information in the "Step 10" of this documentation: https://github.com/dmwm/WMCore/blob/master/CONTRIBUTING.rst

**Comment by amaltaro** [comment]
Can you please also update the initial description of this PR, making a summary of the changes, which I noted to be (and their dependencies):
cherrypy 17.4.0 -> 18.8.0
sqlalchemy 1.3.3 -> 1.4.40
cx-oracle 7.3.0 -> 8.3.0

and mark all the GH issues that this PR is fixing (Fixes blah \n Fixes blahblah, etc). Also, please make sure that those issues that you are working on are marked as "In progress" in the Q3 project board.

**Comment by vkuznet** [comment]
@amaltaro , I squashed three sparsed commits, they appeared a way down in list of commits after rebase such that the ticket tree shows only on commit from me and the merge one which I don't see in my git log output but it shows on web interface. Honestly I don't know if and how it can be squashed. Meanwhile, I updated description too.

**Comment by vkuznet** [comment]
BTW, after jenkins tests came back I see something weird:
- 551 tests newly failing
- 130 tests deleted
- 13 unstable tests changed
- 1 tests improved
And, I have no idea what is wrong, it seems to me that it is jenkins issue.

**Comment by amaltaro** [comment]
Jenkins is now using the new python library versions you provided in cmsdist (merged yesterday evening). It looks like sqlalchemy is breaking pretty badly there, e.g.:
https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCore-PR-test/13545/testReport/junit/WMCore_t.WMBS_t.JobSplitting_t.WMBSMergeBySize_t/WMBSMergeBySize/testMaxMergeSize1/

with an error:
```
unknown strategy: 'threadlocal'
```

Either we revert all those changes and start taking incremental steps, merging one change + test, merge another change + test, and so on. Or we start looking into what are the breaking changes and start updating our baseline WMCore code to be compliant with the new version.

It might be easier to build a new docker image and start testing things over there. Please let me know what you think.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I am planning to make a new release very soon. For that, can you please:
* for better tracking, create a new GH issue reporting that `threadlocal` SQLAlchemy strategy has been removed
  * remove your DBFactory commit from this PR and make a separate PR for it
* update dbs3-client to 4.0.9 in the requirements (to reflect Stefano's changes in https://github.com/cms-sw/cmsdist/pull/8040#issuecomment-1227300844)
  * squash all the commits such that we can merge it
Thanks

**Comment by vkuznet** [comment]
done the following:
- revert threadlocal change
- put it new in PR, see https://github.com/dmwm/WMCore/pull/11257
- add new version of dbs3-client
- adjusted description of this PR

**Comment by amaltaro** [comment]
Thanks Valentin! Unfortunately, I still see a 2nd commit that shouldn't be provided in this PR. 

Looking it further, it looks like your development work is all done upstream (this dmwm repo), where you created this `wmcore-upgrade` branch. Contributions to the project should be provided with branch features created in your own (origin) repository. Can you please check these instructions and properly set up your repositories:
https://github.com/dmwm/WMCore/blob/master/CONTRIBUTING.rst#setting-up-the-repository

if needed, please come with a new PR. If you need further help, please ping me on slack.

**Comment by vkuznet** [comment]
I created new PR with these changes to avoid mess with branching/squashing/upstream. Closing this one in favor of https://github.com/dmwm/WMCore/pull/11258

**Comment by vkuznet** [comment]
@amaltaro  please jump to https://github.com/dmwm/WMCore/pull/11258 which I created with this PR content and description. The new PR should not have mess with branching/squashing/upstream. As I wrote I got another issue with my original branch and it seems to me somewhere in its chain of repair action I screw things up with this PR.

**Pull request closed without merging**
