### PR TITLE
merge jobs should always be run singlecore

### PR DESCRIPTION
**Pull request by hufnagel**
Tier0 repack merges can be scheduled as multicore, make sure they actually only use a single core on the worker node. This behavior is identical to the treatment of multicore repack jobs.

### CODE REVIEW

**Comment by ericvaandering** [comment]
Can you fix the indentation and imports?

**Comment by hufnagel** [comment]
Guess whoever now edits a file gets tagged with fixing all the obvious/easy pylint problems with it :-)

**Comment by ericvaandering** [comment]
yup

**Comment by ticoann** [comment]
retest this please

**Comment by hufnagel** [comment]
retest this please

**Comment by hufnagel** [comment]
@ticoann @amaltaro can you review this too ? Its been used since forever in the Tier0 and is required for the Tier0 to work correctly. A corresponding T0 patch was already merged ages ago.

**Comment by hufnagel** [comment]
@ticoann @amaltaro I am not going to "fix" this. It works as-is. The pyling score is abysmal, but that's just the way this file is coded...

**Comment by ericvaandering** [comment]
Agreed.

**Comment by ticoann** [comment]
Looks fine with me. Sorry for the late.

**Pull request merged**
