### PR TITLE
kill workflow more effiently

### PR DESCRIPTION
**Pull request by ticoann**
This is the first part of the patch. (Only agent side need to be updated)
1. It will skip the couchdb and dashboard update if the job need to be killed is more than 100 (hardcoded)
2. It will update mariadb/oracle db in bulk not by job.

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Please review. I am not sure whether to have hard coded limit for the update is good idea. (I know it is bad idea but whether there is better one).

**Comment by amaltaro** [comment]
I don't have a better suggestion, so it looks good to me.
There is only thing that may be a bit confusing, you call changeState methods using 'liveJob["state"]' value, but this is the last element of liveJobs (which may have a killed state). Perhaps we should change it to liveWMBSJobs[0]['state'] ?

**Comment by ticoann** [comment]
Thanks Alan, that was good catch. I slightly modify the code so executing (running and pending) jobs couch state will get updated even though there are a lot of jobs. Otherwise it will be confusing in monitoring. I will do the pycurl parallel call in the separate ticket.  Please review.

**Comment by amaltaro** [comment]
Looks good. Let me apply this patch and run a few tests over the night.

**Comment by amaltaro** [comment]
I wonder whether BossAir really killed the pending jobs, since I see such error messages in the WorkQueue logs:
```
2015-04-13 22:54:27,542:INFO:WorkQueue:Canceling work for workflow(s): set(['amaltaro_TaskChainPyquenZeemumuJets_PU_Agent105_CDB16_forceComplete_150413_204714_7902'])
2015-04-13 22:54:31,676:ERROR:CondorPlugin:Can't find this job's cache_dir in CondorPlugin.complete
2015-04-13 22:54:31,677:ERROR:CondorPlugin:cache_dir: None
2015-04-13 22:54:31,677:ERROR:CondorPlugin:retry_count: 0
2015-04-13 22:54:31,677:ERROR:CondorPlugin:Can't find this job's cache_dir in CondorPlugin.complete
```

Or maybe it comes from the created but not submitted jobs. Still have to investigate it ...

**Comment by amaltaro** [comment]
It seems it fails exactly in this line:
https://github.com/dmwm/WMCore/blob/b47259e6671e3c05f75762532679062a69b01c27/src/python/WMCore/JobStateMachine/ChangeState.py#L423

How about we catch a DatabaseError there and then retry the DB query?
Does it make any difference if we try to update 10k rows or only 1k? The problem I had today was updating only 204 rows. Also, since it's a deadlock, I don't think the number of rows would improve it..

**Comment by ticoann** [comment]
Thanks Alan for investigating. Since Oracle has row level locking, it would generally help to just small update instead of bulk update. However, in this case I think don't commit until all the jobs updated, so it will increase possibility of deadlock in any case. 
I wonder moving the transaction from
https://github.com/ticoann/WMCore/blob/abort_force_complete/src/python/WMCore/WorkQueue/WMBSHelper.py#L83

to 
https://github.com/ticoann/WMCore/blob/abort_force_complete/src/python/WMCore/WorkQueue/WMBSHelper.py#L128

even we can move inside the loop and commit in the loop.
https://github.com/ticoann/WMCore/blob/abort_force_complete/src/python/WMCore/WorkQueue/WMBSHelper.py#L130

I am not sure that will help or any side effect.
Could you check whether we use existing transaction or create the transaction in the method?
https://github.com/ticoann/WMCore/blob/abort_force_complete/src/python/WMCore/WorkQueue/WMBSHelper.py#L80

Thanks,

**Comment by ticoann** [comment]
Alan, I updated patch as we discussed.
in propagate, move the db update code before couch and dashboard update.
break the transactions for each call.

**Comment by amaltaro** [comment]
Thanks Seangchan. BTW, killWorkflow() is not using an existent transaction. Let me test it again over the night.

**Comment by amaltaro** [comment]
And since we do not want to update couch docs in case the wmbs update fails, I think we should also add/test this one https://github.com/amaltaro/WMCore/commit/b52e0acc8db98293cd86f1090baf1e99a2cad9f7 Otherwise local docs will move from CancelRequested to Canceled and then won't be considered in the next WQ cycle. What do you think?

**Comment by amaltaro** [comment]
Seangchan, you were right, that call was properly updating couch as well :-)
I merged this PR and a few more changes, more logging, etc in this commit https://github.com/amaltaro/WMCore/commit/626273f7ba6a52ab1ca231838ecd48cf7d8423b8

Can you review, pick these changes and update your PR please? Thanks

**Comment by ticoann** [comment]
Thanks Alan, Patch looks fine. Since you already merged the patch. Could you create a pull request. I will close this instead.

**Comment by ticoann** [comment]
duplicate

**Pull request closed without merging**
