### PR TITLE
Moving commands to subprocess

### PR DESCRIPTION
**Pull request by SaltumDis**

### CODE REVIEW

**Comment by ericvaandering** [comment]
@ticoann any reason this shouldn't be merged?

**Comment by amaltaro** [comment]
Seems to be just an import update, but to be on the safe side, let me run a couple of tests first

**Comment by ticoann** [comment]
Thanks Alan, although it is simple I didn't run the test so I didn't merge this. I will apply to the testing agent and run the quick test as well.

**Comment by amaltaro** [comment]
Don't worry, work already sent to cmssrv214. If you prefer, review my other PR :-P

**Comment by amaltaro** [comment]
@ticoann good to go

**Pull request merged**
