### PR TITLE
Remove admin interface

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by amaltaro** [comment]
@vkuznet it seems we can get rid of the following dependencies on this class: RESTMain and RestApiHub. Can you clean this further please?

**Comment by vkuznet** [comment]
Alan, I removed RESTMain and RestApiHub since it seems no other part of code is
using it anymore. My understanding that you tested already this stuff so we're
safe.

**Comment by amaltaro** [comment]
And you can also remove this line https://github.com/vkuznet/WMCore/blob/d524102c8a91be26f2b72b6ccb92028eaf9c9def/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L33
and the `admin` menu/key from this line https://github.com/vkuznet/WMCore/blob/d524102c8a91be26f2b72b6ccb92028eaf9c9def/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L91

**Comment by amaltaro** [comment]
@vkuznet different from what we discussed today, it seems you missed my last comment. Can you remove what I mentioned above please? Thanks

**Comment by vkuznet** [comment]
Done

**Comment by amaltaro** [comment]
@vkuznet please squash these commits. There is no need to have these changes in different commits.

**Comment by vkuznet** [comment]
Done

**Comment by amaltaro** [comment]
Thanks, Valentin!
@vkuznet In order to improve our code, readability and maintenance :-) Can you start helping us with pylint suggestions as well? Only the certain and easy ones. For such cases, please make an additional commit. Imports are the best pick here, though the `check_scripts` into a function looks straight forward as well. Thanks!

**Comment by vkuznet** [comment]
Alan,
there are two ways with pylints, either we should do that with every PR we
create. This is an easy route since when developer creates PR we got jenkins
logs with pylint suggestion and we know (!) that the code we try to fix is
in use. The second approach (as you suggested with separate PR) is more
complex. We can either run pylint over entire WMCore universe and start
fixing the code or start fixing files from our own PRs. The former has
disadvantage that not every WMCore code is in use and we'll be doing
duplicate work, while the later is also duplicate work since we already
have PR in progress and you want yet another PR for pylint changes.

Please think about the approach. I'm fine with fixing pylints suggestions
with PRs as we go. But pylint fixes may not reflect PR intention.

Valentin.

**Comment by amaltaro** [comment]
Valentin, I did not suggest to make a new PR for pylint fixes only. My suggestion is what you call  the "easy route", which means during the development/validation of a PR, once the "real fix" is completed validated, we then make another **commit** pushing the pylint **only** changes. Such that a PR ends with 2 commits, for instance: first one reflecting the PR intention and the second one only with code/pylint improvements.

PS.: The pylint output from jenkins is shrinked, if you want to have a full report, you need to run it on your development environment (passing the WMCore rc file https://github.com/dmwm/WMCore/blob/master/standards/.pylintrc)

**Comment by ericvaandering** [comment]
Yes, this is exactly the route most of us have followed for a while. One commit with functional changes, one commit with pylint/PEP-8 type stuff. The latter gets only a cursory review if at all.

**Comment by amaltaro** [comment]
Needless to say... can you squash the last 2 pylint commits please? :-)

**Comment by vkuznet** [comment]
I fixed "almost" all pylint things, except non-user app/mount in ctor and genobjs in one of the method. The former is tricky since ReqMgrService class is not called directly anywhere in a WMCore, it rather passed via config to REST server. How parameters are treated by REST server is unclear to me, since I can't find direct class which do that. May be @ticoann can help. Therefore I left app/mount in ctor. The genobjs is yet another trick which pylint can't spot, since it is created dynamically (that's why it is not visible in a code). So at this moment the pylint changes are complete except ones I mention above. Alan, @amaltaro , may be we can apply this PR to some of your instances and see if reqmgr2 server will start without problem, then we can remove app/mount in ctor and repeat the test.

**Comment by vkuznet** [comment]
Not until we finalize all details of PR. I wrote about them in a ticket.

**Comment by amaltaro** [comment]
Valentin, just to be clear, you do not need to fix ALL pylint suggestions, some are tricky, others are not really correct, others take quite some work, etc.
I'm applying it to my VM, but for me this PR is completed.

**Comment by amaltaro** [comment]
ReqMgr2 seems to be working fine. Feel free to squash them

**Comment by vkuznet** [comment]
Well, if I do the work with pylint I rather do it once, i.e. fix all issues at
once, rather to have some fixes.

Good that server works, but I asked you to try out in VM to remove app/mount
in ctor of ReqWebService class and see how it will work. I rather want to see
exception where it will complain. The part I'm talking about is here:

https://github.com/vkuznet/WMCore/blob/62039501c9f1147c2213011f974c6df3fd38473a/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L135

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Ok, Valentin and I just removed `app` and `mount` from the `ReqMgrService` class constructor and this is traceback
```
[27/Jun/2016:09:30:24] ENGINE Waiting for child threads to terminate...
[27/Jun/2016:09:30:24]  WATCHDOG: server exited with exit code 0
[27/Jun/2016:09:30:33]  WATCHDOG: starting server daemon (pid 1618)
[27/Jun/2016:09:30:33]  INFO: loading ui into /reqmgr2
[27/Jun/2016:09:30:33]  ERROR: terminating due to error, error trace follows
[27/Jun/2016:09:30:33]  ERROR:   Traceback (most recent call last):
[27/Jun/2016:09:30:33]  ERROR:     File "/data/srv/HG1606f-comp4/sw.amaltaro/slc6_amd64_gcc493/cms/reqmgr2/1.0.18.pre2/lib/python2.7/site-packages/WMCore/REST/Main.py", line 388, in start_daemon
[27/Jun/2016:09:30:33]  ERROR:       self.run()
[27/Jun/2016:09:30:33]  ERROR:     File "/data/srv/HG1606f-comp4/sw.amaltaro/slc6_amd64_gcc493/cms/reqmgr2/1.0.18.pre2/lib/python2.7/site-packages/WMCore/REST/Main.py", line 441, in run
[27/Jun/2016:09:30:33]  ERROR:       self.install_application()
[27/Jun/2016:09:30:33]  ERROR:     File "/data/srv/HG1606f-comp4/sw.amaltaro/slc6_amd64_gcc493/cms/reqmgr2/1.0.18.pre2/lib/python2.7/site-packages/WMCore/REST/Main.py", line 242, in install_application
[27/Jun/2016:09:30:33]  ERROR:       obj = getattr(module, class_name)(self, view, path)
[27/Jun/2016:09:30:33]  ERROR:   TypeError: __init__() takes exactly 2 arguments (4 given)
[27/Jun/2016:09:30:33]  WATCHDOG: server exited with exit code 1
```

**Comment by amaltaro** [comment]
Thanks, Valentin!

**Pull request merged**
