### PR TITLE
List and process only valid files in DBS

### LINKED ISSUE #5589: WMAgent creating jobs for invalid files
Andrew Lahiff reported today that jobs are created for invalid/non-existent files in the pileup sample.
The example was for this file:
/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root

where we can see marked as invalid in DBS [1] and non-existent (probably deleted) in TMDB/PhEDEx [2].

We need to enforce WMAgent not to create jobs (both primary and secondary source) jobs for invalid files.

[1]
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?logical_file_name=/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root&detail=True

[2]
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/data?file=/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root

### PR DESCRIPTION
**Pull request by amaltaro**
With this patch the agent should no longer create jobs with invalid files. Fixes #5589 
It's not straight forward to test it, so I'll first check whether it does not break anything.
Don't merge yet please
@ticoann , I removed those changes to DBSInterface.py

### CODE REVIEW

**Comment by amaltaro** [comment]
I'd like to push it to production, @yuyiguo @ticoann could you please take a last look at it?
cmssrv113 has been operating with this patch for the last 24h and everything looks ok, we ran several workflows there.

**Comment by ticoann** [comment]
Looks fine with me and it even tested. :smile:

**Comment by ticoann** [comment]
I think need to get in GQ as well for correct splitting estimation. So I am merging it.

**Comment by amaltaro** [comment]
Thanks Seangchan! I'm pushing it now to all the agents then.
If things explode, you know what was the reason :-)

**Pull request merged**
