### PR TITLE
[py2py3] futurize src/python/WMCore/Configuration.py

### LINKED ISSUE #9973: [py2py3] Migrate WMCore/Configuration
**Impact of the new feature**
This involves migrating WMCore/Configuration. It does not depend on any other wmcore module, so it can be tackled straight away.

This change can directly impact
```plaintext
'WMCore_WMStats',
'WMQuality_WebTools',
'WMCore_Locale',
'WMCore_JobSplitting',
'WMCore_WMInit',
'WMCore_Agent',
'WMCore_WebTools',
'WMCore_DataStructs',
'WMCore_FwkJobReport',
'WMCore_ReqMgr',
'WMCore_MicroService',
'WMQuality_Emulators',
'WMCore_WMSpec',
'WMComponent_AnalyticsDataCollector',
'WMCore_REST'
```
since these modules import WMCore/Configuration.

**Is your feature request related to a problem? Please describe.**
 Make WMCore/Configuration compatible with both python2 and python3.

**Describe the solution you'd like**

**Describe alternatives you've considered**
 Run futurize on WMCore/Configuration, then apply manual changes if needed

### PR DESCRIPTION
**Pull request by mapellidario**
Fixes #9973

#### Status
Ready

This is the best that we can do at the moment to modernize Configuration.py.

I do not consider this to be absolutely the best final version that I can guarantee works in py3, but this is a good starting point.

Unit test passed, so I am reasonably confident this is py2 compatible, too.

I would suggest merging this now, then I will open a new issue about the python3 validation of Configuration.py 

#### Description

Run futurize on WMCore/Configuration. 

What stll needs to be sorted out:

1. [x] Fix storm of errors in unit tests
1. [x] `import imp`
   - current implementation relies on `imp`
   - They say that [imp](https://docs.python.org/3/library/imp.html) is deprecated since python 3.4, currently working for us in python 3.8
   - Getting out of `imp` and into `importlib` likely requires more careful investigation on how to adapt our modules to be compatible with new `importlib` API. 
1. [x] `Implementing __eq__ without also implementing __hash__ (eq-without-hash)`
  - [__hash__() - python official doc](https://docs.python.org/3/reference/datamodel.html#object.__hash__)
  -  Our class `ConfigSection` have mutable members, such as  `self._internal_settings = set(): self._internal_docstrings = {}; self._internal_children = set()`, so ConfigSection objects are not hashable
  - This warning from pylint is considered a false positive
1. [x] `isinstance(value, unicode)`
  - keep in mind that we faced https://github.com/dmwm/WMCore/issues/10381, so we can only afford a temporary hack at the moment
1. [ ] validation in py3 environment

#### Is it backward compatible (if not, which system it affects?)
It should be. However, any bug would affect directly

```plaintext
'WMCore_WMStats',
'WMQuality_WebTools',
'WMCore_Locale',
'WMCore_JobSplitting',
'WMCore_WMInit',
'WMCore_Agent',
'WMCore_WebTools',
'WMCore_DataStructs',
'WMCore_FwkJobReport',
'WMCore_ReqMgr',
'WMCore_MicroService',
'WMQuality_Emulators',
'WMCore_WMSpec',
'WMComponent_AnalyticsDataCollector',
'WMCore_REST'
```

#### External dependencies / deployment changes

requires python-future, but we already have that

### CODE REVIEW

**Comment by mapellidario** [comment]
I only pushed the changes proposed by `futurize`, but these are not nearly enough. These should be considered only as suggestions, some help to spot potential failure points in the migration. This is why I would need the help of @amaltaro or @todor-ivanov .

Rationale: the main potential source of bugs in this PR is how we deal with types that change between py2 and py3.

### basestring

In python2 `basestring` is used to check if an object is an instance of `str` or `unicode`. Here I have the first question: why do we have

```python
if PY3:
    basestring = str
```

?

If the purpose is to match both types, we could simply import ` from past.builtins import basestring `, which provide a new type in python3 that matches both `bytes` (which is py2 `str`) and `str` (which is py2 `unicode`).


### unicode

We currently have

```
if isinstance(value, unicode):
       value = str(value)
```

which in py2 converts value from `unicode` to `str`.

But then I see

```python
if PY3:
  unicode = str
```

We should notice that if in py2 `str` is a sequence of bytes, in py3 `str` is a sequence of unicode codepoints. So, while ` unicode = str` is a tautology in python3, it would have no effect on `if isinstance(value, unicode): value = str(value)`. Moreover, since `str` changed meaning between py2 and py3, right now we are converting it to a sequence of bytes, in python3 we would leave it unchanged to a sequence of unicode. 

In any case, such a `value` would be used in `object.__setattr__(self, name, value)`, in python3 such a `value` can be either a `str`or `bytes` and in py2 it can be either `str` or `unicode`, and in `self._complexTypeCheck(name, value)`, which in case of `str` or `bytes` would only check that they are in `_SimpleTypes` list, so this should make no difference.

I would propose to remove `  unicode = str` and `if isinstance(value, unicode): value = str(value)`. do you see any possible side effect?


### int and long

in py2 `int` and `long` are different types. In py3 the equivalent of `int` disappeared and `long` has been renamed `int`. what we can do instead of 

```python
if PY3:
    long = int
```

would be importing `from past.builtins import long`. These two options should be identical, you should decide the one that you prefer.

**Comment by amaltaro** [comment]
test this please

**Comment by mapellidario** [comment]
I think that the only way to get out of this haystack is to wait for the py3 environment. It is super unlikely that we can get this right without it :grimacing:

**Review by amaltaro — APPROVED** [review]
It looks good to me, thanks Dario.
@todor-ivanov as we discussed in the past week, could you please try to run a quick test with these changes in (for both central services and wmagent)?

**Comment by todor-ivanov** [comment]
Hi @amaltaro I will run some tests right now. 
@mapellidario  did you manage to create a separate issue just for the action regarding the validation of this module as you mentioned here:
>  I would suggest merging this now, then I will open a new issue about the python3 validation of Configuration.py

**Comment by mapellidario** [comment]
Here we go @todor-ivanov! #10488

**Comment by todor-ivanov** [comment]
Thank @mapellidario ! Working on it now.

**Comment by amaltaro** [comment]
@mapellidario I do not know if you plan to fix any explicit problems with python3 stack(?) If you do, then here is an error while deploying `wmagentpy3` with your changes:
```
*** Initializing the agent ***
Initialising Agent...
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmcore-db-init", line 96, in <module>
    cfgObject = loadConfigurationFile(config)
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Configuration.py", line 597, in loadConfigurationFile
    modPath = my_importlib.find_module(cfgBaseName, [cfgDirName])
AttributeError: module 'importlib' has no attribute 'find_module'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmagent-couchapp-init", line 292, in <module>
    wmagentConfig = loadConfigurationFile(os.environ["WMAGENT_CONFIG"])
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Configuration.py", line 597, in loadConfigurationFile
    modPath = my_importlib.find_module(cfgBaseName, [cfgDirName])
AttributeError: module 'importlib' has no attribute 'find_module'
Done!
```

**Comment by amaltaro** [comment]
@todor-ivanov if you haven't started testing this PR, then do not worry. I'm testing mine for the Dashboard removal and I also have this patch in my setup.

**Comment by amaltaro** [comment]
Quick update on this, it seems to be working fine in python2 (checked on both WMAgent and central services).

**Comment by mapellidario** [comment]
> @mapellidario I do not know if you plan to fix any explicit problems with python3 stack(?) If you do, then here is an error while deploying `wmagentpy3` with your changes:
> 
> ```
> *** Initializing the agent ***
> Initialising Agent...
> Traceback (most recent call last):
>   File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmcore-db-init", line 96, in <module>
>     cfgObject = loadConfigurationFile(config)
>   File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Configuration.py", line 597, in loadConfigurationFile
>     modPath = my_importlib.find_module(cfgBaseName, [cfgDirName])
> AttributeError: module 'importlib' has no attribute 'find_module'
> Traceback (most recent call last):
>   File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmagent-couchapp-init", line 292, in <module>
>     wmagentConfig = loadConfigurationFile(os.environ["WMAGENT_CONFIG"])
>   File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Configuration.py", line 597, in loadConfigurationFile
>     modPath = my_importlib.find_module(cfgBaseName, [cfgDirName])
> AttributeError: module 'importlib' has no attribute 'find_module'
> Done!
> ```

Is this present even with this PR in place? because I added here

```python
# FIXME: python3 deprecation. This will no longer be needed when running in py3
if PY3:
    import importlib as my_importlib
else:
    import imp as my_importlib
```

and it should fix your problem

**Comment by amaltaro** [comment]
test this please

**Review by amaltaro — APPROVED** [review]
LGTM! Thanks Dario.

**Pull request merged**
