### PR TITLE
Change fileset creation to allow multiple output from StepChain

### LINKED ISSUE #6787: Stepchain: sort out duplicate outputModules
As Stepchain is now, it does not support KeepOutput:True for different steps using exactly the same outputModule (not matter the datatier used). The problem is that merge jobs are created for all files created under a specific outputModule (including all datatiers).

### PR DESCRIPTION
**Pull request by amaltaro**
Once this patch is complete, it will fix #6787 

@ticoann as we discussed yesterday, this is my current NON-fully working patch. 

It seems to be working for all type of requests, however there is still a problem that I didn't manage to fix yet. For this template https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/StepChain_MC.json ,
it creates 2 merge jobs for 'DIGIPROD1MergeRAWSIMoutput' and another 2 merge jobs for 'ProdMinBiasMergeRAWSIMoutput'.

Needless to say, do NOT merge it :-D

### CODE REVIEW

**Comment by ticoann** [comment]
Thanks Alan, I will try to understand the patch. :-)

**Comment by amaltaro** [comment]
Only look at it if you don't have anything better to do :-)
The most important changes are:
 1. in WMBSHelper, changing the name of the fileset to append the datatier.
 2. JobAccountant, to properly check the output mapping with what came back from the job.

Changes are very easy... but this part of the code is quite complex :(

**Comment by amaltaro** [comment]
Problem solved with the duplicated merge jobs (and dup records in workflow and fileset). Now onto the next problem :) why the logcollect and cleanup workflow entries were not created

**Comment by amaltaro** [comment]
New PR created in #7998

**Pull request closed without merging**
