### PR TITLE
Fix None couchUrl sent to sanitization

### PR DESCRIPTION
**Pull request by amaltaro**
Possible superseeding #7141

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
At least the following 3 tests are stable now:
```
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testEndPolicyNegotiating
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testMultipleTeams
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testQueueChainingStatusUpdates
```

@ticoann please review and merge

**Comment by ticoann** [comment]
Thanks Alan, I am not sure why it checks _replication_state. I think it was the left over code which was controlling replication restart by agent not couch server itself. Patch looks good.

**Pull request merged**
