### PR TITLE
Skip WorkQueue MonIT statistics for T0 agent

### LINKED ISSUE #9056: AMQ/MonIT uploads fail on T0 WMAgent LocalWQ_INFO
It turned out AMQ uploads are not working for T0 WMAgent since there is some interference with the Local WQ:
```
2019-02-28 11:22:11,634:140493687113472:INFO:AgentStatusPoller:Preparing documents to be posted to AMQ/MonIT..
2019-02-28 11:22:11,634:140493687113472:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: 'LocalWQ_INFO'
Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/2.1.4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch4-comp/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 138, in algorithm
    self.buildMonITDocs(agentInfo)
  File "/data/tier0/srv/wmagent/2.1.4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch4-comp/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 334, in buildMonITDocs
    allDocs.extend(self._buildMonITSitesDocs(dataStats))
  File "/data/tier0/srv/wmagent/2.1.4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch4-comp/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 382, in _buildMonITSitesDocs
    possibleJobsPerSite = dataStats['LocalWQ_INFO'].pop('possibleJobsPerSite', {})
KeyError: 'LocalWQ_INFO'
```

@amaltaro Could you please check it out and let us know if there is anything to be done on T0 side?

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9056

### CODE REVIEW

**Comment by amaltaro** [comment]
@vytjan can you please patch the T0 agent and test this PR for me please? Still waiting on jenkins though

**Comment by vytjan** [comment]
So the fix crashes some WQ unit test, but it actually worked as a fix for Tier0, I just ran a replay:
`2019-03-04 14:39:38,384:140518319822592:INFO:AgentStatusPoller:Preparing documents to be posted to AMQ/MonIT..
2019-03-04 14:39:38,385:140518319822592:INFO:AgentStatusPoller:Found 59 documents to post to AMQ
2019-03-04 14:39:38,439:140518319822592:INFO:AgentStatusPoller:59 docs successfully sent to AMQ
`
Anyway, let's wait until the failing unit test is fixed.

**Comment by amaltaro** [comment]
That crash is unrelated to this fix. I've seen that unit test changing its status quite often in the last days :(

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Thanks @vytjan , I just did a test in one of the dev agents too and it works fine.

**Pull request merged**
