### PR TITLE
only merge and successful job's skipped file will be reported

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan please review

### CODE REVIEW

**Comment by amaltaro** [comment]
Looks good!

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
@amaltaro, @ericvaandering  Alan, this will fail all the time. Jenkins fails all the time unless there is python code change. I am not sure Eric already fixed that.

**Comment by ericvaandering** [comment]
Oh look, he fixed it. :-)

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Oct 13, 2016, at 12:56, DMWM Jenkins <notifications@github.com<mailto:notifications@github.com>> wrote:


No python changes for pull request 7286.

-

**Comment by ticoann** [comment]
Thanks Eric, you fixed it. Now I have fix the unittest. 😄

**Comment by amaltaro** [comment]
@ticoann feel free to merge it as well. It was already backported to the wmagent branch

**Pull request merged**
