### PR TITLE
1.0.21 wmagent

### PR DESCRIPTION
**Pull request by ticoann**
WMAgent branch 1.0.21.

#7449 
#7442 
#7477

### CODE REVIEW

**Comment by ericvaandering** [comment]
I changed Jenkins to only test things that are going to the master branch. I don't know if I can trigger a test on this PR. Let me check.

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
That is good, it doesn't trigger. Thanks Eric

**Comment by ericvaandering** [comment]
I was hoping it would trigger if asked. Oh well, @amaltaro has to be careful now building the branches. Doing them was a pain since the tests may change a lot between this and the reference.

**Comment by amaltaro** [comment]
It's good not to see the unit tests results for branch PRs indeed, thanks!

I suggest we always run pylint checks locally for these branch PRs (especially after sorting conflicts out). If we can run only them here, it would be better, but otherwise it's not a big deal.

**Comment by amaltaro** [comment]
Testing it in vocms0230. If everything goes well, I'll push this patch to all the agents tomorrow.

**Comment by amaltaro** [comment]
@ticoann I forgot we also need this patch on the agent https://github.com/dmwm/WMCore/pull/7477
Can you please cherry-pick it as well? I'm running more tests with this patch in place now.

**Review by amaltaro — CHANGES_REQUESTED** [review]
The site location patch looks good (though I looked only at a couple diff sites).

The abort patch is not ready for production, it will leave workflows stuck in force-complete. Which reminds me, we haven't made the changes to make this transition on GQ, have we?

**Comment by ticoann** [comment]
> The abort patch is not ready for production, it will leave workflows stuck in force-complete. Which reminds me, we haven't made the changes to make this transition on GQ, have we?

As we discussed this is known fact and complimentary script is running as cronjob in vocms049. (every hour). I included #7477 with this patch and running the test. If everything goes fine, I will patch production agents.

**Comment by ticoann** [comment]
All the production and relval agents are updated. (But not hepcloud agents)

https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsWorkflowTeamWmAgentRealeases

**Pull request merged**
