### PR TITLE
Convert a few DBS3Uploader logs to debug

### PR DESCRIPTION
**Pull request by amaltaro**
Complement for #8676

### CODE REVIEW

**Comment by ticoann** [comment]
Sorry Alan, I thought I updated this one.

**Comment by ticoann** [comment]
You can create the patch3 tag with this.

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
No worries!

**Comment by amaltaro** [comment]
[Fix #8757 - Convert a few DBS3Uploader logs to debug](https://trello.com/c/KssH2NLa/118-fix-8757-convert-a-few-dbs3uploader-logs-to-debug)

**Pull request merged**
