### PR TITLE
Use DBSBufferFile module from DBS3 package

### PR DESCRIPTION
**Pull request by amaltaro**
WorkQueueManager was failing to completely create request subscriptions and that was also affecting JobAccountant (which I thought were due to the recent sql schema changes). Turns out the problem was happening because it was using dao that did not consider the new schema.

@ticoann this seems to fix the WMAgent issue I saw yesterday. Anyways, better waiting until tomorrow or Monday to merge it.

### CODE REVIEW

**Comment by amaltaro** [comment]
BTW, with these changes 
DBSBuffer.Database.Interface.DBSBufferFile
should be deletable now. I'll try to clean more DBSBuffer code in the coming week.

**Comment by amaltaro** [comment]
In case you want to merge it today for a new tag, go ahead, tests look ok. Otherwise we talk tomorrow ;)

**Comment by ticoann** [comment]
Wow, that is a big mistake from my part. Thanks.

**Comment by ticoann** [comment]
One thing though, following file is not used anywhere, right? 
 src/python/WMComponent/DBSUpload/Database/Interface/UploadToDBS.py

**Pull request merged**
