### PR TITLE
By default run the PhEDEx emulator

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by amaltaro** [comment]
@ericvaandering it seems this PR needs to be rebased

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
DBS failures are real including some others in DBS testing. Will have to fix these.

**Comment by ericvaandering** [comment]
Test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Should work fine now, want to rewrite the history of these commits once it is, though.

**Comment by ericvaandering** [comment]
I don't understand testListFileBlockLocation. It succeeds in my tests. Will investigate.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Ok @ticoann , this is good to merge. Still learning how mock works.

**Comment by ericvaandering** [comment]
@amaltaro since you are the new sheriff in town, when do you plan to merge this? :-)

**Comment by amaltaro** [comment]
Since it does not affect cmsweb services, I'm merging it now. Thanks Eric!

**Pull request merged**
