### PR TITLE
Add args for rucio get pfn

### LINKED ISSUE #10056: allow Rucio.getPFN to support all args in the upstream API
**Impact of the new feature**
So far only CRAB uses Rucio.getPFN so only CRAB will be affected.
Change will be fully backward compatible.

**Is your feature request related to a problem? Please describe.**
I need to use more arguments then currently supported

**Describe the solution you'd like**
being able to use all functionalities of Rucio python lnfs2pfns API as per
https://rucio.readthedocs.io/en/latest/api/rse.html

**Describe alternatives you've considered**
none possible

**Additional context**
refs: https://github.com/dmwm/CRABServer/issues/6242

### PR DESCRIPTION
**Pull request by belforte**
Fixes #10056 (when applied to master branch as well)

#### Status
 ready

#### Description
introduce new optional parameters for Rucio.client.getPFN
to be able to use all functionalities of Rucio python lnfs2pfns API as per
https://rucio.readthedocs.io/en/latest/api/rse.html

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
will need to make a PR for Master branch as well, but I could only test in 1.3.6.crab

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by amaltaro** [comment]
Stefano, it looks like you're bringing more changes to this branch. How about I close this one and backport the master PR myself? Another option is that you rebase this development branch on top of 1.3.6_crab and bring in only the mentioned changes.

**Comment by belforte** [comment]
thanks for spotting this Alan. Sorry. I saw only the commits I was expecting and did not check the code differences. Yes, if you are familiar with cherry-pick (sorry I am not), I guess the easiest is to close this and backport from #10122

**Comment by amaltaro** [comment]
Sure, I can take care of it once we merge your PR against the master branch.

**Comment by amaltaro** [comment]
Superseeded by https://github.com/dmwm/WMCore/pull/10123

**Pull request closed without merging**
