### PR TITLE
Transfer logCollect tarballs to CERN EOS

### LINKED ISSUE #5719: stage out log files to eos
Hi,

We have set up a special phedex instance to transfer log files from castor to eos. Right now we are using a cronjob to inject the log files into phedex. This cronjob is crashing a lot and @merictaze recommends that wmagent should directly inject the log files into the phedex instance.

Andrew

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #5719 and takes over Seangchan's PR #6294 .
Tested with 2 workflows (one at FNAL and another at Pisa) and everything worked fine.

Credits to Seangchan for doing 99% of the code changes :-)

### CODE REVIEW

**Comment by ticoann** [comment]
Alan,  it is all your effort. we don't count effort by number of lines code wrote but who solve the problem. :smile: Thanks a lot for fixing the problem.

**Comment by ericvaandering** [comment]
@amaltaro this succeeded in its checks an hour ago. :-)

**Comment by amaltaro** [comment]
How come? It silently succeeded then, because what I see here is "Previously working unit tests have failed!" and a big red button saying "All checks have failed"  :(

**Comment by ericvaandering** [comment]
Well, "All checks" means that Jenkins failed. We have no other checks. And it failed because of the unit test failure. And maybe the pylint score decrease.

**Comment by ericvaandering** [comment]
So Jenkins ran successfully, it just doesn't like what it found. Ergo a big red X.

**Comment by amaltaro** [comment]
Ok, I pushed this patch in to all the production agents.
@ticoann feel free to merge it, it does not impact in cmsweb services.

**Pull request merged**
