### PR TITLE
Remove T0 legacy setup and option from resource-control insertion

### PR DESCRIPTION
**Pull request by amaltaro**
This dirty hack has to be removed once #8280 goes in
@ticoann please review

### CODE REVIEW

**Comment by ticoann** [comment]
This is just for the new agent not for the master,  right? I didn't know you were talking about this change (only in bin). I guess we don't need to patch the production agent just back port it, right?
Also we don't need to bother to have pylint change if we are only applying this to new agent.

**Comment by amaltaro** [comment]
Yes, though I created another patch in #8315
I'll change this PR and simply remove a legacy code.

**Comment by ticoann** [comment]
That's good, Thanks Alan.

**Comment by amaltaro** [comment]
Patch was updated. I basically removed the T0 code that was legacy (still storage element?!?) and removed the option too, since one can use `--add-one-site`

**Comment by amaltaro** [comment]
@hufnagel I doubt it can cause any harm to T0, but just in case ...

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
test this please

**Comment by hufnagel** [comment]
No problem, we haven't used that option in ages.

**Comment by ericvaandering** [comment]
This commit seems to have broken Jenkins by causing two tests to time out. Please investigate it and fix it. Look at #8325 for the test names.

**Pull request merged**
