### PR TITLE
Create schedd object for every call - wmagent 1.4.1 branch

### LINKED ISSUE #10170: AgentStatusWatcher errors due to interrupted polling cycle of DrainStatusPooler
**Impact of the bug**
WMAgent

**Describe the bug**
Recently we started noticing in the agents that `AgentStatausWatcher` goes in red. The usual cause is a stuck and not updated thread - `DrainStatusPooler`. No clue what is causing it yet. We only noticed that the sub component in question just stops following its regular pooling cycle, which in general should be once per hour. A single log record for a healthy sub component run is given in [1].

[1]
```
2020-12-10 04:15:25,947:139645241743104:INFO:DrainStatusPoller:Running agent drain algorithm...
2020-12-10 04:16:14,845:139645241743104:INFO:DrainStatusPoller:Checking speed drain threshold for NoJobRetries. 
2020-12-10 04:16:14,846:139645241743104:INFO:DrainStatusPoller:Checking speed drain threshold for EnableAllSites. 
2020-12-10 04:16:14,846:139645241743104:INFO:DrainStatusPoller:Checking speed drain threshold for CondorPriority. 
2020-12-10 04:16:22,538:139645241743104:INFO:DrainStatusPoller:Finished collecting agent drain status.
2020-12-10 04:16:22,538:139645241743104:INFO:DrainStatusPoller:Drain stats: {'workflows_completed': False}
2020-12-10 04:16:22,538:139645241743104:INFO:BaseWorkerThread:DrainStatusPoller took 56.591 secs to execute
```
 
**How to reproduce it**
Unknown - the cause is yet not figured out.

**Expected behavior**
`DrainStatusPooler` to follow its regular polling cycle

**Additional context and error message**
N/A

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #10170 (this is a wmagent branch fix though)

#### Status
not-tested

#### Description
For some reason - which I did not debug deeper - this schedd query:
```
jobs = self.schedd.query(constraint, attr_list)
```
gets stuck in the DrainStatusPoller thread. If we create a new schedd object, the query goes through without any issues.

So, this PR creates an schedd instance for every call to those methods (getCondorJobs and editCondorJobs). Those methods aren't used more than a few times every hour, so the extra burden in creating the schedd object (~10ms) can be said to be negligible.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
I have applied this patch to vocms0250 and everything went fine (even in multiple cycles):
```
2021-01-04 13:03:40,117:139851635902208:INFO:DrainStatusPoller:Running agent drain algorithm...
2021-01-04 13:03:41,071:139851635902208:INFO:DrainStatusPoller:Checking speed drain threshold for EnableAllSites. 
2021-01-04 13:03:41,071:139851635902208:INFO:DrainStatusPoller:Checking speed drain threshold for NoJobRetries. 
2021-01-04 13:03:41,071:139851635902208:INFO:DrainStatusPoller:Checking speed drain threshold for CondorPriority. 
2021-01-04 13:03:41,072:139851635902208:INFO:DrainStatusPoller:Agent will update speed drain configuration for CondorPriority. 
2021-01-04 13:03:41,108:139851635902208:INFO:DrainStatusPoller:Updating agent configuration for speed drain...
2021-01-04 13:03:41,162:139851635902208:INFO:DrainStatusPoller:Bumping condor job priority to 999999 for Production/Processing pending jobs.
2021-01-04 13:03:41,217:139851635902208:INFO:DrainStatusPoller:Finished collecting agent drain status.
2021-01-04 13:03:41,217:139851635902208:INFO:DrainStatusPoller:Drain stats: {'workflows_completed': False}
2021-01-04 13:03:41,217:139851635902208:INFO:BaseWorkerThread:DrainStatusPoller took 1.100 secs to execute
```

I'm going to apply it to the other 1.4.1.patchX agents and restart AgentStatusWatcher.

@todor-ivanov @khurtado please let me know if you have any suggestion to properly debug this problem. Otherwise I'll port it to the master branch by the end of this week.

**Comment by amaltaro** [comment]
[Fix #10206 - Create schedd object for every call](https://trello.com/c/Bguwtzgn/242-fix-10206-create-schedd-object-for-every-call)

**Comment by todor-ivanov** [comment]
Hi @amaltaro I have no suggestions, besides applying it on all agents and waiting to see how it goes.

**Comment by amaltaro** [comment]
And it worked for a few cycles, but eventually it gets stuck and the schedd is not able to serve that query.

**Comment by amaltaro** [comment]
It doesn't fix the issue and 1.4.1 is no longer relevant. Closing

**Pull request closed without merging**
