### PR TITLE
add log db report for db exception

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Review by amaltaro — CHANGES_REQUESTED** [review]
Hmm, ideally we should not put any WMCore specific code in the Utils package. Do you see any other place we could add/delete the logdb record?

**Comment by ticoann** [comment]
Yes I agree how about under WMCore/Database?

**Comment by amaltaro** [comment]
Yes, WMCore/Database looks a perfect place

**Pull request merged**
