### PR TITLE
Script to create and assign DMWM workflows

### LINKED ISSUE #5042: TODO: testing, validation, scripts
So I am creating here a thread, to be able discuss more what we need to have and what to be done :

1) Update json files and keep them up to date; (Justas and Alan)
2) Specify what we are validating, and what we need to validate (lumis, files, phedex, dbs.. etc).
       a) More will be discussed by Alan and me next week.
       b) Finish the script which dones everything;

Comments welcome
Justas

### PR DESCRIPTION
**Pull request by amaltaro**
Partially fixes #5042 . The second needs a few error handling (dataset not in DBS or phedex...)
@juztas please review
@ticoann is it the right place for this script?

### CODE REVIEW

**Comment by ticoann** [comment]
Yes it is the right place

**Comment by amaltaro** [comment]
Just updated the acqera for relvals.

**Comment by amaltaro** [comment]
Don't merge yet, I'm still cooking a few changes.

**Comment by amaltaro** [comment]
Code updated, now one can:
 - specify a directory to search for templates (will be DMWM or Integration, I still need to update them in another PR)
 - specify a single template name for creation/assignment
 - cloning of the official repo is no longer enforced.

**Pull request merged**
