### PR TITLE
Remove jobs by wf name for force-complete and aborted

### PR DESCRIPTION
**Pull request by amaltaro**
Should be a very good improvement when there are big workflows to abort/force-complete.
I still need to test these changes, please don't merge yet. 
@ticoann please review. The WorkQueue change affects only LQ.

### CODE REVIEW

**Comment by ericvaandering** [comment]
While I'm not ready to unleash my Jenkins stuff on the world just yet, I did see an error come by that this test was newly broken: WMCore_t.WorkQueue_t.WMBSHelper_t.WMBSHelperTest:testKillWorkflow

Considering that this PR touches related code, I'm not sure it's a coincidence. Please check.

**Comment by ericvaandering** [comment]
retest this please

**Comment by amaltaro** [comment]
Damnit! It's completely broken, sorry... fixing it later.

**Comment by amaltaro** [comment]
I'll test this patch with the new testbed coming today and if everything goes fine, I'll create the 1.0.8 tomorrow. Don't merge yet please.

**Comment by amaltaro** [comment]
Good to go. Feel free to merge it.

**Comment by ericvaandering** [comment]
test this please

**Comment by amaltaro** [comment]
Seangchan, don't merge yet. Let me digest this automatic report and see what can be fixed/improved.

**Comment by ericvaandering** [comment]
I don't think you have to pay too much attention to the pylint stuff, but if it's in code you added, it would be good to make improvements there. That unit test, I suspect, is spurious. If it continues to pop up randomly we will set it to integration thereby ignoring it.

**Comment by amaltaro** [comment]
In the end it was a good experience to learn a bit of pylint :-)
I applied a few improvements, according to pylint report and I've also disabled W1201 for the (py)condor plugins. I think it's cleaner than casting arguments to str all the time (?)

I also think the unit test failure is spurious, since I did not touch that part of the code :-)
BTW, is pylint going to run again or I (someone) need to trigger it again with the magic words?

**Comment by ericvaandering** [comment]
It's queued up to run again (see the "waiting to hear" on the merge button? Maybe you don't if you can't merge....

You can always use the magic words too. (I won't type them here because it would start a second run).

**Comment by amaltaro** [comment]
Good to know, thanks ;-)

**Comment by ericvaandering** [comment]
I guess this W1201 issue is this: http://stackoverflow.com/questions/4148790/lazy-logger-message-string-evaluation

Personally, I think unless there is a real performance issue, it's best to keep readability and interchangeability between log and print() .

**Pull request merged**
