### PR TITLE
 Add a test site option to resource control bin 

### PR DESCRIPTION
**Pull request by amaltaro**
I missed a unit test in PR #8314 . Hopefully that's the reason for jenkins not to be behaving...

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Maybe we still have to wait for the baseline test to successfully run(?)

**Comment by amaltaro** [comment]
:-)

**Comment by ticoann** [comment]
good job, Alan! 😄

**Comment by amaltaro** [comment]
Of course I caused all this mess :P

**Comment by ticoann** [comment]
@amaltaro, Alan, is this patch still needed?

**Comment by amaltaro** [comment]
Yes, it fixes a unit test and some py2.6 regression checks

**Pull request merged**
