### PR TITLE
allow to renew credential based on userName

### LINKED ISSUE #9544: simplify myproxy credential name
**Impact of the new feature**
only affects CRAB.

**Is your feature request related to a problem? Please describe.**
currently submission from client  needs to go through same REST host as indicated in TaskWorker config. With multiple REST hosts and TW's in docker/k8s era this is not working. Also the numerical hash of the DN makes it always difficult to tell what's happening w/o adding a real extrasecurity value.

**Describe the solution you'd like**
credentail in myproxy should have a simple username, e.g. we can pass
to the WMCore Credential service a string like "CRAB" and credential name will be
CRAB_belforte etc. 

**Describe alternatives you've considered**
no other way is possible

**Additional context**

### PR DESCRIPTION
**Pull request by belforte**
Fixes #9544 

#### Status
ready

#### Description
1. if username is given in proxycfg, use it also for `logonRenewMyProxy()`
2. removes some fake error logging from `vomsExtensionRenewal`
Those functions are only used  by CRAB. You can safely merge and kindly add in next tag so that we can build a new TaskWorker with this and test in preprod.
I tested already in my VM.

#### Is it backward compatible (if not, which system it affects?)
YES 

#### Related PRs
#9548 was a partial fix for same issue
#9577 was an earlier attempt which failed to properly rebase and has some discussions of the changes

### CODE REVIEW

**Comment by belforte** [comment]
from my side this this ready to merge. I tested it again in CRAB.

**Review by amaltaro — APPROVED** [review]
Thanks, Stefano. Everything looks good to me.

**Comment by amaltaro** [comment]
@belforte I have just created a new tag with this fix (and the UserFileCache one) in, please use:
`1.3.2.pre6`

**Comment by belforte** [comment]
thanks Alan

**Pull request merged**
