### PR TITLE
[PY3] Make StringIO and httplib compatible with python3

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #
(no issue created yet)

#### Status
In development

#### Description
Make some imports compatible between python2 and python3, such as:
* httplib --> http.client
* StringIO --> io.StringIO

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
@mapellidario Dario, given that the StringIO part has already been taken care of; and you have other PRs open for PSetTweaks and soon WMCore.Cache. Do you think you could create a new PR taking over a few other changes proposed in this PR?

I'm specifically talking about the http module:
https://python-future.org/compatible_idioms.html#http-module

**Comment by mapellidario** [comment]
Python futurize deals with `httplib` -> `http.client` with the stage2 fixer `futurize -f libfuturize.fixes.fix_future_standard_library $path` . 

Dealing with all standard library in just one fixer, it would also change 

* `cPickle` to `pickle`
* `urlparse` to `urllib.parse` 
* `thread` to `_thread`
* `from commands import getoutput` to `from subprocess import getoutput`

The files affected are 37, mainly in WMCore, but also a handful in WMComponent.

Do we still want to update httplib only? It would require some manual work, that would have to be replicated for cPickle, urlparse, thread and subprocess, while we could just rely as much as we can on the automated fixers changing and testing a single module at a time.

**Comment by amaltaro** [comment]
Dario, as we discussed over slack, please proceed with the automated fixer, but revert the cPickle changes for now (until we can properly profile/evaluate what is the performance penalty in migrating to the non C implementation of pickle).

**Comment by mapellidario** [comment]
Dear Alan, in the last weeks we opened the issue #9761 and its relative PR #9762 dealing with the migration of python std library as a whole, and not only `httplib` to `http.client`. Moreover, migrating the use of strings may require some more extra attention and may be dealt with a gradual approach.

What would you think about closing this PR without merging?

**Comment by amaltaro** [comment]
I agree Dario. Thanks to your and David's work. Closing

**Pull request closed without merging**
