### PR TITLE
Add drain thread

### PR DESCRIPTION
**Pull request by goughes**
Pull request for just the drain thread without the updates to unit tests, emulators, etc.
replace #7615

### CODE REVIEW

**Comment by ticoann** [comment]
@goughes, Eric this seems to be working better. Sorry my code cause this problems. I think we will deal with the unittest later. 
Could you fix Python3 compatibility warnings in separate commit. I will merge the code and update wmagent branch after that.

**Comment by ericvaandering** [comment]
These python3 warnings are @amaltaro 's to fix.

**Comment by amaltaro** [comment]
Bored of creating bugs, so I decided to break py3 compatibility too :-P

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Pull request merged**
