### PR TITLE
Avoid crashing ErrorHandler in case of Couch/HTTP issues

### PR DESCRIPTION
**Pull request by amaltaro**
I'm running this patch in submit1 and submit2 (well, the exception handling part only), since they were crashing all the time.

@ticoann please review and if that's Ok, I'll create two more PRs for 1.0.14 and 1.0.12 branches.

### CODE REVIEW

**Comment by ticoann** [comment]
Hi Alan, patch looks good. I was just wondering whether we can catch more specific errors than HTTPException. i.e. if check the status of the exception etc? If it can't be, go ahead create the patch for other version. Thanks,

**Comment by amaltaro** [comment]
I could make another except block for HTTPException only and print the status and reason for that case, though I'm not sure whether we should take different actions for different status (and which action) :(

Let's see, if jenkins complain about something else, than I could change this PR according, otherwise I'll just backport it.

**Comment by ticoann** [comment]
I was just concern about too catching general exception. (including other exceptions which might be better to make component crash), not about the print out messages. Anyway, current patch will be fine.

**Comment by amaltaro** [comment]
And this master PR we don't merge it, I'll bypass some status code that come to my mind (400, 404, 502, 503) and raise HTTPException otherwise. I also want to do some pylint cleanup.

**Comment by amaltaro** [comment]
Sorry, I'll update and test my changes by Monday.

**Comment by amaltaro** [comment]
I removed all the sendAlert pieces from this component and also removed the outer transaction rollback, we already create them in the two inner methods.
Still need to be tested

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann if unittests run Ok and the code looks Ok for you (I'm running this code in vocms074, but no exception happened so far...), then merge please.

I'll use the new tag for the new agent validation.

**Comment by amaltaro** [comment]
test this please

**Pull request merged**
