### PR TITLE
Remove alert system in JobTracker; other minor improvements

### PR DESCRIPTION
**Pull request by amaltaro**
Should be merged after #6977
Since I already backported the other PR to 1.0.17 branch, I preferred to create another PR for these changes that I missed in the previous patch (I stopped working on that once I found the problem :))

@ticoann please review. I still want to see whether it works Ok in my test node.

### CODE REVIEW

**Comment by ticoann** [comment]
Sorry Alan, could you fix the conflict? It seems it has conflict after merging #6977

**Comment by amaltaro** [comment]
Ok, branch rebased. BTW, anyone know how to rebase a branch without creating an additional commit? I couldn't squash my previous and the merge commit into a single one.

I still have to test it.

**Comment by amaltaro** [comment]
@ticoann it's good to go from my side.

**Comment by amaltaro** [comment]
Seangchan, sorry, let me check one last thing first.

**Comment by amaltaro** [comment]
I misinterpreted the code here. There is no error message to be updated because it's properly set when jobs are killed (by JobStatusLite). I've just updated this patch

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Ok, in the end it's just the alert removal and some move of transaction begin/commit.
@ticoann it's good to be merged as well.

**Pull request merged**
