### PR TITLE
Compact lumi list in the workflow summary doc

### LINKED ISSUE #5216: change how lumi is recorded in workload summary
Instead of making lumi list with all the numbers recorded the range.
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/TaskArchiver/TaskArchiverPoller.py#L713
Need to check whether format change breaks things

### PR DESCRIPTION
**Pull request by amaltaro**
Easier to test and validate with a PR against master... master version of #7205
Fixes #5216 and #7202

Basically 2 changes:
- instead of uploading a list of lumi sections, it uploads a list of lists (ranges)
- check if the workloadsummary is bigger than 6MB, if so, then completely remove the `errors` section from the summary.

### CODE REVIEW

**Comment by ticoann** [comment]
Not sure whether this is temporary glitch or valid error. rerunning the test

root: ERROR: Traceback (most recent call last):
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/src/python/WMComponent/TaskArchiver/CleanCouchPoller.py", line 252, in algorithm
    report = self.wmstatsCouchDB.deleteOldDocs(self.DataKeepDays)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/src/python/WMCore/Services/WMStats/WMStatsWriter.py", line 134, in deleteOldDocs
    result = self.couchDB.loadView(self.couchapp, "time", options)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/src/python/WMCore/Database/CMSCouch.py", line 488, in loadView
    (self.name, design, view), encodedOptions)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/src/python/WMCore/Services/Requests.py", line 104, in get
    encode, decode, contentType)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/src/python/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/src/python/WMCore/Database/CMSCouch.py", line 140, in checkForCouchError
    raise CouchNotFoundError(reason, data, result)
CouchNotFoundError: CouchNotFoundError - reason: Object Not Found, data: {'startkey': '1474455479', 'stale': 'update_after', 'descending': 'true'} result: None

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Now the taskArchiver test should pass

**Comment by amaltaro** [comment]
I'll test this patch tomorrow. I've done tons of code reformat and some manual pylint fixes, so we better test it before it gets merged.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Just as a reference, here is the workload summary using the new format:
https://alan-cloud1.cern.ch/couchdb/_utils/document.html?workloadsummary/amaltaro_MonteCarlo_PhEDEx_DMWM_Test_Sept2016_BAD_160922_115805_9275

and if we use the _show functions, the lumi list is a bit weird, e.g.:
https://alan-cloud1.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/amaltaro_MonteCarlo_PhEDEx_DMWM_Test_Sept2016_BAD_160922_115805_9275

We basically have to update those show functions to handle both kinds of lumi lists format.
@ticoann, should we merge this one and create a new issue for the show functions? I don't think they are actually used anymore though

**Comment by amaltaro** [comment]
I'll just run jenkins once again

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann good to go

**Pull request merged**
