### PR TITLE
Converted popen2 to subprocess

### PR DESCRIPTION
**Pull request by SaltumDis**

### CODE REVIEW

**Comment by ericvaandering** [comment]
This is the only instance of the popen2 library. What about os.popen? We use that a lot.

**Comment by ericvaandering** [comment]
Looks to be still allowed but implemented under the hood with subprocess.

**Comment by ericvaandering** [comment]
@ticoann @amaltaro please review and merge. We will not deal with os.popen, at least now.

**Comment by ticoann** [comment]
Although it seems look fine but this probably need a test.

**Comment by amaltaro** [comment]
I'm going to test it today.

**Comment by ericvaandering** [comment]
@amaltaro @ticoann was this tested? Can it be merged?

**Comment by amaltaro** [comment]
I'm gonna run some quick tests on it as well.

**Comment by ticoann** [comment]
I ran the test before, and I didn't see any apparent problem. but It would be nice Alan can run the test as well.

**Comment by amaltaro** [comment]
@ticoann good to go

**Pull request merged**
