### PR TITLE
Trap mmap.ing empty file exception

### LINKED ISSUE #8368: JobStatusLite failing to read empty condor log
It complains about mmap'ing an empty file. I'll fix it if it pops up again
```
2017-11-28 22:09:23,479:139875628680960:INFO:BossAirAPI:About to complete 20714 jobs
2017-11-28 22:09:54,953:139875628680960:ERROR:SimpleCondorPlugin:No job report for job with id 3938 and gridid 20.137
2017-11-28 22:09:54,964:139875628680960:ERROR:SimpleCondorPlugin:No job report for job with id 4742 and gridid 24.141
2017-11-28 22:09:54,969:139875628680960:ERROR:SimpleCondorPlugin:No job report for job with id 4797 and gridid 24.196
2017-11-28 22:09:54,969:139875628680960:ERROR:BossAirAPI:Exception while completing jobs!
cannot mmap an empty file
2017-11-28 22:09:56,066:139875628680960:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMCore.BossAir.StatusPoller.StatusPoller object at 0x7f375eff0dd0> <@========== WMException Start ==========@>
Exception Class: BossAirException
Message: Exception while completing jobs!
cannot mmap an empty file
	ModuleName : WMCore.BossAir.BossAirAPI
	MethodName : _complete
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py
	ClassName : None
	LineNumber : 535
	ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py", line 527, in _complete
    self.plugins[plugin].complete(jobsToComplete[plugin])

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 312, in complete
    for matchObj in getIterMatchObjectOnRegexp(condorFilePath, WMEXCEPTION_REGEXP):

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/Lexicon.py", line 688, in getIterMatchObjectOnRegexp
    mm = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)

<@---------- WMException End ----------@>  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 183, in __call__
    tSpent, results, _ = self.algorithm(parameters)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/StatusPoller.py", line 70, in algorithm
    self.checkStatus()
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/StatusPoller.py", line 96, in checkStatus
    runningJobs = self.bossAir.track()
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py", line 495, in track
    self._complete(jobs=jobsToComplete)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py", line 535, in _complete
    raise BossAirException(msg)

2017-11-28 22:09:56,067:139875628680960:INFO:Harness:>>>Terminating worker threads
2017-11-28 22:09:56,183:139875628680960:ERROR:BaseWorkerThread:Error in event loop (2): <WMCore.BossAir.StatusPoller.StatusPoller object at 0x7f375eff0dd0> <@========== WMException Start ==========@>
Exception Class: BossAirException
Message: Exception while completing jobs!
cannot mmap an empty file
	ModuleName : WMCore.BossAir.BossAirAPI
	MethodName : _complete
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py
	ClassName : None
	LineNumber : 535
	ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py", line 527, in _complete
    self.plugins[plugin].complete(jobsToComplete[plugin])

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 312, in complete
    for matchObj in getIterMatchObjectOnRegexp(condorFilePath, WMEXCEPTION_REGEXP):

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/Lexicon.py", line 688, in getIterMatchObjectOnRegexp
    mm = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)

<@---------- WMException End ----------@>
Backtrace:
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 211, in __call__
    raise ex

2017-11-28 22:09:56,184:139875628680960:INFO:BaseWorkerThread:Worker thread <WMCore.BossAir.StatusPoller.StatusPoller object at 0x7f375eff0dd0> terminated
cmst1@vocms0256:/data/srv/wmagent/current $ 
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8368

I still have to update this patch on vocms0256 (changed one additional line here).
@ticoann if you agree with this change, I'll then backport it to 1.1.8 and also apply it to the new agents.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
Thanks Alan, patch looks good to me.

**Review by ticoann — APPROVED** [review]

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
only tests flipping success/failed. I'll backport it tomorrow and patch the other few agents.

**Pull request merged**
