### PR TITLE
delay archiving so wmstats can monitor workflow after 

### PR DESCRIPTION
**Pull request by ticoann**
(completed, announced)
fixes first part of #5563

### CODE REVIEW

**Comment by ticoann** [comment]
need to go with #5572

**Comment by ticoann** [comment]
@hufnagel, @lucacopa, Hi Dirk, Luis, I thought I sent email before but I might just draft it. :-)
Anyway, could we test this on Tier0 Agent. testbed is updated but if you want to test it on vm. I can set it up. This patch need to be update on Tier0 Agent for the test. Thanks,

**Comment by lucacopa** [comment]
@ticoann ok, I will run a test when I finish one that I am currently running. I am going to use the testbed endpoint, and update the tier0 agent with the path as you say.

**Comment by ticoann** [comment]
Thanks Luis

**Comment by lucacopa** [comment]
There is a problem, I am getting this error when starting TaskArchiver. It looks like you need to set endTime

Starting : TaskArchiver
Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/1.9.91/sw.pre.hufnagel/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch3/bin/wmcoreD", line 347, in <module>
    startup(config)
  File "/data/tier0/srv/wmagent/1.9.91/sw.pre.hufnagel/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch3/bin/wmcoreD", line 220, in startup
    componentObject = factory.loadObject(classname = namespace, args = config)
  File "/data/tier0/srv/wmagent/1.9.91/sw.pre.hufnagel/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch3/lib/python2.6/site-packages/WMCore/WMFactory.py", line 68, in loadObject
    module = __import__(module, globals(), locals(), [classname])
  File "/data/tier0/srv/wmagent/1.9.91/sw.pre.hufnagel/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch3/lib/python2.6/site-packages/WMComponent/TaskArchiver/TaskArchiver.py", line 19, in <module>
    from WMComponent.TaskArchiver.CleanCouchPoller import CleanCouchPoller
  File "/data/tier0/srv/wmagent/1.9.91/sw.pre.hufnagel/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch3/lib/python2.6/site-packages/WMComponent/TaskArchiver/CleanCouchPoller.py", line 85
    detail =False, endTime)
SyntaxError: non-keyword arg after keyword arg

**Comment by lucacopa** [comment]
For the testing I am setting instead:
detail =False, endTime = endTime)

**Comment by ticoann** [comment]
Thanks Luis, I updated the patch.

**Comment by lucacopa** [comment]
@ticoann Patch is working fine

**Pull request merged**
