### PR TITLE
'future_standard_library' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
Renames standard-library imports to their Py3 names and adds these two lines:
```
from future import standard_library
standard_library.install_aliases()
```
For example:

`import ConfigParser`

becomes:

```
from future import standard_library
standard_library.install_aliases()
import configparser
```

### CODE REVIEW

**Comment by ericvaandering** [comment]
Import in XMLUtils.py are in the wrong order.

**Comment by vkuznet** [comment]
@ericvaandering , Eric could you please clarify whats wrong with "wrong order". I don't think order of imports matters. May be you're saying that
```
from future import standard_library
standard_library.install_aliases()
from __future__ import (division, print_function)
```
should be
```
from __future__ import (division, print_function)
from future import standard_library
standard_library.install_aliases()
```

**Comment by vilnius-dev** [comment]
PSetTweakTest fails, not because of "imports" order. I am skipping this pull request for now.

**Comment by ericvaandering** [comment]
@vkuznet Yes, that's what I'm saying. That mistake causes all the deleted tests

**Comment by mapellidario** [comment]
This has been covered by #9762 . I would suggest closing the PR without merging

**Comment by amaltaro** [comment]
Thanks Roman and Dario for your effort! Closing it

**Pull request closed without merging**
