### PR TITLE
remove recursive call

### PR DESCRIPTION
**Pull request by ticoann**
remove recursive call, not sure about performance improvement but at least it is cleaner code.

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
I ran some performance test with this patch and without this patch. As expected, it is almost identical. (check how many same queries done within 1 seconds) But code is cleaner with this.

Without patch

```

2018-04-12 17:18:07,141:140272470337280:INFO:DBCore:XXXXXX YYYY done:
2018-04-12 17:18:07,141:140272470337280:INFO:DBCore:XXXXXX YYYY 12000: ['INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */\n               INTO dbsbuffer_file_location (filename, location)\n             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl\n             WHERE df.lfn = :lfn AND dl.pnn = :pnn\n          ']
2018-04-12 17:18:07,365:140272470337280:INFO:DBCore:XXXXXX YYYY done:
2018-04-12 17:18:07,365:140272470337280:INFO:DBCore:XXXXXX YYYY 11000: ['INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */\n               INTO dbsbuffer_file_location (filename, location)\n             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl\n             WHERE df.lfn = :lfn AND dl.pnn = :pnn\n          ']
2018-04-12 17:18:07,592:140272470337280:INFO:DBCore:XXXXXX YYYY done:
2018-04-12 17:18:07,592:140272470337280:INFO:DBCore:XXXXXX YYYY 10000: ['INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */\n               INTO dbsbuffer_file_location (filename, location)\n             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl\n             WHERE df.lfn = :lfn AND dl.pnn = :pnn\n          ']
2018-04-12 17:18:07,801:140272470337280:INFO:DBCore:XXXXXX YYYY done:
2018-04-12 17:18:07,801:140272470337280:INFO:DBCore:XXXXXX YYYY 9000: ['INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */\n               INTO dbsbuffer_file_location (filename, location)\n 
```

With patch
```

2018-04-12 17:40:16,087:140613369693952:INFO:DBCore:XXXXXX ZZZZ done
2018-04-12 17:40:16,088:140613369693952:INFO:DBCore:XXXXXX ZZZZ 193: 1000, INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */
               INTO dbsbuffer_file_location (filename, location)
             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl
             WHERE df.lfn = :lfn AND dl.pnn = :pnn
          
2018-04-12 17:40:16,338:140613369693952:INFO:DBCore:XXXXXX ZZZZ done
2018-04-12 17:40:16,338:140613369693952:INFO:DBCore:XXXXXX ZZZZ 194: 1000, INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */
               INTO dbsbuffer_file_location (filename, location)
             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl
             WHERE df.lfn = :lfn AND dl.pnn = :pnn
          
2018-04-12 17:40:16,577:140613369693952:INFO:DBCore:XXXXXX ZZZZ done
2018-04-12 17:40:16,578:140613369693952:INFO:DBCore:XXXXXX ZZZZ 195: 1000, INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */
               INTO dbsbuffer_file_location (filename, location)
             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl
             WHERE df.lfn = :lfn AND dl.pnn = :pnn
          
2018-04-12 17:40:16,829:140613369693952:INFO:DBCore:XXXXXX ZZZZ done
2018-04-12 17:40:16,829:140613369693952:INFO:DBCore:XXXXXX ZZZZ 196: 1000, INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX (dbsbuffer_file_location (filename, location)) */
               INTO dbsbuffer_file_location (filename, location)
             SELECT df.id, dl.id FROM dbsbuffer_file df, dbsbuffer_location dl
             WHERE df.lfn = :lfn AND dl.pnn = :pnn
```

**Review by amaltaro — APPROVED** [review]
Code looks good, Seangchan

**Comment by amaltaro** [comment]
Seangchan, how about we fix these pylints
```
W0102, line 40 in DBInterface.buildbinds: Dangerous default value [] as argument
W0105, line 96 in DBInterface.executemanybinds: String statement has no effect
W0105, line 112 in DBInterface.executemanybinds: String statement has no effect
W0102, line 123 in DBInterface.processData: Dangerous default value {} as argument 
```

I think the first one is a bit trickier, maybe just forget that one.

**Comment by ticoann** [comment]
Sorry Alan, I missed your comments. Actually, this has conflict with my other patch. I will update that patch and fix the pylint as well.

**Pull request merged**
