### PR TITLE
Use x509 attributes directly, rather than a classad expression to handle

### LINKED ISSUE #9331: Move x509 classad expression to handle Volunteer Schedd attributes from to condor configuration
The current classad expression:

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L142

Is used to remove the x509 proxy if the job matches to `T3_CH_Volunteer`. While this is possible with the `schedd.submitMany` condor submission method, it cannot be done using the new `htcondor.submit` method due to security constrains. 

Given that fact that we want to migrate to the new method (#9133), the proposed submission is to move this from the Agent and handle it at the submission infrastructure level (through job transforms in the schedd configuration in the volunteer machine).

With that, we can just pass the x509 attributes as string with the current method, and let the condor client fill those attributes with the new submit method in #9133

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #9331

This passes the x509 attributes rather than a classad expression that was created to handle proxy issues with `T3_CH_Volunteer`. The volunteer schedd(s) will handle that in the condor the configuration instead.
Condor changes will be applied to the volunteer schedd(s) only, through puppet rules [here](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/tree/qa/code/templates/modules/condor).

For reference, rules look like this:
```
JOB_TRANSFORM_NAMES = REMOVE_X509_ATTRS
JOB_TRANSFORM_REMOVE_X509_ATTRS = [ \
  Requirements = !isUndefined(x509userproxy) && isString(x509userproxy); \
  Copy_x509userproxy = "original_x509userproxy"; \
  set_x509userproxy = ifThenElse( \
   !isUndefined(MachineAttrGLIDEIN_CMSSite0) &&  \
   MachineAttrGLIDEIN_CMSSite0 =?= "T3_CH_Volunteer", \
      undefined, \
      strcat(original_x509userproxy)); \
]
```

EDIT: Keeping "Do not merge yet" label until we do the final test in the volunteer schedd.

### CODE REVIEW

**Comment by khurtado** [comment]
test this please

**Comment by khurtado** [comment]
test this please

**Comment by khurtado** [comment]
test this please

**Review by amaltaro — APPROVED** [review]
Changes look good to me, Kenyi. Could you please update your first comment saying that htcondor schedd changes are required (if a line or two only, you might even write down what change exactly need to be applied). Thanks

**Comment by amaltaro** [comment]
Just for the record, it has been applied to the volunteer schedd today.

**Comment by amaltaro** [comment]
@khurtado AFAIK there isn't anything refraining us from merging this PR, is there?

**Comment by khurtado** [comment]
@amaltaro correct, this can be merged.

**Pull request merged**
