### PR TITLE
If url sanitization fails, just return the original str

### PR DESCRIPTION
**Pull request by amaltaro**
@ticoann no need to merge it at the moment. I just wanted to check whether it's going to make some workqueue tests to succeed

### CODE REVIEW

**Comment by ticoann** [comment]
That is good it seems it did. I will trigger the test again. Whether it has the same result.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
I'm having a look at `WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testOpenBlocks`, but it seems all the other workqueue unit tests are passing jenkins now...

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Time to test these 3 unstable tests...

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann @ericvaandering I think I'm done with testing. It fixes at least 3 unstable tests, maybe some more but they are trick to test since they are flipping the final status from time to time.

I've also removed those from the unstable list.
Feel free to merge

**Comment by ericvaandering** [comment]
I just ran into one of the ones this is an issue with too. Real issue is that what is expected to be a string is actually None coming from CMSCouch. @ticoann want to merge?

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
I'll try to figure out why and what returns None.

**Comment by ticoann** [comment]
@amaltaro, Alan can we just close this since #7193 is in. If the url is passed with not a correct format I think it should throw the exception.

**Comment by amaltaro** [comment]
Yes! Closing this PR

**Pull request closed without merging**
