### PR TITLE
stop error messages on dashboard reporting of logarchives

### PR DESCRIPTION
**Pull request by hufnagel**
Get rid of spurious error messages in the dashboard reporting for logArchive, LogCollect and Sqlite output.

### CODE REVIEW

**Comment by hufnagel** [comment]
please test again

**Comment by amaltaro** [comment]
It will be great to get rid of these messages in the component :)
Dirk, it seems we don't need to initialize dataTier and procDataset, we can also remove the ifs in L255 and L257.

**Comment by hufnagel** [comment]
Restructured a bit more, should be easier to read now. I can see why the if not dataTier and if not procDataset statement where there, but it makes the code harder to read and the if not doesn't really save anything compared to getting the value again from the file info. Plus we usually do not have multiple files per output module, so I changed that too to make it more readable. Take a look.

**Comment by amaltaro** [comment]
Sounds good to me.  Would you mind running pylint in these 2 files? Some of its suggestions would be better to follow and move towards standardization of the code :-) E.g.:
```
pylint --rcfile=standards/.pylintrc src/python/WMCore/Services/Dashboard/DashboardReporter.py
```

**Comment by hufnagel** [comment]
I thought the DMWMBot is running pylint.

**Comment by hufnagel** [comment]
In general, I'll follow pylint if it complains about specific changed in my patch. I am NOT going to rework the rest of the code, that should be done in a separate issue.

**Comment by amaltaro** [comment]
It does. But you can always catch some error/warnings and good practices before committing your code e.g.(spaces here and there, trailing whitespaces, etc). 

You don't need to rework the whole code, just avoid injecting more warnings into the code. Variable names and line length are two cases that we cannot avoid, in general.

**Comment by ericvaandering** [comment]
It does run pylint, but it only complains if the code is really bad or if your patch makes it worse, I think. Of course it can be made to do something different if you feel it’s helpful. It also ignores anything that is a “C” warning.

Eric

On Aug 3, 2015, at 07:21, Dirk Hufnagel <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought the DMWMBot is running pylint.

—
Reply to this email directly or view it on GitHub<https://github.com/dmwm/WMCore/pull/6092#issuecomment-127216391>.




Eric W. Vaandering
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 840 6678 office
www.fnal.gov<http://www.fnal.gov/>

**Comment by hufnagel** [comment]
Had to change the patch slightly as it was conflicting with some other changes (and I didn't want to integrate everything into a single pull request).

**Comment by hufnagel** [comment]
Ok, I might have to rework this a bit further. Please don't merge yet.

**Comment by hufnagel** [comment]
retest this please

**Comment by hufnagel** [comment]
So how can I see the details of why the checks failed ? The 'Details' link doesn't work.

**Comment by ericvaandering** [comment]
Yeah, the “details” points to the wrong URL, but I can’t change that and if Shazad changes it, it breaks Offline’s tests. So we leave it for now. That’s why I put that first message there, which should give you the right “Details”.

However, when Jenkins actually fails, it’s because the tests actually fail to run, not because of some criteria on the tests. For instance, if you follow this through you can end up here: https://cmssdt.cern.ch/jenkins/job/DMWM-PR-unittests/SLICE=0,label=slc6_amd64-cloud/103/console (the console log for one slice for the test that failed). In this case, CherryPy refused to shut down…. But the last two tests have had a lot of failures and one looked like a deployment failure, so maybe something is up with a node.

I’ve tried a couple of things to try to get failing slices to re-run, but no luck so far…

Eric



On Aug 3, 2015, at 4:58 PM, Dirk Hufnagel <notifications@github.com<mailto:notifications@github.com>> wrote:


So how can I see the details of why the checks failed ? The 'Details' link doesn't work.

**Comment by hufnagel** [comment]
retest this please

**Comment by hufnagel** [comment]
Will rework and extend this, closing for now.

**Pull request closed without merging**
