### PR TITLE
converting stringIO #6935

### PR DESCRIPTION
**Pull request by SaltumDis**

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
There is a legitimate error here:

```
Traceback (most recent call last):
  File "/build/cmsbuild/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/7/label/slc6_amd64-cloud-tiny/deploy/1.0.19.pre4/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/build/cmsbuild/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/7/label/slc6_amd64-cloud-tiny/code/test/python/PSetTweaks_t/PSetTweak_t.py", line 97, in testE
    tweak2.unpersist(persistFile)
  File "/build/cmsbuild/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/7/label/slc6_amd64-cloud-tiny/code/src/python/PSetTweaks/PSetTweak.py", line 403, in unpersist
    jsoniser.dejson(json.load(StringIO.StringIO(jsonContent)))
TypeError: initial_value must be unicode or None, not str
```

**Comment by ericvaandering** [comment]
Looks good. All we ask before this is ready to merge is that you squash your commits. Our "standard" is to have few commits and none of them "fixing" problems with earlier commits.

**Comment by ericvaandering** [comment]
Looks good to me @ticoann . Can you merge after your review?

**Comment by ticoann** [comment]
Thanks, I will run the test tomorrow and include in testbed update.

**Comment by ticoann** [comment]
@SaltumDis, Adelina, could you briefly state what is this change about in the initial description box.
I am not completely sure about the difference. Is following statement true?

https://docs.python.org/2/library/stringio.html

StringIO.StringIO,  - accept 8 bit  and unicode as input
io.StringIO - only unitcode as input
cStringIO.StringIO - accept 8 bit input

and cStringIO is not supported in python3.

That means all the input need to be unicode at least for the place StringIO.StringIO was used, correct?

I will merge this probably after the cmsweb validation after thorough test in all stages, cmsweb, wmagent and workernode

**Comment by SaltumDis** [comment]
@ticoann, yes, cStringIO is not supported in Python3.
io.StringIO - accept Unicode
StringIO.StringIO - accept Unicode or 8-bit strings
cStringIO.StringIO  accepts Unicode, that can be encoded as plain ASCII strings, or 8-bit strings

And yes, in general we should always use unicode

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
And where do we stand on getting this in?

**Comment by ticoann** [comment]
I think I ran the test before and it was OK. But I will try to rerun the test

**Comment by ericvaandering** [comment]
test this please

**Pull request closed without merging**
