### PR TITLE
skip wq info collection for tier0

### LINKED ISSUE #8020: Disable local WQ monitoring for T0 agents
This code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py#L117-L120

cannot run for Tier0 agents, since they don't install/run WorkQueueManager and they don't use global workqueue.

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8020

### CODE REVIEW

**Comment by ticoann** [comment]
FYI John, @johnhcasallasl,

**Review by amaltaro — APPROVED** [review]
Precisely the same fix I'd have done. Thanks!

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@hufnagel, @johnhcasallasl,  this was included in new Tier0 agent, right?

**Comment by hufnagel** [comment]
Why would it ? Latest Tier0 release uses 1.1.4.patch3.

**Comment by hufnagel** [comment]
AgentStatusWatcher seems to be working in our replays so far (well, the component doesn't crash at least). If this is a mandatory patch, will it be merged into the 1.1.4_wmagent branch ? I would prefer that to adding it manually to the Tier0 deployment.

**Comment by ticoann** [comment]
I can create and merge to 1.1.4_wmagent branch

**Pull request merged**
