### PR TITLE
Add unit tests to FWJR generator and dashboard reporting on local vs. fallback

### PR DESCRIPTION
**Pull request by ericvaandering**
Add FWJRs for local and remote reads of two file workflows, unit tests to FWJR generator and dashboard reporting on local vs. fallback

### CODE REVIEW

**Comment by ericvaandering** [comment]
@ticoann please review and merge. Then it would be good to test for real because communicating with dashboard is never as trivial as it seems. @chwissing should tell us if deploying this can wait for a regular bi-monthly WMAgent release or not.

**Comment by chwissing** [comment]
Hi Eric et al.,
since this has been pending for so long, it does not matter to wait for the next regular release. Can you remind me for which data this is scheduled?

**Comment by amaltaro** [comment]
There is no specific schedule for WMAgent redeployment, but it would be either by mid of August (not sure we'll manage to push what we intend to) or just after the production CMSWEB deployment (first fortnight of September).

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@amaltaro can we test this patch in a "real" workflow or two? And then see if Julia can find the data we insert?

**Comment by amaltaro** [comment]
Sure, just sent some work in for vocms0230. I'll check back on Monday.

**Comment by ericvaandering** [comment]
Awesome

**Comment by amaltaro** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ticoann** [comment]
Alan, can this be merged?

**Comment by ericvaandering** [comment]
It's running OK, but it's not clear it's sending exactly the right thing to the dashboard. Should know more in a few days, but if you are wanting to put together a release, I would include it.

(Yes, I know I am not @amaltaro :-)

**Comment by ticoann** [comment]
Thanks Eric, I am testing wmstats server. But I will make a another release later this week or early next week. So I will wait Alan's green light.

**Pull request merged**
