### PR TITLE
Do not crash JobUpdater in case of couch issues

### PR DESCRIPTION
**Pull request by amaltaro**
Created a new CouchConflictError exception. If that happens to JobUpdater, just skip these updates to the next cycle. I'll try to run basic tests, but I cannot simulate the exception since we have a single agent in the same team in testbed.
@ticoann , please review.

### CODE REVIEW

**Comment by ticoann** [comment]
Thanks Alan, Actually, I think you need to import 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/CMSCouch.py#L1004
instead of creating new Exception class. Isn't that the one is actually raised? Otherwise, patch looks good.

**Comment by amaltaro** [comment]
Oups, I didn't see that exception, sorry. Ok, just updated the patch. Please take one more look at it :-)
If everything is ok, then I'll create it to the master branch as well.

**Comment by ticoann** [comment]
Everything looks fine to me. Thanks,

**Comment by amaltaro** [comment]
Ok, production agents have this patch in now. Thanks

**Comment by amaltaro** [comment]
Fixes #5817 , feel free to merge it

**Pull request merged**
