### PR TITLE
'cmp' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
`past.builtins.cmp(x, y) → integer`

> Return negative if x<y, zero if x==y, positive if x>y.

[[source]](http://python-future.org/_modules/past/builtins/misc.html#cmp)

-----------------------------------------------------------------------------

> ### Python 2 only:
> `assert cmp('a', 'b') < 0 and cmp('b', 'a') > 0 and cmp('c', 'c') == 0`

> ### Python 2 and 3: alternative 1
> `from past.builtins import cmp`
> `assert cmp('a', 'b') < 0 and cmp('b', 'a') > 0 and cmp('c', 'c') == 0`

> ### Python 2 and 3: alternative 2
> `cmp = lambda(x, y): (x > y) - (x < y)`
> `assert cmp('a', 'b') < 0 and cmp('b', 'a') > 0 and cmp('c', 'c') == 0`

### CODE REVIEW

**Comment by ericvaandering** [comment]
This is just changing the behavior of one line of code. Better to just rewrite that code in a better way.

**Comment by ericvaandering** [comment]
I'd suggest following this recipe here and getting rid of cmp entirely

https://stackoverflow.com/questions/72899/how-do-i-sort-a-list-of-dictionaries-by-values-of-the-dictionary-in-python

**Comment by vkuznet** [comment]
@vilnius-dev , any progress on this? Please take Eric's advise and re-write code to use specific key for comparison.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann should be good to merge. @vilnius-dev has removed the problematic code with a more pythonic way of doing this.

**Pull request merged**
