### PR TITLE
Recycling sandbox

### PR DESCRIPTION
**Pull request by mmascher**
This is the WMCore part of https://github.com/dmwm/CRABServer/issues/4948

Please, wiat my green light before merging it, I have to think about possible backward compatibility issues.

### CODE REVIEW

**Comment by ericvaandering** [comment]
You need to fix these " Dangerous default value [] as argument" errors, even if you didn't introduce them.

**Comment by ticoann** [comment]
retest this please

**Comment by ticoann** [comment]
@mmascher, Hi Marco, this is not still ready for merge, right?

**Comment by mmascher** [comment]
Hi, I need to take into account Eric's (simple) comment first. The "retest this please" was for me, are there failing tests?

**Comment by ticoann** [comment]
> Hi, I need to take into account Eric's (simple) comment first. The "retest this please" was for me, are there failing tests?

No it wasn't. But since yesterday, all the pull request is failing the test. I just want to know whether there was problem in jenkins or caused by something I merged.

**Comment by ericvaandering** [comment]
All these failures are from my inadvertently linking my attempt at testing CRAB code to the WMCore github. :-( That's resolved. But please, do not pay attention to the green status just yet. You have to *look* a the unit tests that are failing and if you think the pylint stuff is serious enough to warrant a further patch.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@mmascher, Marco, can this be merged?

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@mmascher, Marco, can this be merged?

**Pull request merged**
