### PR TITLE
fix the job report when ther is no possible matching site

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan please review

### CODE REVIEW

**Review by ericvaandering — CHANGES_REQUESTED** [review]
On line #3 we're turning off detection of one of the more dangerous features of python. Can you remove that and then fix any errors it actually turns up?

**Review by amaltaro — CHANGES_REQUESTED** [review]
I'm not sure it will really fix the problem, but sounds good :)
Can you also update this code please:
https://github.com/ticoann/WMCore/blob/396abf16f8790398d996a2da66dc2a8b6188a059/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L432
?
We shouldn't have any old jobs out there and, to be on the safe side you could use `job.get()` in the `if`

**Comment by ticoann** [comment]
@ericvaandering, @amaltaro,  Eric, Alan, please review again updated what you suggested.

**Review by ericvaandering — APPROVED** [review]

**Comment by ticoann** [comment]
@amaltaro, Alan I updated the patch, could you review again?

**Comment by amaltaro** [comment]
test this please

**Review by amaltaro — APPROVED** [review]

**Pull request merged**
