### PR TITLE
change rev to revision for initial revision

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan please review. As we discussed, I changed the rev to revision for initial setting as well.
Still need to run the test.

### CODE REVIEW

**Comment by amaltaro** [comment]
Do we actually need to set it for new docs?

**Comment by ticoann** [comment]
We do otherwise we have to call separately with new_edit flag = false.

**Review by amaltaro — APPROVED** [review]
Thanks, Seangchan. 
Changes look good, even though I still don't fully understand this feature and can't make sense of what's written in the page 244 of the couch documentation:
https://media.readthedocs.org/pdf/couchdb/1.6.1/couchdb.pdf

which explicitly says we need to provide _id and _rev values for bulk_docs update (but hey, where is _rev in all this?!?)

**Comment by amaltaro** [comment]
Closing this one in favor of #8907

**Pull request closed without merging**
