### PR TITLE
improve the job matching attributes

### PR DESCRIPTION
**Pull request by amaltaro**
Trying to synchronize analysis and production classAds (job matching). Arguments taken from this elog
https://cms-logbook.cern.ch/elog/GlideInWMS/1328

@ticoann Do not merge it yet. Further discussion and testing are required.
Need to check the glidein/factory parameters with @Farrukh-Aftab @vasoto
And I guess @ericvaandering @hufnagel and @belforte will want to take a look

### CODE REVIEW

**Comment by belforte** [comment]
code looks good to me, but indeed there's nothing like running it and looking at JDL which comes out

**Comment by amaltaro** [comment]
ping @vasoto and @Farrukh-Aftab

**Comment by ticoann** [comment]
Can this be merged?

**Comment by amaltaro** [comment]
We didn't hear anything back from Factory and Frontend folks yet. If they don't apply these changes, then it's not going to work anyways...
BTW, Tapas also made a PR to fix the same issue a long time ago (#5262). This one seems to be more flexible according to the scramArch (but maybe too flexible/complex)
@ericvaandering , can you check them and pick one please? Then we follow from there and bug others to apply these changes on their side.

**Comment by ericvaandering** [comment]
I think this is being sorted out in the e-mail thread, right?

**Comment by amaltaro** [comment]
I hope :-)

**Comment by belforte** [comment]
I hope too. Let's try.

**Comment by belforte** [comment]
.hmmm... see:
https://cdcvs.fnal.gov/redmine/issues/5606#change-20510

**Comment by ticoann** [comment]
@amaltaro, Alan, what is the status of this patch?

**Comment by amaltaro** [comment]
It's not moving. I'm bugging glideinwms people again...

**Comment by ericvaandering** [comment]
retest this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Since it's been created since the beginning of 2015 and it still opened, I think people don't really care. Closing it

**Pull request closed without merging**
