### PR TITLE
handle only valid files

### PR DESCRIPTION
**Pull request by ticoann**
additional fix for #5590

### CODE REVIEW

**Comment by ticoann** [comment]
It seems that main problem is pileup still getting invalid files from dbs.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py#L56
I updated the patch to filter out invalid files. However, this is a hacky way to do it. I think dbs api should return valid files only by default and invalid files if the fag is set. However, that api changes could break other code, we can have default value set to return including invalid block as it is. Need to discuss with Yuyi. @yuyiguo

**Comment by ticoann** [comment]
Also need to check returns all the files (invalid ones) ? 
listFileParents 
listFileLumis 
listFileSummaries

**Comment by yuyiguo** [comment]
listFileLumis(validFileOnly=1, ...) return valid file only.
listFileSummaries(validFileOnly=1, ...)  return valid file only.
listfileParents (logical_file_name=Child-lfn) if Child-lfn is valid, all prents have to be valid otherwise, there must be something wrong in the DB. If Child-lfn is invalid, no call needed.

**Comment by amaltaro** [comment]
@ticoann , it seems this patch is really solving the invalid files issue.
In our 2 test workflows, I have not seen any failure related to the invalid/bad PU file:
/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root

IMO we can now abort those test workflows and already push it to production. What do you think?

**Comment by ticoann** [comment]
Thanks Alan, go ahead please.

**Pull request merged**
