### PR TITLE
Implement minute heartbeat for the components and monitor it

### LINKED ISSUE #8109: Agent in red in wmstats but no components/details given
It looks like I finally found the reason for it - I think - this might be triggered when we have a component down but without any component details. This is an example of my agentInfo doc:
```
   "down_components": [
       "PhEDExInjector"
   ],
   "timestamp": 1504025561,
   "down_component_detail": [
   ],
   "agent_version": "1.1.6.pre7"
```

I'll debug it further tomorrow, just wanted to keep it recorded.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8109

Changes so far are:
* while the threads are sleeping, send a heartbeat every 60secs;
* monitor heartbeat (last_updated) based on update_threshold (decreased from 6000 to 1800). Ideally it should be smaller, like 10min, but I'm afraid there are components that may spend > 10min in a busy cycle;
* update the db with a (nice) error when a worker thread is gracefully terminated (TODO: update all the components overriding it).

### CODE REVIEW

**Comment by amaltaro** [comment]
@ticoann no need to review it yet. However, I do have a couple of questions about code that can be possible removed.

I can't find this stuff
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/Agent/Flow
being used anywhere. Apparently it comes from the ProdAgent era.

And second is about the database backends
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/Agent/Database
we have setup for both couchdb and sqllite.

Should we go ahead and remove all that code?

**Comment by amaltaro** [comment]
Seangchan, I still have to fix the unit test and the terminate method, but would you mind having a look at this patch, please? Thanks

**Comment by amaltaro** [comment]
Finally \o/

@ticoann since you haven't created a tag yet, how about you review&merge this PR and then cut a new tag for the weekend?

I still have work to do regarding these components monitoring, but I think it will be mostly agent side now.

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
@amaltaro, Alan patch looks good.

**Pull request merged**
