### PR TITLE
fix indentation

### PR DESCRIPTION
**Pull request by ticoann**
@ericvaandering, Do you want me to fix more pylint issues? 
I didn't fix unused variable warning since they are inside for in statement.  Or do you prefer to use '_'  for that?

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
Here's the problem with messing with setup.py: It runs the test. Screw it up and the tests don't run:

```
python setup.py install --prefix=../install
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    data_files=list_static_files())
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/setup_build.py", line 119, in list_static_files
    static_files.extend(data_files_for('%s/src/%s' % (get_path_to_wmcore_root(), language)))
  File "/build/cmsbld/jenkins-workarea/workspace/DMWM-PR-unittests/SLICE/6/label/slc6_amd64-cloud-tiny/code/setup_build.py", line 88, in data_files_for
    localfiles = [os.path.join(rel_path, f) for f in filenames]
NameError: global name 'filenames' is not defined
```

**Comment by ticoann** [comment]
Sorry Eric, did you have to run manually to find out the exact error?

**Comment by ericvaandering** [comment]
No. Just followed links from "details" for the "default" test. Then I clicked through to find the log file for a particular test slice.

**Comment by ticoann** [comment]
There are still some pylint errors. But indentation is fixed. Merging it for DAS rpm creation.

**Pull request merged**
