### PR TITLE
filter missing PNN PSN mapping for MSS and Buffer

### LINKED ISSUE #6371: Filter MSS, Buffer and Export endpoints?
I see several messages like
2015-10-30 17:25:08,682 WARNING  SiteDB: No PSNs for PNN: T1_ES_PIC_Buffer
2015-10-30 17:25:08,690 WARNING  SiteDB: No PSNs for PNN: T1_ES_PIC_MSS

in the testbed workqueue and I was wondering whether we should filter out such PNNs in the code to avoid flooding logs of warnings. @ticoann what do you think?

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6371

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan please review

**Comment by amaltaro** [comment]
Cool, thanks for fixing it :)

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Pull request merged**
