### PR TITLE
Emit workqueue elements with 0 Jobs

### PR DESCRIPTION
**Pull request by amaltaro**
As reported in the last comment of #7445
I was surprised I could not find any of those 2 requests in this view.

This problem is hitting us right now in production. We have to discuss with cmsweb team to see how we handle this case.

### CODE REVIEW

**Comment by amaltaro** [comment]
And the second commit addresses other WorkQueue views that could be affected by the Jobs value (besides a Available typo).

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
Alan, except jobInjectStatusByRequest/map.js other code was not modified for this deployment, right? I was wondering how Jobs == 0 is legit case in first place.  Which splitting algo allows Jobs == 0?

**Comment by ticoann** [comment]
Actually there is one missing view which cause this problem.  jobStatusByRequest. 
I will create the new branch patch on top of this

**Comment by ticoann** [comment]
Never mind of above comments. You fixed all. Sorry.

**Comment by ticoann** [comment]
I think this doesn't need to be merged. #7618 should guarantee valid WQE has to have jobs more than 1. If we get Jobs == 0 that would be error case and we should investigate.
We can check before the next deployment whether there is remaining WQE with Jobs == 0.

**Review by ticoann — COMMENTED** [review]
This might not be needed anymore.

**Comment by amaltaro** [comment]
But 7618 will go only in the next production upgrade and it may be that there are 0 jobs wqe in production already, though we can manually fix those. In the end I agree with in not adding code that should be cleaned in a month or two.

I'll make another PR to fix only the analytics view. I'm closing this one then.

**Pull request closed without merging**
