### PR TITLE
Minor bugfixes for resource control

### PR DESCRIPTION
**Pull request by amaltaro**
Fixed a race condition where couch view would return no agents on that team (thus a division by zero).
Fixed a typo.
Removed code unused.
And fixed condor plugin complaints when changing site state with 0 jobs executing in the system.

@ticoann please review. initial tests look good.

### CODE REVIEW

**Comment by amaltaro** [comment]
It should be suggesting isinstance(taskType, list) instead, but I guess it's not that smart. Fixing it...

**Comment by ticoann** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ticoann** [comment]
patch looks good to me. merging it

**Pull request merged**
