### PR TITLE
add couch view to check wqe summary

### PR DESCRIPTION
**Pull request by ticoann**
tested the view but need to add unittest

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
The failing test doesn't seems to be related to the patch.

@ericvaandering, also I couldn't find the following test in our test suite 
Api_t.Tester:test_accept_good_gif2 changed from success to error

**Comment by ericvaandering** [comment]
```
Nakuru:cmssw ewv$ cd ~/DMWM/WMCore
Nakuru:WMCore ewv$ git grep test_accept_good_gif2
test/python/WMCore_t/REST_t/Api_t.py:    def test_accept_good_gif2(self):
Nakuru:WMCore ewv$ 
```

**Comment by ticoann** [comment]
Thanks Eric, It seems the report some how didn't show whole path only for that test. (That test doesn't seem to be related either), running the test one more time.

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
It never shows the whole path. It shows the module, class, and function names.

**Comment by ticoann** [comment]
Hmm, but other report does.

WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:test0eventBlock changed from error to failure

**Comment by ericvaandering** [comment]
You are right. Hmm. Those tests also don't work with other tests in a Docker container. Nothing but trouble.

**Comment by ticoann** [comment]
I will make problematic testing unstable. unittest related to the changes seems to work fine and I also ran integration test. I am merging this.

Following test will be unstable. 
Api_t.Tester:test_accept_good_gif2 changed from success to error
WMCore_t.Services_t.pycurlFileUpload_t.PyCurlRESTServer:testFailingFileUpload changed from error to failure
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:test0eventBlock changed from error to failure
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testPrioritiesWorkPolling changed from success to failure

**Pull request merged**
