### PR TITLE
temp script to kill workflow in the agent

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Seems to work fine, I've just used it to kill an aborted workflow in cmssrv217.
You may want to add `.py` extension to it though

**Comment by amaltaro** [comment]
Oh, I guess you want to execute it in the following way
`$manage execute-agent kill-workflow-in-agent workflow_name`

if so, then just make it executable and it's Ok to be merged from my side.

**Comment by amaltaro** [comment]
@ticoann you can merge this one as well

**Pull request merged**
