### PR TITLE
Update to use both psutil 0.6.1 and 3.1.1

### LINKED ISSUE #6153: Upgrade psutil
We are using a super old version of python psutil. We will need to upgrade. Instructions here are

http://grodola.blogspot.com/2014/01/psutil-20-porting.html

### PR DESCRIPTION
**Pull request by ericvaandering**
Fixes #6153

### CODE REVIEW

**Comment by ericvaandering** [comment]
Let's hold off on a merge. I'm going to try to clean up some of these complaints.

**Comment by ericvaandering** [comment]
Ok, @ticoann can be merged when the tests come back. This should work just fine now and when @geneguvo update psutil and we pick it up, it should continue to work. I opened an issue for the after cleanup as well: #6214

**Comment by ticoann** [comment]
retest this please

**Comment by ericvaandering** [comment]
Why? It's good to merge IMO.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Sep 4, 2015, at 15:27, ticoann <notifications@github.com<mailto:notifications@github.com>> wrote:


retest this please

**Comment by ticoann** [comment]
It was showing the test failed notice but there was no list of failed test. (And I don't think it should have failed test) I was wondering why it marked as test failed. That is why I trigger retest

**Comment by ericvaandering** [comment]
Pylint

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Sep 4, 2015, at 15:42, ticoann <notifications@github.com<mailto:notifications@github.com>> wrote:


It was showing the test failed notice but there was no list of failed test. (And I don't think it should have failed test) I was wondering why it marked as test failed. That is why I trigger retest

**Comment by ticoann** [comment]
So if the pylint score is too low it show the fail too?

**Comment by ericvaandering** [comment]
Yes. In fact right now the github status does not pay attention to the unit test status because it's not stable.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Sep 4, 2015, at 16:07, ticoann <notifications@github.com<mailto:notifications@github.com>> wrote:


So if the pylint score is too low it show the fail too?

**Pull request merged**
