### PR TITLE
Cleanup JobCreator_t.py

### PR DESCRIPTION
**Pull request by ericvaandering**
including changing to set literals for @amaltaro

### CODE REVIEW

**Comment by amaltaro** [comment]
wonderful! :)

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ericvaandering I guess there are still a few warnings/errors that you could get rid of? :)

**Comment by ericvaandering** [comment]
Three of these tests are just commented out which is maybe the biggest source of warnings. But it seems they might be useful at some point?

**Comment by amaltaro** [comment]
Hmm, yes, I think so. How about decorating them with `performance` then? If performance unittests are picked up by jenkins, then we could use `integration`, right?

**Comment by ericvaandering** [comment]
Ok, this is as good as it will get. @ticoann please merge when Jenkins comes back.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann please merge

**Pull request merged**
