### PR TITLE
Adapting Reco performance report to new DQM API. Fixes #5356

### LINKED ISSUE #5356: Adapt API changes of DQM GUI to Reco performance reporting
Can't assign the issue to myself, but found interesting to post a ticket to explain the problem and reference it in the pull request coming soon.

DQM GUI changed their API, by the time that Reco perf reporting was written, this is how a relevant part of the JSON looked like :

```
        "xaxis": {
            "title": "instantaneous luminosity [10^{30} cm^{-2}s^{-1}]",
            "first": {
                "id": 1,
                "value": 0
            },
            "last": {
                "id": 1000,
                "value": 10000
            }
```

These days it is :

```
        "xaxis": {
            "title": "instantaneous luminosity [cm^{-2}s^{-1}]",
            "first": {
                "id": 1,
                "value": 0
            },
            "last": {
                "id": 1000,
                "value": 1e+34
            }
        }
```

This breaks compatibility to the old way and settings, resulting in no report at all even when there is interesting data.

However this is much better as it tells the real, same scale as the plot, and we don't have to know/guess it. Taking the chance of this feature I will also change how Ops will possibly configure the reported range. 

Patch already exists in my machine, testing so pull request can be sent. @lucacopa will be happy to know  about this as he was the one testing Reco Perf reporting on T0 Replays.

### PR DESCRIPTION
**Pull request by samircury**
All the details are in #5356 , but looking at the diff you can also see how DQM JSON changed. I updated the code to work with it and also updated the fake inputs for the unit test.

Unit tests work on my machine, maybe we want to test it in a T0 Replay before merging. @lucacopa , if you apply this patch in an ongoing/future replay we can see data being uploaded to DashBoard.

Unit test (with instrumentation) output : 

```
got 24 worth points
----------------------------------------------------------------------
Ran 1 test in 65.363s
OK
```

### CODE REVIEW

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by samircury** [comment]
I was waiting for 2015 results to conclude if this work would actually be applicable (in case peak reconstruction time was way too high at 13 TeV). It was in need of some final patching before it'd work in production.

Marco Rovere's paper shows that it's not (page 7) : 

http://iopscience.iop.org/article/10.1088/1742-6596/664/7/072040/pdf

So I'll have the patches living in my branch and this PR, but I'll declare this as not necessary for now. @amaltaro or others, feel free to close the PR.

**Comment by amaltaro** [comment]
Thanks for your feedback @samircury . Closing this PR due to the many years of lack of activity and follow-up.

**Pull request closed without merging**
