### PR TITLE
Wrap sendAlert() in a try/except block.

### LINKED ISSUE #10464: MSTransferor fails to send alerts through Alertmanager
**Impact of the bug**
MStransferor

**Describe the bug**
Following the lead from this Jira ticket [1] we figured out that in some cases MSTransferor fails to send alerts through the newly established mechanism with the AlertManager as a mediator for the alerts.   

Based on the trace provided in the Jira ticket [3] the MSTransferror is just trying to generate an alert for a big dataset (nothing unusual so far), but the url to the Alertmanager itself has been lost somewhere on the way. As mentioned also in this stackoverflow reply [2] this type of badly expressed error is generated by `pycurl` when the url is `None`. I hope this is lost somewhere up in the chain but not in the `@portForward` decorator.

Another critical question that needs to be answered is whether MSTransferor keeps creating input rules over and over for the same input data, similarly to a previously observed cases. 

**How to reproduce it**
To be investigated what exactly has triggered the bug.

**Expected behavior**

**Additional context and error message**
[1]
https://its.cern.ch/jira/browse/CMSCOMPPR-18772

[2]
https://stackoverflow.com/a/34402229

[3]
```
2021-04-21 06:14:09,570:ERROR:MSTransferor: Unknown exception while making Transfer Request for pdmvserv_task_TOP-RunIISummer20UL17MiniAODv2-00043__v1_T_210414_061607_9526     Error: unsetopt() is not supported for this option
Traceback (most recent call last):
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 208, in execute
    success, transfers = self.makeTransferRequest(wflow)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 628, in makeTransferRequest
    blocks, dataSize, nodes, idx)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 727, in makeTransferRucio
    self.notifyLargeData(aboveWarningThreshold, transferId, wflow.getName(), dataSize, dataIn)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 755, in notifyLargeData
    self.alertManagerApi.sendAlert(alertName, alertSeverity, alertSummary, alertDescription, self.alertServiceName)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/AlertManager/AlertManagerAPI.py", line 93, in sendAlert
    res = self.mgr.getdata(self.alertManagerUrl, params=params, headers=self.headers, verb='POST')
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 316, in getdata
    encode=encode, decode=decode, cookie=cookie)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 280, in request
    verbose, verb, doseq, encode, cainfo, cookie)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 221, in set_opts
    curl.setopt(pycurl.URL, encodeUnicodeToBytes(url))
TypeError: unsetopt() is not supported for this option
```

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #10464 

#### Status
Ready

#### Description
While using the old mechanism for sending alerts from `MSTransferor` we were not trying to handle exceptions at place, when it comes to sending alerts. But this was breaking the creation of the Rucio rules for a  given data block. Or more precisely it was calling Rucio successfully and creating all the necessary rules, and only when it was about some large blocks(which were exceeding the so configured threshold), it was trying to send alerts which from times to times may break, due to a plethora of reasons [1]. In result the function call `self.makeTransferRucio()` was never able to succeed and the call for the given DID was retried every  MSTransferor polling cycle with one and the same RSE list, while the workflow was sitting in `assigned`. In general Rucio is able to protect us from situation like this because it does not recreate already existing rules. A side effect of such behavior, though, is that in case any of the RSEs which are to be used for these rule submissions gets out of quota (i.e. for a reason not related to our broken workflow) `MSTransferor` drops it from the list of RSEs for this DID and in result the new rule to be created is not considered as duplicate and then Rucio creates a brand new rule, which leads to the over replication. 

The current PR aims to enclose the the call to the alertManager in order to avoid situation as the one explained above. 

[1]
https://github.com/dmwm/WMCore/blob/5da7f3c898bb39cdb7efb64070af182419501602/src/python/WMCore/MicroService/MSTransferor/MSTransferor.py#L727

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/83
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/84
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/85
and configuration for MSOutput
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/86
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/87
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/88

#### External dependencies / deployment changes
In order to fix the actual issue we also need to provide the proper PR in the gitlab K8 configuration repository for adding the correct `AlertManagerUrl` to the `MSTransfferor` configuration

### CODE REVIEW

**Review by amaltaro — COMMENTED** [review]
Thanks for providing this fix, Todor. It looks good to me.
However, I'm only approving it once we also have the relevant configuration changes linked in this PR :-D (can you also please update the initial description? There is one field with the placeholder content).

**Comment by todor-ivanov** [comment]
Hi @amaltaro I am getting there (to the PR with the proper configuration changes) really soon ... The problem is I cannot manually generate an alert with the `AlertManaterAPI` and the correct url (which is now known). That's why I've put status "Need more testing". I suspect some more changes to the code may be needed here and there.

**Comment by todor-ivanov** [comment]
Hi @amaltaro,
Now we have the full picture. I just made the three PRs in the K8 `service-config` repository and please take a look at my second commit to the current PR which reflects  a change that we need to make in the current `alertManagerAPI` class in order to use the proper api version, as it is explained in the prometheus documentation  [1]. I decided to split the Url from the Uri and keep the  former in the service config, while the later to be in the code, but if you or @goughes  think otherwise, just let me know.

[1]
https://www.prometheus.io/docs/alerting/latest/clients/

**Comment by amaltaro** [comment]
@todor-ivanov these changes look good to me.

I have two questions though:
*) did you manage to run a basic test with these changes? If so, then I think we can run a final test in the production POD, and if things go through, then we make a new release and ask Imran to push that in as soon as images are available.
*) MSOutput also relies on AlertManager. Perhaps you could update those 3 merge requests in gitlab for ms-output as well? Creating new MR is fine as well.

**Review by amaltaro — APPROVED** [review]
Thanks Todor, these changes look good to me.
I added the MSOutput configuration merge requests to the PR initial description.

Are you done testing these changes? Please also update it in the PR description.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro ! Yes I am done with all the tests needed. Sorry for not reflecting this in the PR description.

**Comment by amaltaro** [comment]
Thanks Todor.

**Pull request merged**
