### PR TITLE
Allow -fake- Campaign arg at chain level

### PR DESCRIPTION
**Pull request by amaltaro**
As requested by @vlimant and @anorkus, allow `Campaign` to be set at task/step level as well, during creation time. It has no meaning in the WMCore code, it's still a request argument and the system will only use the top level argument.

### CODE REVIEW

**Comment by vlimant** [comment]
hey @amaltaro out of curiosity, how is it used at the top level ?

**Comment by amaltaro** [comment]
Campaign gets propagated to WMArchive and AFAIR it's part of the dbs meta-data, at least.

**Comment by vlimant** [comment]
if it is a dataset dbs-meta-data, then it makes sense to have it per task (same as prepid), acquisition era, ... i.e. it should not remain "fake"

**Comment by amaltaro** [comment]
Nope, I was wrong, it's not part of the dbs meta-data.

@ticoann I did a few basic tests and everything looks fine. Once jenkins are happy, please merge. If something needs to be changed, please make a new PR or I'll fix it tomorrow morning.

**Comment by ticoann** [comment]
I was just wondering why this need to set in book keeping purpose? Is due to breaking some McM or Ops code? If Campaign is only meaningful on request level not the chain level (only one campaign per request), we shouldn't set in the chain level as well. I think it could cause the confusion later on.
However, without this if something breaks, we can add this but eventually we should consider removing it again.

**Review by ticoann — APPROVED** [review]

**Comment by vlimant** [comment]
On Ops side, configuration are done per campaign, and need to be specified per task, since they can belong to different campaigns. It's a very useful member, like SubRequestType, or others

**Comment by ticoann** [comment]
So can campaign  be different by tasks? I thought all the tasks in the same workflow should have same campaign. If that is the case this patch  is necessary.

**Comment by amaltaro** [comment]
This patch is now in testbed, tag pre5 :)

**Comment by ticoann** [comment]
> This patch is now in testbed, tag pre5 :)

I know, I just wanted to revert back next release if Campaign is always request level property not varies by task. 😄

**Pull request merged**
