### PR TITLE
prevent failures if host certs does not match underlying host (useful in k8s testing) [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by amaltaro** [comment]
@vkuznet can you please elaborate on this. Why would a service be running in a host that has a host certificate that doesn't match itself?

**Comment by bbockelm** [comment]
Yeah - I don’t think this is a good idea...

**Comment by vkuznet** [comment]
As I wrote in a title, it is (right now) useful for debugging k8s setup, since the setup I'm testing now is nginx->frontend->data-service. When data-service make request it goes through a proxy/load-balancer (nginx) and not directly through frontend.

Long story, the current ReqMgr code uses 2 types of making HTTP requests, one is based on pycurl and another based on httplib2. When request is made from ReqMgr2 data-service to couchdb it goes through nginx first, rather then frontend and I'm getting curl errors like
```
51, "SSL: no alternative certificate subject name matches target host name 'cmsweb-test.web.cern.ch'"
```
I'm using robot certificates which Kate generate at some point for me using a different name from my current k8s hostnames. This is because (A) I don't remember which host name we used 1 year ago, (B) I can't get any other robot certificates since I don't have privileges (they can be done only from service account) and (C) I need to test the service. When I'll get new robot certificates matching current cluster name then I'll re-test again this setup and see if the error will be gone. Meanwhile I want to have a reference and PR in order to make docker images. We don't need to merge it though in a main tree.

Why I'm doing all of the above? Because httplib2 method fails completely in this setup. I think it is different issue and it is related that now we pass requests through nginx and not directly to frontend. If you are interested and wiling to debug/make suggestions here is full output of failed requests:
```
### call https://cmsweb-test.web.cern.ch/couchdb/reqmgr_workload_cache/ {'Content-length': '0', 'accept-encoding': 'gzip,identity', 'Accept': 'application/json', 'User-agent': 'WMCore.Services.Requests/v001', 'Cache-Control': 'no-cache', 'Content-type': 'application/json'}
### _getURLOpener /data/srv/current/auth/reqmgr2/dmwm-service-key.pem /data/srv/current/auth/reqmgr2/dmwm-service-cert.pem None
connect: (cmsweb-test.web.cern.ch, 443)
send: 'GET /couchdb/reqmgr_workload_cache/ HTTP/1.1\r\nHost: cmsweb-test.web.cern.ch\r\ncontent-length: 0\r\naccept-encoding: gzip,identity\r\naccept: application/json\r\nuser-agent: WMCore.Services.Requests/v001\r\ncache-control: no-cache\r\ncontent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Server: nginx/1.15.8
header: Date: Mon, 18 Mar 2019 18:51:50 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: CMS-Server-Time: D=24707 t=1552935110780592
header: Strict-Transport-Security: max-age=15724800; includeSubDomains
header: Content-Encoding: gzip
### response 403 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
 <head>
 <title>CMSWEB Error: Authorisation required</title>
 <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
 <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
 <link rel="stylesheet" type="text/css" media="screen" href="/css/cmsweb.css" />
</head>
<body>
 <div id="main">
  <div id="top">
   <div class="boxTitle"><img src="/img/title.gif" alt="CMSWEB (title)" /></div>
  </div>
  <div id="middle">
   <div class="boxLinkContainer">
    <h2>Authorisation required</h2>
    <p>The site you requested is protected and requires you to authenticate</p><p><a href='/auth/trouble'>Diagnose certificate problems</a></p>
   </div>
  </div>
  <div id="bottom">
   <div class="boxFooter">&nbsp;</div>
  </div>
 </div>
</body>
</html>
 {'status': '403', 'content-length': '922', 'transfer-encoding': 'chunked', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'vary': 'Accept-Encoding', 'server': 'nginx/1.15.8', 'connection': 'keep-alive', '-content-encoding': 'gzip', 'date': 'Mon, 18 Mar 2019 18:47:20 GMT', 'content-type': 'text/html', 'cms-server-time': 'D=25383 t=1552934840699728'}
```

**Comment by vkuznet** [comment]
the request in httplib2 use proper certificates, see
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/CMSCouch.py#L912
but somehow they are not passed through nginx->frontend chain as shown in previous posts. I do see that key/cert are picked up but then the request does not propagate them to load-balancer.

**Comment by vkuznet** [comment]
I resolved issue with my host certificates, closing this ticket.

**Pull request closed without merging**
