### PR TITLE
[py2py3] Migration at level scr/python/A/B/C - slice 6

### LINKED ISSUE #10127: [py2py3] Migration at level scr/python/A/B/C - slice 6
#### Intro

Our purpose is to continue with the gradual migration. 
This is the 6-th slice in which the migration has been divided into. 
We have split migration units at level `src/python/A/B/C`.

A detailed plan of the migration at this depth is available 
at the dmwm mkdocs [detailed plan page](https://cms-dmwm-test.docs.cern.ch/py2py3/plan_detailed/), 
with summary information on top.

#### Impact of the new feature

We start migrating the 6-th bulk of migration units 
at src/python/A/B/C level.

```plaintext
                                       name  nfiles  gradual  future_pm
       WMComponent_DBS3Buffer_DBSBufferUtil       1     True         20
                   WMCore_ACDC_CouchFileset       1     True          3
                   WMCore_ACDC_CouchService       1     True          1
             WMCore_JobSplitting_JobFactory       1     True         14
  WMCore_JobSplitting_ParentlessMergeBySize       1     True         10
 WMCore_JobSplitting_SiblingProcessingBased       1     True          2
         WMCore_JobSplitting_SplitFileBased       1     True          4
           WMCore_JobSplitting_TwoFileBased       1     True          2
        WMCore_JobSplitting_WMBSMergeBySize       1     True          6
                            WMCore_WMBS_Job       1     True          8
                   WMCore_WMBS_Subscription       1     True          8
            WMCore_JobSplitting_MergeBySize       1     True          0
               WMCore_JobSplitting_RunBased       1     True          7
              WMCore_JobSplitting_SizeBased       1     True          2
                  WMCore_Database_MySQLCore       1     True          2
             WMCore_JobSplitting_FixedDelay       1     True          0
           WMCore_JobSplitting_MinFileBased       1     True          2
   WMCore_JobSplitting_TwoFileAndEventBased       1     True          0
                   WMCore_Storage_DeleteMgr       1     True          6
                WMCore_ACDC_CouchCollection       1     True          0
```

#### Is your feature request related to a problem? Please describe.

The end goal is to have WMCore py2 and py3 compatible.

#### Describe the solution you'd like

Run futurize on the first bulk of units 
and then apply the necessary manual changes.

### PR DESCRIPTION
**Pull request by mapellidario**
Fixes #10127 

#### Status
In development

#### Related PRs

* Previous migration PR: #10262 (slice5, issue #10116)
* Next migration PR: #10284  (slice7, issue #10131 )

#### Description

Run futurize and some manual changes on the first batch of src/python/A/B/C.

Use of "native-string" strategy:
- `src/python/WMCore/JobSplitting/JobFactory.py`: no `from bultins import str` here

division:
- `src/python/WMCore/JobSplitting/ParentlessMergeBySize.py`: assuming that 
    ```python
    self.currentJob.addResourceEstimates(jobTime = jobTime, disk = (jobSize+largestFile)/1024)
    ```
    can accept float arguments

#### Is it backward compatible (if not, which system it affects?)

It should be. (Any possible cause for errors will we reported here)

#### External dependencies / deployment changes

Requires python-future in both py2 and py3 environments.

### CODE REVIEW

**Comment by mapellidario** [comment]
@amaltaro Since this slice involved  `src/python/WMCore/WMBS/Job.py`, I run some unit tests in my oracle setup. This PR seems consistent with `master`, so far so good.

However, I noticed that the test

```bash
nosetests test/python/WMCore_t/WMBS_t/Job_t.py:JobTest.testSaveTransaction
```

is ok with mariadb but fails in oracle since at least 1.3.0. Is this to be expected?

##### logs

With code

```python
        testJobA = self.createTestJob()
        ... # (changes to testJobA)
        testJobA.save()
        testJobB = Job(id=testJobA["id"])
        testJobB.loadData()
        assert testJobA["mask"] == testJobB["mask"], \
            "ERROR: Job mask did not load properly" # this assertion pass in both oracle and mariadb
        ... # (otherr changes to testJobA)
        testJobA.save()
        testJobC = Job(id=testJobA["id"])
        testJobC.loadData()

        print("testJobA: ", testJobA["mask"])
        print("testJobC: ", testJobC["mask"])
        assert testJobA["mask"] == testJobC["mask"], \
            "ERROR: Job mask did not load properly"
```

logs from mariadb setup

```plaintext
# apart being long, these are identical and pas the assertion
('testJobA: ', {'LastRun': 12, 'FirstRun': 11, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': 8, 'FirstEvent': 7, 'LastLumi': 10, 'FirstLumi': 9})
('testJobC: ', {'LastRun': 12L, 'FirstRun': 11L, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': 8L, 'FirstEvent': 7L, 'LastLumi': 10L, 'FirstLumi': 9L})
```
while, logs from oracle setup are

```plaintext
('testJobA: ', {'LastRun': 12, 'FirstRun': 11, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': 8, 'FirstEvent': 7, 'LastLumi': 10, 'FirstLumi': 9})
('testJobC: ', {'LastRun': 6, 'FirstRun': 5, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': 2, 'FirstEvent': 1, 'LastLumi': 4, 'FirstLumi': 3})
```

as if the second save does not behave. Do you need some more logs?

**Comment by amaltaro** [comment]
@mapellidario about the testSaveTransaction unit test:
https://github.com/dmwm/WMCore/issues/8372

So, I have no clue of what happens, but it seems to be somehow expected :-)

**Review by amaltaro — APPROVED** [review]
Changes look good Dario. Unless you have anything else to add here, I'll merge it tomorrow first thing in the morning.

**Comment by mapellidario** [comment]
Perfect! I consider this finished and ready to merge! Thanks!

**Pull request merged**
