### PR TITLE
Do not upload skipped files for LogCollect/Cleanup to ACDC Server

### LINKED ISSUE #7077: LogCollect docs being uploaded to the ACDC Server (?)
For more details, see #7074 

The only thing that comes to my mind is a possible `skipBadFiles` usage by the logcollect jobs.... anyways, it needs debugging.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7077

ErrorHandler has this code already, so those files must be coming from skipped files.
@ticoann please review , still needs to be tested though

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan, I think you are right. I wonder where this could happen. Good Job!
Patch looks good and I will merge this.

**Comment by ticoann** [comment]
We can run the test with other patches. (But I can't hardly see this can go wrong)

**Comment by amaltaro** [comment]
I was only worried of not getting these skipped files into the completed (or failed) wmbs_sub_files_* table, but it seems they would go into the complete regardless.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
