### PR TITLE
allow not adding hostname to DN for hash

### PR DESCRIPTION
**Pull request by belforte**
crab branch backport for https://github.com/dmwm/WMCore/pull/9859
by targeting 1.3.6_crab branch instead of master

### CODE REVIEW

**Comment by amaltaro** [comment]
@belforte keep both PRs please. We want to keep that one in master as well for future releases.

**Review by amaltaro — APPROVED** [review]

**Comment by amaltaro** [comment]
@belforte Stefano, do you need a new tag with this fix in (e.g. 1.3.6.crab1)?

**Comment by belforte** [comment]
I think Alans, I would not know how to use it in the rpm spec files otherwise.

**Comment by amaltaro** [comment]
1.3.6.crab1 tagged
enjoy!

**Pull request merged**
