### PR TITLE
Harmonize case of exception labels

### PR DESCRIPTION
**Pull request by ericvaandering**
For whatever reason, the first two of these are one case, the rest another. Make it all the same.

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann please merge

**Comment by amaltaro** [comment]
@ticoann you may want to merge first #6427, to avoid conflict

**Comment by ericvaandering** [comment]
@ticoann this can now be merged. Rebased it.

**Pull request merged**
