### PR TITLE
PR to test Jenkins unittest baseline

### PR DESCRIPTION
**Pull request by goughes**
Fixes Nothing!

#### Status
In development

#### Description
Creating a junk PR so I can work on fixing the Jenkins unit test baseline for #11148 

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by amaltaro** [comment]
@goughes Erik, I noticed that these unit tests that keep being reported as added have an strange name:
```
MSUnmergedRSE_t.MSUnmergedRSETest:testCreateRSE was added with status success
```
instead of something like WMCore_t/Microservices_t/...

I might be wrong, but I think we have had new unit tests being merged and not getting reported as new as soon as a new tag baseline was created. So it might be good to start looking into these unit tests and where they were provided, instead of looking into Jenkins. Just a thought!

**Comment by goughes** [comment]
Hey Alan, indeed those are the ones causing the issue. I did some investigation and found that when generating the baseline tests, they fail due to:

```
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
```

I can resolve this and I think we'll be all good.

**Comment by goughes** [comment]
test this please

**Comment by goughes** [comment]
Closing this PR since #11089 is now fixed.

**Pull request closed without merging**
