### PR TITLE
add campaign prepid in FWJR

### PR DESCRIPTION
**Pull request by ticoann**
replace #7338 (still need to be fixed - don't review yet)

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, Eric, it seems something wrong with Jenkins. It keeps failing.
I made a mistake on setup_depency code. So I thought that cause the problem. 
But after it got fixed. #7666. But it seems still failing without the report.

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Yeah, something with Jenkins is wrong that it can't create a file. I've seen that. Usual clears up. No idea why.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Finally!

**Comment by ericvaandering** [comment]
Can you fix some of the more serious pylint stuff?

**Comment by ticoann** [comment]
Yes I will fix pylint. The patch is not ready though. :-)

**Comment by ticoann** [comment]
tested in vm. merging it.

**Pull request merged**
