### PR TITLE
1.1.15_wmagent branch: wmstats fix for new view (only update when cmsweb is updated)

### PR DESCRIPTION
**Pull request by ticoann**
WMAgent branch version of #8855 
This can be only patched when HG1811 cmsweb is updated

### CODE REVIEW

**Comment by amaltaro** [comment]
[Fix #8873 - wmstats fix for new view](https://trello.com/c/qocsDy3W/133-fix-8873-wmstats-fix-for-new-view)

**Comment by amaltaro** [comment]
Haa, and it fails in the production agent because it has very old documents still in the old revision format
```
2018-11-06 22:28:05,666:140027128878848:ERROR:AnalyticsPoller:Error occurred, will retry later: invalid literal for int() with base 10: 'af95e5be6427810f611613c3b43ddfa5'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py", line 142, in algorithm
    self.centralWMStatsCouchDB.bulkUpdateData(requestDocs, existingDocs)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsWriter.py", line 93, in bulkUpdateData
    doc['_revisions'] = {"start": int(revList[0]) + 1, "ids": [str(int(revList[1]) + 1), revList[1]]}
ValueError: invalid literal for int() with base 10: 'af95e5be6427810f611613c3b43ddfa5'
```

Should we add that line in a try except and do something like
`    doc['_revisions'] = {"start": int(revList[0]) + 1, "ids": [str(1234567890 + 1), revList[1]]}`
?

I reverted that patch again on vocms0256 until we converge with a solution.

**Comment by ticoann** [comment]
Thanks Alan for putting in the production agent and testing. I think suggestion is good. However, I was wondering why there are still old documents. It supposed to be deleted after 3 hours.

**Comment by amaltaro** [comment]
That's a good point!
I see upload to wmstats is actually failing even without applying this patch, in vocms0250:
```
2018-11-07 08:06:19,046:140611546171136:INFO:AnalyticsPoller:329 requests Data combined,
 uploading request data...
2018-11-07 08:16:24,197:140611546171136:ERROR:AnalyticsPoller:Error occurred, will retry later: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py", line 158, in algorithm
    notInCacheDoc, notInCacheKey = self.centralWMStatsCouchDB.bulkUpdateDataAnUpdateCache(requestDocs, self.revCache)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsWriter.py", line 141, in bulkUpdateDataAnUpdateCache
    self.couchDB.commit(new_edits=False)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 153, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 287, in makeRequest_httplib
    raise e
HTTPException
2018-11-07 08:16:37,882:140611546171136:ERROR:AnalyticsPoller:upload Agent Info to central couch failed
```

since that agent has no jobs in condor (and is draining), I'll apply this patch there and debug what's needed.

**Comment by amaltaro** [comment]
It turns out the bulk update performance is much worse than one would imagine (or it's being affected by the bad scenario we are at the moment with central wmstats). The exception above is actually a frontend 5min timeout, which can clearly be seen if we break up the bulk update into smaller chunks, e.g. in vocms0250 again:
```
2018-11-07 09:26:08,461:139727535384320:INFO:WMStatsWriter:Committing bulk of 100 docs ...
2018-11-07 09:27:12,379:139727535384320:INFO:WMStatsWriter:Committing bulk of 100 docs ...
2018-11-07 09:28:22,817:139727535384320:INFO:WMStatsWriter:Committing bulk of 100 docs ...
2018-11-07 09:29:35,071:139727535384320:INFO:WMStatsWriter:Committing bulk of 29 docs ...
2018-11-07 09:32:36,979:139727535384320:INFO:AnalyticsPoller:Request data upload success
 329 request, 
sleep for next cycle
2018-11-07 09:32:37,352:139727535384320:INFO:BaseWorkerThread:AnalyticsPoller took 396.108 secs to execute
```

so avg of 0.7secs/doc :-( At least the component is now managing to successfully complete a cycle.

Seangchan, can you update this patch with the changes I have in
cmst1@vocms0250:/data/srv/wmagent/current $ ls /data/srv/wmagent/v1.1.15.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsWriter.py
?

Then we can start applying to the other agents too. We still have to find a better solution though, this one is not gonna scale.

**Comment by amaltaro** [comment]
Seangchan, I created a new PR with what was discussed here in order to buy me a few hours of testing. I'm closing this one to avoid confusion

**Pull request closed without merging**
