### PR TITLE
Make assigned->staging->staged transition configurable in ReqMgr2

### LINKED ISSUE #9507: Make request status transition to staging/staged configurable in ReqMgr2
**Impact of the new feature**
ReqMgr2

**Is your feature request related to a problem? Please describe.**
Given that it's configurable for ReqMgr2MS and, we might have troubles when putting microservices in production. It's better to have those 2 state transition configurable for ReqMGr2 as well.

**Describe the solution you'd like**
Make 
assigned -> staging
staging -> staged 
state transition supported and configurable in ReqMgr2. Default should be to disable it.

**Describe alternatives you've considered**
Trust that we will not have issues in production and just use what we have already in place for ReqMgr2MS.

**Additional context**
https://github.com/dmwm/WMCore/pull/9481

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9507 

#### Status
tested

#### Description
Added back the status transition that are meant to be performed by Microservices. It uses a new configuration parameter (reqmgr2): `enableMSStatusTransition` which defaults to False.

To be used only if we find critical issues with MicroServices regarding the workflow status transition; where we need to stop status transition in MS and enable it in ReqMgr2.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
Yes, sort of reverts back this: https://github.com/dmwm/WMCore/pull/9481

#### External dependencies / deployment changes
Yes, deployment changes are required: https://github.com/dmwm/deployment/pull/842

### CODE REVIEW

**Comment by amaltaro** [comment]
Tests went fine too.

**Review by todor-ivanov — APPROVED** [review]
This one looks correct. 
Is this the only flag we need to add for the final transition to MS on March, though?

**Comment by amaltaro** [comment]
Yes, but the way it's configured we are not supposed to touch it, unless we have BIG problems with MicroServices in production.

**Comment by amaltaro** [comment]
test this please

**Pull request merged**
