### PR TITLE
change job splitting algorithm for AlcaSkim

### PR DESCRIPTION
**Pull request by hufnagel**
Also change the default for the PromptReco job splitting, but that new default is the value we have been using from the Tier0 since a long time, so this is not a functional change.

### CODE REVIEW

**Comment by hufnagel** [comment]
I really would like to have this in 1.1.16 since I am going to build a new Tier0 release with that tag.

@amaltaro @ticoann

**Comment by ticoann** [comment]
I will create a new tag once Jenkins report comes back. It will be 1.1.6.pre7

**Comment by ticoann** [comment]
test this please

**Review by amaltaro — APPROVED** [review]
Looks good!

**Comment by amaltaro** [comment]
@hufnagel can you fix those 2 PromptReco unit tests to get this merged? Thanks

**Pull request merged**
