### PR TITLE
make sure no empty string in Teams workqueue elements

### LINKED ISSUE #8095: agent need to acquire in their team
related to #8074 I do not understand the reason for having team="" go to *any* team. This is highly un-desirable IMO and WQE should just get in nowhere land. Better the request should not be able to assign if Team="" is the one that is decided.

I don't know why this is happening more frequently now, but this is happening and impacting urgent requests

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8095

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan please review

**Comment by amaltaro** [comment]
Seangchan, I think we should catch any of these problems right in the beginning. If you look at StdBase, you see `Team` is properly validated, but couch update sort of messes that up later on.

I'm fixing the  root cause at the moment and then we can see how to proceed.

**Comment by ticoann** [comment]
For root cause of fix, we should remove either Teams or Team and keep just one. If we never allow multiple teams we can just keep 'Team'. It looks like that is current assumption anyway (in WorkQueue)

**Comment by amaltaro** [comment]
Seangchan, how about this patch. Has it been applied anywhere?

**Comment by ticoann** [comment]
This patch is not necessary. Closing it.

**Pull request closed without merging**
