### PR TITLE
Remove query_string since it is covered by params in CherryPy.request dump

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by yuyiguo** [comment]
@vkuznet 

I added you code and made some changes to make the log a little leaner. Here are the GET and POST logs before and after processing.
```
INFO:cherrypy.access:REQUEST [02/May/2019 00:54:35] 188.184.94.167 41958 GET /files [/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo] [{'logical_file_name': u'/store/mc/Fall08/BBJets250to500-madgraph/GEN-SIM/StepChain_/54696/0.root', 'detail': u'True'}]

INFO:cherrypy.access:[02/May/2019:00:54:35] dbs3-test2.cern.ch 188.184.94.167 "GET /dbs/dev/global/DBSWriter/files?logical_file_name=%2Fstore%2Fmc%2FFall08%2FBBJets250to500-madgraph%2FGEN-SIM%2FStepChain_%2F54696%2F0.root&detail=True HTTP/1.1" 200 OK [data: 6478 in 681 out 8537 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo" "" ] [ref: "" "DBSClient/3.7.8.2/" ]


INFO:cherrypy.access:REQUEST [02/May/2019 00:54:35] 188.184.94.167 41946 POST /fileparents [/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo] [{}]

INFO:cherrypy.access:[02/May/2019:00:54:35] dbs3-test2.cern.ch 188.184.94.167 "POST /dbs/dev/global/DBSWriter/fileparents HTTP/1.1" 200 OK [data: 237 in 4 out 264292 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo" "" ] [ref: "" "DBSClient/3.7.8.2/" ]

```

**Comment by yuyiguo** [comment]
What I did for the changes are (1) use the server time instead of GMT so it has the same timezone as the after log. (2) instead of all the headers, I only took headers['Cms-Authn-Dn'].  I am not working on the head of wmcore. Could you add these changes to you patch to them together?
Thanks,
Yuyi

`
RESTModel.py
14 from datetime import datetime

184                 tst = time.gmtime(time.time())
185                 msg = 'REQUEST {} {} {} {} {} [{}] [{}]'.format(\
186                         datetime.now().strftime('[%d/%b/%Y %H:%M:%S]'),
187                         request.remote.ip,
188                         request.remote.port,
189                         request.method,
190                         request.path_info,
191                         headers['Cms-Authn-Dn'],
192                         request.params
193                         )
`

**Comment by yuyiguo** [comment]
@vkuznet 
code need to be change to below in order to get the server side tests pass.
`191                         headers.get('Cms-Authn-Dn', ''),
`

**Comment by vkuznet** [comment]
Yuyi, please check I committed the changes.

**Comment by yuyiguo** [comment]
Thanks @vkuznet , it looked good to me.
@amaltaro I still need some tests before committing them. I will let you know later.

**Comment by yuyiguo** [comment]
@amaltaro 
Could you commit this patch?

**Comment by amaltaro** [comment]
@vkuznet please squash these commits.
@yuyiguo  I assume you need it backported to the dbs branch and a new tag, right?

**Comment by amaltaro** [comment]
@yuyiguo  tag `1.1.16.dbs2` has been released: https://github.com/dmwm/WMCore/commits/1.1.16.dbs2
I will wait for Valentin to squash these commits before this PR gets merged.

**Comment by vkuznet** [comment]
squash: done.

**Comment by amaltaro** [comment]
There are still a few pylint complaints and unused code that could have been removed in this PR. I'll get those fixed in a different PR.
In the future, you might want to scan the PR report and get some of those pylint issues fixed (like unused vars, imports, some errors and warnings).

**Comment by amaltaro** [comment]
@yuyiguo @vkuznet I just noticed this PR is basically a dup of #9171 
Can you please clarify which PR you were testing and which PR we had to get merged?

This one has the logging fixed, but it lacks one extra attempt to get the income request size which is available in #9171

**Comment by vkuznet** [comment]
Alan, I'm not sure I understand your last comment. You wrote that this PR (which is 9171) is basically a duplicate of 9171. I think you meant another PR, if so please provide its number.

**Comment by amaltaro** [comment]
Sorry, I meant to say https://github.com/dmwm/WMCore/pull/9169

**Comment by vkuznet** [comment]
Ahh, I see, I was in a rush. The #9169 has fixed this part:
https://github.com/dmwm/WMCore/pull/9169/files#diff-e0f21be5aa9ce07a539bfc7b6f8cae79R107 which was missed here. It is `%(i)s` (which is correct) in there over `%(i)` in here. So either merge #9169 or we'll make another PR to fix this tiny bug.

**Comment by amaltaro** [comment]
Valentin, if you have time, can you please rebase/update #9169? Otherwise - I believe it's your day off, no? - I can make a new PR and get it fixed.

**Comment by vkuznet** [comment]
I don't have time until I back. Feel free to discard this PR and make new one.

**Pull request merged**
