### PR TITLE
Add possible sites in job submission error reports (SubmitFailed).

### LINKED ISSUE #9047: SubmitFailed not reporting site in wmstats
for pdmvserv_task_HIG-RunIIFall18wmLHEGS-00388__v1_T_181126_083424_8286 for example, job failed with SubmitFailed but the site is not reported in wmstat (while it should to my understanding, @amaltaro ?)

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #9047.

### CODE REVIEW

**Comment by khurtado** [comment]
test this please

**Comment by amaltaro** [comment]
Another suggestion would be to create a `setSiteName` method in the Report class and then call it in JobSubmitterPoller under `job['fwjr'].addError...`. No further changes would be needed.

**Comment by khurtado** [comment]
> Another suggestion would be to create a `setSiteName` method in the Report class and then call it in JobSubmitterPoller under `job['fwjr'].addError...`. No further changes would be needed.

Done. I tested briefly before `cmsweb-testbed.cern.ch` went down and it worked fine.

**Review by amaltaro — COMMENTED** [review]
Kenyi, I actually thought we could leave `addError` untouched and simply add a new public method `setSiteName` to the Report module. Then in JobSubmitterPoller, we make two calls, one to addError and one to setSiteName.

If you agree :), can you also create a simple unit test testing getSiteName and setSiteName?

**Comment by khurtado** [comment]
@amaltaro Ah, I see! Actually, I was actually trying to avoid setting a public method to allow setting `siteName` as much as possible, because in my mind, this is something that should never be done outside the worker node, except of course, during submission errors where the task couldn't reach the WN. Am I overthinking things (or is this not the case)? I can create the public method and do as you say otherwise.

**Comment by amaltaro** [comment]
That's a valid point, Kenyi. In practice it makes no difference whether we have a setter method or we set it from `addError` though.
I think having a setter method would be slightly more friendly, but these changes are so small that I think it's not worth it changing this PR once again.

**Review by amaltaro — APPROVED** [review]

**Pull request merged**
