### PR TITLE
Add initial port of unified scripts: utils and transferor (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by vkuznet**
This is a copy of #8099 without additional merges from WMCore head tip.

### CODE REVIEW

**Comment by vkuznet** [comment]
@ericvaandering, Eric where can I find jenkins unit tests failures. I don't see them on jenkins page. The failed tests are not related to my changes per se , but I want to see what failed.

**Comment by ericvaandering** [comment]
If you click on details under "Default" (not Unit tests, I know :-) ) you can see the actual failures and tracebacks.

**Comment by vkuznet** [comment]
Eric,
I can't find where to see it.
The page I'm talking about should be like this:
https://cmssdt.cern.ch/jenkins/job/DMWM-PR-unittests/8122/
and I scan https://cmssdt.cern.ch/jenkins/view/DMWM/ and can't find my PR.
Valentin.

**Comment by ericvaandering** [comment]
https://cmssdt.cern.ch/jenkins/job/DMWM-WMCore-PR-test/5848/

screenshot 2017-09-02 20 55 22

**Comment by vkuznet** [comment]
@ticoann , Seangchan, could you please the two unit tests which failed here. The problem is that they fail in master branch too. It seems to me that previous commits to master changed something in environment of unit tests. In both cases the environment is not set which cause test to fail. For example the test/python/WMCore_t/WMInit_t.py test fails because DIALECT environment is not set. I doubt it is related to my PR since errors exists in master too. But my PR complains about this test once I rebased it to master tip.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by vkuznet** [comment]
@ticoann , @ericvaandering , @amaltaro please review this PR. Here is a list of implemented changes and logic:
- Common.py contains list of common utilities used by the code, most of the functions are adopted from original unified script
- RequestInfo.py module provides all aux function to acquire request information based on original unified script. In particular see logic of requestsInfo function which get everything and construct list of request
- Transferor.py module contains transferor logic outlined in Seangchan's [wiki](https://github.com/dmwm/WMCore/wiki/Unified-Porting)
- TaskManager.py module provides all necessary pieces for setting up threads for RequestManager which is defined in Transferor module
So far I implemented APIs for transferor key-value store. It is based on python [shelve](https://docs.python.org/2/library/shelve.html) module. I named it as RequestStore and it belongs to transferor module. The shelve module is persistent key-value store based on python dict object. If we'll need later to scale it to more sophisticated product (like [redis](https://redis.io)) we can replace shelve with it.

I tested Transferor logic (request registration, checking status and bookkeeping) in Transferor_t.py test module. You may see logic of the code. So far it performs all actions using existing PhEDEx subscription, i.e. it creates fake request from subscription dataset and its nodes and perform all transferor logic. The code has commented phedex.subscribe calls which we'll enable once verify transferor logic.

**Comment by vkuznet** [comment]
To enable PhEDEx subscription we need to merge this PR: #8144

**Comment by vkuznet** [comment]
@ticoann Seangchan, I also need a reference to requested WorkQueue APIs to move forward with this code. Can you provide them here and give timeframe/priority for their implementation.

**Comment by vkuznet** [comment]
Here is basic benchmarks, I was able to connect MS Unified code to cmsweb and read workflows from it. Here are the obtained information from real workflows:
```
total # of workflows 850, datasets 147, blocks 4340, evts 6274113721, size 3812351290403331 (3467.31329992 TB), cput 28068714.3377 (hours)
workflows info: 5.1 sec
Elapsed time: 168.0 sec
```
The total size of Python based (shelve module) Berkley DB for all of this workflows is 203MB.

**Comment by vkuznet** [comment]
@ticoann , Seangchan the code in this PR now is identical to what I shown at last meeting. All commits are squashed too. I've added basic stats as well.

**Comment by vkuznet** [comment]
Seangchan feel free to review and merge that we can proceed with making spec/manage/etc.

**Comment by vkuznet** [comment]
@ticoann , Seangchan, what's your thoughts about this PR? Strangely, the failed unit test does not belong to this PR at all and I think it is false alarm. Can you have a look?

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
I don't think unittest failure is related to this patch. I will make sure and run the test in local and merge this.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@vkuznet, Valenitn,
It is reporting this errors.

WMCore_t.Services_t.MicroService_t.Unified_t.Transferor_t.TransferorTest:testRequestManager was added with status error. Must be fixed
WMCore_t.Services_t.MicroService_t.Unified_t.Transferor_t.TransferorTest:testRequestManagerAutomation was added with status failure. Must be fixed

Could you check on that?

**Comment by vkuznet** [comment]
Test failed since I pick up dataset without subscriptions. Logic is fixed now.
Please test again.

**Comment by ticoann** [comment]
Thanks Valentin,

**Comment by vkuznet** [comment]
@ticoann , Seangchan, could you please trigger the test.

**Comment by amaltaro** [comment]
test this please

**Comment by vkuznet** [comment]
@ticoann , Seangchan, once again a new WMCore test fail, this time WMCore_t.WMBS_t.JobSplitting_t.EventAwareLumiByWork_t.EventAwareLumiByWorkTest:test_NotEnoughEvents which completely irrelevant for this PR. Please have a look.

**Comment by ticoann** [comment]
Yes that is irrelavant, merged the patch. Thanks Valentin.

**Pull request merged**
