### PR TITLE
remove send alert

### PR DESCRIPTION
**Pull request by ticoann**
wmagent version of #6815

### CODE REVIEW

**Comment by amaltaro** [comment]
But was the component crashing at this call? I though it had no use, but wouldn't complain as well.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann I'm pushing it to all FNAL nodes for now, if it really solves the issue, then we push it to the other CERN agents and also make a master branch fix.

**Comment by amaltaro** [comment]
@ticoann feel free to merge this

**Pull request merged**
