### PR TITLE
Proper type for Multicore parameter

### LINKED ISSUE #7296: Mutlicore is a string
Looked at this that would not assign via unified

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_PPD-RunIISummer16FSPremix-00001_00001_v0_PUMoriond17_161014_081231_5111

"Multicore":"1" 

 a string unexpectedly. Isn't there a type conversion in request manager regardless of what the injected schema might be ? 

 pdmvserv_PPD-RunIISummer16FSPremix-00001_00001_v0_PUMoriond17_161014_081231_5111.request.schema.Multicore = '1'

it's injected as int https://github.com/cms-PdmV/wmcontrol/blob/master/wmcontrol.py#L671 @anorkus

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7296 

@ericvaandering @hufnagel was there any reason to validate its value against "auto"?

It needs to be tested.

### CODE REVIEW

**Comment by amaltaro** [comment]
It passes simple tests in my VM. Just waiting for a confirmation on that `auto` value.

**Comment by amaltaro** [comment]
Silence implies consent :-)
@ticoann please review and merge

**Comment by ticoann** [comment]
WMCore_t.WMSpec_t.StdSpecs_t.TaskChain_t.TaskChainTests:testMultithreadedTasksTaskChain changed from success to failure

Is real failure. Need to fix unitest

**Comment by amaltaro** [comment]
Sorry, I missed this one :-(
I see you already have a fix for it, thanks a lot!

**Comment by amaltaro** [comment]
Oh no, that was just an issue :) On it.

**Comment by ticoann** [comment]
Hi Alan, I will fix it. Don't worry about it.

**Pull request merged**
