### PR TITLE
fix race condition for site white list update

### LINKED ISSUE #7890: MonteCarlo workflows with empty SiteWhitelist at WorkQueue creation
Issue related to #7707 , where we added a validation at workqueue level such that we don't create GQE without a valid site white list.
However, this still happens once per month or so, where workqueue fails to retrieve the sitewhitelist for the initial task. Example being the following request:
```
pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923.tasks.HIG-RunIIWinter15pLHE-00359_0.constraints.section_('sites')
pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923.tasks.HIG-RunIIWinter15pLHE-00359_0.constraints.sites.blacklist = []
pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923.tasks.HIG-RunIIWinter15pLHE-00359_0.constraints.sites.whitelist = [u'T2_CH_CERN']
pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923.tasks.HIG-RunIIWinter15pLHE-00359_0.constraints.sites.trustPUlists = True
pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923.tasks.HIG-RunIIWinter15pLHE-00359_0.constraints.sites.trustlists = False
```

which had this global workqueue log
```
2017-05-30 17:32:39,938:INFO:WorkQueue:queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923/spec"
2017-05-30 17:32:42,523:INFO:WorkQueue:Splitting /pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923/HIG-RunIIWinter15pLHE-00359_0 with policy MonteCarlo params = {'ResubmitBlock': {'args': {}, 'name': 'ResubmitBlock'}, 'MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Block'}}
2017-05-30 17:32:42,523:ERROR:WorkQueue:Terminal exception splitting WQE: {'ChildQueueUrl': None, 'NumberOfEvents': 0, 'StartPolicy': {'SliceSize': 500000, 'policyName': 'MonteCarlo', 'SubSliceSize': 200, 'SplittingAlgo': 'EventBased', 'blowupFactor': 67201.66433932906, 'SubSliceType': 'NumberOfEventsPerLumi', 'SliceType': 'NumberOfEvents'}, 'CreationTime': 0, 'NumOfFilesAdded': 0, 'Priority': 0, 'ParentData': {}, 'PileupData': {}, 'RejectedInputs': [], 'ParentFlag': False, 'TaskName': None, 'Status': 'Negotiating', 'Inputs': {}, 'NumberOfLumis': 0, 'Jobs': 0, 'ParentQueueUrl': None, 'ParentQueueId': None, 'PercentSuccess': 0, 'PercentComplete': 0, 'WMBSUrl': None, 'OpenForNewData': False, 'EndPolicy': {'policyName': 'SingleShot'}, 'FilesProcessed': 0, 'Task': None, 'SiteWhitelist': [], 'ACDC': {}, 'NumberOfFiles': 0, 'TeamName': u'production', 'NoPileupUpdate': False, 'RequestName': u'pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923', 'SubscriptionId': None, 'WMSpec': <WMCore.WMSpec.WMWorkload.WMWorkloadHelper instance at 0x7ff98e349440>, 'NoInputUpdate': False, 'TimestampFoundNewData': 0, 'ProcessedInputs': [], 'SiteBlacklist': [], 'Mask': None, 'Dbs': None, 'EventsWritten': 0}
2017-05-30 17:32:43,022:ERROR:WorkQueue:Failing workflow "pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923": Invalid WMSpec: 'pdmvserv_task_HIG-RunIIWinter15pLHE-00359__v1_T_170525_121221_5923': Site whitelist validation error: Empty site whitelist
```

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7890

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro Alan, I looked through the code this is the place I think it could cause the problem.
I checked the config for the workflow Jean-Roch pointed and it had correct config value for site.whitelist.

Unfortunately I couldn't reproduce the problem so I can't really test it but at least it is a safe change. (I think)

**Review by amaltaro — APPROVED** [review]
Interesting change. That may be the place indeed. Change looks good.

**Comment by vlimant** [comment]
stupid comment maybe. don't you need to "resave" after the update ?

**Comment by ticoann** [comment]
That was actually good point. However,  this case actual spec update happens.

```
https://github.com/ticoann/WMCore/blob/e6131194fe4a3f3836b5991af8686bdd4acfef30/src/python/WMCore/ReqMgr/Service/Request.py#L408
```

The last line is only couch db update, so we should be good. 
I suspect in rare case workqueue pulls down the request  after couch is update but before spec is uploaded to couch. But I am not completely sure whether that is the case. 

@amaltaro, Alan,
One thing I want to check more is whether workqueue is getting the spec data from reqmgr or workqueue db. I think I change to reqmgr db before but if it gets from wq db. There might be another race condition

**Comment by ticoann** [comment]
@amaltaro, Alan, it seems we are getting from reqmgr db, so hopefully this would fix the problem.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L224

https://cmsweb.cern.ch/wmstatsserver/data/filtered_requests?RequestStatus=running-closed&mask=RequestWorkflow

**Comment by amaltaro** [comment]
Just to summarize, with this change it will first save the spec in couch and then it will update properties (update the request json in workload_cache). And it should solve the problem - if the problem is really here :) - since GWQ gets the list of workflows in assigned based on the workload_cache doc.

Is that correct? Patch looks good!

**Comment by ticoann** [comment]
Yes, if that is the problem which I am not 100% sure. :-)

**Pull request merged**
