### PR TITLE
Fix typo in wmarchive parameter

### PR DESCRIPTION
**Pull request by amaltaro**
Complement for #7040

### CODE REVIEW

**Comment by amaltaro** [comment]
Nope, I still don't get the url from the secrets into the config.py (applying this patch and your to deployment). Still to be investigated...

**Comment by amaltaro** [comment]
Okay, the second problem was with that misplaced return statement.
Just tested and it looks good now.
@ticoann please merge

**Comment by ticoann** [comment]
Sorry Alan, I couldn't test this part yesterday. Thank you

**Comment by amaltaro** [comment]
No problem! It's great we get the component enabled by default now, thanks! ;)

**Pull request merged**
