### PR TITLE
Improve py2 compatibility of WMException __init__

### LINKED ISSUE #9862: Report message encoding error in JobCreator
**Impact of the bug**
WMAgents

**Describe the bug**
I've seen an issue with JobCreator - while creating a job area - and it looks like WMException class is unable to encode all the error message raised from JobCreator, which actually masks the original exception/error in the component.

**How to reproduce it**
not sure

**Expected behavior**
Error messages should be properly encoded/decoded using utf-8 codec. If needed we can ignore and bypass when a byte/word can't be encoded/decoded, it's only for error reporting anyways.

**Additional context and error message**
Exception from submit8, running the latest WMAgent tag 1.3.6:
```
2020-08-08 01:43:29,680:140258839922432:INFO:JobCreatorPoller:Found end in iteration over subscription 12124
2020-08-08 01:43:29,755:140258839922432:INFO:JobCreatorPoller:Retrieved 1 jobGroups from jobSplitter
2020-08-08 01:43:29,783:140258839922432:ERROR:CreateWorkArea:Error in creating directories: mkdir: cannot create directory ‘/storage/local/data1/cmsdataops/srv/wmagent/v1.3.6.patch4/install/wmagent/JobCreator/JobCache/cmsunified_ACDC0_task_JME-RunIISummer19UL16GENAPV-00004__v1_T_200808_062137_1106/JME-RunIISummer19UL16GENAPV-00004_0MergeRAWSIMoutput/JobCollection_78499_0/job_1124238’: File exists


2020-08-08 01:43:29,784:140258839922432:ERROR:JobCreatorPoller:Exception in processing wmbsJobGroup 78499
. Error: 'ascii' codec can't encode character u'\u2018' in position 62: ordinal not in range(128)
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 208, in creatorProcess
    cache=False)
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/CreateWorkArea.py", line 170, in processJobs
    self.createWorkArea(cache=cache)
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/CreateWorkArea.py", line 273, in createWorkArea
    createDirectories(nameList)
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/CreateWorkArea.py", line 42, in createDirectories
    raise CreateWorkAreaException(msg)
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 62: ordinal not in range(128)
2020-08-08 01:43:29,884:140258839922432:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobCreator.JobCreatorPoller.JobCreatorPoller object at 0x7f908e8688d0> <@========== WMException Start ==========@>
Exception Class: JobCreatorException
Message: Exception in processing wmbsJobGroup 78499
. Error: 'ascii' codec can't encode character u'\u2018' in position 62: ordinal not in range(128)
        ModuleName : WMComponent.JobCreator.JobCreatorPoller
        MethodName : creatorProcess
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py
        ClassName : None
        LineNumber : 233
        ErrorNr : 0
Traceback: 
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 208, in creatorProcess
    cache=False)

  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/CreateWorkArea.py", line 170, in processJobs
    self.createWorkArea(cache=cache)

  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/CreateWorkArea.py", line 273, in createWorkArea
    createDirectories(nameList)

  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMComponent/JobCreator/CreateWorkArea.py", line 42, in createDirectories
    raise CreateWorkAreaException(msg)

  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch4/lib/python2.7/site-packages/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')

  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
```

### PR DESCRIPTION
**Pull request by mapellidario**
Fixes #9862 

#### Status
ready

#### Description

Small change to `WMException.__init__` in order to improve its handling of unicode error messages in python2

#### Is it backward compatible (if not, which system it affects?)
yes

#### External dependencies / deployment changes
This makes WMException depend on python future

### CODE REVIEW

**Comment by amaltaro** [comment]
Dario, can you please apply the suggested "python3 idioms"?

**Comment by mapellidario** [comment]
I did not do it because it can cause trouble such as in #9852, but I agree that in this case it should cause any problems using isinstance instead of checking the typed directly

**Comment by amaltaro** [comment]
@mapellidario could you please fix the conflicts here and fire another review request once you're done with your changes? Thanks

**Review by amaltaro — APPROVED** [review]
Thanks Dario!

**Comment by amaltaro** [comment]
I was looking at the backfill agent (vocms0285), and I've spotted a few jobs failing with errors like (wmagentJob.log):
```
2020-09-01 23:18:55,930:INFO:PerformanceMonitor:PSS: 133864; RSS: 133860; PCPU: 0.0; PMEM: 0.0
2020-09-01 23:23:44,021:CRITICAL:CMSSW:Error running cmsRun
{'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', u'slc7_amd64_gcc700', 'scramv1', 'CMSSW', 'CMSSW_10_6_9', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
Linux Return code: 135

2020-09-01 23:23:44,021:CRITICAL:CMSSW:Error message: None
2020-09-01 23:23:44,352:ERROR:ExecuteMaster:Exception occured when executing step
2020-09-01 23:23:44,352:ERROR:ExecuteMaster:Exception is unknown encoding: utf-8
2020-09-01 23:23:44,353:ERROR:ExecuteMaster:Traceback:
2020-09-01 23:23:44,354:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 139, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 284, in execute
    raise WMExecutionFailure(returnCode, "CmsRunFailure", msg)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py", line 18, in __init__
    WMException.__init__(self, detail, code)
  File "/srv/job/WMCore.zip/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')
LookupError: unknown encoding: utf-8

2020-09-01 23:23:44,354:CRITICAL:CMSSW:CMSDefaultHandler Diagnostic Handler invoked
2020-09-01 23:23:44,356:ERROR:ExecuteMaster:Encountered error while running ExecuteMaster:
unknown encoding: utf-8
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 73, in __call__
    result = self.doExecution(executor, step, wmbsJob)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 149, in doExecution
    executor.diagnostic(99109, executor, ExceptionInstance=ex)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Diagnostic.py", line 87, in __call__
    handler(errCode, executor, **args)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Diagnostics/CMSSW.py", line 102, in __call__
    self.parse(executor, jobRepXml)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Diagnostic.py", line 42, in parse
    executorInstance.report.parse(jobRepXml, executorInstance.stepName)
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py", line 156, in parse
    raise FwkJobReportException(msg)
  File "/srv/job/WMCore.zip/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')
LookupError: unknown encoding: utf-8


2020-09-01 23:23:44,357:INFO:Watchdog:MonitorThread: JobEnded
```

@mapellidario can I ask you to look into this PR and try to backport it to the branch `1.3.6_wmagent`? That branch does not have any of these code modernization, so it might not be very straight forward...
Once you have it ready, please make a PR against the `1.3.6_wmagent` branch and we can start testing your changes in the backfill agent itself (I'll take care of the testing). Thanks

**Comment by amaltaro** [comment]
Oh, if you consider it to be a new issue, then go ahead and file a new GH issue and start working on a bug fix please.

**Pull request merged**
