### PR TITLE
Only change jobPrio when it has a diff prio

### PR DESCRIPTION
**Pull request by amaltaro**
Quick patch provided by Brian. @bbockelm @ticoann iplease review. We need to push it to production asap.

There is still one thing we have to fix, it seems we first submit jobs to condor queue and only then we change its prio (creating one condor_qedit more). But this will have to wait.

### CODE REVIEW

**Comment by bbockelm** [comment]
There's a second condor_qedit below this that also needs to be changed.  Can you update it?

**Comment by ericvaandering** [comment]
Are we using condor plugin or pycondor plugin?

**Comment by amaltaro** [comment]
@bbockelm code updated.
@ericvaandering no, but move to pycondor is my plan for the next wmagent production release (beginning of june)

**Comment by amaltaro** [comment]
Eric, trying to answer you again :-) we are still using condor plugin. It seems pycondor is much more stable now (I know T0 guys ran a few replays using it).

**Comment by ericvaandering** [comment]
So do we need to make sure the same sort of change gets into PyCondorPlugin or does it not suffer from the problem?

**Comment by bbockelm** [comment]
Yup - same sort of change needs to be ported.

**Comment by ticoann** [comment]
I guess it was causing the problem when it try to update the priority with same priority, right?
Since I don't know the syntax, if Brian said it looks OK, it is good to go. 
Do you want me to updated the production agent? You can include the PyCondor version on master patch. Thanks,

**Comment by bbockelm** [comment]
Yeah - even if the classad is unchanged, it apparently sends an "update pending" message which is causing a problem.

**Comment by amaltaro** [comment]
PyCondor has been updated as well. I guess we can now go ahead and patch the production agents (?)

**Comment by amaltaro** [comment]
Pushed to production. I'll create the master version tomorrow or on Monday :-)

**Comment by ticoann** [comment]
Thanks Alan, merging it since this is against WMAgent version. I will create the master version.

**Comment by ticoann** [comment]
#5852 is created

**Comment by amaltaro** [comment]
:+1:

**Pull request merged**
