### PR TITLE
Remove site from DESIREDSites if task thresholds are 0

### LINKED ISSUE #7181: Multi-psn jobs don't respect all site thresholds
Diego noticed some merge jobs being sent to both CERN and HLT, even though HLT Merge task has 0 threshold (both sites are normal and have site thresholds, but only CERN has Merge thresholds > 0).

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7181

Hopefully it won't affect much the component's performance. I'm out of ideas on how to efficiently remove a site from the DESIRED_Sites when one of them is up but its task has 0 thresholds.

### CODE REVIEW

**Comment by ticoann** [comment]
Are you planning to add this to production new agents?

**Comment by amaltaro** [comment]
I was planning to patch at least the cms@home agent, since it has a special setup and we need this fix in. However, if we can properly test it, then we could indeed patch the agents, it touches only one file in the end. I'm still checking the performance though

**Comment by bbockelm** [comment]
@vlimant - take note of this one.

@amaltaro - this only takes in effect at job submit time, right?  If so, I can't think of possible issues right now.

**Comment by amaltaro** [comment]
> @amaltaro - this only takes in effect at job submit time, right? If so, I can't think of possible issues right now.

that's correct! If someone sets a task-specific thresholds to 0, it has no impact on anything already in the condor queue or somewhere else.

**Comment by amaltaro** [comment]
I was using a key from the other cache data structure. I'll try to merge them altogether in another PR with minor improvements to this code (related to the JobPackage investigation).

**Comment by amaltaro** [comment]
Ok, I tested with HLT Merge thresholds set to 0 and I see that site being taken out of the site list:
```
  DESIRED_Sites = "T2_CH_CERN"
  ExtDESIRED_Sites = "T2_CH_CERN,T2_CH_CERN_HLT"
```

@ticoann please review and merge. I'll come with further changes tomorrow, but in another PR :)

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
Nice, Alan.

**Pull request merged**
