### PR TITLE
Apply glideIn restrictions to resource estimation - master

### PR DESCRIPTION
**Pull request by amaltaro**
master version of #6200

### CODE REVIEW

**Comment by ericvaandering** [comment]
retest this please

**Comment by amaltaro** [comment]
I don't think it will pass pylint tests, since it will complain about the non-member in PromptReco spec.
Unless it's failing due to something else (?)
@ticoann just finished my latest test and it's good to go

**Comment by amaltaro** [comment]
Changed default value to None here as well. Now good to go

**Comment by amaltaro** [comment]
Fixes #5738 and it's ready to be merged

**Pull request merged**
