### PR TITLE
add deployment script

### PR DESCRIPTION
**Pull request by ticoann**
depends on #8011 Do not merge until new agent is ready

### CODE REVIEW

**Comment by amaltaro** [comment]
Seangchan, this bin script should have been merged with 8011. Otherwise we need to cut another tag when this deployment fix is merged.

**Comment by ticoann** [comment]
Hi Alan, yes. But didn't we agree that we won't merge this until we need to deploy new agent with a new tag. Actually it seems we can just need to change the deploy instruction so it can work with different tags.

```
wget -nv https://raw.githubusercontent.com/dmwm/WMCore/master/bin/deploy-wmagent.sh
->
wget -nv https://raw.githubusercontent.com/dmwm/WMCore/1.1.6.pre4/bin/deploy-wmagent.sh
```

**Comment by amaltaro** [comment]
Yes, for the deployment script. The other script (wmagent-upload-config) is sort of part of the WMCore base code, since we need to execute it during deployment (meaning, we'd have to patch the agent during deployment to make it work).

We could indeed update the deployment instructions, but then it's another thing that we need to keep track and keep updating. Taking the master one is always easier :)

**Comment by ticoann** [comment]
Alan, I updated the patch do have default location in separate location. I am not sure that is the best location. Also I think we need to have some discussion on the structure of the config.

**Review by amaltaro — APPROVED** [review]
Patch looks good to me. As we discussed, feel free to merge it.

**Pull request merged**
