### PR TITLE
[py2py3] Fix unittests from Slice 11 in py3

### LINKED ISSUE #10542: [py2py3] Check unittests from Slice 11 in py3
#### Intro

We need to make sure that the work done in the migration slices
is py3 compatible. In particular, we should make sure that the
unittests that are involved in each slice do not fail.

The schedule for this validation / bug-fixing campaign is kept at #10422

#### Details

This issue is about checking that the unittests from Slice 11,
issue #10135 and PR #10299, do not fail.
A non-exhaustive list of the ut that need to pass is

```
# broken
test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/Block_t.py
# ok
test/python/WMQuality_t/Emulators_t/DBSClient_t/MockDbsApi_t.py
test/python/WMCore_t/Services_t/TagCollector_t/XMLUtils_t.py
test/python/WMCore_t/Services_t/TagCollector_t/TagCollector_t.py
test/python/WMCore_t/Storage_t/Backends_t/VandyImpl_t.py
test/python/WMCore_t/Storage_t/Backends_t/GFAL2Impl_t.py
test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py
test/python/WMCore_t/Storage_t/Backends_t/XRDCPImpl_t.py
test/python/WMCore_t/Storage_t/Backends_t/CPImpl_t.py
test/python/WMCore_t/Storage_t/Backends_t/LCGImpl_t.py
test/python/WMCore_t/Storage_t/Backends_t/FNALImpl_t.py
test/python/WMCore_t/WorkQueue_t/Policy_t/End_t/SingleShot_t.py
test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/Dataset_t.py
test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/MonteCarlo_t.py
test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/ResubmitBlock_t.py
test/python/WMCore_t/WMSpec_t/WMStep_t.py
```

check also
- [x] `src/python/WMCore/Storage/Plugins/`
- [x] `src/python/WMQuality/Emulators/DataBlockGenerator/`
- [x] `src/python/WMCore/Services/WMStats/`
- [x] `src/python/WMCore/WorkQueue/Policy/`
- [x] `src/python/WMCore/WMSpec/WMStep.py`

### PR DESCRIPTION
**Pull request by mapellidario**
Fixes #10542

#### Status
In development

##### fixed

`SRMV2Impl_t.py`
- [x] `test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py:SRMV2ImplTest.testCreateOutputDirectory_exitCode`
- [x] `test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py` raises some warning realted to buffersize of `Popen`, but the uinittests pass and they are marked as integration anyways. Despite no changes have been made, i consider these "fixed"

`src/python/WMCore/Services/Requests.py`
- [x] fixes `test/python/WMCore_t/Services_t/TagCollector_t/TagCollector_t.py`
  - check if the unittest failure is caused by this change
- [x] `test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/Block_t.py:BlockTestCase.testContinuousSplittingSupport`. Rucio mock data has a similar problems to DBS mock data, with `u''` in the key strings
  - implemented a first draft / proposal, by emulating what has been done by Alan with DBS mock data

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
follow up to #10299 

#### External dependencies / deployment changes
nope

### CODE REVIEW

**Comment by mapellidario** [comment]
@amaltaro `test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py:SRMV2ImplTest.testCreateOutputDirectory_exitCode` is failing in py3 with [1]


This seems to be erlated to how we are using `self.assertRaises`, if I try to fix with

```diff
-        self.assertRaises(RuntimeError("ERROR creating directory, test"),
-                          self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5"))
+        with self.assertRaises(RuntimeError):
+            self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5")
```

I get [2]. This is reasonable, since the raise should come from [3], but it is inside a `try - except` block and it does not reach `assertRaises`. 

Moreover, in py2 both (syntax taken from [stackoverflow](https://stackoverflow.com/a/25047330/5313348))

```diff
-        self.assertRaises(RuntimeError("ERROR creating directory, test"),
-                          self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5"))
+        self.assertRaises(RuntimeError("ERROR creating directory, test"),
+                          self.SRMV2Impl.createOutputDirectory, "/folder/test/test2/test3/test4/test5")
```
and
```diff
-        self.assertRaises(RuntimeError("ERROR creating directory, test"),
-                          self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5"))
+        with self.assertRaises(RuntimeError):
+            self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5")
```
also fail with [2], so it seems like the current implementation in py2 is not really checking that the exception is being raised.

Do you have idea how this works in py2? I am a bit confused

[1]: 


```plaintext
======================================================================
ERROR: testCreateOutputDirectory_exitCode (WMCore_t.Storage_t.Backends_t.SRMV2Impl_t.SRMV2ImplTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre6/sw/slc7_amd64_gcc630/external/py3-mock/4.0.3/lib/python3.8/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py", line 61, in testCreateOutputDirectory_exitCode
    self.assertRaises(RuntimeError("ERROR creating directory, test"),
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre6/sw/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre6/sw/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/unittest/case.py", line 187, in handle
    raise TypeError('%s() arg 1 must be %s' %
TypeError: assertRaises() arg 1 must be an exception type or tuple of exception types
-------------------- >> begin captured stdout << ---------------------
Warning: Exception while invoking command:
srmls -recursion_depth=0 -retry_num=1 
/folder/test/test2/test3/test4Exception: ERROR checking directory existence, test
Go on anyway...

--------------------- >> end captured stdout << ----------------------
```

[2]:

```plaintext
======================================================================
FAIL: testCreateOutputDirectory_exitCode (WMCore_t.Storage_t.Backends_t.SRMV2Impl_t.SRMV2ImplTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre6/sw/slc7_amd64_gcc630/external/py3-mock/4.0.3/lib/python3.8/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py", line 62, in testCreateOutputDirectory_exitCode
    self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5")
AssertionError: RuntimeError not raised
-------------------- >> begin captured stdout << ---------------------
Warning: Exception while invoking command:
srmls -recursion_depth=0 -retry_num=1 
/folder/test/test2/test3/test4Exception: ERROR checking directory existence, test
Go on anyway...

```

[3] https://github.com/dmwm/WMCore/blob/ec888c374d727f5ec3614d4e5e707373fb9e2cff/src/python/WMCore/Storage/Backends/SRMV2Impl.py#L75-L88

**Comment by amaltaro** [comment]
@mapellidario regarding this test that you just asked about:
SRMV2Impl_t.py:SRMV2ImplTest.testCreateOutputDirectory_exitCode

it's actually a mystery to me as well. Your observation is correct btw, the `RuntimeError` exception is trapped in the try/except, so that test is actually ill.

I just tested it in the PY2 environment, and the current test actually evaluates to true. However, if I replace that assert to be used with the context manager `with self.assert...`, then it fails with "RuntimeError not raised". 

There must be a trick in the way those are evaluated, but my preference is always to use the one with a context manager, that way we have a clean command to be executed. 

Given that that command does not raise any exception, and it does not return anything, we might simply replace that assertRaises check by something:
```
        self.assertIsNone(self.SRMV2Impl.createOutputDirectory("/folder/test/test2/test3/test4/test5"))
```

Not a great test, but we have what we have ...

**Comment by mapellidario** [comment]
Thanks Alan for having taken a look and for the suggestion!

**Comment by mapellidario** [comment]
@amaltaro `test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/Block_t.py:BlockTestCase.testContinuousSplittingSupport` fails with 

```plaintext
KeyError: "Rucio mock API failed to find key for signature: getDID:[('didName', '/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace'), ('dynamic', False)]"
```

while the file `test/data/Mock/RucioMockData.json` contains

```plaintext
"didExist:[('didName', u'/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace')]": true,
```

This seems like what we already faced with DBS mock data. Shall I remove the `u''` from the RucioMockData or does rucio actually put those `u''`?

Thanks!

**Review by amaltaro — APPROVED** [review]
It's perfect to me! Once it's rebased, it's ready to go.

PS.: I checked the output of Rucio calls, and its py2 unicode:
```
>>> pprint(rucio.getDID("/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace", dynamic=False))
{u'account': u'sync_t0_ch_cern_tape',
 u'bytes': 4445699,
 u'expired_at': None,
 u'length': 1,
 u'monotonic': False,
 u'name': u'/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace',
 u'open': False,
 u'scope': u'cms',
 u'type': u'DATASET'}
```

so the change you made looks good to me either. Thanks, Dario.

**Comment by mapellidario** [comment]
Oh no, I removed all the `u''` from the mock file! Thanks for checking, i think i need some other investigation, we risk breaking py2 code with my changes

**Comment by mapellidario** [comment]
@amaltaro , can I ask you to run 

```python
pprint(rucio.getDID("/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace", dynamic=False))
```

in py3 also? thanks!

**Comment by mapellidario** [comment]
### we are good to go in py2 and py3

Actually, I was mistaken and now understood how it works (and I will state some obvious things for you, but will certainly help future-me). Looking into `RucioMockData,json`, it contains 

```json
...
 "getDID:[('didName', u'/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace'), ('dynamic', False)]": {
  "account": "sync_t0_ch_cern_tape",
  "bytes": 4445699,
  "expired_at": null,
  "length": 1,
  "monotonic": false,
  "name": "/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace",
  "open": true,
  "scope": "cms",
  "type": "DATASET"
 },
...
```

so when you call `rucio.getDID("/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace", dynamic=False)` inside a unittest that calls the mocked version of rucio, `MockRucioApi.py` parses the calls, builds a string like ` "getDID:[('didName', u'/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace'), ('dynamic', False)]"` and uses it as a key for the dictionary built from `test/data/Mock/RucioMockData.json`

**Conclusion**: removing `u''` inside `RucioMockData.json` only affects how the mock retrieves the data, not how the mock emulates rucio. Removing `u''` from `RucioMockData.json` and adapting `MockRucioApi.py` to the new file is a viable solution to keep py2 and py3 compatibility. 

### we are lucky in py2

In py2 `rucio.getDID()` returns a dictionary with all unicode strings (as in Alan's comment https://github.com/dmwm/WMCore/pull/10584#pullrequestreview-683258095). 

In py2, `json.load()` returns a dictionary where all strings (both keys and values) are unicode strings, so that when retrieving the data from the json file inside `MockRucioApi` with

```python
result = MOCK_DATA[signature]
print("DM result", type(result), result)
print("DM result.get('name')",   type(result.get('name')),result.get('name'),)
print("DM result.get(b'name')",  type(result.get(b'name')), result.get(b'name'))
return result
```

we get

```plaintext
DM result <type 'dict'> {u'account': u'sync_t0_ch_cern_tape', u'name': u'/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace', u'type': u'DATASET', u'bytes': 4445699, u'monotonic': False, u'length': 1, u'scope': u'cms', u'open': True, u'expired_at': None}
DM result.get('name') <type 'unicode'> /MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace
DM result.get(b'name') <type 'unicode'> /MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace
```

We are lucky (or maybe it was a conscious design choice) that rucio behaves in the same way as `json.load`.

Moreover, we are also lucky that in py2 when you look for a key of a dictionary, if the key is a string, then it automatically looks for both the unicode string and the automatically-encoded corresponding bytes string.

### py3: everything works as expected

From `MockRucioApi` we get

```plaintext
DM result <class 'dict'> {'account': 'sync_t0_ch_cern_tape', 'bytes': 4445699, 'expired_at': None, 'length': 1, 'monotonic': False, 'name': '/MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace', 'open': True, 'scope': 'cms', 'type': 'DATASET'}
DM result.get('name') <class 'str'> /MinimumBias/ComissioningHI-v1/RAW#217ea8d8-0c4f-11e1-b764-003048caaace
DM result.get(b'name') None None
```

notice that when we look for a key that is a unicode string (`'name'`) with its corresponding bytes string (`b'name'`) we do not receive anything back

**Comment by amaltaro** [comment]
The description you gave for the mock API usage is precise. We use the exactly the same mechanism for DBS as well.

Dario, these changes are looking good to me, and I think you have already squashed the commits as you could, so I'm getting it merged. Thanks again!

**Pull request merged**
