### PR TITLE
Make filesize BIGINT in MySQL

### PR DESCRIPTION
**Pull request by ticoann**
#6436 for 1.0.12_wmagent

### CODE REVIEW

**Comment by amaltaro** [comment]
thanks Seangchan!

**Comment by ticoann** [comment]
Thank YOU!, Alan, do you need a new tag with this?

**Comment by amaltaro** [comment]
Sounds a good idea, can you create a 1.0.12.patch1 tag please? DB schema changes are always painful to patch, better an rpm for that.

**Comment by ticoann** [comment]
@amaltaro, Alan, is there any other patch need to included?

**Comment by amaltaro** [comment]
Nope, not yet :)

**Comment by ticoann** [comment]
How about https://github.com/dmwm/WMCore/pull/6427?

**Comment by amaltaro** [comment]
Needs to be reviewed and it's not critical to the current agent, from what I can tell (you should get some sleep :), we can tag the repo later)

**Comment by ticoann** [comment]
Thanks Alan. I will go sleep. :smile:  1.0.12.patch1 is created.

**Comment by amaltaro** [comment]
Hmm, something bad happened. The only tags I see in WMCore are JENKINS or 1.0.12

**Comment by ticoann** [comment]
Indeed, but if you check out WMCore and do "git tag -l". you can see all the tags. I wonder whether it is temporary problem on github or there is some limit on displaying number of tags.

**Comment by amaltaro** [comment]
True. I hope it's not a GH feature... The tag is there, thanks

**Comment by ticoann** [comment]
Yes, the link is even there (so we shouldn't have problem creating rpm).
https://github.com/dmwm/WMCore/tree/1.0.12.patch1

**Pull request merged**
