### PR TITLE
bring back exit code 60317: for use in CRAB3

### PR DESCRIPTION
**Pull request by belforte**
as requested in https://github.com/dmwm/WMCore/pull/7741#issuecomment-288147907

### CODE REVIEW

**Comment by amaltaro** [comment]
I see you managed to do so :-)

**Comment by belforte** [comment]
the ugly way: git checkout master, copy the edited file somwhere,  git checkout -b 1.1.0_crab, copy back the changed file, git push origin 1.1.0_crab, visit github and do the PR.
I thought GIT had a way to say "pick what I changed in this branch and apply same change to this other branch"... but maybe branches can potentially be so different that that's insane to support ?

**Comment by ticoann** [comment]
@belforte Stefano, do you need a new tag?

**Comment by belforte** [comment]
@ticoann not now, thanks. We'll let you know

**Comment by ericvaandering** [comment]
> I thought GIT had a way to say "pick what I changed in this branch and apply same change to this other branch"... but maybe branches can potentially be so different that that's insane to support ?

Not sure if this was before or after my previous comment, but this is what cherry-pick does. It can do one commit or a range. It works by generating patches from one branch and applying them to the other. It works well as long as you didn't change the same files in the 2nd branch.

**Comment by belforte** [comment]
it was before. And your comment answers all my doubts.
thanks again

**Pull request merged**
