### PR TITLE
Try to solve issues with DBS not using the mocked emulator

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
1st and second round results are more or less what I expected. 3rd round is not.

**Comment by ericvaandering** [comment]
I understand the emulator error. Will try to fix. It's that a list inside a dictionary inside a list is not in the same order.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann please merge. The issue I was seeing before seems to be intermittent so when it happens again, I will know where to fix it.

**Pull request merged**
