### PR TITLE
update Stageout Errors with some heuristic for WebDav

### LINKED ISSUE #11329: add WebDav errors to StageOut Exceptions
**Impact of the bug**
Reporting webdav errors with generic failure even when a proper reason is available, this makes troubleshooting and user support in CRAB (at least) un-necessarely painful

**Describe the bug**
`STAGEOUT_ERRORS` dictionary in `WMCore/WMExceptions.py` is a collections of regexp's which are used to parse error messages from FTS in order to assing one exit code to the job. The current version pre-dates WebDav and needs updating, there are a couple common use cases (at least) where current code reports `60324 - Other stageout exception. ` but we could set a more meaningful exit code instead.

**How to reproduce it**
no need to

**Expected behavior**
When WebDav report a useful message like "Permission refused" we should map into proper exit code.

**Additional context and error message**
Since we discover FTS messages as we operate and they are not standardized but can change, there will always be need to update the list of regexp which we match in here

### PR DESCRIPTION
**Pull request by belforte**
Fixes https://github.com/dmwm/WMCore/issues/11329

#### Status
ready

#### Description
long due addition of heuristic for webdav message when write to RSE fails

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by belforte** [comment]
@amaltaro @todor-ivanov I squashed commits and Jenkins tests are OK. These changes will be useful for CRAB users and fully harmless for everybody else. Is there something more I need to do before this is merged ? Thanks

**Comment by amaltaro** [comment]
@belforte thanks Stefano. Would you mind making a WMCore GH issue just to summarize the problem and what would be expected behavior? Just so we can properly track developments and changes.

**Comment by belforte** [comment]
> @belforte thanks Stefano. Would you mind making a WMCore GH issue just to summarize the problem and what would be expected behavior? Just so we can properly track developments and changes.

Done. See #11329

**Review by amaltaro — APPROVED** [review]
Thanks Stefano! It looks good to me.

**Pull request merged**
