### PR TITLE
fix AnalyticsDataCollector_t

### PR DESCRIPTION
**Pull request by ticoann**
Just Erik to start with not failing test. - We should change this to mock as well.

### CODE REVIEW

**Comment by ticoann** [comment]
I didn't expect this will break other test. Thread shouldn't be shared between test.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by goughes** [comment]
test this please

**Comment by ticoann** [comment]
this was just for the reference. Closing it.

**Pull request closed without merging**
