### PR TITLE
add mendatory down_components field.

### PR DESCRIPTION
**Pull request by ticoann**
global workqueue report also need to contain this value.

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
I don't know why following unittest fails. I will create the separate issue.

    WMCore_t.Services_t.LogDB_t.LogDB_t.LogDBTest:test_thread_name changed from error to failure
    WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testProcessingWithPileup changed from error to failure

**Comment by amaltaro** [comment]
Hmm, that may explain then why I didn't see my agent in the list of agents :-)
I'll fix it today.

**Comment by ticoann** [comment]
With this patch, do you still have problem?

**Pull request merged**
