### PR TITLE
Remove support for Unpacking user tarballs. No longer used by CRAB.

### LINKED ISSUE #10442: Deprecate or Re-implement support for user tarballs (used by CRAB)
**Impact of the new feature**
Simplify cmssw step deprecating support of python-based user tarballs unpacking.

**Is your feature request related to a problem? Please describe.**
We use some python-based code living in WMCore in the bash script we use to execute [cmsRun](https://github.com/dmwm/WMCore/blob/748fb8df96a9328600b254b934c8f96ced00505c/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L400-L413). We want to decouple cmsRun from WMCore and this script that lives in WMCore, would be executed using the CMSSW python version 

**Describe the solution you'd like**
We don't use this in production, but we should make sure CRAB is not using it either so we can deprecate its use. Otherwise, we could likely re-implement [this script](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/UnpackUserTarball.py
) in full-bash, so it doesn't depend on any python version.

Note:  This is where CRAB seems to use it.
https://github.com/dmwm/CRABServer/blob/dc26ef6512e5c75cf7ce0106f9838e63b870dac1/scripts/CMSRunAnalysis.py#L886
https://github.com/dmwm/CRABServer/blob/dc26ef6512e5c75cf7ce0106f9838e63b870dac1/scripts/CMSRunAnalysis.py#L740

**Additional context**
Although this is sort of related to python2/3 migration,  it does not affect production but CRAB, as we don't call this part of the code in production, so we can deal with this later on

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #10442

#### Status
ready

#### Description
This gets rid of the user tarball unpacking support, which was calling it via python2 and is no longer used by CRAB.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
Related CRAB issue:
https://github.com/dmwm/CRABServer/issues/7215

Where it's confirmed the user tarballs python script isn't used by CRAB anymore

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@khurtado I am not sure whether you are still working on this, but it's looking good to me and we could have it in a release for tomorrow (well, cmsweb services release). Please let me know.

**Comment by khurtado** [comment]
@amaltaro Yes! I tested locally but besides the bash wrapper changes, I  wanted to be sure CRAB isn't using the UnpackUserTarball.py file anywhere either. Since Stefano [confirmed](https://github.com/dmwm/CRABServer/issues/7215) they don't, I think we can proceed with this PR approval

**Review by amaltaro — APPROVED** [review]
Perfect! It looks good to me then! Thanks Kenyi.

**Pull request merged**
