### PR TITLE
Apply glideIn restrictions to resource estimation

### LINKED ISSUE #5738: Do not submit jobs asking for too much resources
Now that glideInWMS is enforcing "MaxWallTimeMins" and "RequestDisk", we should change WMAgent NOT to submit greedy jobs to condor, otherwise those will be pending forever.
Instead, these jobs should be marked as jobfailed (or submitfailed) with a clear message.

It should be configurable and I guess it needs further discussion, but here is a first idea:
 - don't submit if job asks for more than 48h MaxWallTimeMins
 - don't submit if job asks for more than (27GB * RequestCpus) RequestDisk

### PR DESCRIPTION
**Pull request by amaltaro**
After being beat by PyCharm, I went back to the terminal :-)
Fixes #5738 We basically define in the agent min/max limits for diskUsage and
wallTime and these are going to be enforced. 

First test was Ok, will run more using different algos/cores.

@hufnagel do you want me to remove your previous patch (#6077)?

### CODE REVIEW

**Comment by hufnagel** [comment]
The cap for requested disk is nCores dependent, ie. nCores * MaxRequestDiskKB. Otherwise the logic looks ok and usable for the Tier0. Thefore you can remove some code I added in my previous patch.

 - capResourceEstimates method from DataStructs.Job
 - capJobTime and capJobDisk code in the EventAwareLumiBased job splitter
 - capJobTime and capJobDisk code in the PromptReco spec

**Comment by amaltaro** [comment]
> The cap for requested disk is nCores dependent,

Oups, I missed that detail. Will fix it soon.
About the previous patch, ok, I'll push it all together here. Thanks!

**Comment by amaltaro** [comment]
Code updated, I'll make a new commit later on with pep8 fixes.

**Comment by ericvaandering** [comment]
So is there not a pull against master for this? Jenkins is failing because of the merge against 109_wmagent issue. Should have it fixed now.

**Comment by amaltaro** [comment]
Sorry, not yet Eric. Should I always make a PR for master first?

**Comment by ericvaandering** [comment]
No, just wondering.

**Comment by ericvaandering** [comment]
retest this please

**Comment by hufnagel** [comment]
Reviewed the code, never use an empty dict as the default value for a parameter in the function definition. Pylint should complain about it too.

Reason its dangerous is that any modifications to said default parameter will survive to the next function call, ie. if you then still use the default, it'll now be the value that parameter had at the end of the previous function call. The dictionary is not reinitialized between function calls.

You wouldn't be exposed to this with your code here, but please change the default value to None.

**Comment by amaltaro** [comment]
sigh... I wrongly rebased this PR and now it;s a mess! I will create a new one and close this one

**Comment by amaltaro** [comment]
Yeah, it did complain. But I kept an empty dict for clarity, so if someone look at that var, he knows right away that it's supposed to be a dict.

**Comment by hufnagel** [comment]
No, please don't do that. None is a perfectly appropriate value for any parameter.

**Comment by hufnagel** [comment]
The problem here is that dicts are passed by reference, not value. So no deep copy. Which means your {} default is initialized once when the class is loaded and then is just reused and reused and reused.

**Comment by amaltaro** [comment]
Yes, but in this case that dict will only change when the component gets restarted (class loaded) and no code is supposed to update it. Anyways I will initialize it to None then.

**Comment by amaltaro** [comment]
New PR made, closing this one. Sorry for the mess

**Comment by hufnagel** [comment]
I wouldn't insist if we weren't bitten by this before :-). I can tell you, this is a total pain to debug if you don't expect it.

Plus the code might be ok now, but you never know how its going to evolve. I'd rather not leave booby traps lying around...

**Comment by amaltaro** [comment]
Thanks Dirk! I updated master as well.

**Comment by ericvaandering** [comment]
Could not agree more with Dirk. You have the same issue with lists as parameters. So while it's ugly to have 

```python

if myDict is None:
    myDict = {}

```
it's the only safe way.

**Comment by amaltaro** [comment]
Ok, will consider it from now on :-)

**Pull request closed without merging**
