### PR TITLE
take dict param for stepchain

### PR DESCRIPTION
**Pull request by ticoann**
Possibly replace #7650. Not at all tested. @amaltaro, Alan, could take a quick look whether this is completely non sense or not?

### CODE REVIEW

**Comment by ticoann** [comment]
Also I have one question, For step chain, the first step is basically a Task, correct?

**Comment by ticoann** [comment]
@amaltaro, Alan, don't review this one, I try to  make a little cleaner but getting messier. 😄

**Comment by amaltaro** [comment]
First, stop working.
Second, too late, I already have a big text with some pointers :) I'll post them in a few minutes

**Comment by ticoann** [comment]
Yes, it is hard to get the  Step level args, this patch only handles dict format. I initially thought nested level (Step level definition is automatically handled but it seems not the case).
And there are code I don't quite understand, (Merge case).

**Comment by amaltaro** [comment]
This is the basic structure of a StepChain request:
 *) one production/processing task (let's say AllStepsTask), 
  -) inside this single task, we have the output modules section (they are not a task here). Each of them contain the definition of the unmerged files created (that would be inherited from the task, 1st problem!)
 **) for each output module in AllStepsTask, we also create a merge Task (the first merge task is created at the moment we create the top level task - so StdBase uses the workload properties without, 2nd problem!).
 ***) and once we get into the assignment business, it goes beyond the spec files and it gets much dirtier :-(

All in all, the task properties (AcqEra/ProcStr/ProcVer) doesn't mandate what a Task is going to produce - and it's supposed to be a simple string/integer value - thus we need to make sure the output modules section are updated accordingly.

Looking at this example
https://alan-cloud1.cern.ch/reqmgr2/config?name=amaltaro_StepChain_Tasks_StepChain_Validation_170224_131205_6908

these kind of parameters are not correct:
```
amaltaro_StepChain_Tasks_StepChain_Validation_170224_131205_6908.tasks.GENSIM.parameters.processingString = 'GENSIM_StepChain_Tasks_StepChain_Validation_TEST_Alan_v1'
amaltaro_StepChain_Tasks_StepChain_Validation_170224_131205_6908.tasks.GENSIM.parameters.acquisitionEra = 'Integ_TestStep1'
```
since they actually correspond to the first step (cmsRun1) only, but the further two steps would need different settings. Which's why we have to edit the output module sections. In that config page, look for `.transient =`. You'll find 4 True (creating unmerged files, running all in the only Production task) and then 4 False, corresponding to the merge tasks and creating the merged files. They need to match, otherwise I believe the agent could get lost merging them (and we don't want incorrect info between them). When looking at those transient stuff, a few lines below you should see `processedDataset`, AFAICS this is how we build the list of outputDatasets.

**Comment by amaltaro** [comment]
(I stil didn't check my tests, first a coffee :-)) but I suggest we try to refactor it in the next month or so, if desired. Though I'm not sure we can make it much better, it's a nasty thing to do

**Comment by ticoann** [comment]
I think refactor would be major change. We need a codefest for that. 😄

**Pull request closed without merging**
