### PR TITLE
Proper fix for extraline in voms proxy info and add diagnostics

### LINKED ISSUE #12075: protect voms-proxy-info in Credential/Proxy against JVM warning message
**Impact of the bug**
sometimes CRAB TaskWorker fails to submit a user taskl

**Describe the bug**
CRAB TW have multiple processes running at same time. the JVM used in `voms-proxy client` can at time print a warning line before the actual information, still returning exit code 0. Proxy.py tries to eval the reply as an int, and raises an exception.
More details in https://github.com/dmwm/CRABServer/issues/8625

**How to reproduce it**
not easily reproducible. A full protection may be out of reach. But curing the known use case will surely help.

**Expected behavior**
fewer "obscure" submission failure

**Additional context and error message**
`voms-proxy-info --timeleft` returns
```
[0.002s][warning][perf,memops] Cannot use file /tmp/hsperfdata_crab3/760874 because it is locked by another process (errno = 11)
447504
```

I will provide a PR to fix this

### PR DESCRIPTION
**Pull request by belforte**
Fixes #12075 

#### Status
Ready

#### Description
Remove possible extra lines in voms-proxy-info stdout when parsing it. Avoid using `| tail`
Also add messages in case of error and add exception catching

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
overrides https://github.com/dmwm/WMCore/pull/12076

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by belforte** [comment]
I will not try to fix tricky pylint complains about 10+ years old code. Too much risk. All in all at some point this will not be needed anymore.

**Comment by belforte** [comment]
tested on crab-dev-tw01, currently deployed on crab-preprod-tw01

**Comment by amaltaro** [comment]
@belforte once you are happy with your changes, please make a review request through the GitHub interface (right top corner, under `Reviewers`). For more details, please check out Step 9 under this link: https://github.com/dmwm/WMCore/blob/master/CONTRIBUTING.rst#contributing

**Comment by belforte** [comment]
and squash commits of course !

**Comment by belforte** [comment]
running in production TaskWorker since this morning. Let's wait a couple of days

**Comment by belforte** [comment]
no proxy related errors in CRAB anymore. Finalizing PR

**Review by amaltaro — APPROVED** [review]
It looks good to me and the failing unit tests are actually unstable. Thanks Stefano!

**Comment by amaltaro** [comment]
@belforte it looks like you have already found 2.3.6rc2 in pypi. I didn't share that with you because our CD pipeline got broken with a recent release, and we have not yet merged that fix in. In any case, that failed only the Docker image creation, which seems irrelevant to you.

**Comment by belforte** [comment]
We have been running production TW with my branch since more than a week. My branch has the fix on top of what master was few days ago... :man_shrugging:  I believe it is good for us :-)

**Pull request merged**
