### PR TITLE
add cascade rejected and aborted

### PR DESCRIPTION
**Pull request by ticoann**
still need to be tested

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
Change sounds good.
About the update status itself:
https://github.com/ticoann/WMCore/blob/40a2a815224d1d70de223e45771ce5c9beb0332f/src/python/WMCore/ReqMgr/Service/Request.py#L504

in case it fails (let's see the transition is not allowed), it will just return a http error exit code, right? It won't raise an exception, such that it will keep going updating all the children?

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, Eric, do you know why this still complains about unused argument?

**Comment by ericvaandering** [comment]
Yesterday morning that exception was not in place. This run should not complain about W0613

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
create the new issue related to pylint.

**Pull request merged**
