### PR TITLE
treat all the request as reqmgr2

### PR DESCRIPTION
**Pull request by ticoann**
#replace 7401 (need to create the 1.0.22_cmsweb branch and 1.0.21_wmagent branch)

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, Alan, I think it is better solution then the #7401.  We need to also flip the ReqMgr2Only flag for reqmgr1 request for active workflows, to ops script won't use reqmgr1 api.

**Comment by amaltaro** [comment]
It's likely a better approach indeed (and there are no unit tests to be fixed :))

**Comment by ticoann** [comment]
Also, I think we can make script to do the same thing for now instead of updating cmsweb.

**Comment by ticoann** [comment]
separate script is created and change the problematic requests. cmsweb branch doesn't needs this patch anymore only wmagent branch.

handling reqmgr1 request vlimant_task_EXO-RunIIFall15DR76-04661__v1_T_161103_041731_9842: running-closed
reporting... vlimant_task_EXO-RunIIFall15DR76-04661__v1_T_161103_041731_9842
handling reqmgr1 request pdmvserv_task_EXO-RunIIFall15DR76-04677__v1_T_161019_035339_1562: running-closed
reporting... pdmvserv_task_EXO-RunIIFall15DR76-04677__v1_T_161019_035339_1562
handling reqmgr1 request prozober_ACDC1_EXO-RunIISummer15GS-07200_00442_v0__161103_113427_2848: running-closed
reporting... prozober_ACDC1_EXO-RunIISummer15GS-07200_00442_v0__161103_113427_2848
handling reqmgr1 request prozober_ACDC0_EXO-RunIISpring16DR80-04683_00676_v0__161031_101230_8231: acquired
handling reqmgr1 request dmason_task_HIG-RunIISummer15wmLHEGS-00749__v0_HEPCloudII_161110_041127_2287: running-closed
reporting... dmason_task_HIG-RunIISummer15wmLHEGS-00749__v0_HEPCloudII_161110_041127_2287
handling reqmgr1 request pdmvserv_task_EXO-RunIIFall15DR76-04663__v1_T_161018_081956_9812: running-closed
reporting... pdmvserv_task_EXO-RunIIFall15DR76-04663__v1_T_161018_081956_9812

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Changes look good to me, Seangchan. Of course, if there is still any reqmgr1 request out there, then oracle will get inconsistent, but I guess we don't really care :)

**Pull request merged**
