### PR TITLE
transaction logic fix (for tier0) 1.0.17 version NEVER MERGE

### PR DESCRIPTION
**Pull request by ticoann**
when test is finished we will just close the patch

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, Valentin, I applied your changes please review.

**Comment by vkuznet** [comment]
Seangchan,
if you didn't make any cut-and-paste errors it seems ok. I only looked at
try/except parts since the rest of the logic were in previous PR.
Sorry I don't have time for deep comparison with previous PR.
Valentin.

**Comment by ticoann** [comment]
Thanks Valentin, I didn't change the original patch. I just want to make sure the new part is correct. You have a wonderful vacation, hopefully when you come back everything is merged 😄

**Comment by ticoann** [comment]
don't need this any more (T0 using newer version)

**Pull request closed without merging**
