### PR TITLE
Fix a problem with new lumilist format

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by ticoann** [comment]
@mmascher, Marco, do you need a new tag with this patch?

**Comment by ticoann** [comment]
@amaltaro, did we see any problem with this case. I assume it returns "string" format in some cases? I am asking whether we should create wmagent branch patch for this.

**Comment by ericvaandering** [comment]
I think this has to do with how CRAB is constructing them that the lumi numbers are not guaranteed to be integers, probably because the lumi numbers are now dict keys.

What I find interesting is that this code works with the dict of events/lumi now too. I never envisioned that usage. :-)

**Comment by amaltaro** [comment]
Nope, I haven't spotted any issues with LumiList. Even if it didn't cause a real code execution problem, I would expect problems in the final outcome, but there where none as well.

**Pull request merged**
