### PR TITLE
work around EOS auth problems

### PR DESCRIPTION
**Pull request by hufnagel**
There is a problem with the gsi authentication plugin in xrootd. Effect is that jobs running at CERN loose their EOS privileges after a while and the job dies as it can't read any input anymore.

This patch works around this problem by increasing an internal xrootd timeout.

This has been open for a while, the xrootd team didn't really provide a real fix apart from "please upgrade to the latest xrootd client and check if this is still an issue". Even if the latest xrootd client fixes this, it'll take a while until we stop using CMSSW releases that use older clients.

Making a pull request because a) don't want to run with this custom patch in the Tier0 forever and b) CompOps production jobs at CERN should also be affected by this.

### CODE REVIEW

**Comment by hufnagel** [comment]
Ok, addressing these issues too...

**Comment by amaltaro** [comment]
Dirk, is this 86400 the maximum length a job can run at CERN without facing these xrootd disconnections? If so, then we should increase it to 2 days at least, no?

**Comment by hufnagel** [comment]
24h is what was recommended, I actually don't know exactly what this timeout does...

Also fixed the last spurious import.

**Comment by hufnagel** [comment]
Btw, I feel a bit uncomfortable merging this, but I also feel uncomfortable leaving it out as it seems to ne absolutely required for Tier0 operations (or also CompOps operations) at CERN. I started a HN thread about whether this is safe to merge

https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3572.html

maybe we should push a bit more to get an answer on this...

**Comment by amaltaro** [comment]
Yeah, to be honest I'm not really confident this problem happens in central production at CERN. Is Tier0 being locally mapped to cmsprd or cmsprod?

**Comment by ericvaandering** [comment]
Maybe on the timeout question, ask on the wan-access HN.

**Comment by hufnagel** [comment]
Maybe it doesn't happen to CompOps because they don't run much on the CERN cloud resources. But once you do you'll be inside the same pilots as the Tier0 jobs, I very much doubt that you won't be affected by this. CompOps using T2_CH_CERN/LSF is a different question, but that use should go down to almost zero over time.

**Comment by hufnagel** [comment]
Anyways, the way this was explained to me was a problem between CMSSW, the gsi plugin authentication handling inside xrootd and EOS, so to first order *everyone* running at CERN should be affected.

**Comment by hufnagel** [comment]
retest this please

**Comment by hufnagel** [comment]
retest this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by hufnagel** [comment]
Modify the patch to only implement the workaround at CERN.

**Comment by hufnagel** [comment]
@ticoann @ericvaandering , this is ready to be merged, can you review it please ?

**Comment by ticoann** [comment]
patch looks fine to me.

**Pull request merged**
