### PR TITLE
Use workflow datasets rather full list of datasets

### LINKED ISSUE #9226: MS Transferor is not creating PhEDEx subscription on a workflow basis
The subject is too short to describe the problem, so let me clarify it here.

It looks like MS Transferor is first finding out all datasets/blocks that have to be subscribed (belonging to workflows in a given status, like `assigned`), then it adds the same datasets/blocks to the requests to be made in PhEDEx, here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/RequestInfo.py#L486

which then make it to repeated PhEDExSubscription here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Transferor.py#L149

The expected behaviour would be to make a workflow-wise data placement, such that we can store the transfer ids and properly track their progress.

### PR DESCRIPTION
**Pull request by vkuznet**
Fixes https://github.com/dmwm/WMCore/issues/9226

#### Status
not-tested

#### Description
Use dataset list from workflow spec

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
https://github.com/dmwm/WMCore/issues/9226

#### External dependencies / deployment changes
no

### CODE REVIEW

**Comment by vkuznet** [comment]
Alan, can you invoke test again, the pylint report didn't process my last change and therefore is not accurate.

**Comment by amaltaro** [comment]
test this please
(you can also trigger it with this sentence, not sure it has to be alone in a comment or not, we shall see)

**Comment by vkuznet** [comment]
Alan, this sentence never worked for me (for whatever reason). I think only
admins can do that, and I'm not admin of WMCore.

**Comment by amaltaro** [comment]
Nah, it should work for you too. Give it a try please.

**Comment by vkuznet** [comment]
test this please

**Comment by vkuznet** [comment]
Alan, as you can see when I put `test this please` comment it does not trigger anything. So it still does not work for me.

**Comment by vkuznet** [comment]
And, according to posted report Unit test failure has nothing to do with changes I made. In this case the unit test which failed was `WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testSitesFromResourceControl`. It is clear that it is not related to MicroService.

**Comment by amaltaro** [comment]
You lack patience, Valentin. It's running.

Please have a look at the pylint reports, there is work for you in there.

**Comment by vkuznet** [comment]
ok, good to know that it works.

But, pylint is clean now. I don't know what you're talking about. It is the random (and not related to MS) unit test which is failing.

**Comment by amaltaro** [comment]
Don't worry about that unittest, I just ran it on my node and it succeeds.

About pylint, this is what I'm talking about:
```
C0330, line 228: Wrong continued indentation (add 11 spaces).
C0330, line 229: Wrong continued indentation (add 11 spaces).
C0303, line 418: Trailing whitespace
and these
Line 328, E502 the backslash is redundant between brackets 
```

all the rest is Ok.

**Comment by vkuznet** [comment]
Alan, I don't mind of fixing pylints but:
- it reported to be ok (green check mark)
- there are more CXXX type comments from the one you suggested and it is unclear which should be taken into consideration and which not
- in the same spirit, if (some) CXXX suggestions should be fixed why not to fix WXXX and/or RXXX ones?

So, it should be some rules to be applied and if you insist on them they should be available somewhere. 

Anyway, I'll submit changes to those you pointed out, but you should revisit how pylint should be treated and make it clear to everyone.

**Comment by amaltaro** [comment]
I'll create some guidelines once I have some free time. I agree it's important to have them to avoid saying the same thing hundreds of times in these pull requests.

In general, we have to fix any error and warnings (E and W types), unless they are too intrusive or labor intensive. Pylint refactoring and convention (R and C types) are less important and not required to fix, BUT we should get those fixed whenever the fix is simple (like pushing one button in the IDE).

In the end, many of those are common sense (I guess you don't want to rename every single variable in a module that someone else wrote...). But if you write them, then you should fix it.

Anyhow, now that you know this information, please save your and my time and get those fixed before asking for my review (keep in mind pylint fixes are meant to be in a **separate** commit)

**Comment by vkuznet** [comment]
Alan,
I suggest that you put guidelines link (or guidlines themselves) under your
issue template you recently introduced such that they will be visible in every
issue/PR.
V.

**Comment by amaltaro** [comment]
@vkuznet what's the status of thix fix? Is it ready for a review? Has it been properly tested?

**Comment by vkuznet** [comment]
it is ready for review and I run the code in my VM.

**Comment by amaltaro** [comment]
@vkuznet first error on the first second of MS execution:
```
Traceback (most recent call last):
  File "/data/srv/HG1906f-comp2/sw.amaltaro/slc7_amd64_gcc630/cms/reqmgr2ms/0.1.0.pre3/lib/python2.7/site-packages/WMCore/MicroService/Unified/Transferor.py", line 119, in transferor
    requestRecords = requestsInfo(requestRecords, self.svc, self.logger)
  File "/data/srv/HG1906f-comp2/sw.amaltaro/slc7_amd64_gcc630/cms/reqmgr2ms/0.1.0.pre3/lib/python2.7/site-packages/WMCore/MicroService/Unified/RequestInfo.py", line 395, in requestsInfo
    requestsToProcess = unified(svc, requestRecords, logger)
  File "/data/srv/HG1906f-comp2/sw.amaltaro/slc7_amd64_gcc630/cms/reqmgr2ms/0.1.0.pre3/lib/python2.7/site-packages/WMCore/MicroService/Unified/RequestInfo.py", line 501, in unified
    logger.debug("total # of workflows %s, datasets %s, blocks %s, evts %s, size %s (%s TB), cput %s (hours)", len(winfo.keys()), len(datasets), totBlocks, totEvents, totSize, teraBytes(totSize), totCpuT)
UnboundLocalError: local variable 'totBlocks' referenced before assignment
```

So you need to set those vars before the `for` loop as well, just in case the loop doesn't get executed (lack of work).

**Comment by amaltaro** [comment]
Besides the error I pointed out, changes are sound.

**Comment by vkuznet** [comment]
ok, I fixed the issue with total counters

**Review by amaltaro — APPROVED** [review]
Thanks, code looks good to me.

**Pull request merged**
