### PR TITLE
use the bulk lfns to dbs call to improve the performance

### PR DESCRIPTION
**Pull request by ticoann**
This is not really tested since agent is not deployed with new dbs rpm. Merging it so we can test when testbed is deployed. (This affects only WMAgent side not cmsweb applications)

### CODE REVIEW

**Comment by amaltaro** [comment]
This listFileArray call providing a list of parentLFNs worries me a lot. There are datasets with more than 5k files. I just hope we don't hit any limitation downstream...

**Comment by yuyiguo** [comment]
You are right. This is the function that Seangchan requested if I recalled correctly. I am thinking that the API has to put a maximum limit on the list length. My question for you guys is that what is the maximum length of the lfn list WMAgent calls? The same question goes for lumi list too. If I put a limit on DBS side, WMAgent needs to check for it.

**Comment by amaltaro** [comment]
Yuyi, I don't see any limit for number of LFNs or lumi list inside WMAgent. I believe we'll hit a limitation sooner or later, be that in WMAgent, DBS, Apache, etc. Sorry Seangchan, I didn't think of it before :-(

Perhaps we should slice these queries in WMAgent and make "half-bulk" DBS calls? IF so, I'd go for 10 LFNs/blocks (large strings) and 100 lumi list (smaller strings).

If we don't see any issues during validation phase, we could aim these changes for the next cycle IMO.

**Comment by ticoann** [comment]
Actually we are querying by blocks not dataset. I am not sure what will be the max length (length means number of lfns her not actually string length, right?)  I am guessing it would be < 1K.
I missed one thing which need to change though. I have another pull request made (#5718).
Since it is broken down in DBS side for Oracle call now I am using the dbs POST call api, it should handle this, shouldn't it?
What I am worrying about it how long will this call takes if we have close to passing 1K lfns. It talks to long (longer than 5 min which set in cmsweb), we should break down the calls.

**Pull request merged**
