### PR TITLE
Adapt OS/Arch requirements to Glidein proposed version

### LINKED ISSUE #5047: Adapt WMCore OS/Arch requirements to Glidein proposed version
See Stefano's talk for exact values. https://indico.cern.ch/event/293016/session/5/contribution/49/material/slides/0.pdf

Policy twiki to come, should be linked here when it does.

I inadvertently filed this in CRABServer and @belforte comments from there are reproduced below.

### PR DESCRIPTION
**Pull request by tsarangi**
Fix #5047
Adapt OS/Arch requirements to Glidein proposed version  (hang on until gWMS is ready for this)

### CODE REVIEW

**Comment by ericvaandering** [comment]
@belforte , @jamesletts ping! Are you ready for us to implement this change yet? It's been stuck in limbo as we move from shell based to python-library based condor interfaces.

**Comment by belforte** [comment]
I think new matching it is tested (or under test) in Integration Test Bed but not deployed yet.

**Comment by amaltaro** [comment]
There are 2 PRs changing the same thing and waiting for glidein/factory development to happen as well. @ericvaandering @tsarangi shall we close this one in favor of #5600 ?

**Comment by ericvaandering** [comment]
Did we come to consensus on this?

**Comment by belforte** [comment]
did glidein/factory converge on what they want us to do ? In the end the issue is how to communicate to glidein on which op.sys./hardware to start this executable.

**Comment by amaltaro** [comment]
I'm closing this one in favor of #5600 , feel free to re-open it if you wish

**Pull request closed without merging**
