### PR TITLE
Switch to MonteCarlo spec test to mock DBS

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann there is some issue here that I don't understand. Will try to investigate it today.

**Comment by ticoann** [comment]
Thanks Eric, I ran trigger the test again for following report.

WMCore_t.WMSpec_t.StdSpecs_t.MonteCarlo_t.MonteCarloTest:testMCWithPileup changed from success to error

**Comment by ericvaandering** [comment]
Yeah, I know. There is something going wrong with the mocking that is preventing that test from running.

**Comment by ericvaandering** [comment]
The failure in testMCWithPileup is being caused by some interaction with another test. If I split the tests more finely, it starts to succeed. Candidates are:

```
WMCore_t.WorkQueue_t.Policy_t.Start_t.Block_t.BlockTestCase" name="testInvalidSpecs"
WMCore_t.WorkQueue_t.WorkQueueSchema_t.WorkQueueSchemnaTest" name="testSchemaGeneration"
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest" name="testProcessing" 
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest" name="testSitesFromResourceControl" 
WMCore_t.Configuration_t.ConfigurationTest" name="testB" 
WMCore_t.Configuration_t.ConfigurationTest" name="testE" 
WMCore_t.DataStructs_t.File_t.FileTest" name="testDefinition" 
WMCore_t.DataStructs_t.Job_t.JobTest" name="testChangeOutcome"
WMCore_t.DataStructs_t.Subscription_t.SubscriptionTest" name="testGetWorkflow" 
WMCore_t.Database_t.CMSCouch_t.CMSCouchTest" name="testAttachments"
WMCore_t.Database_t.CMSCouch_t.CMSCouchTest" name="testCommitOne"
WMCore_t.RequestManager_t.ReqMgrPriority_t.ReqMgrPriorityTest" name="testB_InvalidPriority" 
WMCore_t.RequestManager_t.ReqMgrWebTools_t.ReqMgrWebToolsTest" name="testC_RemovePassword"
WMCore_t.Services_t.DBS_t.DBSReader_t.DBSReaderTest" name="testlistDatasetFileDetails"
WMCore_t.Services_t.Requests_t.TestRequests" name="testNoCache" 
WMCore_t.SiteScreening_t.BlackWhiteListParser_t.BlackWhiteListParserTest" name="testCEBlackList"
WMCore_t.Storage_t.TrivialFileCatalog_t.TrivialFileCatalogTest" name="testTrivialFileCatalog"
WMCore_t.WMBS_t.File_t.FileTest" name="testGetBulkLocations"
WMCore_t.WMBS_t.Fileset_t.FilesetTest" name="testSetLastUpdate"
WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest" name="testSingleRunsMultipleLumiCombineUneven"
WMCore_t.WMBS_t.Job_t.JobTest" name="testGetOutputMapDAO"
WMCore_t.WMRuntime_t.SandboxCreator_t.SandboxCreator_t" name="testMakeSandbox" 
WMCore_t.WMSpec_t.Persistency_t.PersistencyTest" name="testSplitUrl
WMCore_t.WMSpec_t.Steps_t.Template_t.TemplateTest" name="testC"
WMCore_t.WMSpec_t.WMWorkload_t.WMWorkloadTest" name="testPileupDatasetList"
WMComponent_t.TaskArchiver_t.TaskArchiver_t.TaskArchiverTest" name="testA_BasicFunctionTest"

Going to see if I can figure this out with a binary search.

**Comment by ericvaandering** [comment]
Seems the problem may be in testMakeSandbox which is running this very suspicious looking code:

```
        # Gotta remove this since python caches subpackage folders in package.__path__
        del sys.modules['WMCore']
        if 'WMCore.ZipImportTestModule' in sys.modules:
            del sys.modules['WMCore.ZipImportTestModule']

        import WMCore.ZipImportTestModule
```

Will look at it tomorrow. Anyone have a bright idea? @ticoann @amaltaro

**Comment by amaltaro** [comment]
Not really. Looking at the source code, we can likely isolate/improve that block of code needed for testing from the real one:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/SandboxCreator.py#L169

though it's not going to solve the test problem :)

**Comment by ericvaandering** [comment]
Ok @ticoann this is ready to merge finally.

**Pull request merged**
