### PR TITLE
Efficiently update the condor site lists

### LINKED ISSUE #7315: Jobs for site in drain not getting removed
spotted this, while trying to get jobs removed for T2_FR_IPHC

```
2016-10-20 13:06:35,544:140117853804288:INFO:ResourceControlUpdater:Changing T2_FR_IPHC state from Normal to Draining
2016-10-20 13:06:45,590:140117853804288:INFO:PyCondorPlugin:Retrieved 43451 classAds
2016-10-20 13:08:27,735:140117864294144:INFO:AgentStatusPoller:Getting agent info ...
2016-10-20 13:08:46,611:140117864294144:INFO:AgentStatusPoller:CouchDB is running with 10 processes
2016-10-20 13:08:46,611:140117864294144:INFO:AgentStatusPoller:Getting wmbs job info ...
2016-10-20 13:08:49,077:140117864294144:INFO:AgentStatusPoller:finished collecting agent/wmbs info
2016-10-20 13:12:14,664:140117853804288:ERROR:BossAirAPI:Unhandled exception while calling update method for plugin PyCondorPl
ugin
Unable to edit jobs matching constraint
2016-10-20 13:12:14,721:140117853804288:ERROR:ResourceControlUpdater:Failed to update T2_FR_IPHC state to Draining:
2016-10-20 13:12:14,722:140117853804288:ERROR:ResourceControlUpdater:BossAirException
Message: Unhandled exception while calling update method for plugin PyCondorPlugin
Unable to edit jobs matching constraint
        ModuleName : WMCore.BossAir.BossAirAPI
        MethodName : updateSiteInformation
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages
/WMCore/BossAir/BossAirAPI.py
        ClassName : None
        LineNumber : 786
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Bos
sAir/BossAirAPI.py", line 777, in updateSiteInformation
    tempjoblist = pluginInst.updateSiteInformation(jobs, siteName, excludeSite)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Bos
sAir/Plugins/PyCondorPlugin.py", line 687, in updateSiteInformation
    sd.edit('WMAgent_JobID == %i' % jobID, "DESIRED_Sites", classad.ExprTree('"%s"' % desiredSites))


2016-10-20 13:12:14,723:140117853804288:ERROR:ResourceControlUpdater:Traceback: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponen
t/AgentStatusWatcher/ResourceControlUpdater.py", line 344, in updateSiteState
    self.resourceControl.changeSiteState(siteName, state)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Res
ourceControl/ResourceControl.py", line 66, in changeSiteState
    jobtokill = bossAir.updateSiteInformation(jobInfo, siteName, state in ("Aborted","Draining","Down"))
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Bos
sAir/BossAirAPI.py", line 786, in updateSiteInformation
    raise BossAirException(msg)
BossAirException: BossAirException
Message: Unhandled exception while calling update method for plugin PyCondorPlugin
Unable to edit jobs matching constraint
        ModuleName : WMCore.BossAir.BossAirAPI
        MethodName : updateSiteInformation
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages
/WMCore/BossAir/BossAirAPI.py
        ClassName : None
        LineNumber : 786
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py", line 777, in updateSiteInformation
    tempjoblist = pluginInst.updateSiteInformation(jobs, siteName, excludeSite)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/PyCondorPlugin.py", line 687, in updateSiteInformation
```

### PR DESCRIPTION
**Pull request by amaltaro**
Making a PR before it gets lost in my remote.
Fixes #7315 . Also related to #7319

I still have to carefully test it.

### CODE REVIEW

**Comment by hufnagel** [comment]
@amaltaro , now that SimpleCondorPlugin is merged, can you rebase this branch and make the same changes in SimpleCondorPlugin. Better to have it in one pull request...

**Comment by amaltaro** [comment]
@hufnagel @bbockelm @ticoann you may want to review this patch. The PyCondor was already tested and it behaves as expected (though I didn't test it in a very loaded schedd, of course).

SimpleCondor fix must be properly validated, since it has no clue of what WMAgent_Id is, but instead all the condor interface is done with gridid.

**Comment by hufnagel** [comment]
While I tested normal agent function with SimpleCondiorPlugin, all the utility functions that are called by Ops scripts are completely untested. They should work in principle as I tried to implemented the same functionality, but all of them will need to be tested. Might as well integrate any changes you want to make there before running tests.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
I'm keeping `WMAgent_JobID` handling in the SimpleCondor plugin as well. Otherwise that requires more changes at ResourceControl and BossAir, since SimpleCondor would need the RunJob id (gridid) instead of the Job one (wmbs id).

If we make changes over there, then I suggest to refactor the whole job tracking... and I don't have a week or so to work on that.

**Comment by amaltaro** [comment]
Both PyCondor and SimpleCondor passed my tests.
Please review and merge

**Comment by hufnagel** [comment]
Why did you change back to using WMAgent JobId ? I already changed all the tracking, everywhere else it's using ClusterId and ProcId. You query for certain jobs to kill, you get an id back, you kill these jobs based on id. What does it matter which type of id it is ?

**Comment by amaltaro** [comment]
Because we need a list of wmbs ids that are returned to ResourceControl
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ResourceControl/ResourceControl.py#L76

which then is passed along to BossAir for updating the database, actually killing jobs and creating a correct error report.

**Comment by hufnagel** [comment]
Ok, yeah, that make sense. So you are using the return information outside the plugin and it currently expects WMAgent JobId. Doesn't fit into the original BossAir design nicely (as you are supposed to kill an instance of a WMAgent Job, not the whole job), but ok. Easier to leave this method using WMAgent JobId.

**Comment by amaltaro** [comment]
@ticoann please review and merge, it's all tested already

**Pull request merged**
