### PR TITLE
Fix Pset setup unit tests for Alma9 nodes

### LINKED ISSUE #12105: Add support for EL9 architecture in cmssw scram related unit tests
**Impact of the new feature**
Unit tests

**Is your feature request related to a problem? Please describe.**
When our test is created, the scram architecture is hardcoded to RHEL7. 

**Describe the solution you'd like**
Detect major OS version and make changes it accordingly  

**Describe alternatives you've considered**
Change architecture completely and break RHEL7 unit tests

**Additional context**

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #12105

#### Status
ready

#### Description
This PR detects the major OS version and make changes accordingly. While this could be made more generic, I don't think we are planning to support RHEL7 anymore, so this is temporary, in order not to break the current RHEL7 jenkins setup.

In addition to that, it uses a method to get the maxEvents input value for some setupCMSSEPset unit tests.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
[<Add cvmfs cms environment (needed for CMSSWSetupPset tests)>
](https://github.com/d-ylee/jenkins-test/pull/1)

#### External dependencies / deployment changes
Related issue:
https://github.com/dmwm/WMCore/issues/11978

### CODE REVIEW

**Comment by khurtado** [comment]
@amaltaro I followed your suggestion to detect the OS version and change the scram arch. While this could be made more generic, I don't think we are planning to support RHEL7 anymore, so this is temporary, in order not to break the current RHEL7 jenkins setup

**Comment by khurtado** [comment]
@d-ylee @amaltaro These (and the related PR in the comments) are changes that I needed in order to make CMSSWSetupPSet unit tests work on Alma9. These changes should not break the RHEL7 unit tests.

**Review by amaltaro — CHANGES_REQUESTED** [review]
Kenyi, this error in jenkins report:
```
WMCore_t.WMRuntime_t.Scripts_t.SetupCMSSWPset_t.SetupCMSSWPsetTest:testChainedProcesing (success) was deleted
```
tells me that something is broken in this test module (maybe an import). Please revisit that and/or run if with our current Docker container, if preferred.

In addition:
* please update the initial PR description accordingly to the placeholders (if there is nothing to comment, please remove the placeholder message)
* please look at the jenkins report as there are other hints in there.

**Comment by khurtado** [comment]
@amaltaro Thanks, I didn't notice the deleted tests, I just fixed this. Please, have another look.

**Review by amaltaro — APPROVED** [review]
Changes look good to me.
Before merging it though, please:
1) squash the commits
2) overwrite the PR placeholder "<YES | NO | MAYBE>" by the relevant content.

Thanks Kenyi!

**Comment by khurtado** [comment]
@amaltaro done!

**Comment by amaltaro** [comment]
Thanks Kenyi!

**Pull request merged**
