### PR TITLE
Nicely handle CouchConnectionError exception in JobAccountant - wmagent branch

### PR DESCRIPTION
**Pull request by amaltaro**
wmagent branch version of #7736

### CODE REVIEW

**Comment by amaltaro** [comment]
[Fix #7738 - Nicely handle CouchConnectionError exception in JobAccountant](https://trello.com/c/k9MnVx1J/16-fix-7738-nicely-handle-couchconnectionerror-exception-in-jobaccountant)

**Comment by amaltaro** [comment]
@ticoann can you merge this one and #7742 and then cut a new patch tag (patch4 I guess)

**Comment by ticoann** [comment]
Alan patch4 tag is created. Thanks

**Comment by amaltaro** [comment]
Thanks, you're the man!

**Pull request merged**
