### PR TITLE
update view right away

### PR DESCRIPTION
**Pull request by ticoann**
This will fix the problem not updating the page right away when request mgr link is clicked (approved, assigned)

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, Valentin, please review. You can test it reqmgr2-dev.cern.ch instance.

**Comment by vkuznet** [comment]
Seangchan, yes I tested the proposed behavior and it works fine. Please go ahead and merge. One question though. When I created my new request I didn't see pop-up showing new request name, see issue https://github.com/dmwm/WMCore/issues/5875 and PR https://github.com/dmwm/WMCore/pull/5877 I just wonder if you put this code into reqmgr2-dev or not (since PR is merged).

**Comment by ticoann** [comment]
Hmm, that should be updated as well

**Comment by ticoann** [comment]
Hi Valentin, I just check. Your codes are upto date in reqmgr2-dev

**Comment by vkuznet** [comment]
Ok, I'll check then why it is not shown.

**Pull request merged**
