### PR TITLE
PY3: support urlparse in both py2 and py3 version

### PR DESCRIPTION
**Pull request by amaltaro**
Since I stumbled upon this difference a week ago, here is a fix in order to support it for python3 as well.

### CODE REVIEW

**Comment by amaltaro** [comment]
This pylint check returns errors that I don't get in my development setup. Apparently the problem lies on the different version of pylint, I have 1.6.4 in my laptop while wmagent docker uses 1.4.4.
I'm creating a new spec for that (but apparently there are tons of dependencies).

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Yahhaaa! It's finally running the new version of pylint and it no longer complains about the py3 imports.

**Comment by amaltaro** [comment]
It's good to go now, but I'll wait for the cmsweb upgrade before it gets merged.

**Review by khurtado — COMMENTED** [review]
Looks good to me.

**Pull request merged**
