### PR TITLE
Don.t expand job classAds into a plain list; remove default values

### PR DESCRIPTION
**Pull request by amaltaro**
And I also replaced the classAd "MachineAttrGLIDEIN_CMSSite0" by "MATCH_EXP_JOBGLIDEIN_CMSSite", which is what we use in the Condor plugin and sounds more familiar to everyone.

@hufnagel was there any motivation for keeping default values for what is retrieved from condor?
@ticoann I still need to run tests on this PR

### CODE REVIEW

**Comment by hufnagel** [comment]
I have no idea what you are asking me about here ? Did I write the previous code ?

**Comment by amaltaro** [comment]
I thought you could know about it since you are the main PyCondor user (and also made a few fixes to it).
No problem, I'm patching now the testbed agent and we can see whether it will work.

**Comment by amaltaro** [comment]
I had to put back some of those default values, otherwise the job tracking was failing.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Good to be merged

**Pull request merged**
