### PR TITLE
Add an option to get back a true LumiList

### PR DESCRIPTION
**Pull request by ericvaandering**
This is something I want for my job splitting work, but it can function as a stand-alone thing. Just a wrapper around an existing function.

Sub-test added

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Review by ticoann — CHANGES_REQUESTED** [review]
Eric, could you hold on this patch for a while.
We are changing the view for ACDC.
https://github.com/dmwm/WMCore/pull/7590
This patch need to be updated after that patch is merged. Other than patch looks fine. But I am not sure why unittest is failing. 

At least one of the failing test looks legit.

WMCore_t.ACDC_t.DataCollectionService_t.DataCollectionService_t:testChunking changed from success to error

**Comment by ericvaandering** [comment]
Thanks. There was a typo. OK, yeah, let's wait then.

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, #7590 is merged now. Could you update this patch? I will create a new tag and rpm in wmagent-dev, today.

**Comment by ericvaandering** [comment]
Awesome. Yes.

**Comment by ericvaandering** [comment]
Cherry-picking onto master in another PR. Closing this one.

**Pull request closed without merging**
