### PR TITLE
Update WorkQueue Interface code for getting work by status

### PR DESCRIPTION
**Pull request by amaltaro**
Tricky returned data from ReqMgr apis. If details are set to False, then it returns a flat list.
If True, then it returns a list with a dict (plus several inner dictionaries).

BTW, I completely removed `_getRequestsByTeamsAndStatus` because it was used only by GQ and, GQ doesn't get/split work based on teams, it simply gets whatever is in "assigned" or "running-closed".

Finally, I've also removed the "Teams" check because we now validate the team data during assignment (must be a non empty string - tested it this afternoon).

@ticoann we need this patch in otherwise GQ will break nicely. Please review. 
Tests look good so far

### CODE REVIEW

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
What about: " TODO remove "aborted-completed status when state transition happens in reqmgr2"?

**Comment by amaltaro** [comment]
@ticoann Seangchan can correct me, but I think the idea is to make the aborted-completed transition from ReqMgr/WorkQueue, instead of the agent. Fixing the other simple things.

**Comment by ticoann** [comment]
Alan, yes you are right I am trying to create another patch for that - moving status transition to reqmgr. (It would take a while)

**Comment by amaltaro** [comment]
@ticoann there were 2 other places affected by the different data type. JobUpdater and ReqMgrService.

I think it's all fixed now. Please review and merge

**Comment by amaltaro** [comment]
Another unstable test failing.

**Comment by ticoann** [comment]
I will add below to unstable test
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testQueueChainingStatusUpdates

**Comment by ericvaandering** [comment]
Once they are added you can ignore if they fail. The unstable tests are not currently fetched in real time.

**Comment by ticoann** [comment]
test this please

**Review by ticoann — APPROVED** [review]

**Pull request merged**
