### PR TITLE
1.0.5 wmagent

### PR DESCRIPTION
**Pull request by ticoann**
There is the patch need to get in 1.0.5 wmagent
#5763
#5756
#5755
#5752

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, @ericvaandering, please review.
#5754 - didn't include this one since this requires both agent and reqmgr update

**Comment by amaltaro** [comment]
Patches look ok to me, though I cannot find 5774 and 5775 PRs :-)

**Comment by ticoann** [comment]
My mistake, updated the right issues. :smile:

**Comment by amaltaro** [comment]
BTW, "Loop over tasks..." has not been tested in the latest release. We can risk and add it now and run 1 or 2 tests before put it into production though...

**Comment by ticoann** [comment]
I would put it in it is not big change and code looks fine to me. I can create the tag 1.0.5.patch1 with these patches. (I deleted original 1.0.5.patch1 - Eric pointed that it was confusing).

**Comment by amaltaro** [comment]
Sounds ok. Good job guys :-P

**Comment by ericvaandering** [comment]
Loop was put in only to fix bug reported by @hufnagel.

**Comment by ticoann** [comment]
Alan, do you need a new tag with these patches? Or do you want to add some other patches?

**Comment by amaltaro** [comment]
I suggest to add in at least 2 more patches:
 1) protection against MSS auto-approval (will work on it soon)
 2) the "new" force-complete #5682 (I still need to finish a couple of tests)

**Pull request merged**
