### PR TITLE
fixes proxy info warning 1.1.2_wmagent version

### PR DESCRIPTION
**Pull request by ticoann**
#7796 wmagent branch version

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
You said it was tested, right? Including and not including the proxy_warning message?

If so, then it's good to go ;)

**Comment by ticoann** [comment]
Yes it was tested for error, warning, and ok condition.

**Comment by amaltaro** [comment]
Seangchan, I'm merging this one to add it to the patch3 tag. Thanks!

**Comment by amaltaro** [comment]
[Fix #7801 - fixes proxy info warning](https://trello.com/c/4NtIFuCu/30-fix-7801-fixes-proxy-info-warning)

**Pull request merged**
