### PR TITLE
Upload to pypi using twine

### LINKED ISSUE #9768: PyPI build scripts should use twine for upload
**Impact of the new feature**
Upload procedure for putting wmcore packages into PyPI

**Is your feature request related to a problem? Please describe.**
distutils requires a password to be stored in clear text when scripting build/upload procedure

**Describe the solution you'd like**
Switch to twine where the password can be input via stdin

**Describe alternatives you've considered**
You can use keyrings for credentials, but only on Mac/Win

**Additional context**

### PR DESCRIPTION
**Pull request by goughes**
Fixes #9768 

#### Status
Ready

#### Description
Updates PyPI build scripts to use twine for upload. Allows for getting prompted for a password instead of having to supply one in clear text in .pypirc.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by goughes** [comment]
Just uploaded a couple wmcore and wmagent packages with these changes. Was prompted for password as expected.

**Review by amaltaro — COMMENTED** [review]
I think there will be a moment that we will want to have automated packaging and upload.
Which I see two alternatives here:
1. get back to this once we get to the point of setting up automated builds
2. update this shell script to take a command line option to read the credentials from a local file (or have some sort of automatic check and fallback to prompting for the password).

What are your thoughts Erik? I'm happy either way, just wanted to raise these points before merging it.

**Comment by goughes** [comment]
I'll go ahead and a parameter to this script to support both auto (read pw from .pypirc) and manual upload (prompt for pw).

**Comment by goughes** [comment]
Turns out that if you have a password set in .pypirc this script works just fine for automated builds. If you don't have a password set, you are prompted for it. 

I just added a line to clean up old builds from the dist folder. Should be GTG after the Jenkins checks.

**Review by amaltaro — APPROVED** [review]
Thanks Erik!

**Pull request merged**
