### PR TITLE
Pycurl multi sso

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by ticoann** [comment]
Valentin, could you check the 4 unittests failure above?

**Comment by vkuznet** [comment]
@ticoann , all tests have passed, I squashed commits, everything is ready for you to merge it :)

**Comment by ticoann** [comment]
FYI. @mmascher, Marco, crab uses pycurl library, right? It seems it is a safe change but I just want to let you know.

**Comment by mmascher** [comment]
thanks, I will keep an eye on it when we will update the WMcore version

**Pull request merged**
