### PR TITLE
script to fetch and parse campaign configs from Unified MongoDB

### LINKED ISSUE #9228: Persist the campaign configurations in couch
List of actions to be taken here are:
* fetch all the current campaigns available in the Unified database (or repository?)
* insert every single of them in ReqMgrAux (one time insert for now)
* we already have REST APIs to insert/update/retrieve them, so we're all set on that respect
* create a default campaign configuration such that we can use in testbed and for our tests (whether we use it or not has to be configurable, we do NOT want to fallback to it in production)

However, before taking this issue, we better work on a campaign schema and make sure we have reasonable data stored in the Campaign collection, tracked in this issue:
https://github.com/dmwm/WMCore/issues/9139

### PR DESCRIPTION
**Pull request by amaltaro**
Partially fixes #9228 , we still have to find a way to continuously update campaign configs in CouchDB.

#### Status
ready

#### Description
Script to access the Unified MongoDB, fetch all the campaign configuration records, parse them (convert from Unified to WMCore schema) and - if needed - to inject the new campaign configuration in ReqMgr auxiliary DB.

Most of the work has been done by Valentin here: https://github.com/dmwm/WMCore/pull/9273
this PR contains a few bug fixes and allows someone to dump a final json file (in case the place we're running this script doesn't have the WMCore library).

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
Yes, continuation of #9273

#### External dependencies / deployment changes
no

### CODE REVIEW

**Comment by amaltaro** [comment]
@vkuznet please review. I've ran many tests, including the upload of documents to central couch - a total of 313 campaign configuration at this very moment - in this case against my private VM:
https://alancc7-cloud1.cern.ch/couchdb/_utils/database.html?reqmgr_auxiliary

@thongonary could you please spare a couple of minutes and carry out a spot check on the output campaign configuration, I dumped all of them here
http://amaltaro.web.cern.ch/amaltaro/forAlan/output.json

I've made many comparisons already, but just in case I missed something.

**Comment by thongonary** [comment]
Why SecondaryLocation is always blank in campaigns with premix library?

**Comment by amaltaro** [comment]
It's only empty if the secondaries dict doesn't define it (or if it's empty in there). For instance, campaign `RunIISpring16DR80` has the proper values, no?

**Comment by thongonary** [comment]
@amaltaro Most campaigns have SecondaryLocation at the top-level (like `RunIIAutumn18FSPremix`). Also `RunIISpring16DR80` is a very old campaign which was created 3 years ago -- nowadays we reserve `DR` for classical mixing (no secondary location) and `DRPremix` for premixing (with secondary location).

**Comment by amaltaro** [comment]
Good catch, @thongonary !
I was missing the `SecondaryLocation` from the top level dict, since it was not in the `remap` dict.
Fix was pushed in the 2nd commit (which will be squashed later) and a new output json was put in place.

Would you mind having another quick look? :)

**Comment by thongonary** [comment]
Looks good. I'm just wondering whether we should change `SecondaryLocation` to `PremixLocation` to reduce confusion (for the future generation 😄).

**Comment by amaltaro** [comment]
IF we can make the campaign configuration something better and much more understandable (and maintanainable), I'm all for it ;) I'm just reluctant to diverge too much from the original campaign configuration kept/used by Ops/Unified.

I know Sharad has the first attempt in a WmAgentScripts PR.

**Review by vkuznet — COMMENTED** [review]
Alan, code looks good to me, feel free to proceed.

**Comment by amaltaro** [comment]
Thanks @thongonary and @vkuznet

**Pull request merged**
