### PR TITLE
fix cache refresh

### PR DESCRIPTION
**Pull request by ticoann**
Because this bug cache som of the workflow info doesn't get to updated. tested in vm. Updating production agents.

### CODE REVIEW

**Comment by ticoann** [comment]
[Fix #8889 - wmstats cache refresh fix](https://trello.com/c/MaEl3WVe/132-fix-8889-wmstats-cache-refresh-fix)

**Comment by ticoann** [comment]
[Fix #8889 - wmstats cache refresh fix](https://trello.com/c/MaEl3WVe/132-fix-8889-wmstats-cache-refresh-fix)

**Comment by ticoann** [comment]
updated production agents. twiki, trello is updated as well

**Comment by amaltaro** [comment]
Stupid bug! I guess it means we should have this covered by unit tests :-)

**Comment by ticoann** [comment]
Yes, all my fault as well. 
The damage is not that bad. It is only for the newly pulled workflows after patch is 
 upgraded and only for updates not initial insert. Also, when the component restarts it should be updating all the docs. 
Anyway, this is temp patch. All will be gone when the cmsweb is upgraded.

**Pull request merged**
