### PR TITLE
Improve JobExtractionError message

### LINKED ISSUE #7273: Investigate the JobExtractionError error during bootstrap
Info from wmstats

```
Job Name: 24fdfab4-81c9-11e6-9565-001e67abef8c-27
    WMBS job id: 1548420
    Workflow: cerminar_Run2016B-v2-BTagCSV-23Sep2016_8020_160923_163236_9822
    Task: /cerminar_Run2016B-v2-BTagCSV-23Sep2016_8020_160923_163236_9822/DataProcessing
    Status: jobcooloff
    Input dataset: /BTagCSV/Run2016B-v2/RAW
    Site: T2_CH_CERN_HLT
    Agent: vocms0311.cern.ch
    ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
    State Transition
    Exit code: 11003
    Retry count: 0
    Errors:
        CRITICAL
            JobExtractionError (Exit Code: 11003)

                Failed to extract Job 1548420
                1548420
```

condor.out

```
...
WMAgent bootstrap : Sat Oct  1 11:27:37 UTC 2016 : WMAgent is now running the job...
Startup.py : 2016-10-01T06:27:37 : loading job definition
WMAgent bootstrap : Sat Oct  1 11:27:37 UTC 2016 : WMAgent finished the job, is copying the pickled report
WMAgent bootstrap : Sat Oct  1 11:27:37 UTC 2016 : WMAgent is finished. The job had an exit code of 1
```

and condor.err

```
Traceback (most recent call last):
  File "Startup.py", line 15, in <module>
    job = Bootstrap.loadJobDefinition()
  File "/storage/local/data1/condor/execute/dir_1529846/glide_PMCpkr/execute/dir_1735873/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 153, in loadJobDefinition
WMCore.WMRuntime.Bootstrap.BootstrapException: BootstrapException
Message: Failed to extract Job 1548420
1548420
        ModuleName : WMCore.WMRuntime.Bootstrap
        MethodName : loadJobDefinition
        ClassInstance : None
        FileName : /storage/local/data1/condor/execute/dir_1529846/glide_PMCpkr/execute/dir_1735873/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py
        ClassName : None
        LineNumber : 153
        ErrorNr : 0

Traceback:
  File "/storage/local/data1/condor/execute/dir_1529846/glide_PMCpkr/execute/dir_1735873/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 148, in loadJobDefinition
    job = package[index]


cp: cannot stat `WMTaskSpace/Report*.pkl': No such file or directory
ls: cannot access WMTaskSpace: No such file or directory
ls: cannot access WMTaskSpace/*: No such file or directory
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7273

Not really a fix, but will improve the error message and should be useful for debugging this issue further.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Review by ericvaandering — CHANGES_REQUESTED** [review]
I know you can fix the bolded pylint problems and I bet a quick "reformat code" in PyCharm will fix most of the rest of the pylint comments

**Review by ericvaandering — APPROVED** [review]

**Comment by amaltaro** [comment]
@ticoann please review and merge

**Pull request merged**
