### PR TITLE
Make LumiList understand the WMAgent format

### PR DESCRIPTION
**Pull request by ericvaandering**
Totally untested at the moment.

### CODE REVIEW

**Comment by ericvaandering** [comment]
@amaltaro please review. If you don't agree with the format, make a PR against the unit test and I will update the code to make it pass. Otherwise sign off and @ticoann can merge

**Comment by ericvaandering** [comment]
@amaltaro please review.

**Comment by amaltaro** [comment]
Thanks Eric! This patch looks good. I also ran a couple of tests for this implementation.

On a side note, I understand izip saves some memory and it's a preparation for py3, right? Should I make an issue for us to update zip to izip in all wmcore code?

**Comment by ericvaandering** [comment]
Unless I'm mistaken zip in python3 does what itertools.izip does in python2. You can make an issue, no problem. 

The python 3 conversion stuff will convert zip() to list(zip() )

**Pull request merged**
