### PR TITLE
Backport remove multicore enabled flag everywhere

### PR DESCRIPTION
**Pull request by amaltaro**
Backporting #5655 applied to master.
Applying it to testbed agents in order to run the HG1504 tests.

### CODE REVIEW

**Comment by amaltaro** [comment]
Also backporting #5650 and #5652. Hopefully that will be all :)

**Comment by ticoann** [comment]
I think we need to be careful to apply this to production agent since it will only be affected on newly created request after production cmsweb is deployed. I am not sure this patch is backward compatible.

**Comment by amaltaro** [comment]
That's true! I'll also run a couple workflows that were created before HG1504 release.

**Comment by amaltaro** [comment]
I managed to run workflows from HG1503 (and HG1502) validation with this patch. So we should be fine.

**Pull request merged**
