### PR TITLE
'filter' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
Wraps filter() usage in a list call.
Second commit applied to "test" only and first applied to the rest files

### CODE REVIEW

**Comment by vilnius-dev** [comment]
@vkuznet

**Comment by amaltaro** [comment]
Is it because filter and map return a generator in py3?

**Comment by ericvaandering** [comment]
Filter and lambda functions in general are falling out of favor as well. But yeah, I bet filter itself is changing. @vilnius-dev are you also documenting these changes with an explanation in a Twiki?

**Comment by vilnius-dev** [comment]
Usually I document all changes on Friday.

**Comment by ericvaandering** [comment]
@ticoann this is a good candidate for testing and integration early in the process.

**Comment by vkuznet** [comment]
@vilnius-dev , where are the documented changes on (T)wiki. I don't see them. Please make them available asap.

**Comment by ericvaandering** [comment]
@ticoann this is good to go as far as I'm concerned. I guess I need to add this fixer to the python 3 checker now.

**Comment by ticoann** [comment]
That is good idea. :-) Thanks.

**Pull request merged**
