### PR TITLE
Set numberOfCores for all tasks in a ReDigi

### LINKED ISSUE #7393: multicore workflows with singlecore steps
In this useful page https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752 that we have to keep around for this exact purpose (PLEASE DO NOT DEPRECATE AND REMOVE IT).
One can see
pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752.tasks.StepOneProc.steps.cmsRun1.application.multicore.numberOfCores = 4
pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752.tasks.StepOneProc.steps.cmsRun1.tree.children.cmsRun2.application.multicore.numberOfCores = 1
which means there is a problem somewhere.
thx @bbockelm for noticing.

I have not looked for an equivalent workflow in reqmgr (this one above is reqmgr2) to check whether the issue is "new"

### LINKED ISSUE #7394: StepNTimePerEvent in the schema
looking at injection tools @anorkus, it does not look like 

pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597.request.schema.StepTwoTimePerEvent = 1.0

pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597.request.schema.StepThreeTimePerEvent = 1.0

 were actually not injected as such. Please confirm.

Furthermore @amaltaro @ticoann they are not considered at all in splitting it seems, given, I assume, the presence of 

pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597.request.schema.TimePerEvent = 35.0

This is somehow related to https://github.com/cms-PdmV/cmsPdmV/issues/789 @bbockelm

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7393
Fixes #7394

Summary of this PR:
* minor change on how we handle multicore at spec level
* fixed multicore settings for ReDigi spec (cmsRun2 was never set)
* fixed multicore settings for StepChain (was set only for cmsRun1)
* fixed *TimePerEvent default values in ReDigi

I tested different settings of StepChain, TaskChain and ReDigi and they work Ok. I still have to run further tests and make some unit tests for all these specs.

### CODE REVIEW

**Comment by amaltaro** [comment]
@ticoann you may want to review it. I guess I'm not changing the code anymore, just TaskChain tests...

**Comment by amaltaro** [comment]
And there was a specific use case that would cause problems in TaskChain as well. Now I don't know whether or those issues were legit or whether they shown up once I started working on it :-)

If jenkins are happy, this will be my last commit. I still want to create unit tests for the other specs, but that can be done along the week...

**Comment by ticoann** [comment]
Hi Alan, this need to be in tomorrow testbed deployment, right? This patch will have conflict with #7400.  I can update this one first and modify the other #7400 when this is ready to be merged.

**Comment by amaltaro** [comment]
That's right, Seangchan. Yes, I think merging this one first and then rebasing 7400 is going to be less troublesome :)

**Comment by amaltaro** [comment]
Ok, it's in your hands now Seangchan :). @ticoann please review and merge

**Comment by ticoann** [comment]
Thanks Alan

**Comment by hufnagel** [comment]
Sorry, only now had a chance to review this. These changes break PromptReco.

Basically, these changes force all processing tasks in a spec to use the same multicore settings, which is wrong. You can have the top-level task be multicore and following processing tasks be single core, nothing wrong with that. It's up for the spec in question to define this. I'll review and make a pull request to fix it.

**Comment by amaltaro** [comment]
I've just talked to Dirk and since I still have the unit tests to write, I'm going to fix this PR problem as well. Dirk pointed out this task basically:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/PromptReco.py#L85

**Pull request merged**
