### PR TITLE
Don't validate Resubmission specs

### LINKED ISSUE #7835: Resubmission crashes on "old" requests with unknown key args
As resubmission is handled now, it will break when the original request has arguments that it "should not", because we simply copy those over to the new request:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/Request.py#L74

issue reported here:
https://github.com/CMSCompOps/WmAgentScripts/issues/222

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7835 (if you allow me to call it a fix :))

@ticoann this is the fix I suggest to be pushed into cmsweb as a critical patch release.
Then we can properly implement and test Resubmission creation/validation for the next cycle.
What do you think? If you agree, we can ask the HTTP team to push it to testbed even today and to production tomorrow morning.

### CODE REVIEW

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
I will create the branch patch and new tag then

**Comment by amaltaro** [comment]
Thanks, Seangchan! I should've listened to you when you said "why don't we skip the resubmission validation?!?" :-)
BTW, Jenkins may fail since Eric is pushing a new container in.

**Comment by ticoann** [comment]
Did I say that? 😄  I think maybe we should treat resubmission same way as clone for validation.

**Comment by ericvaandering** [comment]
So little faith!

**Pull request merged**
