### PR TITLE
campaign length - increase to 80

### LINKED ISSUE #7830: set campaign str length limit to 80 for validation

### PR DESCRIPTION
**Pull request by ticoann**
fixes #7830  @amaltaro, hope this is not to complicated to review. :smile:

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
Thanks, Seangchan!

**Comment by ticoann** [comment]
Wow, a lot of unittest failure.

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
you need to fix one or two Lexicon unittests :-)

**Comment by ticoann** [comment]
Yes but didn't expect all other test to fail. 😄

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Pull request merged**
