### PR TITLE
'map' fix applied 

### PR DESCRIPTION
**Pull request by vilnius-dev**
Wraps `map()` in a list call. It also changes `map(None, x)` to `list(x)`.
Using from `future_builtins import map` disables this fixer.
Fix applied because `map()` don’t return lists anymore in Python 3.

### CODE REVIEW

**Comment by vkuznet** [comment]
@ticoann , we should look at if this PR will have some performance issues due to change of data-type for map. Could you please test results here.

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
On python 2 this shouldn't matter as map already produces a list. On python 3, we should get the same behavior as python 2 which might not be optimal (using iterators is nicer) but shouldn't be any worse.

**Comment by mapellidario** [comment]
This is covered by our gradual migration. However, we follow the performance suggestions at https://python-future.org/compatible_idioms.html#map, which suggests

```python
from builtins import map  # in py2 "map = itertools.imap" , so that py2 and py3 behave the same
mynewlist = list(map(f, myoldlist))
assert mynewlist == [f(x) for x in myoldlist]
```

instead of

```python
# Python 2 and 3: option 1
# Idiomatic Py3, but inefficient on Py2
mynewlist = list(map(f, myoldlist))
assert mynewlist == [f(x) for x in myoldlist]
```

I would suggest closing this PR without merging, since it is superseded by our current efforts.

**Comment by mapellidario** [comment]
Thanks Roman for your work! Closing this

**Pull request closed without merging**
