### PR TITLE
Update the DBS emulator and DBSReader

### PR DESCRIPTION
**Pull request by ericvaandering**
This is the PR that should run correctly

Update DBS to promote strings to unicode in some places to minimize the data we need for the mocked Emulator
Handle the special case where we ask DBS about a list of LFNs by constructing the list out of individual bits of cached data
Add more data to make WorkQueue tests happy

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann please merge. Failures are pylint trying to check JSON and missing imports in __init__.py

**Comment by ticoann** [comment]
I don't think unicode change will affect anything but since there is change in DBS3Reader I will run the quick test before merging it.

**Comment by ericvaandering** [comment]
+1 @ticoann

**Comment by ticoann** [comment]
tested in vm for cmsweb applicaiton (GQ). Agent need to be tested (will do after merge and create rpm)

**Pull request merged**
