### PR TITLE
temp fix for authentication (need to make it configurable).

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by amaltaro** [comment]
Seangchan, there is no FacOps role. The correct thing is
group: "facops"
role: "web-service"
See it here to be on the safe side :-)
https://github.com/dmwm/WMCore/blob/master/src/couchapps/ReqMgr/validate_doc_update.js#L42

**Comment by ticoann** [comment]
Actually this is current reqmgr config sets.
https://github.com/dmwm/deployment/blob/master/reqmgr/ReqMgrConfig.py#L44
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/HTTPFrontEnd/RequestManager/ReqMgrConfiguration.py#L78

I will double check and put it everywhere. :-)

**Comment by ticoann** [comment]
Alan, you are right I clean up the roles and groups and updated the patch.
Basically only reqmgr/admin and web-service/facops can modify any field without updating status. All other roles has to update the status go modify something.

**Comment by amaltaro** [comment]
Thanks Seangchan! These permissions are still a bit confusing in my opinion, but we can improve it in the next cmsweb cycle maybe :)

**Comment by ticoann** [comment]
Yes, I agree. This need to be redone.

**Pull request merged**
