### PR TITLE
Strip trailing whitespace

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by ticoann** [comment]
Oh my! :smile:

**Comment by ericvaandering** [comment]
Hasn't been done in a while.

**Comment by amaltaro** [comment]
Are you also fixing these warning and errors
803 warnings and errors that must be fixed 
?
:-)

**Comment by ericvaandering** [comment]
Yup, every single one of them. And the 7K comments.

**Comment by ticoann** [comment]
@ericvaandering, Sorry Eric I cause the conflict on this patch by merging another patch. I still have to merge a couple of patches first. Could you create new patch in the beginning of next week?

**Comment by ticoann** [comment]
test this please

**Pull request merged**
