### PR TITLE
Fix StageOut at CERN

### PR DESCRIPTION
**Pull request by lucacopa**

### CODE REVIEW

**Comment by ticoann** [comment]
Luis, it it tested? can this be merged?

**Comment by lucacopa** [comment]
I am testing it

**Comment by amaltaro** [comment]
Applying it to testbed agents since I also saw failures today... :-(

**Comment by hufnagel** [comment]
Please be aware that this will only fix newly created workflows. Workflows that already exist will need a manual patching of their workflow sandbox file on disk.

**Comment by lucacopa** [comment]
@ticoann it is working.

**Comment by ticoann** [comment]
Thanks, I will merge it, Alan, should we need to patch the production agent?

**Comment by amaltaro** [comment]
Yes, I just wanted to run a test workflow before in testbed. You know... :P

**Comment by ticoann** [comment]
Just for the book keeping sake. #5744

**Comment by amaltaro** [comment]
Feel free to merge this one

**Pull request merged**
