### PR TITLE
Don't share the same DBS object amongst multiple threads

### LINKED ISSUE #9221: Error: cannot invoke setopt() - perform() is currently running
Given that it has been happening much more often in the last months, I think it's time to tackle this issue.
The problem seems to be in the dbs-client, which affects both global and local workqueue (WorkQueueManager).

I haven't looked into how to reproduce it - I believe it's even not reproducible - and it happens in a random way. @vkuznet since you conceived the pycurl module, perhaps you have an idea of what this problem might be?

Here is a traceback [1] extracted from the global workqueue.

[1]
```
2019-05-25 00:09:38,042:INFO:LogDB:<LogDB(url=https://cmsweb-testbed.cern.ch/couchdb/wmstats_logdb, identifier=global_workqueue, agent=1)>
2019-05-25 00:09:39,080:ERROR:CherryPyPeriodicTask:Periodic Thread ERROR pycurl.error cannot invoke setopt() - perform() is currently running
2019-05-25 00:09:45,129:ERROR:CherryPyPeriodicTask: Traceback (most recent call last):
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/workqueue/1.2.3.pre4/lib/python2.7/site-packages/WMCore/REST/CherryPyPeriodicTask.py", line 91, in run
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:     self.taskFunc(self.config)
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/workqueue/1.2.3.pre4/lib/python2.7/site-packages/WMCore/GlobalWorkQueue/CherryPyThreads/LocationUpdateTask.py", line 24, in updateDataLocation
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:     globalQ.updateLocationInfo()
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/workqueue/1.2.3.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 720, in updateLocationInfo
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:     result = self.dataLocationMapper()
2019-05-25 00:09:45,157:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/workqueue/1.2.3.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/DataLocationMapper.py", line 198, in __call__
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:     dataLocations, fullResync = DataLocationMapper.__call__(self, dataItems, fullResync)
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/workqueue/1.2.3.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/DataLocationMapper.py", line 100, in __call__
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:     if isGlobalDBS(dbs):
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/workqueue/1.2.3.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/DataLocationMapper.py", line 38, in isGlobalDBS
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:     dbs.dbs.serverinfo()
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/dbs3-client/3.7.8-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 1532, in serverinfo
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:     return self.__callServer("serverinfo")
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/dbs3-client/3.7.8-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 197, in __callServer
2019-05-25 00:09:45,158:ERROR:CherryPyPeriodicTask:     self.http_response = method_func(self.url, method, params, data, request_headers)
2019-05-25 00:09:45,159:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.7.8-comp/lib/python2.7/site-packages/RestClient/RestApi.py", line 34, in get
2019-05-25 00:09:45,159:ERROR:CherryPyPeriodicTask:     return http_request(self._curl)
2019-05-25 00:09:45,159:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1906b/sw/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.7.8-comp/lib/python2.7/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 51, in __call__
2019-05-25 00:09:45,159:ERROR:CherryPyPeriodicTask:     curl_object.setopt(key, value)
2019-05-25 00:09:45,159:ERROR:CherryPyPeriodicTask: error: cannot invoke setopt() - perform() is currently running
```

### LINKED ISSUE #9253: Fix how we evaluate whether DBS is global or not
While looking at this code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataLocationMapper.py#L24

which makes a couple of calls to figure out whether our DBS instance is talking to the `global` DBSServer instance or not, I noticed it calls `getServerInfo`, which does NOT exist either in the DBSReader nor in DbsApi.

The DBSReader instance has this attribute:
```
>>> d.dbsURL
'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/'
```

while the DbsApi has
```
>>> dbs.url
'https://cmsweb-testbed.cern.ch:8443/dbs/int/global/DBSReader/'
```

thus it's one less http request made to the DBSServer.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9221 
Fixes #9253

#### Status
not-tested

#### Description
Instead of using a global cache of DBSReader, which are then shared between multiple threads, make sure each thread constructs its own DBSReader object (and then reuse it within the thread).

This PR also fixes how we evaluate whether the DBSReader object is pointing to the global instance or not (no need to make any calls to the server).

I wanted to get rid of this __dbses global variable:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueUtils.py#L30

but it would require substantial changes to the start policy algorithms. Given that only those are now using this global var, and they are sequential, I decided to let them be.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
no

#### External dependencies / deployment changes
Needs to be validated on both levels: global and local workqueue.

### CODE REVIEW

**Comment by vlimant** [comment]
does this mean that the dbsapi is not really thread safe @yuyiguo @vkuznet ?

**Comment by amaltaro** [comment]
Yes, Jean-Roch. See this comment
https://github.com/dmwm/DBS/pull/610#issuecomment-503639476
where Valentin describes the problem.

I let them comment it further though.
Don't you see DBS problems on the Unified side? Or it catches an exception and silently retry?

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Tests look good in my VM as well. I double checked the jenkins job configuration and I still don't get why those Rucio tests don't get reported as unstable...

**Pull request merged**
