### PR TITLE
remove alert unittest in job/task archiver

### LINKED ISSUE #6235: JobArchiver/TaskArchiver unit tests broken
@ticoann these two sets of unit tests are broken by the removal of the alert unit tests with errors like

    from WMComponent_t.AlertGenerator_t.Pollers_t import utils
ImportError: No module named AlertGenerator_t.Pollers_t

I suspect the fixes are trivial

### PR DESCRIPTION
**Pull request by ticoann**
fixes #6235

### CODE REVIEW

**Comment by ericvaandering** [comment]
Can you check up on the failed tests (I don't know if they were failing before) and also check up on the pylint stuff?

**Comment by ticoann** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ticoann** [comment]
retest this please

**Comment by ticoann** [comment]
retest this please

**Comment by ticoann** [comment]
failing test should be fixed by reqmgr2 code update

**Comment by ericvaandering** [comment]
Can you go back to the previous PR that caused these tests to drop out and see what the status of WMComponent_t.TaskArchiver_t.TaskArchiver_t.TaskArchiverTest:testA_BasicFunctionTest and 
WMComponent_t.TaskArchiver_t.TaskArchiver_t.TaskArchiverTest:testB_testErrors were

**Comment by ticoann** [comment]
The errors were due to the missing configuation. 'reqmgr2Only' but master shouldn't use this configuration any more. Is this patch running over the master base?

**Comment by ticoann** [comment]
retest this please

**Comment by ericvaandering** [comment]
Yup, it runs on master with this PR merged onto it. As long as it merges, it does not matter what your branch point for the PR is.

**Comment by ticoann** [comment]
Hmm now I see some couch connection error for following which works in local test.

> WMComponent_t.TaskArchiver_t.TaskArchiver_t.TaskArchiverTest:testA_BasicFunctionTest was added. Status is failure
> WMComponent_t.TaskArchiver_t.TaskArchiver_t.TaskArchiverTest:testB_testErrors was added. Status is error

**Comment by ticoann** [comment]
retest this please

**Comment by ticoann** [comment]
merging it, The 2 error is caused by some other reason. Will fix it separately

**Pull request merged**
