### PR TITLE
Remove legacy site black/white list parser

### PR DESCRIPTION
**Pull request by amaltaro**
One of these unit tests failed in my other PR. Having a quick look at it, it isn't used in WMCore/CRABServer/Unified, so I think it's safe to delete it.

### CODE REVIEW

**Comment by amaltaro** [comment]
Just in case, @hufnagel @mmascher @ericvaandering you might know of another usage of those...

**Comment by ericvaandering** [comment]
I also seem to have recall finding that this was not used.

**Comment by hufnagel** [comment]
Never seen this, AFAIK we don't use it in the Tier0.

**Comment by amaltaro** [comment]
Then I think we can merge it, @ticoann :)

**Review by ticoann — APPROVED** [review]

**Pull request merged**
