### PR TITLE
See if we can get these to be reliable now

### PR DESCRIPTION
**Pull request by ericvaandering**
Do not merge this, I just want to see if these tests (or some of them) have become more reliable.

### CODE REVIEW

**Comment by amaltaro** [comment]
retest this please

**Comment by amaltaro** [comment]
retest this please

**Comment by amaltaro** [comment]
It seems this testArchive was the only test that had different results from the last 3 runs.
@ericvaandering have fun :)

**Comment by ericvaandering** [comment]
Thanks for starting new tests of these. Was my plan…

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Aug 25, 2015, at 04:06, Alan Malta Rodrigues <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems this testArchive was the only test that had different results from the last 3 runs.
@ericvaandering<https://github.com/ericvaandering> have fun :)

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
Retest this please

**Comment by ericvaandering** [comment]
Ok @ticoann this set of tests is completely stable now. Please merge. And having fixed 14 tests, I will now go on vacation for 3 months. :-)

**Comment by amaltaro** [comment]
Good to know, re-prioritizing my issues right now :-P

**Comment by ticoann** [comment]
Thanks Eric, no vacation until we have 0 unittest failure. :smile:

**Comment by ticoann** [comment]
retest this please

**Comment by ericvaandering** [comment]
Jenkins is never going to say this succeeds because of the pylint stuff. And I've cleaned it up as much as I feel comfortable.

**Comment by ericvaandering** [comment]
CMSWeb alarms were complaining about DBS, so I assume that's the source of unit test issues #2 and #3.

**Pull request merged**
