### PR TITLE
Fix unittest deployment for the new pkgtools

### PR DESCRIPTION
**Pull request by BrunoCoimbra**
This PR fixes deploy_unittest.sh to work with the new structure of cmsrep.
The problem is reported on issue #7261.

### CODE REVIEW

**Comment by amaltaro** [comment]
Looks good to me. I think @ericvaandering won't manage to test it in Jenkins these days because we have CHEP starting on Monday.

**Comment by ericvaandering** [comment]
Trying in a docker container: so far so good:

INFO: bootstrapping comp software area in /home/dmwm/unittestdeploy/wmagent/1.0.21.pre6/sw

**Comment by BrunoCoimbra** [comment]
Please don't merge it yet.
Shahzad just provided us a new script that will make this script much simpler:

http://cmsrep.cern.ch/cgi-bin/repos-dev/comp/slc6_amd64_gcc493?C=M;O=D

**Comment by BrunoCoimbra** [comment]
Changes done. Now it's ready to go.

**Comment by ericvaandering** [comment]
Now I'm getting 1.0.10pre6....

**Comment by ericvaandering** [comment]
Actually 

```INFO: bootstrapping comp software area in /home/dmwm/unittestdeploy/wmagent/1.0.21.pre6/sw```

even though 1.0.21 is out.

**Comment by amaltaro** [comment]
There is 1.0.21 tag, but not the RPM yet. We may create a new RPM later tomorrow (1.0.21.patch1), in case you want to x-check it.

**Comment by ericvaandering** [comment]
Ah. Let me know when its out. The script should know that patch is later than pre even if not alphabetically. And that "neither" is in the middle.

**Comment by amaltaro** [comment]
@ericvaandering wmagent-dev 1.0.21.patch1 is out since this morning.

**Comment by ericvaandering** [comment]
Looks like it is working. :-)

**Comment by ericvaandering** [comment]
@ticoann seems we should merge this.

**Pull request merged**
