### PR TITLE
Add templates for Integration tests

### PR DESCRIPTION
**Pull request by amaltaro**
Ok, I did a big clean up and fixed some old templates. Changes are basically:
 a) DMWM: requests under this directory are supposed to run quickly (a couple of hours)
 b) Integration: requests under this directory are supposed to exercised LOTS of WMAgent/ReqMgr/WorkQueue/WMStats features. These - along the DMWM ones - will be used to run full validation of services.

### CODE REVIEW

**Comment by ericvaandering** [comment]
What is the reason for having tests in the top directory and other tests in the DMWM or Integration sub-directories?

**Comment by ticoann** [comment]
I think top directory samples need to be removed. We will just keep DMWM (simpler test) and Integration (more complete test)

**Comment by amaltaro** [comment]
That's what I did :-) I either removed all templates from the top directory or moved them to either DMWM or Integration. Unless there is some leftover, but I just x-checked and could not find any.
BTW, I just notice ReDigi_cmsRun3 does not create jobs for step2 and 3 ...

**Comment by amaltaro** [comment]
Just fixed ReDigi_cmsRun3.json template. Feel free to merge it now. Thanks

**Pull request merged**
