### PR TITLE
remove JobCreatorWorker, Sam and Registration Served unused code

### LINKED ISSUE #8610: Is there anyone using Registration?
This module
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Registration/Registration.py
seems not to be used within WMCore. If external services are not using it either, then let's delete it.

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan please review
fixes #8610, #8609 as well

### CODE REVIEW

**Comment by amaltaro** [comment]
Haaa, its code is very similar to the JobCreatorPoller. How come we kept this unused code around for so long?!? :)
Seangchan, can you update this comment as well then
https://github.com/dmwm/WMCore/blob/c4fe8efccc70a3a182a87b878db72951d077ad2f/src/python/WMComponent/JobCreator/CreateWorkArea.py#L52
Thanks

**Review by amaltaro — APPROVED** [review]

**Comment by amaltaro** [comment]
These tests can be deleted
https://github.com/dmwm/WMCore/tree/master/test/python/WMCore_t/Services_t/Registration_t

**Comment by amaltaro** [comment]
Thank you, Seangchan.

**Comment by ticoann** [comment]
test this please

**Pull request merged**
