### PR TITLE
Apply glideIn restrictions to resource estimation - 1.0.9

### PR DESCRIPTION
**Pull request by amaltaro**
Pull replacing #6200 . Good to be merged

### CODE REVIEW

**Comment by amaltaro** [comment]
Seangchan, I don't know whether we create a new patch2 tag once we get this merged or we move the patch1 to this PR (I believe the latter is not really advised to do..)

**Comment by ticoann** [comment]
retest this please

**Comment by ticoann** [comment]
Hi Alan, yes I will create a new tag. 1.0.9.patch2. No reason to patch over 1.0.9.patch1 since agent is not deployed yet

**Comment by ticoann** [comment]
Made the mistake firing retest. (Didn't realize this is for branch)

**Comment by ericvaandering** [comment]
Jenkins should be OK with PRs to branches now.

**Comment by amaltaro** [comment]
retest this please

**Comment by amaltaro** [comment]
retest this please

**Comment by amaltaro** [comment]
Just reduced the maxWallTime cap to 45h, otherwise we are in trouble.
@ticoann please merge this one ASAP. I'd like to push this new version to all the production agents today before I vanish for a week.

**Pull request merged**
