### PR TITLE
remove unused PhEDEx call

### PR DESCRIPTION
**Pull request by ticoann**
Removed unused phedex api. (Checked in WMCore and Unified)

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, @vlimant, Alan, Jean-Roch please review.

**Comment by ticoann** [comment]
@belforte, Hi Stefano, could  you check this patch whether this will affect CRAB?

**Comment by amaltaro** [comment]
If you say it's not used in WMCore, then I believe you :)
Did you check whether T0 uses any of those? FYI @hufnagel

**Comment by ticoann** [comment]
test this please

**Pull request merged**
