### PR TITLE
Initial Rucio Service class with basic functionality

### LINKED ISSUE #8796: Create a Service class for Rucio with data discovery APIs
https://github.com/dmwm/WMCore/wiki/PhEDEx-to-Rucio-Transition

Related to: https://its.cern.ch/jira/browse/CMSRUCIO-97
and
https://its.cern.ch/jira/browse/CMSRUCIO-37

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8796 

Summary of changes are:
* added some basic methods just to test communication between client and server
* added API to list blocks present in a Rucio container
* added API to retrieve block replicas (still need a fine tuning)

The last 2 APIs were basically copied from an example pointed out by Eric, here:
https://github.com/dmwm/CMSRucio/blob/3793a0b3f8ed1c0541427060fda81e5cd84d6c47/docker/CMSRucioClient/scripts/CMSRucio.py#L128

I'm still figuring out how to test it; a) which datasets are available in Rucio db; b) getting rucio-clients in the unit tests docker image; and c) finally compare output against PhEDEx

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Two issues in this PR that I still can't make sense of:
* some Rucio unit test work while others failed to authenticate. How come if they all use the same image and setup!?!
* using the WMAgent docker image, I can import rucio.client from the Rucio_t module, but then it fails to import rucio.client from the import line in the Rucio module being tested(!?)

investigating...

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
and this is why the Rucio unit tests are failing, RUCIO_HOME
`/build/cmsbld/jenkins/workspace/DMWM-PR-unittests/SLICE/8/label/cms-dmwm-cc7/deploy/1.2.1.pre2-comp/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.19.3/lib/python2.7/site-packages`
 points to the wrong configuration file.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please
(and let the magic happen)

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
And finally it works. I had to add this line under the jenkins DMWM-PR-unittests task:
`export RUCIO_HOME=$WORKSPACE/deploy/current/config/rucio/`
otherwise it was using the default rucio.cfg with the unavailable X509 env vars.

Eventually I have to push something in in the `cms-sw/cms-bot` repo and remove those lines from the jenkins setup.

The replica tests are still failing though, and I don't think there is anything I can do at the moment. Those blocks (and all the others I looked against a french site) are returning state:UNAVAILABLE.

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Tests seem to be all succeeding, but from time to time we get a "read time out" error from the server.
@ericvaandering if you can spare a few minutes, it would be great if you could have a quick look at this PR just to make sure I'm not missing anything about the block replicas logic.

**Comment by ericvaandering** [comment]
Looks good. We're getting timeouts too. Not sure what's going on, Natalia is looking at the database.

For getPFN we need to do something. It's a known hole for CRAB. I think I know what to do, but good job stubbing it out and making a test for it.

**Comment by amaltaro** [comment]
Thanks, Eric! It's way past the time to get it merged now ;)

**Pull request merged**
