### PR TITLE
refactor getKeyCert method

### PR DESCRIPTION
**Pull request by ticoann**
move getKeyCert method from Request class. So it can be used in other code.

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, @amaltaro please review.
@ericvaandering, is it OK to put in Utils package?

**Comment by ericvaandering** [comment]
How about Services? 

I intended Utils as things that are useful for just about any python project to deal with things like lists, etc. Certificates are something a bit less broadly useful. 

In the end I don't have a very strong opinion though.

**Comment by vkuznet** [comment]
changes looks fine to me, and, I would probably move them from request module to utils. They may be used in Services and others modules but they are generic functions.

**Comment by ticoann** [comment]
I cleaned up code a little more. So Eric prefers under Service, but Valentin prefers under Utils, right? 😄 , I guess it is Alan's call. 😄  @amaltaro

**Comment by amaltaro** [comment]
I think it could go under Utils/Utilities.py
OR... we create it just under Services, like the UUID function.

**Comment by ticoann** [comment]
Alan, you are not helping. :-)

**Comment by amaltaro** [comment]
LoL. It's a hard pick, but seems to fit better under Utils, since it's generic enough and has not a single bit of WMCore code. Anyways, depending on Eric's offer, I can easily change my mind :P

Seangchan, I think we can rename the module as well (and get rid of that typo), how about CertTools or something like that?

**Comment by ticoann** [comment]
CertTools is better. I was thinking that this module can be expanded if you have some common CMS related environment value handling but that might be not so common. Anyway, updated the module name to CertTools

**Comment by ericvaandering** [comment]
Why do we have Utils/Utilities? As an uninformed person, what am I going to expect to find there?

**Comment by ericvaandering** [comment]
Yes, I realize I am not helping either. :-)

**Comment by vkuznet** [comment]
I treat Utils as a set of helpers. These helpers should be generic and free
from dependencies, therefore it will allow to use them anywhere in a codebase.
Based on this definition
```
def bla():
    return 1
```
is a helper function. You may certain structure within Utils to better address
the use cases. That's why my vote for Utils, would it be Utilities or Singleton
is a separate topic for discussion.

The Services on a contrary provides set of actions to codebase, they already
depend on independent utilities and represent more sophisticated set of tools
dedicated to an action.

Hope this helps.

**Comment by ticoann** [comment]
> Why do we have Utils/Utilities? As an uninformed person, what am I going to expect to find there?

Yes, you are not helping. 😄  I agree we that we can use more specific module name there but that might require more changes  outside of WMCore

**Comment by ticoann** [comment]
Valentin, that is valid point. I was just wondering whether certificate is only used for making a "Request" and nowhere else and whether the code itself is too specific (i.e. searching order of the certificates) to be used broadly outside Service package. Anyway, I will leave that in Utils then. Thanks.

**Comment by ericvaandering** [comment]
@vkuznet I agree with you, but that's not my point. Everything in Utils is already a Utility. But lets not just throw everything in to an already poorly named file called "Utilities.py". So far Utilities.py contains a bunch of functions for generating lists, converting strings, benchmarking, counting processes, and doing a "df". What do they have in common? Nothing. Let's stop this madness now.

If certificate stuff is going to go here, make a file called "certificates". Singleton should go in Singleton.py or Patterns.py if we think there will be more.

**Comment by vkuznet** [comment]
Good, we have a consensus. I agree with Certificates.py (since it may include
other cert related stuff or sign-ons) and Patterns.py to which Singleton and
others belongs.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, Eric, could you check whether Jenkins has some problem when you get a chance?

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Pull request merged**
