### PR TITLE
Remove deprecated workqueue argument: NoLocationUpdate

### PR DESCRIPTION
**Pull request by amaltaro**
This argument was replaced more than 6 months ago by `NoInputUpdate` and `NoPileupUpdate`.
Thus I'm removing this code.

I've also updated the json file with workqueue elements that had only the deprecated arg. Both args were added and kept the same default value (False).

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ericvaandering** [comment]
Why is the updated Jason file 60k lines longer?

**Comment by amaltaro** [comment]
Because I pretty dumped it, in case someone needed to look at one "document" structure. Maybe it's not a good idea and I should just dump without indent (single line)?

**Comment by ericvaandering** [comment]
It's fine. One thing I'd suggest is using options like

```json.dump(lookup, mockData, indent=1, separators=(',', ': '), sort_keys=True)```

which will keep the size a bit smaller and keep things sorted. Then future diffs won't be as large

**Comment by amaltaro** [comment]
Json file updated as you suggested.

**Review by ericvaandering — APPROVED** [review]

**Comment by amaltaro** [comment]
@ticoann good to be merged

**Review by ticoann — APPROVED** [review]

**Pull request merged**
