### PR TITLE
Fix Trust flags for Resubmission requests

### LINKED ISSUE #7138: TrusPUSiteList=True not functionning in ACDC assignment
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_ACDC_EXO-RunIISpring16DR80-03702_00622_v0__160901_084155_3027

 was assigned with TrustPUSitelist=True and yet the WQE has "NoPileupUpdate":false and does not want to move on to acquired because of the PU location.

 no DR80 ACDC is getting to run now because of this.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7138 
Still need to be tested.

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Test sounds good. I'll merge it and cut a new tag for Bruno

**Comment by vlimant** [comment]
does this allow to change the parameter for the ACDC, or does it pick it up from the original workflow regardless of the assignment value ?

**Comment by amaltaro** [comment]
You provide it for the acdc workflow itself.

**Comment by vlimant** [comment]
Can you please confirm this is now in production ? @prozober we can then do ACDC for DR80.

**Comment by ticoann** [comment]
Yes, this is in production cmsweb.

**Comment by prozober** [comment]
I made a couple of ACDCs for EXO-RunIISpring16DR80-03708. The trustPUlists parameter was correctly assigned https://cmsweb.cern.ch/reqmgr/view/showWorkload?requestName=prozober_ACDC_EXO-RunIISpring16DR80-03708_00659_v0__160915_123950_2043.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/element/23feb676dea515c3713ac1e44e4cf7e4 
"NoPileupUpdate":true

OK, we can do ACDC on premix workflows. thx @amaltaro

**Pull request merged**
