### PR TITLE
failed without retry for exit code 8006 and 70

### LINKED ISSUE #8026: Exit code 70: Job should not be resubmitted
Exit code 70 (or 8006 thrown from WMAgent, see [1]): Fatal exception due to request's misconfiguration. Jobs with this exit code should go straight to _failed_, instead of being resubmitted over and over.

FYI @vlimant 

[1] https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4198.html

### PR DESCRIPTION
**Pull request by ticoann**
fixes #8026

### CODE REVIEW

**Comment by ticoann** [comment]
This might be a good candidate to move to aux db. What do you think, Alan?

**Comment by amaltaro** [comment]
Just updated the issue, there may be other exit codes that we can add in here.

**Comment by amaltaro** [comment]
While we wait for Ops feedback, yes, I totally agree on having this setting in aux db. Another good candidate would be maxRetries.

**Comment by amaltaro** [comment]
@ticoann as discussed in the issue, can you also add 73 and 8009 to the list of failed exit codes?

**Comment by ticoann** [comment]
Yes I will add that. Does this need to be patched to production agents? If not I will put every thing in aux db.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
replaced by #8050

**Pull request closed without merging**
