### PR TITLE
Adding support to use certificates on StompAMQ

### PR DESCRIPTION
**Pull request by ddavila0**
Superseeds #8890

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
I think the tests won't be triggered unless Diego gets added to one of the WMCore/DMWM teams.
Since it's a one time PR, I guess we can just skip that, this module doesn't have any unit tests anyways...

I ran a pylint and code looks good. We can merge it and proceed with further testing afterwards.

**Comment by ticoann** [comment]
Is username and password is not mandatory parameter anymore?

**Comment by ticoann** [comment]
I am merging it but I think we should set the default values if the parameters are optional and validate in the function. (either cert/key or user/pass  has to be set - both cannot be empty)

**Comment by amaltaro** [comment]
Sigh, I was going to reply that that was a good point :-) We could make it all kwargs, this is the only usage in WMCore:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/HeartbeatMonitorBase.py#L67

**Pull request merged**
