### PR TITLE
Workunit job association 

### PR DESCRIPTION
**Pull request by ericvaandering**
This is a work in progress for a job to make and associate work units when the job is created. 

Not sure at the time of job creation is the best place to ultimately make work units, but for now it is expedient.

### CODE REVIEW

**Comment by ericvaandering** [comment]
@amaltaro and @ticoann I'd like comments on this. This now starts creating work units in the database when jobs are created and when workflows are removed.  Also comments on additional unit tests I should perform are welcome and I'd like to see it tested in the next round of @amaltaro 's agent testing. It will have a performance impact, the question is how much.

**Comment by amaltaro** [comment]
Given you know there will be a performance penalty, how about you make some performance tests? :-)

**Comment by ticoann** [comment]
Hey Alan, I thought you are on vacation. :-) As far as performance testing, I am not sure how we can test it isolated. I assume performance hit comes from the work_units being many more than jobs and which access the queries those tables will impact on performance. I would assume the limit we have ~50K(I am not sure this is the right number) jobs per agent mostly depends on DB capability. In that case, we might have much less jobs each agent can handle.

**Comment by ticoann** [comment]
@ericvaandering, As far as testing goes, we have to use below job splitting, right?
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiByWork.py

This is backward compatible, right? (We can still run other job splitting with this patch) 

Before we start testing, we have to list what to test, first correctness and then performance.
I guess we need to test whether final product is the same (same events, lumis) when jobs are 100 successful.
@amaltaro, any good idea what to test and how? - Not expecting to get an answer until after your vacation. :-)

Anyway, I think we need to have stable version of agent before we test this one.

**Comment by ericvaandering** [comment]
Nope, it doesn't have anything to do with job splitting. You should start to see these extra tables get populated with any jobs that are assigned to run on files with lumis.

**Comment by ericvaandering** [comment]
What I want to do is make sure it doesn't blow up by violating any constraints in the database, for instance. Then I think the plan @PerilousApricot and I hatched was that we could start doing correctness tests in JobArchiver to verify that jobs and work units both agree about what the work to be done still is.

**Comment by ericvaandering** [comment]
Exactly, it's going to insert a couple of rows/lumi section/workflow into the database. Deletes will be massive but only once per workflow, so that should be quick.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@ericvaandering, Hi Eric, finally found the problem. 😄 After following line. 
self.associateWorkUnits() need to be added. 

https://github.com/ericvaandering/WMCore/blob/3d15b7727b4b944578f2e749047d9dfad5f42695/src/python/WMCore/WMBS/Job.py#L117

**Comment by ericvaandering** [comment]
Thanks @ticoann !

**Comment by ericvaandering** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ericvaandering** [comment]
@ticoann if you want to try this on your test machine, I think it's ready. It is putting the correct info when called from Subscription

**Comment by ticoann** [comment]
@ericvaandering, Thanks Eric, It is working fine. All the data is populated in the workunit tables.
Could you squash the commit? I will merge it, then I will try to run some performance test.

**Comment by ericvaandering** [comment]
Ok, it looks like this is ready @ticoann

**Comment by ticoann** [comment]
Thanks Eric, I will try to run some performance test.

**Pull request merged**
