### PR TITLE
fix ErrorHandler unittest

### LINKED ISSUE #6175: Broken unit test
Headed home for the day, but ....

@amaltaro , pull request #5860 seems to have broken unit test

test/python/WMComponent_t/ErrorHandler_t/ErrorHandler_t.py , ErrorHandlerTest.testA_Create 

The files now come back with -90 events to analyze. Any ideas?

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #6175

### CODE REVIEW

**Comment by amaltaro** [comment]
It cannot be that this fix would affect even WorkQueueTest:testTeams... I'll look at it tomorrow.

**Comment by ericvaandering** [comment]
No, I think those are the recently unstable tests. You could clean up the pylint stuff.

**Comment by ticoann** [comment]
When test changed from success/fail to error, it seem it most likely one of the unittest wasn't able to clean up the db.  (Hopefully patch Valentin is working on should remove that problem)

Yes, you should just ignore WorkQueue errors.

**Comment by amaltaro** [comment]
Sure! Pylint stuff cleaned up. Also marked the profilling test as integration.

**Comment by amaltaro** [comment]
@ticoann feel free to merge this request

**Pull request merged**
