### PR TITLE
Reorganize microservices in their own package; remove unused

### LINKED ISSUE #10356: Reorganize microservices packages and modules within their own package
**Impact of the new feature**
Microservices

**Is your feature request related to a problem? Please describe.**
With all the microservices already created, and still others already planned to be created, I think we should better organize those packages/modules under WMCore/MicroService to properly reflect the code and service provided.

**Describe the solution you'd like**
Still trying to make the whole picture in my mind, but the obvious re-organization is that each microservice should live inside its own package (named after the microservice).

TODO: update this description once other things are more clear.

**Describe alternatives you've considered**
Keep things as they are.

**Additional context**
none

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #10356 

#### Status
ready

#### Description
This PR doesn't contain any logical changes, only:
* removed unused modules, such as: Regexp.py, Injector.py, Stageout.py, UnifiedStageout.py (from WMCore/MicroService/Unified)
* restructuration of our microservices core code (and direct data structure) into their own package

#### Is it backward compatible (if not, which system it affects?)
yes (the IDE should have caught all the references and updated them for me)

#### Related PRs
none

#### External dependencies / deployment changes
Deployment changes are provided in:
https://github.com/dmwm/deployment/pull/1040
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/76
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/75

### CODE REVIEW

**Comment by amaltaro** [comment]
Previous tree organization was:
```
src/python/WMCore/MicroService/
|-- CherryPyThreads
|   |-- HeartbeatMonitor.py
|   `-- __init__.py
|-- DataStructs
|   |-- DefaultStructs.py
|   |-- DefaultStructs.pyc
|   |-- MSOutputTemplate.py
|   |-- MSOutputTemplate.pyc
|   |-- MSRuleCleanerWflow.py
|   |-- MSRuleCleanerWflow.pyc
|   |-- Workflow.py
|   |-- Workflow.pyc
|   |-- __init__.py
|   |-- __init__.pyc
|   `-- campaigns.json
|-- Regexp.py
|-- Service
|   |-- Data.py
|   |-- Data.pyc
|   |-- RestApiHub.py
|   |-- RestApiHub.pyc
|   |-- __init__.py
|   `-- __init__.pyc
|-- Tools
|   |-- PycurlRucio.py
|   |-- PycurlRucio.pyc
|   |-- __init__.py
|   `-- __init__.pyc
|-- Unified
|   |-- Common.py
|   |-- Common.pyc
|   |-- Injector.py
|   |-- MSCore.py
|   |-- MSCore.pyc
|   |-- MSManager.py
|   |-- MSManager.pyc
|   |-- MSMonitor.py
|   |-- MSMonitor.pyc
|   |-- MSOutput.py
|   |-- MSOutput.pyc
|   |-- MSOutputStreamer.py
|   |-- MSRuleCleaner.py
|   |-- MSRuleCleaner.pyc
|   |-- MSTransferor.py
|   |-- MSTransferor.pyc
|   |-- RSEQuotas.py
|   |-- RSEQuotas.pyc
|   |-- RequestInfo.py
|   |-- RequestInfo.pyc
|   |-- SiteInfo.py
|   |-- SiteInfo.pyc
|   |-- Stageout.py
|   |-- TaskManager.py
|   |-- TaskManager.pyc
|   |-- __init__.py
|   `-- __init__.pyc
|-- UnifiedStageout.py
|-- WebGui
|   |-- FrontPage.py
|   `-- __init__.py
|-- __init__.py
`-- __init__.pyc

6 directories, 56 files
```

with this PR, the tree became:
```
src/python/WMCore/MicroService/
|-- CherryPyThreads
|   |-- HeartbeatMonitor.py
|   `-- __init__.py
|-- DataStructs
|   |-- DefaultStructs.py
|   |-- DefaultStructs.pyc
|   |-- __init__.py
|   |-- __init__.pyc
|   `-- campaigns.json
|-- MSCore.py
|-- MSManager.py
|-- MSMonitor
|   |-- MSMonitor.py
|   `-- __init__.py
|-- MSOutput
|   |-- MSOutput.py
|   |-- MSOutputStreamer.py
|   |-- MSOutputTemplate.py
|   `-- __init__.py
|-- MSRuleCleaner
|   |-- MSRuleCleaner.py
|   |-- MSRuleCleanerWflow.py
|   `-- __init__.py
|-- MSTransferor
|   |-- MSTransferor.py
|   |-- RSEQuotas.py
|   |-- RequestInfo.py
|   |-- Workflow.py
|   `-- __init__.py
|-- Service
|   |-- Data.py
|   |-- Data.pyc
|   |-- RestApiHub.py
|   |-- RestApiHub.pyc
|   |-- __init__.py
|   `-- __init__.pyc
|-- TaskManager.py
|-- Tools
|   |-- Common.py
|   |-- PycurlRucio.py
|   |-- PycurlRucio.pyc
|   |-- __init__.py
|   `-- __init__.pyc
|-- Unified
|   |-- SiteInfo.py
|   |-- SiteInfo.pyc
|   |-- __init__.py
|   `-- __init__.pyc
|-- WebGui
|   |-- FrontPage.py
|   `-- __init__.py
|-- __init__.py
`-- __init__.pyc

10 directories, 43 files
```

**Comment by todor-ivanov** [comment]
Well done @amaltaro! I like this reorganization pretty much. It is in perfect coherence with my practice of running the micro services standalone. And I like to have everything from a module at a single place.

**Comment by vkuznet** [comment]
@amaltaro , if you do reorganization please be consistent, e.g.
```
|-- MSCore.py
|-- MSManager.py
|-- MSMonitor
|   |-- MSMonitor.py
|   `-- __init__.py
```
Instead, you should put MSCore and MSManager in their own areas. This will achieve consistency and proper importing, e.g. `from WMCore.MicroService.MSCore import MSCore`, etc. It also will allow proper expansion of MSCore and MSManager if you'll need this in a future.

**Comment by amaltaro** [comment]
@vkuznet Valentin, the reason I kept those at the top level package of `MicroService` is:
* `MSCore` is a super class common to all microservices
* `MSManager` is sort of a microservice manager, creating/start/stop them; it also provides REST source code(which one could say it sort of doesn't belong here though).

In my opinion, it's also consistent with other parts of the WMCore repository, like the WMCore/Services package (where Service/Requests/pycurl_manager are common modules for all those services).

Perhaps another alternative could be to create another directory named `MSCore` (or even `Core`) and move both modules inside it (and the TaskManager, which isn't clear to me whether it's currently used or not). Still, I'm not convinced this approach would be better than leaving them at the top level `MicroService` package. 
What do you/Todor think? Thanks for your feedback btw, I wanted to ask you about this as well.

**Comment by todor-ivanov** [comment]
Hi @amaltaro @vkuznet I would apply a simple logic here. If any of those could exist and provide meaningful functionality for instantiating or controlling (some kind of) a micro service independent of the other, then I would opt for putting them each in its own area. But in case their internal logic is inseparably connected then I would put them both together in a their common space.

So all that  said and giving a quick look again on them both I notice they do not even import each other. They both serve kind of core functionality, but while one is providing an interface to other central services, the other one is meant to be for driving the running MS processes. I can foresee a use case where a service of some kind may be created and using one of them but not the other. So in this case I tend to be more inclined in separating them each one in its own area.

**Comment by amaltaro** [comment]
Most of the WMCore project has been organized before I was even part of the team. However, in my analysis I see it organized in the following two ways:
1) by service/component and or functionality
2) by information/data type, e.g.: structures, utils, tools, rest/http, main logic, etc

So, in my opinion, the two alternatives that make more sense are:
a) as it is provided in this PR, thus core functionality for the microservices at the `WMCore/MicroService` package
b) we create a `Core` package and move MSCore, MSManager and TaskManager under it. Those provide core functionality and none of the WMCore Microservices can work without MSCore and MSManager.

It isn't clear what would we gain by creating another package for MSCore, and another for MSManager (and perhaps even another one for TaskManager). That's why I don't even list it as another alternative. Meaningful names also don't come to my mind.

Todor, Valentin, if you have further comments, please let me know. Otherwise I planning to get it merged tonight. It's anyways a big improvement on the current structure.

**Comment by todor-ivanov** [comment]
That is fine with me Alan, and the key sentence here is:
>  Those provide core functionality and none of the WMCore Microservices can work without MSCore and MSManager.

As I said earlier a valid reason for me to put them in a common package would be if their logic is hardly coupled. 
And I totally agree this is a huge improvement!

**Review by todor-ivanov — APPROVED** [review]
Changes look great to me!
Thanks @amaltaro

**Comment by amaltaro** [comment]
Thanks Todor. I will just try to separate the test from the src changes, which I mistakenly put all in the same commit.

**Comment by amaltaro** [comment]
For future reference, it took me some commands like:
```
git reset --soft HEAD~1
git reset HEAD test/*
and etc
```

**Comment by amaltaro** [comment]
Conflicts resolved. Thanks Todor.

**Comment by todor-ivanov** [comment]
Hi @amaltaro, Sorry for writing in an already closed PR, but I just found we  have reorganized the source code modules but we somehow missed to do so for the unit tests related to them. If you did not leave those behind for a reason, I think we should change the directory structure there too.

**Comment by amaltaro** [comment]
Good catch Todor, sorry for missing it. I'm going to create another PR to complement this one.

**Pull request merged**
