### PR TITLE
Add PyPI support for reqmon, reqmgr2ms, global-workqueue, acdcserver

### LINKED ISSUE #9823: Migrate Reqmon to PyPI
**Impact of the new feature**
Reqmon

**Is your feature request related to a problem? Please describe.**
RPM builds of python based applications are out! PyPI is in!

**Describe the solution you'd like**
Provide pypi setup scripts to build and upload ReqMon to PyPI

### PR DESCRIPTION
**Pull request by goughes**
Fixes #9823 #9820 #9828 #9821 

#### Status
Ready

#### Description
Updated the pypi build script and requirements.txt file to include reqmon, reqmgr2ms, workqueue, acdcserver. 

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
NA

#### External dependencies / deployment changes
cms-dist dependency: https://github.com/cms-sw/cmsdist/pull/6442

### CODE REVIEW

**Comment by goughes** [comment]
This has one issue: the name "workqueue" is already taken in PyPI so we'll need to use a different name. I was thinking "cms-workqueue", but will take suggestions.

I uploaded 1.4.1pre5 for reqmon, reqmgr2ms and acdcserver and validated their installation via PyPI. I did not perform any validation of the services on my VM, just the installation.

Current PyPI status: https://pypi.org/user/cms-oc-dmwm/

**Comment by goughes** [comment]
This has been updated to change the "workqueue" package name to "global-workqueue". We need to keep the workqueue name around so RPM builds can continue. I had a decision here to either add a bunch of logic all over the place to translate between the two names, or add a global-workqueue dictionary to the current dependency set (which is an exact copy of the workqueue dict used for RPM builds) and simply reference that during pypi builds. This adds some redundancy, but avoids complicating the pypi build scripts and lets RPM builds continue under the same workqueue name. 

https://github.com/dmwm/WMCore/blob/80c09e92832338aa439faa9efc40430c9ec512b4/setup_dependencies.py#L114

**Comment by amaltaro** [comment]
@goughes perhaps we could try changing how we call setup.py here:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/workqueue.spec

L15 and L19, such that we can keep only `global-workqueue` in the list of dependencies? So we would start building global-workqueue, even though the RPM would still be named after workqueue.

I'm not sure whether there are other places that we would have to change things though.

**Comment by goughes** [comment]
@amaltaro, great idea! I will test the python build portion of the RPM spec with the `global-workqueue` name.

**Comment by goughes** [comment]
Looks like the python pieces of the RPM build process work fine with the `global-workqueue` name. I tested locally and compared the files to what I had in my RPM based VM installation of workqueue.

https://github.com/cms-sw/cmsdist/blob/f192a845b254fde90c4acc52900aa4c7c97f0339/workqueue.spec#L15
https://github.com/cms-sw/cmsdist/blob/f192a845b254fde90c4acc52900aa4c7c97f0339/workqueue.spec#L19

I can make a deployment PR to update the name and remove the duplicate entry from the dependencies dictionary.

**Comment by amaltaro** [comment]
@goughes Erik, Dario and I noticed that py2-cjson is not a direct WMCore dependency, but it gets shipped with dbs3-client instead. Said that, should we remove it from our requirements.txt list?

**Comment by goughes** [comment]
Yes, I will push that change here. Thanks!

**Comment by goughes** [comment]
> @goughes Erik, Dario and I noticed that py2-cjson is not a direct WMCore dependency, but it gets shipped with dbs3-client instead. Said that, should we remove it from our requirements.txt list?

Just fixed this @amaltaro

**Comment by amaltaro** [comment]
@goughes Erik, are you still working on this branch? Or is it ready to go?

**Comment by goughes** [comment]
@amaltaro Should be good to merge. Please give a review at your convenience.

**Review by amaltaro — APPROVED** [review]
Thanks Erik! It looks good to me.

**Pull request merged**
