### PR TITLE
Make sure NANOAOD files go straight to UNmerged

### LINKED ISSUE #8278: Ban NANOAOD{SIM} files from going straight to merge
Otherwise we could end up with some EDM and non-EDM files under the same dataset. The idea is to never have NANOADO EDM format registered in DBS.

This hook can be added either with:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Templates/StageOut.py#L51

or checking the datatier here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/StageOut.py#L151

@hufnagel you use these mechanism in T0, let me know if there is a better place for adding this tweak.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #8278

Still have to test though

### CODE REVIEW

**Comment by hufnagel** [comment]
Might be wrong, but don't merge jobs run through the same code path ? Ie. merge jobs are just processing jobs whose output is always straightToMerge ? Or is that done differently ? Haven't looked at this in a while...

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
I'm not sure... if that's the case, then it means straightToMerge is always False

**Comment by amaltaro** [comment]
@ericvaandering it looks like jenkins don't want to run for this PR. Would you mind having a look at it once you have some spare cycles?

**Comment by ericvaandering** [comment]
Looks like two tests might be timing out:

#487 _testInsertAllPNNs_
#489 _testInsertT0_ 

(from two different slices) both in test/python/WMCore_t/ResourceControl_t/ResourceControl_t.py

**Comment by amaltaro** [comment]
Now it works :-) from the condor.err log (should be .out, but ...)
`INFO:root:NANOAOD and NANOAODSIM files never go straight to merge!`

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann @hufnagel  it has been backported already to 1.1.8, but please review even if it's already merged :)

**Comment by hufnagel** [comment]
Logic looks alright.

**Pull request merged**
