### PR TITLE
Switch from WMCore StompAMQ to CMSMonitoring one 

### LINKED ISSUE #9291: Migrate to CMSMonitoring/StompAMQ package
Such that we use the same baseline code and get all the features (schema validation, broker round-robin, etc) already available there.
It requires changes to cmsdist specs, thus new RPMs.

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9291 
Superseeds #9214 

#### Status
not-tested

#### Description
As the subject says, remove the StompAMQ module from WMCore in favor of the CMSMonitoring package https://github.com/dmwm/CMSMonitoring

#### Is it backward compatible (if not, which system it affects?)
no (requires a new RPM)

#### External dependencies / deployment changes
https://github.com/cms-sw/cmsdist/pull/5083

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by vkuznet** [comment]
Alan, I made PR for cmsmonitoring RPM, here it is https://github.com/cms-sw/cmsdist/pull/5082

**Comment by amaltaro** [comment]
Thanks, Valentin.
If Lina doesn't merge it, I'll trigger the merge a bit later (once the bot builder is done).

BTW, 0.2.4 seems to be working fine either on my central services and on a WMAgent box.

**Comment by amaltaro** [comment]
Tests fail because we need a new docker image with the CMSMonitoring dependency.
I'm getting this merged and will trigger a new docker image once I have another tag.

**Pull request merged**
