### PR TITLE
Add MicroService classes

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vkuznet** [comment]
Example of config file for micro-service:
https://gist.github.com/vkuznet/49d07398357d88e9b967b3c9722083de

**Comment by vkuznet** [comment]
Script to run Micro-Service:
https://gist.github.com/vkuznet/6a5b77ec59a59d68577c637328dea164

**Comment by ticoann** [comment]
@vkuznet, Valentin, could you fix pylint warnings (bold ones)

**Comment by ericvaandering** [comment]
Not just bold warnings. Everything that can be fixed. No reason to have problems in completely fresh code. Also, why is UnifiedStageout in the MicroService category? I think what's micro and what is not going to be well defined and "Services" is not providing services, but APIs to the existing services. Should give a thought to organization here. Maybe chat tomorrow.

**Comment by vkuznet** [comment]
Guys, I sketched the code to show you the idea. The UnifiedStageout may be
elsewhere outside of MicroService, that what we need to discuss.
The warnings will be fixed once we agree on approach.

**Comment by ticoann** [comment]
@vkuznet, So Valentin, you don't need to include this one in today's tag?

**Comment by vkuznet** [comment]
Yes, I don't to include this one in today's tag.

**Comment by PerilousApricot** [comment]
I was reading through the PR for curiosity's sake, and tried to follow the following link https://github.com/dmwm/WMCore/pull/7949/files#diff-aac8b14095c9afe5b6234329c0b10f2eR65 but it's broken. Is that mirrored somewhere else?

**Comment by vkuznet** [comment]
Andrew,
it works for me now, may be transient error.
Valentin.

**Comment by vkuznet** [comment]
@ticoann could you please review and merge.

**Comment by ticoann** [comment]
Sorry Valentin for the late review. Patch looks good. Just a couple of small things.

1. Could you send cherrypy.HTTError with specific status and messages, so if client gets knows wether something wrong with request or serverside error.
2. I think you can remove import statement from __init__ function although pylint complains, unless you are planning to wright code there.

If you can squash the commit that will be great too. Thanks,

**Comment by vkuznet** [comment]
@ticoann, Seangchan, I squashed commits as well as provided proper HTTPError and removed import from init. Please review/test/merge.

**Comment by ticoann** [comment]
Thanks Valentin,

**Comment by PerilousApricot** [comment]
Sorry, @vkuznet -- I just now saw this notification. The link I was referring to is: https://github.com/knly/MicroServiceAggregation -- which currently returns a "not found"

**Pull request merged**
