### PR TITLE
get only valid files from dbs

### LINKED ISSUE #5602: Get only valid files from dbs
Updates agent only after https://github.com/dmwm/DBS/issues/445 is in production

### PR DESCRIPTION
**Pull request by ticoann**
fixes #5602

### CODE REVIEW

**Comment by ticoann** [comment]
@yuyiguo, Yuyi could you review whether I used the correct parameter and value? (validFileOnly)

**Comment by yuyiguo** [comment]
Yes. validFileOnly=1  for WMagents/valid file, otherwise everything will be included by default.

**Comment by ticoann** [comment]
Thanks, Yuyi. To test this, is there a no need to update dbs client? So changes is only server side?

**Comment by yuyiguo** [comment]
Yes. This is a new to listFiles API so new client needed.

**Pull request merged**
