### PR TITLE
Update CMSMonitoring module version to use StompAMQ7 with latest stomp

### PR DESCRIPTION
**Pull request by mrceyhun**
Fixes #11180

#### Status
ready

#### Description
CMSMonitoring module pypi version is upgraded with the new release which uses latest stomp.py version (>=6.1.1,<8.0.0)

#### Is it backward compatible (if not, which system it affects?)
NO . 
Affected: `HeartBeatMonitor.py`, `AgentStatusPoller.py`
Reason: new StompAMQ7 does not use camel case parameters

#### Related PRs
[dmwm/CMSMonitoring/pull/146](https://github.com/dmwm/CMSMonitoring/pull/146)

#### External dependencies / deployment changes
`CMSMonitoring~=0.6.2` applied in requirements.txt

@amaltaro I could not test with the `wmagent`AMQ  producer because of a credential issue. MONIT uses a different flume agent for WMA and I could not understand which producer should I use to test. Since I don't want to take your time by asking more details, I created this PR to be able test. New StompAMQ changes are applied. If it is possible, could you please deploy this PR to test and then we can check data in ES.

fyi @vkuznet

### CODE REVIEW

**Comment by amaltaro** [comment]
Thank you for creating this PR @mrceyhun . I am afraid it won't be easy to test though, unless we build and deploy WMAgent with these changes in. Shall we try going through your concerns and see if you can test it with a standalone setup? Feel free to reach out to us via MM channels (either DMWM or privately, if needed).

**Comment by mrceyhun** [comment]
Hi @amaltaro , sorry for the delay. 

I tested with the configs you provided and it worked well. These[1] are test data submission and it does not break any schema as it seems.

I updated `CMSMonitoring` version with the latest release version. I think I did not miss any setting but it would be good to review.

For future tests, we can use below commands:
```
stompSvc = StompAMQ7(username=username, password=password, producer=producer, topic=topic, key=ckey, cert=cert, validation_schema=None, host_and_ports=[(host, port)])
messages = []

doc_type="metadata_doc_type_test"

# multiple docs should be sent to be processed by MONIT
doc = {"wmbs_status": "test_220704_1", "type": "type_test_ceyhun", "num_jobs":0, "agent_url": "test_220704_1"}
notif, _, _ = stompSvc.make_notification(payload=doc, doc_type=doc_type, ts=int(time.time()), data_subfield="payload")
messages.append(notif)

stompSvc.send(messages)
```

[1] https://monit-kibana.cern.ch/kibana/goto/ba7091aea06bd33f10b99f6aa0779718

**Review by amaltaro — APPROVED** [review]
Thank you very much for providing this fix and getting it tested as well, @mrceyhun .

**Comment by amaltaro** [comment]
Indeed the PR fixed the version incompatibility. A new WMCore version - 2.1.0.pre5 - has been released with that fix in.

**Pull request merged**
