### PR TITLE
Add erlang views for wmstats

### PR DESCRIPTION
**Pull request by geneguvo**
This is the set of erlang views we already have written for wmstats. The two remaining ones @BrunoCoimbra is working on.

I tested these erlang views with a snapshot of the production database and did various performance tests. I haven't tested the rewrite rules, though. I just added them similarly to the ones that already existed.

We also need to do corresponding changes for the frontend rules in deployment (https://github.com/dmwm/deployment/blob/master/frontend/app_couch_ssl.conf) once these views have been included in the next reqmon release.

This is work done as agreed in #6382.

### CODE REVIEW

**Comment by geneguvo** [comment]
Please review/test and include it in the upcoming release HG1512.

**Comment by ticoann** [comment]
Thanks a lot, Diego. I will run the test. If it works fine we will drop js code completeley.

**Comment by geneguvo** [comment]
Dont drop the js code yet. We need it for the validation of the new views. We should also keep both for a month or two. In case of any problem, we could easily set to use the js views instead.

**Comment by ticoann** [comment]
Thanks Diego, that is good point. I will keep the js code for a while then. I was talking to Alan earlier, though. What happen if we keep js view. I mean isn't it affect the view creation time?  What is the performance increase with erlang over javascript. It is one view creation(update) or view accessing or both?

**Comment by ticoann** [comment]
All view created in erlang gives the same result as js view in my vm test. merging the patch.

**Pull request merged**
