### PR TITLE
Add check list to the request json templates

### PR DESCRIPTION
**Pull request by amaltaro**
No issue has been created

#### Status
not-tested

#### Description
Provided the recently added `CheckList` field in the request json templates. I started populating it with validation items retrieved from our usual validation twiki. Some items are present in multiple templates, others are nowhere, but still it should give anyone a better idea of which features of the system are getting exercised with each of those templates.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
Follow up of: https://github.com/dmwm/WMCore/pull/9467

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
@todor-ivanov can you please apply this patch to your node where you inject workflows and get back here once your tests have ran and you're happy with the check list comments?

**Review by todor-ivanov — COMMENTED** [review]
Testing it with the current validation now.

**Comment by amaltaro** [comment]
@todor-ivanov did you manage to verify the outcome of your tests and whether the checklist is sound? Thanks

**Comment by todor-ivanov** [comment]
@amaltaro  I am currently trying to do so. But I cannot reach cmsweb-testbed.cern.ch And I see those beautiful alarms in my mail:
```
Labels
alertname = service_down
env = preprod
instance = vocms0132:18240
job = reqmgr2-preprod
severity = dmwm
Annotations
description = preprod has been down for more than 5m
summary = reqmgr2 preprod is down
```

**Comment by todor-ivanov** [comment]
@amaltaro. Yes, I do see the checklist properly now. It is only that it come before the Workflow Description. It obviously come from here: [1]. But anyway, we can live with that for the moment.

[1]
https://github.com/dmwm/WMCore/blob/5780eff408dfe81bf0d23d3823b99c7a483d9857/test/data/ReqMgr/validate-test-wfs.py#L306

**Comment by amaltaro** [comment]
Dictionaries are by nature not ordered. One could order them though on the validation script, but it should be fine.

**Review by todor-ivanov — APPROVED** [review]
It is perfect

**Pull request merged**
