### PR TITLE
Avoid WebTools depending on the REST package 

### LINKED ISSUE #9263: REST.Auth
@amaltaro 
I got below errors [1] when I was running DBS with WMCore 1.2.3. The build was successful, but when I started DBS server, I got these errors. The Auth was introduced last month. I did not get why the building did not bring REST into the rpm. Please take a look. I will need this for the HG1907 release.
Thanks,
Yuyi

[1] Traceback (most recent call last):
  File "/data/srv/HG1906f/sw.yuyi/slc7_amd64_gcc630/cms/dbs3/3.10.0/lib/python2.7/site-packages/WMCore/WebTools/Root.py", line 35, in <module>
    from WMCore.WebTools.FrontEndAuth import FrontEndAuth, NullAuth
  File "/data/srv/HG1906f/sw.yuyi/slc7_amd64_gcc630/cms/dbs3/3.10.0/lib/python2.7/site-packages/WMCore/WebTools/FrontEndAuth.py", line 8, in <module>
    from WMCore.REST.Auth import get_user_info
ImportError: No module named REST.Auth
~

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9263 

#### Status
not-tested

#### Description
Duplicated the `get_user_info` util function such that WebTools don't need to depend on the REST package.

#### Is it backward compatible (if not, which system it affects?)
YES

#### External dependencies / deployment changes
No

### CODE REVIEW

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, can you please apply this patch to your VM and check whether things run Okay? If so, then I can backport it to the DBS branch.

**Comment by yuyiguo** [comment]
@amaltaro 
Alan, I tried to build again using the my local branch and patch with this PR. I checked the my branch was patch correctly. I modified dbs3.spec a bit to trigger the rebuilding and it seemed to rebuilt, but the patched code was not there. I still had the old code.  How to make the building process to pick the new code?

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, that would be certainly the best test. However, it takes too much effort for the fix proposed here, so I think we could simply apply this patch to one of your DEV DBS services, restart it and make sure it works (or that it does not crash). What do you think?

So you'd need something like:
```
cd /data/srv/current
  wget -nv https://patch-diff.githubusercontent.com/raw/dmwm/WMCore/pull/9264.patch -O - | patch -d apps/dbs3/lib/python2.7/site-packages/ -p 3
```

on your VM and that's it (note that the path might not be precisely what you use for DBS).

**Comment by yuyiguo** [comment]
Ok, I give it a try.

**Comment by yuyiguo** [comment]
@amaltaro 
It worked. Please merge.

**Comment by amaltaro** [comment]
Thanks, Yuyi.

**Comment by amaltaro** [comment]
test this please

**Pull request merged**
