### PR TITLE
Untar with python2.6 for older release

### PR DESCRIPTION
**Pull request by juztas**
Patch to CRAB3 branch only until CRAB3 will finish all movement to python2.7 and also fix environment issues.

### CODE REVIEW

**Comment by mmascher** [comment]
Hi @juztas , remember to always start PR to CRAB3 branches with `1.0.14_crab version of`. This way @ericvaandering @amaltaro or @ticoann know they can merge without review.

**Comment by amaltaro** [comment]
Shall I merge it now? Do you need a new tag?

**Comment by mmascher** [comment]
yes (merge) and yes (new tag) please :)

**Comment by amaltaro** [comment]
Ok, on it in the next minutes. @juztas @mmascher and @emaszs make sure to talk to each other in the future, I created a CRAB task an hour ago...

**Comment by amaltaro** [comment]
Sorry, I forgot this PR. Tag was created: 1.0.14_crab_6

**Pull request merged**
