### PR TITLE
'xrange_with_import' fix applied

### PR DESCRIPTION
**Pull request by vilnius-dev**
Renames `xrange()` to `range()` and wraps existing `range()`calls with list

### CODE REVIEW

**Comment by ericvaandering** [comment]
ReqMgrDocGenerator.py has imports in the wrong order

**Comment by vkuznet** [comment]
@ticoann , this should be tested for performance impact since range and xrange are different data-types in py2. Changing to range (which is generator in py3) will impact py2 code since range is a list.

This may be an example to be applied later when we'll do py2/py3 conversion.

**Comment by ticoann** [comment]
test this please

**Comment by mapellidario** [comment]
This is covered by our gradual migration.

I would suggest closing this PR without merging, since it is superseded by our current efforts.

**Comment by mapellidario** [comment]
Thanks Roman for your work! Closing this

**Pull request closed without merging**
