### PR TITLE
Delete Analysis and PrivateMC spec, task etc

### PR DESCRIPTION
**Pull request by amaltaro**
@ticoann don't merge it please
@ericvaandering @mmascher I'm sorry if I'm doing something stupid

This PR basically removes all the existence of Analysis and PrivateMC code (spec, taskType, ACDC analysis service, etc).

Unless we want to keep this code around - or some of them is actually being used by CRAB - this would be a nice cleanup :)

### CODE REVIEW

**Comment by ticoann** [comment]
@mmascher, @juztas, Marco, Justas, are these codes used in CRAB? or can we clean up?

**Comment by mmascher** [comment]
They are not, go ahead

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
@ticoann good to go

**Comment by amaltaro** [comment]
assigning to @ticoann such that you don't forget it :-)

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Going into my VM as well.

**Comment by amaltaro** [comment]
Tested in my VM and agent.

**Pull request merged**
