### PR TITLE
fix status mismatch when reqmgr is down but couch server is running

### LINKED ISSUE #6263: DecodeError parsing json in ReqMgr2
These errors seem to be happening quite often in the logs. Traceback example here [1]

and another example here [2]

[1]
```
[16/Sep/2015:15:48:59] vocms0136.cern.ch 131.225.205.13 "GET /reqmgr2/data/request?name=pdmvserv_BPH-RunIISpring15DR74-00038_00341_v0__150905_183106_4346 HTTP/1.1" 200 OK [data: 3167 in 3540 out 9473 us 
] [auth: OK "/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=Services/CN=wmagent/cmsgwms-submit1.fnal.gov" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[16/Sep/2015:15:49:05]  SERVER OTHER ERROR __builtins__.KeyError a892def79050efbf10a6f6eea2143d77 ('rows')
[16/Sep/2015:15:49:05]    Traceback (most recent call last):
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[16/Sep/2015:15:49:05]        return self._call(RESTArgs(list(args), kwargs))
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 772, in _call
[16/Sep/2015:15:49:05]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[16/Sep/2015:15:49:05]  SERVER OTHER ERROR cjson.DecodeError 91ac402c439dfe1f70582f8d59e1cf9d (cannot parse JSON description)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/Service/Request.py", line 278, in get
[16/Sep/2015:15:49:05]    Traceback (most recent call last):
[16/Sep/2015:15:49:05]        request_info.append(self.reqmgr_db_service.getRequestByNames(name))
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 152, in getRequestByN
ames
[16/Sep/2015:15:49:05]        return self._call(RESTArgs(list(args), kwargs))
[16/Sep/2015:15:49:05]        requestInfo = self._formatCouchData(data, detail = detail)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 772, in _call
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 62, in _formatCouchDa
ta
[16/Sep/2015:15:49:05]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[16/Sep/2015:15:49:05]        for row in data['rows']:
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/Service/Request.py", line 278, in get
[16/Sep/2015:15:49:05]    KeyError: 'rows'
[16/Sep/2015:15:49:05]        request_info.append(self.reqmgr_db_service.getRequestByNames(name))
[16/Sep/2015:15:49:05] vocms0136.cern.ch 188.184.162.209 "GET /reqmgr2/data/request?name=anlevin_RVCMSSW_7_6_0_pre5PhotonJets_Pt_10_13_HI_150916_124311_7729 HTTP/1.1" 500 Internal Server Error [data: 3939 in 723 out 5779881 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0308.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 150, in getRequestByNames
[16/Sep/2015:15:49:05]        data = self._getRequestByNames(requestNames, detail = detail)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 82, in _getRequestByNames
[16/Sep/2015:15:49:05]        result = self.couchDB.allDocs(options, requestNames)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 532, in allDocs
[16/Sep/2015:15:49:05]        {'keys':keys})
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 117, in post
[16/Sep/2015:15:49:05]        encode, decode, contentType)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 113, in makeRequest
[16/Sep/2015:15:49:05]        encode, decode,contentType)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 145, in makeRequest
[16/Sep/2015:15:49:05]        encoder, decoder, contentType)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 280, in makeRequest_httplib
[16/Sep/2015:15:49:05]        result = self.decode(result)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 571, in decode
[16/Sep/2015:15:49:05]        data =  decoder.decode(data)
[16/Sep/2015:15:49:05]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Wrappers/JsonWrapper/__init__.py", line 93, in decode
[16/Sep/2015:15:49:05]        return cjson.decode(idict)
[16/Sep/2015:15:49:05]    DecodeError: cannot parse JSON description
[16/Sep/2015:15:49:05] vocms0136.cern.ch 131.225.205.13 "GET /reqmgr2/data/request?name=pdmvserv_EXO-RunIISpring15DR74-01763_00354_v0__150910_183215_8358 HTTP/1.1" 500 Internal Server Error [data: 3167 in 723 out 5020031 us ] [auth: OK "/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=Services/CN=wmagent/cmsgwms-submit1.fnal.gov" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
```

[2]
```
[16/Sep/2015:17:32:03] vocms0136.cern.ch 131.225.205.13 "GET /reqmgr2/data/request?name=pdmvserv_SUS-RunIISummer15GS-00051_00076_v0__150912_201437_5351 HTTP/1.1" 200 OK [data: 3163 in 2789 out 15116 us ]
 [auth: OK "/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=Services/CN=wmagent/cmsgwms-submit1.fnal.gov" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[16/Sep/2015:17:32:03]  SERVER OTHER ERROR cjson.DecodeError 9bd7eb571764483ed2e41b77b0c2bdca (cannot parse JSON description)
[16/Sep/2015:17:32:03]    Traceback (most recent call last):
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[16/Sep/2015:17:32:03]        return self._call(RESTArgs(list(args), kwargs))
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 772, in _call
[16/Sep/2015:17:32:03]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/Service/Request.py", line 278, in get
[16/Sep/2015:17:32:03]        request_info.append(self.reqmgr_db_service.getRequestByNames(name))
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 150, in getRequestByN
ames
[16/Sep/2015:17:32:03]        data = self._getRequestByNames(requestNames, detail = detail)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 82, in _getRequestByN
ames
[16/Sep/2015:17:32:03]        result = self.couchDB.allDocs(options, requestNames)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 532, in allDocs
[16/Sep/2015:17:32:03]        {'keys':keys})
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 117, in post
[16/Sep/2015:17:32:03]        encode, decode, contentType)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 113, in makeRequest
[16/Sep/2015:17:32:03]        encode, decode,contentType)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 145, in makeRequest
[16/Sep/2015:17:32:03]        encoder, decoder, contentType)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 280, in makeRequest_httplib
[16/Sep/2015:17:32:03]        result = self.decode(result)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 571, in decode
[16/Sep/2015:17:32:03]        data =  decoder.decode(data)
[16/Sep/2015:17:32:03]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Wrappers/JsonWrapper/__init__.py", line 93, in decode
[16/Sep/2015:17:32:03]        return cjson.decode(idict)
[16/Sep/2015:17:32:03]    DecodeError: cannot parse JSON description
[16/Sep/2015:17:32:03] vocms0136.cern.ch 128.142.209.43 "GET /reqmgr2/data/request?name=pdmvserv_HIG-RunIISummer15GS-00019_00069_v0__150909_001636_4546 HTTP/1.1" 500 Internal Server Error [data: 3930 in 723 out 5018451 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0308.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
```

### PR DESCRIPTION
**Pull request by ticoann**
Fixes #6263, #6262 (Hopefully)

### CODE REVIEW

**Comment by amaltaro** [comment]
Thanks a lot for fixing it Seangchan! I have a couple of suggestions though:
1. if it's a 404 exit code, how about we create an 'info' entry in LogDB just saying "It's a ReqMgr2 request"?
2. if it's not 404, then we should make a 'warning' log and write the error in LogDB

BTW, if reqmgr1 call succeeds we don't call updateRequestStatus(). Shouldn't we put it in an else after the try/except block to make sure we also update the status in reqmgr2?

**Comment by ticoann** [comment]
Thanks Alan for reviewing. I changed the code as you suggested. 1, 2
We don't need except else case since self.reqMgr.reportRequestStatus call contains reqmgr2 db update as well. Could you review again?

**Comment by amaltaro** [comment]
Then it sounds good now. Maybe just fix the "faile" misspelled :-D

**Comment by ticoann** [comment]
> Then it sounds good now. Maybe just fix the "faile" misspelled :-D

Thank Alan, fixed the typo. I thought that was french. :smile:

**Pull request merged**
