### PR TITLE
Ensure StageOut error details contain only valid bytes

### LINKED ISSUE #8403: Another unicode encoding failure
It is in

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Execute.py#L70

output contains "\x95" which cause encoding error
  
and

'utf8' codec can't decode byte 0xb2 in position 24451

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/8403
Replaces #8404 (but to be applied in new agents only)

I did run that recipe in https://github.com/dmwm/WMCore/issues/8056 to see whether I could encode the sicky FJR and it seems to go through with this fix.

Just for reference, another complement to #8295

### CODE REVIEW

**Comment by amaltaro** [comment]
@ticoann can you please double check it before I proceed with pylint and backport it?

**Comment by amaltaro** [comment]
Just in case, you can find an erratic fjr here:
cmst1@vocms0257:/data/srv/wmagent/current $ cp /data/srv/wmagent/v1.1.8.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BPH-RunIIFall17DRPremix-00037__v1_T_171229_130339_8611/BPH-RunIIFall17DRPremix-00037_0/JobCollection_208364_0/job_1777615/Report.2.pkl .

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Alan is this code the only path which could pass to below?

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Execute.py#L70

If that is the case patch looks fine. Otherwise, I would encode above line.

**Comment by ticoann** [comment]
Alan, I don't think this need to be back ported since we have temp patch. Just for the new agent

**Comment by amaltaro** [comment]
I'm not completely sure, but I think the error message/details only get persisted in the FJR in the code I changed in this PR. I can try running a test tomorrow, but it isn't going to be that simple to get it properly tested :(

**Comment by amaltaro** [comment]
@ticoann I was going to apply the changes we discussed, but it seems WMException is even a better place for that and it should then cover the whole code. If you prefer, I can move it back to the StageOutError class.
Otherwise, I think we can merge it if it passes jenkins (I haven't tested though :))

**Comment by ticoann** [comment]
I was thinking more about not applying this in the place if we don't get the those characters. However it would be more robust in WMException, hope it doesn't have any performance issue.
I will merge it when Jenkins is done.

**Comment by amaltaro** [comment]
Just for reference in case we need to fix it again in the next agent release, I'm not completely sure the decoded error message will be passed all the way until here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Diagnostics/StageOut.py#L30

**Pull request merged**
