### PR TITLE
'newstyle' fix updated

### PR DESCRIPTION
**Pull request by vilnius-dev**
python 2:
   `class PSetTweak:`  

python 2/3:
`from builtins import object`  

`class PSetTweak(object):`

### CODE REVIEW

**Comment by vilnius-dev** [comment]
@ericvaandering patch is updated please review

**Comment by ericvaandering** [comment]
It looks OK except for the failing tests. I don't know why those are failing. I wonder if someone used the "object" keyword somewhere in the code as a variable.

**Comment by ericvaandering** [comment]
I'm going to try to take a look at this and see what I can figure out. I found three places in the code we use "object" where we shouldn't. Two I put in a PR already to remove.

**Comment by ericvaandering** [comment]
I have no idea how, but I managed to push this to @vilnius-dev repository. Maybe because I own dmwm?

**Comment by vilnius-dev** [comment]
that means this PR can be closed?

**Comment by ericvaandering** [comment]
No, it means it can be merged! :-) or at least further tested in a real production environment. I'm going to trigger one last round of tests.

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Looks good, @ticoann

**Comment by bbockelm** [comment]
What should be done with this?  Seems like it is reasonably safe work that just never got merged?

**Comment by ticoann** [comment]
I can fix the conflict and merge the patch.

**Comment by amaltaro** [comment]
It's probably safer to run the fixer over, to make sure it covers all modules added since then as well.

**Comment by ericvaandering** [comment]
Agreed with @amaltaro . It was #8205 that got rid of some code using object as a variable name

**Comment by mapellidario** [comment]
This is covered by our gradual migration. I would suggest closing this PR without merging

**Comment by amaltaro** [comment]
Agreed! Thanks Roman and Dario for your effort! Closing it

**Pull request closed without merging**
