### PR TITLE
Update snapshot of Unified campaigns; update a couple json templates

### LINKED ISSUE #10241: Update json test templates to use data/campaigns already available
**Impact of the new feature**
WMCore integration validations

**Is your feature request related to a problem? Please describe.**
Many sites are out of quota, which makes most of our test workflows to sit stuck in `assigned` status.
We need to update them and use as many primary/secondary/parent data already available on disk as we can.

**Describe the solution you'd like**
Change test json templates to use input data that is already locked and available on disk RSEs.
In addition to that, make sure that they are associated with known campaigns (or test campaigns that we create with our own parseCampaigns script).
 
**Describe alternatives you've considered**
Release space on the FNAL and CERN RSEs, such that we can proceed with validation using our current json templates...

**Additional context**
This is pretty urgent, current validation is blocked by this!

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #10241 

#### Status
not-tested

#### Description
This PR brings in the following changes:
* update the test campaigns to be injected into CouchDB (via parseUnifiedCampaigns.py)
* update our dump of the Unified campaigns
* update a few json templates to avoid transferring 90TB of data for a pileup that is no longer available on the Disk RSEs

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
none

#### External dependencies / deployment changes
none

### CODE REVIEW

**Review by todor-ivanov — APPROVED** [review]
Hi @amaltaro - I just tested it and it was working fine

**Comment by amaltaro** [comment]
Templates with the RelVal pileup fail to complete, all the jobs fail in Task3/Step3 with:
```
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 208 stream: 5
   [1] Running path 'RAWSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'RAWSIMoutput'
   [3] Prefetching for module CSCDigiProducer/'simMuonCSCDigis'
   [4] Calling method for module MixingModule/'mix'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: std::vector<PCaloHit>
Looking for module label: g4SimHits
Looking for productInstanceName: CastorFI

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

Will have to find another small pileup that works and that can be transferred... lovely!

**Comment by amaltaro** [comment]
Now these templates can trigger input data placement (very small data) and they all work fine.
FYI @todor-ivanov

**Comment by todor-ivanov** [comment]
Thank you @amaltaro

**Pull request merged**
