### PR TITLE
Make dir creation correct in SRMV2 impl

### PR DESCRIPTION
**Pull request by juztas**
@hufnagel please, review 
For others: https://github.com/dmwm/WMCore/pull/6150#issuecomment-134251674

### CODE REVIEW

**Comment by hufnagel** [comment]
You don't need the line defining self.directoryErrorCodes at all, it is already defined in the base class.

**Comment by juztas** [comment]
updated

**Comment by hufnagel** [comment]
Looks good now

**Comment by ericvaandering** [comment]
retest this please

**Comment by ticoann** [comment]
retest this please

**Comment by amaltaro** [comment]
Justas, Dirk, did you manage to run any real test for this patch? Otherwise I'll simply run the standard tests and then push it to production.

**Comment by hufnagel** [comment]
I don't think a test is needed. This effectively removes on line of code and that line of code did something (skip directory creation for stageout). Now with the line removed we simply don't skip it anymore.

But Justas might have tested it too.

**Pull request merged**
