### PR TITLE
Assign test_authz_key in unit test

### PR DESCRIPTION
**Pull request by vkuznet**
This recipe may fix some of the failed unit tests.

### CODE REVIEW

**Comment by ticoann** [comment]
Thanks Valentin, 
I will merge this when the test finished.

**Comment by ericvaandering** [comment]
And if Valentin fixes 10 tests in one go, I owe him a beer. Or vodka.

**Comment by vkuznet** [comment]
The PR fixed the unit test test_accept_reject_xfoo and couple of others. 
I'll count on free beer.

I'll walk through test area and fix other unit tests which inherit this bug.

**Comment by vkuznet** [comment]
Here PR for other two tests with similar issue: https://github.com/dmwm/WMCore/pull/6181

**Comment by ericvaandering** [comment]
Jenkins say's it's still broken. Happy to be wrong, though.

**Comment by vkuznet** [comment]
Which version of cherrypy jenkins use? Where does it comes from?
The cherrypy version I have does not have testmain method of cherrypy.helper.

**Comment by ericvaandering** [comment]
It comes from deploying the latest WMAgent RPM.

On Aug 28, 2015, at 15:12, Valentin Kuznetsov <notifications@github.com<mailto:notifications@github.com>> wrote:

Which version of cherrypy jenkins use? Where does it comes from?
The cherrypy version I have does not have testmain method of cherrypy.helper.
On 0, Eric Vaandering <notifications@github.com<mailto:notifications@github.com>> wrote:
> Jenkins say's it's still broken. Happy to be wrong, though.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/6180#issuecomment-135870460

—
Reply to this email directly or view it on GitHub<https://github.com/dmwm/WMCore/pull/6180#issuecomment-135877116>.




Eric W. Vaandering
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 840 6678 office
www.fnal.gov<http://www.fnal.gov/>

**Comment by vkuznet** [comment]
Hi,
digging further with code I found that the unittests in WMCore relies on
cherrypy-3.1.2 (see helper.testmain()) while the RPMs we are testing use
cherrypy-3.2.2 which modified its helper class (there is no anymore testmain).
I modified Api_t.py to work with cherrypy-3.2.2 and it passed all tests in my
local environment. Can we take PR: https://github.com/dmwm/WMCore/pull/6183
and test jenkins with it. I intentionally added couple of print statements
to check what test is doing. Therefore please do not merge #6183 yet, instead I
need to see output from jenkins.
Valentin.

**Comment by ericvaandering** [comment]
Yes, the cherry py tests are a PITA. I looked at converting them to 3.2 and gave up. Thanks for picking this up.

**Comment by ticoann** [comment]
@vkuznet, Valentin, I can just close this one without merging it, right?

**Comment by vkuznet** [comment]
yes

**Pull request closed without merging**
