### PR TITLE
Remove xmlData from subscribe/delete APIs since it is provided by sub…

### PR DESCRIPTION
**Pull request by ticoann**
…scription/deletion parameter 

replace #8144

### CODE REVIEW

**Comment by ticoann** [comment]
Just for the unittest checking. Still need to improve the code.

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
@vkuznet, @amaltaro, Alan please review.

**Comment by vkuznet** [comment]
+1

**Comment by ticoann** [comment]
test this please

**Review by amaltaro — APPROVED** [review]
Changes look good, Seangchan. Still, I think it's worth running a test workflow (with input data) before merging it.

**Comment by vkuznet** [comment]
@ticoann Seangchan where do we stand on this? I need this PR to be merged before moving forwards with Unified Transferor. Alan asked to run test workflow with this PR, did you able to do this test?

**Comment by ticoann** [comment]
I found some problem on the test. I am investigating. I will try to fix that and merge later today.

**Comment by ticoann** [comment]
@vkuznet, Valentin, sorry for the late update. 1.1.7.pre2 tag contains this.

**Pull request merged**
