### PR TITLE
Use _revisions instead of _rev; create small chunks of docs to update

### PR DESCRIPTION
**Pull request by amaltaro**
Superseeds #8898 

Changes are:
* cherry-picked Seangchan's change from 8898, replacing _rev by _revision
* don't upload all docs in a single HTTP request, bu create small chunks of 100 docs per request (performance varies A LOT, from a few seconds to a few minutes)
* no need for the try/except block, all docs should be well formatted in a new agent
* creates a random revision id for the first time a document is created (to avoid issues if a doc gets deleted in central wmstats)

It appears to have a bad performance, we should keep an eye on this mode of upload and make further changes if needed.

### CODE REVIEW

**Comment by ticoann** [comment]
This doesn't seem to work.  It seems for the initial doc, _rev has to be set

**Comment by amaltaro** [comment]
test this please

**Comment by ticoann** [comment]
test this please

**Comment by ticoann** [comment]
Alan, how was the performance test went. (You said initial call take long time 18 sec for 32 requests)

**Comment by ticoann** [comment]
This is for only new inserts, right? After the first insert is it faster (for updating records)?

**Comment by amaltaro** [comment]
Yes, new inserts take quite a while. Only document updates are much faster.

**Review by ticoann — APPROVED** [review]

**Comment by ticoann** [comment]
test this please

**Comment by amaltaro** [comment]
Now that we have wiped out the wmstats database, AnalyticsDataCollector became 10x faster. 
Checking a CERN agent (0250), time to upload agent_request docs went down from ~250secs to 16secs (310 docs).
While at FNAL it went down from 250secs to 50secs (~430 docs).

**Comment by amaltaro** [comment]
That was the execution time of the component cycle in general, so including everything. Still, I made an average (by eye) of the last 50 cycles or so.
Yes, DB is much healthier since we applied this patch yesterday, it grew only 13GB over the night.

**Comment by ticoann** [comment]
13G? Before the compaction? Right now it seems it is 2.7G. I expect it keeps growing until we hit the revision limit. current revision is around ~30 revision.

**Comment by amaltaro** [comment]
No no, it went from 332GB (yesterday afternoon) to 345GB (this morning). While the night before it grew ~150GB :)

**Comment by ticoann** [comment]
I see.  That is after you patch the agent, right?

**Comment by amaltaro** [comment]
Yes sir!

**Comment by ticoann** [comment]
Thanks Alan, it looks a lot better than before. Hope it stays that way. :-)

**Pull request merged**
